hashicorp/vagrant

- plugins/providers/hyperv/scripts/start_vm.ps1
Fix for "Start-VM exceptions are not caught' #5101
> Fix catching "Start-VM" exceptions on Hyper-V during starting up VM

- plugins/providers/virtualbox/driver/version_4_1.rb
- plugins/providers/virtualbox/driver/version_4_2.rb
- plugins/providers/virtualbox/driver/version_4_3.rb
Fix for issue #5093 to allow symlinks to work in Docker shared folders with using VirtualBox as the host.
> enable symlinks before adding shared folder

- plugins/commands/up/start_mixins.rb
Type `vagrant reload --provision-with ...` instead of
`vagrant reload --provision --provision-with ...`.
Same as for `vagrant up`.
> Enable provision with --provision-with flag

- plugins/provisioners/chef/config/base.rb
- plugins/provisioners/chef/config/base_runner.rb
- plugins/provisioners/chef/config/chef_apply.rb
- plugins/provisioners/chef/provisioner/chef_apply.rb
- plugins/provisioners/chef/provisioner/chef_solo.rb
- plugins/provisioners/puppet/config/puppet.rb
- plugins/provisioners/puppet/provisioner/puppet.rb
- test/unit/plugins/provisioners/chef/config/base_runner_test.rb
- test/unit/plugins/provisioners/chef/config/chef_apply_test.rb
Fixes #4988 
This changes the Chef provisioner from using counters to using predictable names based on the MD5 of the local path. These are then verified using the synced folder cache. This removes the need for two things causing problems.
1. Counter usage for synced folder paths in the provisioner itself. This was originally necessary to avoid conflicts. We no longer worry about this anymore since use the MD5 of the local path as the name, this avoids conflicts, and if they do conflict, its the same folder so it doesn't matter.
2. Counter usage for the provisioning path. We needed this in case multiple `config.vm.provision` was there since the counters from 1 above were scoped to each provisioner. We no longer need this because 1 is gone and the same logic applies for conflicting folders …
> provisioners/chef: use synced folder cache instead of counter

- plugins/guests/funtoo/cap/configure_networks.rb
fixed name of temporary network configuration file to work with the further process of copying file to configuration directory in funtoo guests
fix for https://github.com/mitchellh/vagrant/issues/4812
> Update configure_networks.rb for funtoo

- plugins/providers/docker/hostmachine/Vagrantfile
Vagrant >1.7 is unable to login to the default boot2docker host if it has
been halted and brought back up again.
This is because the insecure SSH keypair is replaced but boot2docker doesn't
persist filesystem changes between reboots. So when next brought up Vagrant
tries to use the new keypair which is no longer valid and subsequently isn't
able to login.
Prevent this from happening by disabling the `ssh.insert_key` option on
versions where it is available.
---
I'm not sure how this will affect users that upgrade from an earlier version to 1.7, because this `Vagrantfile` will have already been copied out to `~/.vagrant.d/data/docker-host` and they won't receive this change. Any ideas?
> Disable insert_key for boot2docker host

- lib/vagrant/util/is_port_open.rb
Sometimes in use ports can raise a Errno::EACCES exeptions on Windows hosts. This fixes issue #3031.
> Fix issue 3031

- plugins/provisioners/docker/cap/debian/docker_install.rb
docker.io seems to be deprecated & handled differently from docker.com; see https://twitter.com/clint_newsom/status/557290529810313217
Anecdotally, the docker.com URLs worked while the docker.io URLs were failing, so I have more long-term confidence in them
> Switch to docker.com

- plugins/hosts/bsd/cap/nfs.rb
- plugins/hosts/linux/cap/nfs.rb
In developing a Vagrant plugin for XenServer[1], the unique identifier that the API uses for VMs contains a colon. They are of the form:
OpaqueRef:1530c1b3-2cd8-9561-5dc8-7aaa160fb641
It seems the other plugins use their platform's unique identifier for the machine ID and so do we.
The issue is that this machine ID is used by the SyncedFolders built-in plugin to create an entry in `/etc/exports`. This functions correctly, however the SyncedFoldersCleanup plugin doesn't clean them up because the regex in `prune_nfs` doesn't allow for colons in the line.
An alternative would be to allow any string after the "VAGRANT-BEGIN <uid>" since there are no limitations on what can be put into the machine's ID.
Signed-off-by: Si Beaumont <simon.beaumont@citrix.com>
> Allow colon in NFS ID regex

- lib/vagrant.rb
- test/unit/vagrant_test.rb
If one passes a version spec to `Vagrant.has_plugin?`, the actual plugin name is ignored and any installed plugin which matches the version spec makes the check pass. Fix this by also checking for plugin name match in addition to the requested version spec.
> Check plugin name with version spec in has_plugin

- lib/vagrant/action/builtin/handle_box.rb
- test/unit/vagrant/action/builtin/handle_box_test.rb
This fixes https://github.com/mitchellh/vagrant/issues/4665 which I ran into today.
I had added the wrong shasum to my Vagrantfile but the box still got downloaded and imported, so I decided to take a stab at fixing it.
Manually adding the box from the command line with
```
vagrant box add --name randombox --checksum-type sha256 --checksum <sha256_of_box>
```
validates the checksum just fine so I used plugins/commands/box/command/add.rb as model.
It turned out that lib/vagrant/action/builtin/handle_box.rb wasn't passing either of box_checksum and box_checksum_type to Vagrant::Action.action_box_add.
> fix checksum verification for downloaded boxes (fixes #4665)

- plugins/providers/virtualbox/driver/version_4_0.rb
- plugins/providers/virtualbox/driver/version_4_1.rb
- plugins/providers/virtualbox/driver/version_4_2.rb
- plugins/providers/virtualbox/driver/version_4_3.rb
- test/unit/plugins/providers/virtualbox/support/shared/virtualbox_driver_version_4_x_examples.rb
This should fix the cleaning up of the default VirtualBox dhcpserver,
which we've been fighting with for ages over in #3083. We were checking
for a structure _including_ a netmask, but the driver was not populating
netmask.
> providers/virtualbox: read netmask from dhcpservers

- lib/vagrant/action/runner.rb
I found this output to be very helpful in debugging an action hook
problem in a plugin.  problem. I'm not sure why the callable_id is
useful (seem to always show up as an instance of `Builder` or `Warden`
for me), but I left it in there just in case it's useful to someone.
> core: log action name to info

- website/docs/source/v2/other/environmental-variables.html.md
The hashicorp checkpoint gem's [current documentation](http://www.rubydoc.info/gems/hashicorp-checkpoint/0.1.4) has this to say:
> We understand that software making remote calls over the internet for any reason can be undesirable. Because of this, Checkpoint can be disabled in all of our software that includes it. You can view the source of this client to see that we're not sending any private information.
Instructions how to do the disabling have been omitted from the Vagrant documentation. This pull request contains a (very minimal) fix for that omission.
Thank you for providing fine software!
> Kindly document how to disable checkpoint remote call.

- website/docs/source/v2/cli/index.html.md
I was looking for the environment variable definition at the place where the cli is documented. Didn't find it. For the next guy who ticks like I do, let's put a link there.
> Make the environment variable documentation more easy to find.

- website/docs/source/v2/vmware/usage.html.md
Instead of having the user download a .box file and manually installing it, just use the hashicorp/precise64 box and let Vagrant handle the download.
> Do not encourage users to download a box directly

- website/docs/source/v2/provisioning/chef_solo.html.md
In the [chef_solo provisioner documentation](https://docs.vagrantup.com/v2/provisioning/chef_solo.html) there are several outdated links. This PR resolves this issue.
- links to http://docs.chef.io/roles.html instead of https://docs.chef.io/essentials_roles.html
- links to https://docs.chef.io/nodes.html#about-run-lists instead of https://docs.chef.io/essentials_node_object_run_lists.html
- links to http://docs.chef.io/data_bags.html instead of https://docs.chef.io/essentials_data_bags.html
Fixes #5318
> Fixes broken/deprecated links on the chef_solo provisioner documentation

- website/docs/source/v2/networking/public_network.html.md
Add disable auto-configuration on public net
Add example to setup manually ip and ipv6
Add example to set default router for ip and ipv6
> example to set default router on public net

- website/docs/source/v2/provisioning/salt.html.md
I discovered this option by digging in the source for a way to pass extra params to `bootstrap_salt.sh`.
> Added bootstrap_options param to the salt provisioner docs

- vagrant.gemspec
API changes seem pretty minor:  https://github.com/svenfuchs/i18n/blob/master/CHANGELOG.md
Useful for folks that package instead of omnibus.
> Relax i18n gem spec to support 0.7.0

- plugins/guests/darwin/cap/insert_public_key.rb
- plugins/guests/darwin/cap/remove_public_key.rb
- plugins/guests/darwin/plugin.rb
Here's an implementation of the private key caps for darwin. It's copied from the Linux guest caps, with a minor tweak to the variant of sed that ships on OS X. This fixes #5204.
> Support insert_public_key and remove_public_key on darwin guest

- plugins/providers/virtualbox/action/network.rb
Most of the time when using a bridged interface we want to connect to the first available interface. Depending on various conditions, hardcoding the exact interface name can be troublesome and difficult to share.
Changing the config a bit permits the usage of a Regexp (or anything that respond to === actually) which helps avoiding to type "1" each time we launch a VM.
I've kept the old "downcase" behaviour so it shouldn't break anything.
> Support Regexp usage for bridge configuration

- plugins/provisioners/docker/cap/linux/docker_configure_vagrant_user.rb
Doesn't in recent Fedora docker-io installs.
> Only add user to docker group if docker group exists

- plugins/guests/redhat/cap/flavor.rb
Extends code committed for #4195 (EL7 Dynamic network cards fix) to include "Scientific Linux release 7.0 (Nitrogen)" in the list of RHEL 7 flavors.
> Add Scientific Linux to RHEL 7 flavors.

- website/docs/source/v2/vagrantfile/ssh_settings.html.md
Related to the issue #5059, because of the changes introduced by pull request #4707. It's a nice feature, but a lot of people are having a hard time to find this configuration because the documentation is not clear.
> [DOCS] Clarifies the entry for config.ssh.insert_key

- plugins/guests/windows/cap/rsync.rb
- plugins/guests/windows/plugin.rb
- test/unit/plugins/guests/windows/cap/rsync_test.rb
Some of the other guests have a folder structure pre-creation on an rsync command, so I thought Windows could benefit from one as well, especially those of us using Windows guests on AWS. This will fix #5255 (without the need for the work-around).
> Windows rsync needs to create folders before syncing

- plugins/guests/fedora/guest.rb
Last week I noticed that there was some issues regarding the dynamic network cards using Fedora 21 and yesterday I finally tracked down the issue. The grepping didn't support Fedora 21 so I added a trailing 1 to the regexp.
> detect fedora 21

- website/docs/source/v2/getting-started/networking.html.md
Just a quick update to Networking under Getting Started. In the main Networking section, there's a line that states, 
"In the case of forwarded ports, two numeric arguments are expected: the port on the guest followed by the port on the host that the guest port can be accessed by."
However, in the Networking section under Getting Started, it has them flipped around. So, this flips them so it's consistent with the main Networking section in the docs where the examples show `guest` followed by `host`.
> Reorder forward port args in Getting Started

- website/docs/source/v2/cli/box.html.md
Added the missing "be" in "version of the box can retrieved using".
> website/docs: fix typo in cli box repackage

- README.md
Fixes capitalization of 'Vagrant' in `README.md`, so it matches the rest of the file. Hope you're having a great week! :)
> Fix capitalization of Vagrant in README.md

- plugins/communicators/winrm/scripts/elevated_shell.ps1.erb
StopOnIdleEnd was set in the task definition for elevated/privileged
windows guest scripts. This setting:
> specifies that the task stops when the idle condition ceases to be true [1]
The "idle condition" is something that Windows periodically checks for,
and it's defined by a bunch of criteria like user presence/absence, CPU
/ IO idle time, etc. [2]
Telling our provisioner to stop the task if the "idle condition" ceases
to be true is a recipe for some sporadically stopped tasks, which seems
like precisely the behavior being reported in #5362.
I'm pretty sure this fixes #5362
[1] https://msdn.microsoft.com/en-us/library/cc248332.aspx
[2] https://msdn.microsoft.com/en-us/library/windows/desktop/aa383561%28v=vs.85%29.aspx
> communicators/winrm: don't stop task on idle end

- plugins/providers/hyperv/scripts/import_vm.ps1
Stopping the EFI secure boot Set-VMFirmware commands from running on generation 1 machines.  If the Set-VMFirmware commands are run, generation 1 machines won't load.
> only set EFI secure boot for gen 2 machines in hyperv provider

- templates/locales/en.yml
Currently, a VirtualBox error message suggests
`VirtualBox internal networks can only be enabled on "private_networks"`
which is incorrect. This PR changes the error message to
`VirtualBox internal networks can only be enabled on "private_network"`.
Fixes #5418.
> Fixed VirtualBox's error message on 'private_network'

- plugins/pushes/ftp/adapter.rb
list method is not safe to check if a dir exist or not on remote.
To re-produce the error, you could do  'git clone git@github.com:sinatra/sinatra.git' in directory which Vagrantfile stay in, and run $vagrant push.
> fix ftp push check bug

- plugins/provisioners/salt/bootstrap-salt.ps1
- WinRM communicator error detection was tightened up thus exposing an issue in the salt bootstrap script creating directories that already exist.
> Salt bootstrap ps1 should be idempotent

- website/docs/source/v2/synced-folders/nfs.html.md
I recently went through quite a bit of NFS troubleshooting and found that there are several undocumented NFS options for Vagrant. It's possible to override both client and server-side NFS arguments, which is awesome. 
So this PR aims to document these 2 options in the NFS section.
For reference, PR #1029  contains most commits which added these options.
> [docs] Documenting more NFS options.

- lib/vagrant/util/platform.rb
- plugins/providers/virtualbox/driver/version_4_3.rb
- test/unit/vagrant/util/platform_test.rb
Proposed fix for #4815 (and #1953) based on many comments, notably @Ingramz and @celtric. 
This changes the VirtualBox share on Windows to use UNC paths, for which Windows allows > 256 characters.
Long paths become an issue when using npm for example, which can result in multiple sub directories. Once the path reaches 256 characters, the guest OS usually throws a Permission Denied or Protocol Error.
All rake tests passing, but couldn't get acceptance tests for virtualbox running so acceptance tests are not run. Tested in Windows 7 with VirtualBox 4.3.20 and Vagrant 1.7.2.
> Proposed fix for #4815 - Windows UNC path to allow > 256 characters

- templates/locales/en.yml
Add the word `flag` to the phrase `or use the '--provision' flag`, which is displayed when `vagrant up` is run for a VM that's already been provisioned.
> Add missing word to output of "vagrant up"

- website/docs/source/v2/cli/ssh.html.md
stdin is supported by vagrant ssh. updated the html docs to reflect the same.
https://github.com/mitchellh/vagrant/issues/5614
> Updated ssh docs

- website/docs/source/v2/provisioning/chef_apply.html.md
- links to http://docs.chef.io/recipes.html instead of https://docs.chef.io/essentials_cookbook_recipes.html
> Fixed deprecated link on chef_apply documentation

- plugins/providers/hyperv/action/import.rb
Currently if one has more than one Hyper-V switch, vagrant will require user intervention to select the switch to use when importing a machine. This is always slightly annoying and problematic when using applications such as Test-Kitchen that do not allow interactive setup of a vagrant box.
This PR allows a Vagrantfile to include a public or private network with a network name. If a switch exists with the same name, it is the one that will be chosen:
```
config.vm.network "public_network", bridge: 'External Virtual Switch'
```
Considering one has multiple switches and one is named after the `bridge`, that switch will be chosen. If no network name is specified, the the current behavior takes over and prompts the user.
This is a modified steal from @Taliesin's PR #3480 that was previously …
> select a Hyper-V switch based on a network_name

- plugins/providers/hyperv/action.rb
- plugins/providers/hyperv/action/net_set_vlan.rb
- plugins/providers/hyperv/config.rb
- plugins/providers/hyperv/driver.rb
- plugins/providers/hyperv/scripts/set_network_vlan.ps1
- test/unit/plugins/providers/hyperv/config_test.rb
- website/docs/source/v2/hyperv/configuration.html.md
This PR mostly based on #5169 it adds possibility to configure vlan_id for hyperv provider
My improvements gives possibility to leave vlan_id untouched in case it does not set
also added description of this option to documentation.
tests present, feature documented
tested on 2012hyperv server
with #5207 will be great improvements for hyperv networking possibilities, and reduce it limitations
> HyperV provider: VlanID configuration possibility

- plugins/guests/debian/cap/configure_networks.rb
When a vagrant box has two private network ips /etc/network/interfaces
will duplicate eth2 and bigger. sed matches greedy, so the first
#VAGRANT-END matches. This will result in:
/etc/network/interfaces:29: interface eth2 declared allow-auto twice
/sbin/ifup: couldn't read interfaces file "/etc/network/interfaces"
Tac print files in reverse and will match the first vagrant-end and only print what is under the last vagrant-end. Tac is in coreutils and is installed with a debootstrap wheezy, so i am assuming that nobody will have an issue on Debian.
> vagrant duplicates >= eth2 when defining two private network ips

- lib/vagrant/util/ssh.rb
PLink 0.64 (released 28-2-2015) changes the command-line description, so the previous text-match no longer works.
This fixes one of the issues that frequently occurs on Windows systems.
> Update ssh.rb to detect PLink v0.64

- plugins/guests/tinycore/cap/change_host_name.rb
- plugins/guests/tinycore/plugin.rb
- test/unit/plugins/guests/tinycore/cap/change_host_name_test.rb
The capability code was already there, but not declared in the plugin file.
> TinyCore change_host_name capability

- lib/vagrant.rb
Allows usage of VAGRANT_NO_PLUGINS env var to disable plugins.
Fixes #5430.
> If plugins are disabled, report them as not available.

- plugins/guests/fedora/guest.rb
With Fedora 22 to be released and Fedora 23 in development, let's fix the Fedora recognition pattern for Fedora future releases.
> Recognize new Fedora releases

- plugins/providers/virtualbox/action/network.rb
This change allows you to specify multiple network interfaces to bridge to in the order you want them tried, picking the first match.
```ruby
VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
config.vm.network "public_network",
bridge: ["en4: Thunderbolt Ethernet",
"en6: Broadcom NetXtreme Gigabit Ethernet Controller",
"en0: Wi-Fi (AirPort)"]
end
```
> virtualbox: handle a list of bridged nics

- lib/vagrant/box.rb
Fixes GH-5657
While doing a box repackage, we have to select only files to avoid duplicates in the resulted tar.
> Fix issue #5657: Take only files while box repackage

- plugins/guests/darwin/cap/change_host_name.rb
#4535 has broken Darwin guests if `config.vm.hostname` is set to FQDN, with dots:
```
<...>
==> default: Setting hostname...
scutil --set LocalHostName holly-chef.com
SCPreferencesSetLocalHostName() failed: Invalid argument
```
I've reproduced it on OS X 10.9.5 and 10.10.2 as well.
It is caused by the fact that `LocalHostName` should not contain dots and it could not be equal the FQDN. 
The good practice here is to leave only the first part of hostname, like I've done.
> Fixed error in ChangeHostName capability for Darwin

- plugins/guests/fedora/cap/configure_networks.rb
If biosdevname isn't installed it doesn't make sense to try using it
for persistent device names.  Just treat lack of biosdevname as
virtual networking.
> fedora: don't try to use biosdevname if it's not installed

- plugins/commands/rdp/command.rb
Any specific reason the password was omitted from the rdp_info hash?
Without the password in the rdp_info hash I see no way of figuring out the password in the rdp_client capability.
> Add password to rdp_info hash

- website/docs/source/v2/cli/destroy.html.md
Hi,
Because `vagrant destroy` doesn't remove the box installed during `vagrant up`, the statement:
After running this command, your computer should be left at a clean state, 
as if you never created the guest machine in the first place.
is a bit of an exaggeration, I think. Maybe you will find the notice I have written useful?
> doc destroy - notice about space occupied by the box

- lib/vagrant/action/general/package.rb
- templates/locales/en.yml
The package error message will now show the actual package name if the
package already existed.
Fixes #5380
> Improved the package error message

- lib/vagrant/action/builtin/box_add.rb
- templates/locales/en.yml
Importing a base box from the local file system currently outputs `Downloading: file://...`.
This PR changes this to  `Unpacking necessary files from: file://...` which is more accurate.
Fixes #5386.
> Fixed inaccurate downloading status message

- lib/vagrant/ui.rb
- test/unit/vagrant/ui_test.rb
Use of $stdin, $stdout, and $stderr globals makes testing difficult. By
exposing the IO objects as writable attributes, input/output can be more
easily simulated using StringIO or doubles.
> core: allow IO redirection of UI for testing

- website/docs/Vagrantfile
When attempting to run vagrant up on the Vagrantfile provided in the documentation directory, I get an error related to rvm's gpg signature and the bundle gem not being installed. 
This commit adds a line to retrieve the key and another to install the bundle gem to the Vagrantfile's provisioning script. 
Gist of the error:
https://gist.github.com/brooksbrown/e0d53d995d8dfcc9204d
> added gpg signature for rvm and bundle gem install to the docs Vagrantfile

- plugins/provisioners/shell/config.rb
- plugins/provisioners/shell/provisioner.rb
- website/docs/source/v2/provisioning/shell.html.md
This allows the display of friendly output to the user when we think an
important action should be labeled a certain way. This makes vagrant
output a lot more useful when many inline shell provisioners are
present.
This patch includes documentation updates too! w00t :)
> Add :name attribute to shell provisioner.

- website/docs/source/v2/provisioning/salt.html.md
Based on this vagrant code:
```
@machine.env.ui.info "Copying salt master config to vm."
@machine.communicate.upload(expanded_path(@config.master_config).to_s, temp_config_dir + "/master")
end
```
It seems that the current documentation:
* master_config (string, default: "salt/minion") Path to a custom salt master config file
is probably incorrect and the master_conifg probably defaults to salt/master, not salt/minion.
Unless I'm reading the code wrong.
> fix master_config documentation

- lib/vagrant/errors.rb
- plugins/guests/darwin/cap/choose_addressable_ip_addr.rb
- plugins/guests/darwin/cap/mount_smb_shared_folder.rb
- plugins/guests/darwin/plugin.rb
This integrates a simple [plugin](https://github.com/alh84001/vagrant-darwin-smb) I wrote that enables mounting SMB shares in OSX boxes.
In addition to `mount_smb_shared_folder` capability, `choose_addressable_ip_addr` capability is also added.
Related issue I opened some time ago:
https://github.com/mitchellh/vagrant/issues/5392
> Capability to mount smb shares in darwin guests

- Vagrantfile
This fixes the following issues when using the provided Vagrantfile
that can be used to develop Vagrant.
* use -s for curl
* set a hostname
* set the config.ssh.shell in the development Vagrantfile
==> default: stdin: is not a tty
* export the DEBIAN_FRONTEND variable
==> default: dpkg-preconfigure: unable to re-open stdin: No such file or
directory
* import the mpapis public key to verify downloaded release
==> default: -su: rvm: command not found
* use official Ubuntu Trusty box
New release '14.04.2 LTS' available.
> Fix Vagrantfile to develop Vagrant

- lib/vagrant/util/downloader.rb
Goal is to enable passwords with special characters to be used.
Escape special characters in URL provided before parsing with `URI.parse`, then unescape them again in the authentication details.
> Escape/unescape cURL URLs/auth

- vagrant.gemspec
[winrm-fs 0.2.0](https://github.com/WinRb/winrm-fs/blob/master/changelog.md#020) is a bit more polished, Vagrant should use it.
> Use latest winrm-fs release

- contrib/bash/completion.sh
An update to the bash auto-completion script to complete VM names for the `vagrant up` command.
I made a similar commit at https://github.com/kura/vagrant-bash-completion/commit/e720d90ae9a6589eb13c578b40a503e902d4897c earlier but what I really intended was to put it here since this is the "official" location.
> contrib/bash: Auto-complete VMs for up command

- plugins/provisioners/salt/config.rb
- plugins/provisioners/salt/provisioner.rb
Fix for https://github.com/mitchellh/vagrant/issues/4370 . Adds a config option orchestrations, which when set on the master node (config.install_master = true), will cause each orchestration in the provided list of orchestrations to be run
> Added ability to run salt orchestrations to Salt provisioner

- plugins/provisioners/salt/bootstrap-salt.ps1
Copy the config after we know the installer exits. Also rev the
installed version to 2014.7.1 (latest stable as of 3/4/2015)
It seems to work with a Windows 8.1 box that I have tested. Works on initial bootstrapping and succeeds on re-provisioning.
> Fix issue #4152: Salt minion bootstrapping

- plugins/guests/windows/cap/configure_networks.rb
When upping a Win XP box, vagrant found a lot of "virtual" network
connections that did not have DHCP enabled, and tried to configure them
for DHCP. This did not work because their :net_connection_id is nil.
Ignoring these network connections enabled the XP box to be upped.
I realize that Windows XP is not officially supported, but I hope that you'll accept contributions that enable it to function. I also tested this change against a Windows 7 box to confirm that this change does not affect a newer Windows version.
> Ignore Windows NICs with nil :net_connection_id

- plugins/guests/linux/cap/mount_smb_shared_folder.rb
- test/unit/plugins/guests/linux/cap/mount_shared_folder_test.rb
- website/docs/source/v2/synced-folders/smb.html.md
For SMB on Linux guests, specify the user's domain as a separate parameter to the mount command. This is more reliable than passing user@domain as the username. This is not needed for SMB on Windows guests as they expect the user@domain form.
This does not change how it is configured in the Vagrantfile.
Fixes #3620
> For SMB on Linux guests, specify the user's domain as a separate parameter

- plugins/guests/freebsd/cap/remove_public_key.rb
Sed on freebsd seems to be mores strict than on other
platforms about use of -i: the extension is not optional.
Signed-off-by: Michael Adam <obnox@samba.org>
> guests/freebsd: fix call of set -i : missing extension

- website/docs/source/v2/vmware/kernel-upgrade.html.md
We should only create the backup file on the first `sed` modification. The second `sed` operation will create a backup with the changes from the first `sed` operation.
> VMware Documentation Fix - SED Syntax

- plugins/provisioners/docker/cap/debian/docker_configure_auto_start.rb
Very simple tweak I'm using personally for Debian-based boxes. upstart ships by default on Ubuntu, but not on Debian, and `service` works in both. Fixes #5245.
> Use service command to restart docker, not upstart.

- website/docs/source/v2/synced-folders/smb.html.md
Related to https://github.com/mitchellh/vagrant/issues/5569. Adds a note on PowerShell version requirements to the prerequisites section of SMB synced folders documentation.
> Added a note on PowerShell to prerequisites SMB documentation.

- lib/vagrant/ui.rb
- plugins/provisioners/ansible/provisioner.rb
- plugins/provisioners/chef/provisioner/base.rb
- plugins/provisioners/puppet/provisioner/puppet.rb
- plugins/provisioners/puppet/provisioner/puppet_server.rb
- test/unit/vagrant/ui_test.rb
This adds a `.color?` function to the UI classes that returns false by default and then true for the colored ui. You can see from the output that this is more explicit than checking the type of UI class.
/cc @phinze for UX thoughts :smile:
> Add UI::Interface#color?

- lib/vagrant/box_collection.rb
- vagrant.gemspec
Fixes https://github.com/mitchellh/vagrant/pull/4758
> Ignore hidden directories

- plugins/provisioners/salt/bootstrap-salt.ps1
- plugins/provisioners/salt/config.rb
- plugins/provisioners/salt/provisioner.rb
Updated version to latest, 2015.5.2. Added passing in the version via vagrantfile. This is only for windows, but the linux bootstrap script is outside of this repo. This is my first PR so let me know if I missed anything.
> Updated version for windows and added passing in version via vagrantfile

- plugins/provisioners/docker/cap/debian/docker_install.rb
Depending if a Debian system is up to date or not, Docker install will fail because it may try to install an invalid linux-image-extra- kernel package url.
Fix is to do update before trying to install anything.
--------------------
Error output:
--------------------
lsmod | grep aufs || modprobe aufs || apt-get install -y linux-image-extra-`uname -r`
Reading package lists...
Building dependency tree...
Reading state information...
The following extra packages will be installed:
crda iw libnl-3-200 libnl-genl-3-200 wireless-regdb
The following NEW packages will be installed:
crda iw libnl-3-200 libnl-genl-3-200 linux-image-extra-3.13.0-55-generic …
> [Fix] Docker Provisioner fails on Debian [ubuntu/trusty64]

- plugins/guests/atomic/cap/change_host_name.rb
- plugins/guests/atomic/cap/docker.rb
- plugins/guests/atomic/guest.rb
- plugins/guests/atomic/plugin.rb
This adds a new guest to Vagrant: Atomic.
More info on Atomic: http://www.projectatomic.io/
Rationale on why this is a guest and not flavour: https://github.com/projectatomic/vagrant-atomic/issues/5
Note that this was already released as a vagrant-atomic plugin[0], but we would like to have this in Vagrant itself.
[0] https://github.com/projectatomic/vagrant-atomic/
> Add Atomic guest support

- plugins/communicators/winrm/communicator.rb
- plugins/communicators/winrm/scripts/elevated_shell.ps1.erb
- test/unit/plugins/communicators/winrm/communicator_test.rb
Leaving around plaintext username and passwords in a script on a box isn't the best from a security standpoint. This change ensures the scheduled task wrapper script for WinRM doesn't leave these around on the box, and instead passes them to the script as arguments.
> Fix issue 5790

- plugins/synced_folders/smb/scripts/host_info.ps1
fixes #5797 This sorts the ips by `AddressFamily` returning ipv4 first.
> prefer ipv4 host address over ipv6 for smb synced folders

- plugins/hosts/linux/cap/nfs.rb
This PR replaces #5030.
---
Interactive `sed` needs write permission on the file itself. However, it
may create a backup file, which leads to the fact that the directory
where the file is located must be writable as well. That is a side
effect because this directory does not need to be writable.
This patch fixes this side effect by editing the file in `/tmp`, and
replaces it right after.
> Being able to edit a file does not mean you can write in its parent directory

- plugins/guests/ubuntu/cap/change_host_name.rb
> Fix #5673 - Use hostnamectl to set the hostname on Ubuntu Vivid 15.

- plugins/guests/redhat/plugin.rb
- plugins/hosts/redhat/plugin.rb
Red Hat Linux no longer exists, so let's make it RHEL.
> Fix RHEL name and description

- plugins/guests/linux/cap/mount_nfs.rb
- plugins/guests/linux/cap/mount_smb_shared_folder.rb
- plugins/guests/linux/cap/mount_virtualbox_shared_folder.rb
Fixes issue #5377.
Check that Upstart is not just installed but currently actively running
before attempting to emit an event after mounting shared folders.
Only requires the binary be named upstart, not that it lives in /sbin.
> Check Upstart is running before emitting upstart events.

- templates/guests/debian/network_dhcp.erb
Inspired by e7dce43af3905a7a986ef6e3402bf6809ab90f16.
I'm using this configuration in my Vagrantfile:
```ruby
config.vm.network :public_network, use_dhcp_assigned_default_route: true
```
Every once in a while the secondary network interface would not come
up properly and cause the init scripts to wait for ~ 3 minutes before
giving up and continue with booting.
(My guess is that sometimes the VirtualBox dhcp server takes longer to respond than the physical network and that causes the default route deletion to fail).
I haven't seen this issue since I made this change locally on my machine.
> Make sure debian net post-up never returns an error code.

- lib/vagrant/environment.rb
- lib/vagrant/vagrantfile.rb
It fixes GH-5189
Actually, machine data directory should be created after machine configuration, e.q. when checks will be passed : [lib/vagrant/vagrantfile.rb#L108-L141](https://github.com/mitchellh/vagrant/blob/59dbe51ef2f0ba021b5e9c213710303d45c3b2d2/lib/vagrant/vagrantfile.rb#L108-L141)
Currently we have this issue on OS X hosts: GH-5189, and it affects all providers: https://forum.parallels.com/threads/vagrant-builds-vms-but-cannot-locate-them.327487/
It is caused by two facts: 
- Machine data directory is created before check that the specified provider exists. Vagrant doesn't delete this dir even if provider check has been failed.
- The filesystem on OS X host is case insensitive by default. Thats why this "hidden error" still exists and make all subsequent "vagrant" commands not …
> Create machine data directory only after the machine will be checked

- lib/vagrant/errors.rb
- lib/vagrant/machine.rb
- plugins/providers/virtualbox/provider.rb
- templates/locales/en.yml
- test/unit/vagrant/machine_test.rb
Fixes #4739
This adds UID tracking to created machines, and errors in VirtualBox if they mismatch.
> Track UID used to create machine, error in VB if mismatch

- plugins/providers/docker/action.rb
Resolves #5353
After this change Docker's caching mechanism is now applicable to the build process during `vagrant reload` by default, speeding up the reload process considerably for large/complex Dockerfiles.
Forcing the image to be rebuilt from scratch, without cache, can still be achieved via adding the `--no-cache` flag to the `build_args` array.
> Docker Provider: Don't destroy built Docker image on reload

- lib/vagrant/machine.rb
- lib/vagrant/util/ssh.rb
- plugins/commands/ssh_config/command.rb
- plugins/kernel_v2/config/ssh.rb
Lets the user specify what ssh to use or even direct Vagrant to use an ssh wrapper like sshrc (https://github.com/Russell91/sshrc).
I haven't added tests or documentation yet, but I can add it if you're interested in the idea.
In my `Vagrantfile`, I set:
```ruby
config.ssh.ssh_command = 'sshrc'
```
Now I can do `vagrant ssh` and have it invoke `sshrc` instead of `ssh`.
```
$ bundle exec vagrant ssh
...
-------> marca-mac2.local:~/.sshrc
vagrant@localmonkey:~$ exit
```
> Add setting config.ssh.ssh_command

- plugins/guests/fedora/cap/configure_networks.rb
Using vagrant-libvirt, setting a fixed interface IP address fails if the guest VM runs RHEL7 or Fedora and has a docker0 interface.
The symptom is that **eth0** is brought up successfully for management, Vagrant connects in via ssh, then **eth1** fixed IP configuration is erroneously written to /etc/sysconfig/network-scripts/ifcfg-**eth0**. Then eth0 is bounced (incorrectly) and the "up" process hangs.
The fault occurs because 'docker0' is not removed from this network interface enumeration, causing a subsequent off-by-one error. The fault was probably introduced (inadvertently) in commit 55a90445cdfc290d4a1f68c66835c0249ca59cdd.
> Remove docker0 from guest network interface enumeration

- lib/vagrant/machine.rb
I have different virtual machines with the same name in Vagrant and using the same Vagrantfile, but different names in virtualbox (and different directories).
This allows me to run action on both VMs at the same time.
Fixes #4822
> Allow to use several boxes with the same name

- lib/vagrant/action/builtin/mixin_synced_folders.rb
- plugins/kernel_v2/config/vm.rb
- test/unit/vagrant/action/builtin/mixin_synced_folders_test.rb
Currently Vagrant selects the default synced folder type based on hardcoded priorities. It will select the highest-priority "usable" plugin. Usable doesn't necessary mean working, it usually just checks that pre-requisite software is either installed or can be installed automatically. It might still be unusable in practice because of security policies or the need for additional configuration.
I've also found that the order is not always deterministic. Currently rsync and nfs have equal priority. I've seen some users report that NFS is selected, and others report that rsync is selected, when both are "usable" on their system. The `config.nfs.functional = false` property can let you disable nfs to ensure rsync is selected, but there currently isn't a way to disable rsync and force NFS to be …
> Allow filtering/reprioritization of synced folder preferences

- plugins/guests/fedora/cap/configure_networks.rb
Configuring by :interface doesn't work very well because Vagrant has
no idea about what interfaces are present in the VM, for example if
the image has 'docker' installed but not biosdevname, then
interface_names[0] = "docker0" which is usually not what you want
mapped to the first network from the Vagrantfile.
So if the plugins (like vagrant-libvirt) or the Vagrantfile has
given us a network with a MAC address, use that to find the interface
name for the network.  Otherwise use slot numbers as before.
> [fedora] honor MAC address when configuring networks

- plugins/guests/fedora/cap/configure_networks.rb
Running `vagrant up` with the fedora box where `nmcli` is not installed fails to configure guest networks.
Here is the reproducing step:
$ vagrant box add --name fedora-cloud-22 https://download.fedoraproject.org/pub/fedora/linux/releases/22/Cloud/x86_64/Images/Fedora-Cloud-Base-Vagrant-22-20150521.x86_64.vagrant-virtualbox.box
$ cat <<EOF > Vagrantfile
Vagrant.configure('2') do |config|
config.vm.box = 'fedora-cloud-22'
config.vm.network :private_network, ip: '10.0.0.2'
end
EOF
$ vagrant up
(snip)
==> default: Configuring and enabling network interfaces...
which nmcli >/dev/null 2>&1 && nmcli c reload eth1
This PR fixes …
> guests/fedora: don't fail if nmcli doesn't exist on the guest

- plugins/provisioners/salt/config.rb
After upgrading to 1.7.3 we found that our VMs would not execute salt. I narrowed that down to the use of the verbose option. So removing that is a workaround for now. However we don't get any salt output which makes debugging changes to our config difficult.
I found that #5435 added a new `install_command` option but that seemed to always set the options value to a `DummyConfig` type instead of the expected string. It seems that the option wasn't initialized in `config.rb` so I've added that which fixes the problem on my machine.
Our current VMs already have salt installed but I think this might actually break normal salt install so it might be very urgent to fix for a good amount of people.
Fixes https://github.com/mitchellh/vagrant/issues/5939
> Fix salt bootstrap issue after 1.7.3 upgrade with verbose option set

- plugins/communicators/winrm/shell.rb
As described in issue #5970 communicate.ready? returns an exception on connection timeout, instead of returning false.
This catches the Errno::ETIMEDOUT, which will be caught by:
https://github.com/mitchellh/vagrant/blob/master/plugins/communicators/winrm/communicator.rb#L104
```ruby
rescue Errors::TransientError => e
```
And resulting in returning "just" false.
> Raise Errno::ETIMEDOUT as "acceptable" Errors::ConnectionTimeout

- CHANGELOG.md
- plugins/provisioners/salt/bootstrap-salt.ps1
- plugins/provisioners/salt/config.rb
- plugins/provisioners/salt/provisioner.rb
Simple typo was killing the copy of the minion file when masterless config flag was set.
> Fixed salt minion configuration directory typo

- website/docs/source/v2/provisioning/salt.html.md
Added details about what works for windows and what doesn't, fixed typo, broke runners out from states, added 3 options (version, masterless, and minion_id).
> Update salt install options in documentation

- website/docs/source/layouts/layout.erb
- website/www/source/layouts/layout.erb
Hello,
currently www.vagrantup.com and docs.vagrantup.com are loading web fonts using HTTP even when HTTPS is used (default for vagrant's website).
This causes most browsers (Chromium and Firefox at least) to block those resources by default due to security issues (HTTPS is useless if an active element such as a script is loaded using plain HTTP because it has access to the whole DOM...).
Loading the external resources over HTTPS avoids this issue.
Thanks,
Marcello
> [website] load external scripts without schema

- plugins/provisioners/cfengine/config.rb
With this fix, Debian will now work with `cfengine` provisioner.
> Fix for Issue #6006 - cfengine will now install

- plugins/provisioners/salt/provisioner.rb
Vagrant 1.7.4 seems to break the masterless provisioning process for SaltStack.
It throws an error during provisioning:
```
Salt binaries found. Configuring only.
/tmp/bootstrap_salt.sh  -C
% Total    % Received % Xferd  Average Speed  Time    Time    Time  Current
Dload  Upload  Total  Spent    Left  Speed
0    0    0    0    0    0      0      0 --:--:-- --:--:-- --:--:--    0 * ERROR: In order to run the script in configuration only mode you also need to provide the configuration directory.
23  204k  23 48521    0    0  257k      0 --:--:-- --:--:-- --:--:--  929k
curl: (23) Failed writing body (631 != 16384)
```
The …
> Fix broken masterless minion configuration

- vagrant.gemspec
Update winrm-fs 0.2.2 fixes some problems with Windows 10 guests.
I have solved my issue similar to #6060 and #6055 running on OSX 10.10.4 with VirtualBox 5.0.0 spinning up a Windows 10 guest VM.
> Update winrm-fs to fix Windows 10 problems

- website/docs/source/v2/cli/destroy.html.md
The alert box within destroy command documentation contains markdown-style link.
The link should be written in raw HTML within alert box.
> Fixed link in destroy command documentation

- plugins/provisioners/ansible/provisioner.rb
- test/unit/plugins/provisioners/ansible/provisioner_test.rb
This patch fixes `Invalid ini entry` error when ansible_ssh_private_key_file contains spaces in generated inventory file.
The error:
```bash
$ pwd
/Users/konomae/Dropbox (Personal)/test
$ cat Vagrantfile  
Vagrant.configure(2) do |config|
config.vm.box = "hashicorp/precise64"
config.vm.provision :ansible do |ansible|
ansible.playbook = "site.yml"
end
end
$ cat site.yml 
---
$ vagrant provision 
==> default: Running provisioner: ansible...
ERROR: /Users/konomae/Dropbox (Personal)/test/.vagrant/provisioners/ansible/inventory/vagrant_ansible_inventory:3: Invalid ini entry: (Personal)/test/.vagrant/machines/default/virtualbox/private_key - need more than 1 value to unpack
Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again. …
```
> Fix invalid ini entry error when ansible_ssh_private_key_file contains spaces

- plugins/commands/cap/command.rb
- plugins/commands/cap/plugin.rb
- test/unit/plugins/commands/cap/command_test.rb
This introduces a new hidden (non-primary) command: `vagrant cap`.
This can be used to execute and check for arbitrary capabilities of Vagrant, the host, the guest, and the provider. This can be used to fingerprint the environment from the outside. This is an advanced feature that we don't intend to document publicly.
> "cap" command

- plugins/guests/fedora/cap/configure_networks.rb
Previously, configuring and enabling network interfaces failed with:
```
/usr/sbin/biosdevname --policy=all_ethN -i bash: /usr/sbin/biosdevname:
No such file or directory
bash: /usr/sbin/biosdevname: No such file or directory
```
The previous attempt to fix this (ccc4162) doesn't work since it doesn't
properly parse the `bash: /usr/sbin/biosdevname: No such file or
directory` error message.
This patch works around that problem and adds a comment explaining the
meaning of the return codes.
> Fixes Fedora network issues when biosdevname command is not present.

- plugins/communicators/winrm/communicator.rb
- test/unit/plugins/communicators/winrm/communicator_test.rb
We gained a ton of improvemnts to WinRM error handling in
https://github.com/mitchellh/vagrant/pull/4943, but we also got one bug.
The new code raises an exception when `winrm_info` does not return right
away. This was preventing us from catching the retry/timout logic that's
meant to wait until boot_timeout for the WinRM communicator to be ready.
This restores the proper behavior by rescuing the WinRMNotReady
exception and continuing to retry until the surrounding timeout fires.
> communicators/winrm: respect boot_timeout when fetching winrm_info

- plugins/providers/hyperv/action.rb
- plugins/providers/hyperv/action/net_set_mac.rb
- plugins/providers/hyperv/config.rb
- plugins/providers/hyperv/driver.rb
- plugins/providers/hyperv/scripts/set_network_mac.ps1
- test/unit/plugins/providers/hyperv/config_test.rb
- website/docs/source/v2/hyperv/configuration.html.md
Implements the ability for the Hyper-V provider to set VMs' mac address from the vagrant file. Same implementation as the set VLAN feature.
> Hyper-V set mac address

- lib/vagrant/ui.rb
- test/unit/vagrant/ui_test.rb
This includes the standard UI output in the machine-readable UI. We do this because it is sometimes convenient to parse this out and select what UI output you want.
> core: machine-readable output should include standard UI output

- lib/vagrant/errors.rb
- lib/vagrant/ui.rb
- plugins/commands/provider/command.rb
- plugins/commands/provider/plugin.rb
- plugins/hosts/darwin/cap/provider_install_virtualbox.rb
- plugins/hosts/darwin/plugin.rb
- plugins/hosts/darwin/scripts/install_virtualbox.sh
- plugins/hosts/windows/cap/provider_install_virtualbox.rb
- plugins/hosts/windows/plugin.rb
- plugins/hosts/windows/scripts/install_virtualbox.ps1
- templates/locales/en.yml
- test/unit/plugins/commands/provider/command_test.rb
This introduces a non-primary (hidden) command `vagrant provider` for listing the provider in use for an environment and also has the capability to install providers. I currently only implemented installing VirtualBox on OS X but other OS's will soon follow.
> command/provider: non-primary command to check and install providers

- lib/vagrant/environment.rb
- lib/vagrant/plugin/v2/provider.rb
- plugins/commands/up/command.rb
- plugins/providers/virtualbox/provider.rb
- templates/locales/en.yml
- test/unit/vagrant/environment_test.rb
- test/unit/vagrant/plugin/v2/provider_test.rb
- website/docs/source/v2/cli/up.html.md
This introduces a new flag `--install-provider` (set by default) that automatically installs the requested provider if possible. This is a completely backwards compatible change: any providers that don't explicitly implement the `installed?` function will just always be seen as installed.
> Add provider install to `vagrant up`

- website/docs/source/v2/other/environmental-variables.html.md
Now reflects the not-vagrant-specific version, `CHECKPOINT_DISABLE`
> Change docs for checkpoint environment variable

- plugins/commands/ps/command.rb
- plugins/commands/ps/errors.rb
- plugins/commands/ps/plugin.rb
- plugins/commands/ps/scripts/enable_psremoting.ps1
- plugins/commands/ps/scripts/reset_trustedhosts.ps1
- plugins/communicators/winrm/shell.rb
- plugins/hosts/windows/cap/ps.rb
- plugins/hosts/windows/plugin.rb
- templates/locales/command_ps.yml
This adds a new vagrant command:
```
vagrant ps
```
Example:
```
C:\dev\vagrant\win8.1x64> vagrant ps
default: Creating powershell session to 192.168.1.14:5985
default: Username: vagrant
[192.168.1.14]: PS C:\Users\vagrant\Documents>
```
The command is very similar to the ssh command but drops the user into a remote powershell session. The command is currently only supported on windows hosts with a guest running via the winrm communicator. The command, similar to `vagrant ssh` also supports a `--command` argument that can execute any powershell command over winrm.
Would be great to add @sneal 's repl to add support for linux hosts.
*note:* this PR is a squashed and final version of #4330 
Fixes https://github.com/mitchellh/vagrant/issues/5725
> Add a ps command to vagrant that drops the user into a remote powershell shell

- plugins/commands/login/middleware/add_authentication.rb
- test/unit/plugins/commands/login/middleware/add_authentication_test.rb
This fixes GH-6395 by only appending the access_token once. It also fixes a bug that was never reported. If a user supplied an access_token for a box URL, Vagrant would silently overwrite it.
After this commit, Vagrant only appends an access_token to the URL if no value exists at the key.
> Only append access_token the first time

- plugins/guests/debian8/cap/halt.rb
The current (1.7.3) behaviour leads to vagrant force-shutdown every time I halt a Debian 8 box:
```
vagrant halt
==> d8: Attempting graceful shutdown of VM...
==> d8: Forcing shutdown of VM...
```
On executing ```shutdown -h -H``` I understand why, because this simply schedules a shutdown in one minute:
```
root@vagrant:~# shutdown -h -H
Shutdown scheduled for Fri 2015-07-17 21:32:54 CEST, use 'shutdown -c' to cancel.
Broadcast message from root@vagrant (Fri 2015-07-17 21:31:54 CEST):
The system is going down for system halt at Fri 2015-07-17 21:32:54 CEST!
```
Also the usage of shutdown says:
```
shutdown [OPTIONS...] [TIME] [WALL...]
-H --halt      Halt the machine
-h             Equivalent to --poweroff, overridden by --halt
```
> Specify time and don't do -h -H which is not really a valid usage.

- .gitignore
- lib/vagrant/bundler.rb
- plugins/commands/plugin/command/mixin_install_opts.rb
This parameter that will allow for only those sources that are defined by the user to be used. I also added editor swapfiles to the .gitignore.
I work in a corporate environment behind firewalls which prevent access to both rubygems.org and gems.hashicorp.com. We have our own rubygems repository where we host (among other things) Vagrant plugins (both internally-created and external). Without a patch like this, `vagrant plugin install vagrant-triggers` (for instance) will fail because it cannot retrieve the specs from gems.hashicorp.com. Furthermore, we need something like this so that the risk and audit groups don't see the attempts at forbidden traffic.
I'm not thrilled with the parameter behavior I created - it means that parameter parsing is a state machine and that could be …
> Added a --plugin-clean-sources parameter

- website/docs/source/v2/provisioning/salt.html.md
The basic Vagrantfile file example for a masterless setup wasn't setting the masterless value to true.  That value defaults to false in config.rb and used on line 350 here:  https://github.com/mitchellh/vagrant/blob/master/plugins/provisioners/salt/provisioner.rb
> Corrected masterless example for salt provisioner in documentation

- plugins/provisioners/puppet/provisioner/puppet.rb
- website/docs/source/v2/provisioning/puppet_apply.html.md
Fixes: #5987
Please review: @benh57 
To test this I used a Vagrantfile with the following code:
```
config.vm.provision 'puppet' do |puppet|
puppet.environment = 'all'
puppet.environment_path = 'environments'
end
```
I also created a `environments/all/` directory.
To verify what command Vagrant sent through to the VM I used:
`vagrant provision --debug --provision-with puppet`
**Without environment.conf**
`puppet apply --detailed-exitcodes --environmentpath /tmp/vagrant-puppet/environments/ --environment all /tmp/vagrant-puppet/environments/all/manifests/site.pp`
**With environment.conf but no manifest setting**
`puppet apply --detailed-exitcodes --environmentpath /tmp/vagrant-puppet/environments/ --environment all /tmp/vagrant-puppet/environments/all/manifests/site.pp`
**With …
> Fix puppet apply environment default manifest

- plugins/provisioners/salt/provisioner.rb
Salt-minion and salt-call are batch files on a windows guest, not executables.
> Correct salt-minion and call ext on windows guest

- plugins/provisioners/puppet/config/puppet.rb
Small typo in the puppet environment code.
Currently if you specify puppet.environmentpath and it is missing, you get this error:
C:/HashiCorp/Vagrant/embedded/gems/gems/i18n-0.7.0/lib/i18n/config.rb:92:in `block in missing_interpolation_argument_handler': missing interpolation argument :environmentpath in "The configured Puppet environment folder %{environment} was not found in the\nspecified environmentpath %{environmentpath}.\nPlease specify a path to an existing Puppet directory environment." ({:environment=>"test", :environment_path=>"C:/Users/bhines/Documents/Code/t/puppet"} given) (I18n::MissingInterpolationArgument)
from C:/HashiCorp/Vagrant/embedded/gems/gems/i18n-0.7.0/lib/i18n/interpolate/ruby.rb:29:in `call'
post-fix:
There are errors in the configuration of this machine. …
> Fix string parse error in the environment path missing error message.

- website/docs/source/v2/vagrantfile/ssh_settings.html.md
Modified the description of `config.ssh.insert_key` a bit to improve readability.
> Clarify config.ssh.insert_key docs

- plugins/provisioners/salt/config.rb
- plugins/provisioners/salt/provisioner.rb
The issue #5973 was caused by commit 74d22069d41b35bae50e32c1c68a92a4958afebb. Normally, the minion config is installed to the privileged `/etc/salt` directory by `salt-bootstrap.sh` as part of the `config_salt()` function. The reverted commit was having Vagrant upload the minion file *directly* to the `/etc/salt` directory - most installations probably don't have permissions to do this since vagrant is not running as root.
The original commit was to address situations where vagrant was being used with a basebox that already had salt installed. For these situations, users can simply provide the "-C" option as part of `bootstrap_options".
I've spent hours sorting this out and [addressing another issue with salt-bootstrap](https://github.com/saltstack/salt-bootstrap/pull/642) (I have to …
> Stop trying to upload minion config to privileged directory

- website/docs/source/v2/virtualbox/networking.html.md
The parameter name in the VirtualBox provider source is nic_type, not nictype.
The typo is probably caused by the fact that the parameter maps to nictype args in the VirtualBox CLI.
> The docs typo'd the nic_type parameter

- plugins/kernel_v2/config/vm.rb
When the network's type is :dhcp, the :ip option is used to derive the DHCP server configuration, and it doesn't actually indicate the IP that will be received by the VM(s).
> Don't warn about an .1 IP for DHCP networks

- website/www/source/layouts/layout.erb
I think that there should be a prominent link to box discovery on the Vagrant home page.
A few times I've Googled "vagrant", ended up here, and didn't know how to get to a box search page without doing another Google search.
However, a better solution may be to add a `<section>` with "Discover Vagrant Boxes on Atlas".
> website/www: Add Atlas box search to nav

- plugins/guests/pld/cap/flavor.rb
- plugins/guests/pld/plugin.rb
pld linux uses redhat as base, but lacks :flavour
this will add it
> fix network detection on pld-linux

- plugins/guests/windows/cap/rsync.rb
- plugins/guests/windows/plugin.rb
- plugins/synced_folders/rsync/helper.rb
Windows offers no out-of-the-box rsync utility. By far, the most
commonly used external utilities for Windows rsync are built with the
GNU Cygwin libraries. The cost for this convenience is that rsync on
Windows has to be provided paths that begin “/cygdrive/c” rather than
“c:/“ like other Windows-API utilities. Compounding the situation,
rsync doesn’t create paths/to/sub/targets and so the vagrant plugin
code, when performing an rsync, is responsible for creating
intermediate directories in guest paths if there are any. Furthermore,
the mkdir utility in Windows is not another Cygwin utility like rsync
but the routine mkdir of Windows command.com. Therefore, while rsync
needs the /cygwin paths, mkdir uses the Windows paths. Later, the
chef_solo.rp provisioner running within the guest will …
> Scrub Guest Paths for Windows Rsync leaving Dirty Paths for Winrm Mkdir

- plugins/communicators/winrm/scripts/elevated_shell.ps1.erb
Schedule.Service is not available for e.g. Windows XP. This PR catches that case and simply executes the script immediately since Windows XP does not require elevation.
I have tested the script in Windows XP, Vista and 8.1.
> Check if Schedule.Service com object is available

- plugins/guests/fedora/cap/change_host_name.rb
Update so that localhost entries don't get deleted when the hostname
gets added to the 127.0.0.1 line. Closes #6202
> Fix Fedora /etc/hosts bug

- plugins/communicators/winrm/communicator.rb
- plugins/communicators/winrm/config.rb
- plugins/communicators/winrm/scripts/elevated_shell.ps1.erb
- plugins/communicators/winrm/shell.rb
- test/unit/plugins/communicators/winrm/communicator_test.rb
Please see mitchellh/vagrant#5506
Adds a configurable value for WinRm and the elevated permission shell ExecutionTimeLimit.
Ex: config.winrm.execution_time_limit = "P1D"
Unit tests are passing, please consider for merge.
> Winrm execution timeout

- website/docs/Makefile
- website/docs/README.md
- website/docs/source/layouts/layout.erb
- website/www/Makefile
- website/www/README.md
- website/www/source/layouts/layout.erb
Following [this pattern](https://github.com/mitchellh/packer/pull/2396), this PR adds 'edit this page' links to the footers of the Vagrant `docs` and `www` sites. Note that it also adds Makefiles for each Middleman site.
> Add 'Edit this page' links to `www` and `docs` websites

- plugins/hosts/slackware/cap/nfs.rb
- plugins/hosts/slackware/host.rb
Slackware's version file is /etc/slackware-version not
/etc/slackware-release.
pidof is not on PATH by default (not running as root) so call it using
full path
> Fix Slackware Host detection and nfsd checks

- plugins/provisioners/puppet/provisioner/puppet.rb
Starting with vagrant 1.7.3 (commit 1152b4e1df97fb5f468491954932d4f0c09875b1) we don't
save the command to be executed in the file anymore, but we send
it as a parameter, thus the back tick makes things break.
Fixes #6403 
CC #3958
> Remove back tick in puppet facts definitions #6403 (Fix vagrant 1.7.3+ with puppet)

- website/docs/source/v2/provisioning/salt.html.md
If this is not set to tpc, then the minion will fail to communicate with the master.
> Document windows minion requirement for ipc_mode

- lib/vagrant/errors.rb
- plugins/guests/darwin/cap/configure_networks.rb
- plugins/guests/windows/cap/configure_networks.rb
- plugins/guests/windows/errors.rb
- templates/locales/en.yml
- templates/locales/guest_windows.yml
Fixes #6385
Currently `configure_networks` guest cap for Darwin configures NICs following the device order and fails
when this order is mixed. 
While performing the network configuration on the guest side, we have to detect the appropriate NIC by its MAC address (like it is implemented for Windows guests).
/cc: @mitchellh @sethvargo
> Fix network configuration in OS X (Darwin) guests

- website/www/Vagrantfile
Latest middleman requires ruby 2.2.2 and bundler gem.
> Fix Vagrantfile for latest middleman

- plugins/provisioners/puppet/config/puppet_server.rb
- plugins/provisioners/puppet/provisioner/puppet_server.rb
- website/docs/source/v2/provisioning/puppet_agent.html.md
puppet_server provisioner fails with Puppet Collection 1 with the
following error:
```bash
==> default: Running provisioner: puppet_server...
The `puppet` binary appears not to be in the PATH of the guest. This
could be because the PATH is not properly setup or perhaps Puppet is not
installed on this guest. Puppet provisioning can not continue without
Puppet properly installed.
```
refs #6151
> Fix for #6151 / provisioner puppet_server with Puppet Collection 1

- plugins/communicators/winrm/communicator.rb
- test/unit/plugins/communicators/winrm/communicator_test.rb
This fix was made in commit 1dd081d but was removed by 1152b4e. This was causing passwords with $ in them to stop working as the dollar sign was getting stripped out
> Fix for interpolated strings being used for username and passwords

- lib/vagrant/errors.rb
- plugins/hosts/linux/cap/rdp.rb
- templates/locales/en.yml
This resolves #6140.
`rdesktop` fails to connect to newer versions of Windows Server due to not supporting newer features of RDP such as Network Level Authentication.
`xfreerdp` [supports such features and is an all-around better option](https://unix.stackexchange.com/questions/140047/what-are-the-differences-between-rdesktop-and-xfreerdp/188168#188168), so I've made it the default RDP client when running `vagrant rdp` on a Linux host. If it's not installed, `rdesktop` will be used as a fallback. If neither are installed, an error message will be displayed as usual.
> Prefer xfreerdp for RDP connections on Linux hosts.

- lib/vagrant/action/builtin/handle_forwarded_port_collisions.rb
This call should not be in the `handle` helper method. It is specified in the `call` method already.
It is not critical in the current implementation of `HandleForwardedPortCollisions` class. 
But it causes a pretty big problems if we want to crate a child class (in the 3rd-party plugin) and call `handle` helper there:
```ruby
module VagrantPlugins
module PluginName
module Action
class HandleForwardedPortCollisions < Vagrant::Action::Builtin::HandleForwardedPortCollisions
@@lock = Mutex.new
def call(env)
@@lock.synchronize do
begin
env[:machine].env.lock('fpcollision') do
handle(env)
my_custom_method(env)
end
rescue Vagrant::Errors::EnvironmentLockedError
sleep 1
retry
end
end
@app.call(env)
end
end
end
end
end
```
In the result, `my_custom_method` will be never executed because `handle` …
> Bugfix: Remove redundant app call from action "handle_forwarded_port_collisions"

- plugins/communicators/ssh/communicator.rb
This changes the ssh ready? method to treat ENETUNREACH the same way as
EHOSTUNREACH errors.
When attempting to SSH into a box, it tries up to 5 times to connect to
the box, ignoring various errors.  Later it will catch and gracefully
handle most of those errors so that callers don't have to know the
details.
However, the Errno::ENETUNREACH error is not caught, which means that
callers that expect a clean boolean return from ready? don't get that,
and instead get an exception they probably aren't expecting.
> Add Errno::ENETUNREACH to SSH rescue

- plugins/provisioners/docker/cap/debian/docker_install.rb
The current docker installer attempt to install the linux-image-extra-`uname -r` DEB package on Debian systems.
This package may not exist, for example on custom kernels (e.g., Linode servers).
If this happens, Vagrant halts the provisioning. However, this package is not really needed in newer Debian releases (such as Ubuntu 14.04).
This small patch checks if the linux-image-extra-`uname -r` package exists, and it will install it if it does. In either case, it will continue provisioning.
> Update docker installer to work on custom kernels

- plugins/provisioners/salt/config.rb
- plugins/provisioners/salt/provisioner.rb
- website/docs/source/v2/provisioning/salt.html.md
Hey all! This PR answers #6276. For the brave/bored, feel free to drill down through the referenced issues and PRs. 
For the everyone else, this PR reverts the show stopper bug introduced in #5435 and the work done on top of it in #5936. My goal was to simply bring the salt provisioner back to a working state. The issue seeming to involve vagrant using the Salt dummy config file instead of the file set with the `minion_config` setting.
At provision time, the user supplied `minion_config` is copied to the inside the vagrant VM as you would expect. Therefore, the provisioner no longer hangs at "Bootstrapping Salt... (this may take a while)". This unblocks the Salt community. :confetti_ball: 
[There were no provision tests for the salt provisioner to begin …
> [salt] [bugfix] Restablize Salt provisioner 

- plugins/providers/virtualbox/driver/version_4_3.rb
- plugins/providers/virtualbox/driver/version_5_0.rb
This pull request is essentially the same as #5495 which enables use of long (>260 characters) path names for Windows hosts. This way creating longer than 260 character paths inside a shared folder doesn't fail inside the guest system (most common example: installing npm packages with long dependency chains).
Based on feedback from #5933, which caused the previous PR to be reverted, we contacted VirtualBox team and got them to fix
1. Missing support for shares using UNC paths on VirtualBox 5.0
2. Inability to get information about disk sizes for mounted shares, which used UNC paths on host, dubbed `df -h` issue on VirtualBox 4.3
The fixes are available for builds >=4.3 r103933 and >=5.0 r103713.
Are the changes to those drivers OK as-is or should we enable this only for builds higher than …
> Re-enable UNC paths for shared folders on Windows hosts

- lib/vagrant/machine_index.rb
- lib/vagrant/plugin/v2/command.rb
- test/unit/vagrant/plugin/v2/command_test.rb
Fixes #4742
If `vagrant something ID` is used where ID represents a machine where the cwd was deleted, we now automatically prune the index from the global status DB. Tests included.
> core: prune machine if non-existent CWD from index [GH-4742]

- plugins/providers/virtualbox/provider.rb
After replacing the insecure key and writing a new key to .vagrant/machines/default/virtualbox/private_key vagrant continues to use the old insecure key ( /Users/myuser/.vagrant.d/boxes/mybox/0/virtualbox/vagrant_private_key)
This patch instructs vagrant to search first for the newly generated key and use this key if it is already generated.
> #5186: Warning: Authentication failure. Retrying... after packaging box

- plugins/provisioners/chef/config/chef_solo.rb
- plugins/provisioners/chef/config/chef_zero.rb
- plugins/provisioners/chef/provisioner/chef_solo.rb
- plugins/provisioners/chef/provisioner/chef_zero.rb
- templates/provisioners/chef_solo/solo.erb
- templates/provisioners/chef_zero/zero.erb
- test/unit/plugins/provisioners/chef/config/chef_solo_test.rb
- test/unit/plugins/provisioners/chef/config/chef_zero_test.rb
- website/docs/source/v2/provisioning/chef_solo.html.md
- website/docs/source/v2/provisioning/chef_zero.html.md
This fixes an issue #6025 by re-adding support for the `nodes_path` declaration to feed Chef Zero a directory (or an array of directories) containing nodes in JSON format.
> Chef Zero - Fix 'nodes_path' Support

- plugins/provisioners/chef/provisioner/chef_client.rb
- templates/locales/en.yml
- Fixes https://github.com/mitchellh/vagrant/issues/6005
- Fixes https://github.com/mitchellh/vagrant/issues/6064
> Do not throw an error when the Chef node_name is nil

- lib/vagrant/action/builtin/box_add.rb
- test/unit/vagrant/action/builtin/box_add_test.rb
Fixes #5477 
If the protocol isn't HTTP, we don't do a HEAD request.
> core: don't do HEAD request for box on non-HTTP [GH-5477]

- lib/vagrant/environment.rb
- test/unit/vagrant/environment_test.rb
Fixes #6336 
If we have a custom set `VAGRANT_DOTFILE_PATH`, don't litter the drive with dot folders everywhere.
> core: don't make dotfile path if no Vagrantfile

- plugins/provisioners/salt/bootstrap-salt.ps1
The URL for the download has changed as per issue #6274
> Fixing the Salt bootstrap script for Windows

- website/docs/source/layouts/layout.erb
- website/www/source/layouts/layout.erb
This PR more safely builds the `edit this page` link on the main website and the docs website.
We ran into some issues deploying other Middleman sites with the `current_page.source_file.match(/website.*/)[0]` strategy, because the server's file structure may not map directly to the GitHub repo's file structure (if there's no `website` directory, the method errors out). The new strategy doesn't assume that the server's file structure has the same layout.
> Safer way to build 'edit this page' link

- plugins/providers/virtualbox/driver/meta.rb
Fixes #6468 
Apparently just reading the VirtualBox version on some systems can be SUPER slow. Let's cache that as recommended in #6468 to speed that up since its unlikely to change.
> providers/virtualbox: cache VirtualBox version [GH-6468]

- plugins/pushes/heroku/push.rb
- test/unit/plugins/pushes/heroku/push_test.rb
Fixes #6123 
This changes the way we get the branch to be the current branch.
This will fail (exit code != 0) on things that aren't on branches, which will be exposed to the user.
> push/heroku: use correct current branch [GH-6123]

- plugins/provisioners/chef/provisioner/base.rb
- plugins/provisioners/chef/provisioner/chef_client.rb
- templates/locales/en.yml
- test/unit/plugins/provisioners/chef/provisioner/base_test.rb
This is required because the Chef Server almost always needs a node name to interact. This will default to the hostname, but that's always going to be `vagrant.vm`, which will collide easily.
This generates a random hostname with `vagrant-` as the prefix and stores the result in the machine's data directory.
> Automatically generate a node_name for Chef

- plugins/provisioners/chef/cap/debian/chef_install.rb
- plugins/provisioners/chef/cap/omnios/chef_install.rb
- plugins/provisioners/chef/cap/redhat/chef_install.rb
- plugins/provisioners/chef/cap/windows/chef_install.rb
- plugins/provisioners/chef/command_builder.rb
- plugins/provisioners/chef/config/base.rb
- plugins/provisioners/chef/config/base_runner.rb
- plugins/provisioners/chef/installer.rb
- plugins/provisioners/chef/omnibus.rb
- plugins/provisioners/chef/plugin.rb
- plugins/provisioners/chef/provisioner/base.rb
- plugins/provisioners/chef/provisioner/chef_client.rb
- test/unit/plugins/provisioners/chef/config/base_test.rb
- test/unit/plugins/provisioners/chef/omnibus_test.rb
- website/docs/source/v2/provisioning/chef_common.html.md
This allows users to install a different version of a Chef product (like `angrychef` or `chefdk`):
```ruby
chef.product = "chefdk"
```
This fixes https://github.com/mitchellh/vagrant/issues/6466.
The second part of this PR implements the existing Chef installation, as well as the new ChefDK installation to Windows. I could've sworn there was an open issue about that, but I guess there isn't. Well, it's fixed now :smile:
> Allow ChefDK installation, add Windows installer support

- lib/vagrant/action/builtin/box_remove.rb
- lib/vagrant/box_collection.rb
- test/unit/vagrant/action/builtin/box_remove_test.rb
As per my comment at the issue page, please check if I've missed some sort of concurrency check in my patch.
> Fix #3570 'Box data left in ~/.vagrant.d/boxes after removal'

- lib/vagrant/action/builtin/box_check_outdated.rb
- lib/vagrant/box.rb
- plugins/commands/box/command/add.rb
- plugins/commands/box/command/download_mixins.rb
- plugins/commands/box/command/outdated.rb
- plugins/commands/box/command/update.rb
- test/unit/plugins/commands/box/command/update_test.rb
- test/unit/vagrant/action/builtin/box_check_outdated_test.rb
Vagrant::Box.load_metadata did not provide a way to specify the HTTPS
download options that could be specified when downloading boxes
(ca cert, ca path, client cert, insecure). As a result, while it was
possible to add a box whose metadata file needed to be downloaded with one of
those options specified, it was impossible to check for updates. The following
changes have been made to address the situation:
1. Create a DownloadMixins module to provide the --insecure, --cacert, --capth,
and --cert command line options to all of `vagrant box add`,
`vagrant box update`, and `vagrant box outdated`.
2. Extend `Vagrant::Box.has_update?` and `Vagrant::Box.load_metadata` to accept
said download options.
3. Extend `box outdated` and `box update` commands to pass download options
down.
4. Extend …
> Add HTTPS download options to `box update` and `box outdated`

- plugins/guests/linux/cap/remove_public_key.rb
Fixes #6104 
`-i` isn't a POSIX flag, just do the move manually.
> guests/linux: POSIX sed [GH-6104]

- plugins/synced_folders/rsync/command/rsync_auto.rb
- plugins/synced_folders/rsync/helper.rb
Fixes #6399 
This uses OpenSSH control paths for a faster rsync. On my system where rsync was already fairly fast, it went from ~250ms on every invocation to ~175ms. I've heard on some systems executing rsync is hundreds more ms, so this should speed up even more.
> synced_folders/rsync: SSH control for faster rsync

- plugins/provisioners/ansible/config/base.rb
- plugins/provisioners/ansible/errors.rb
- plugins/provisioners/ansible/provisioner/base.rb
- plugins/provisioners/ansible/provisioner/guest.rb
- plugins/provisioners/ansible/provisioner/host.rb
- templates/locales/en.yml
- test/unit/plugins/provisioners/ansible/config_test.rb
- test/unit/plugins/provisioners/ansible/provisioner_test.rb
- website/docs/source/v2/provisioning/ansible_common.html.md
Resolve #2718. 
@mitchellh @sethvargo This **must be and will be merged** for 1.8 release to satisify https://github.com/mitchellh/vagrant/issues/2103#issuecomment-75657728. 
Before merging, I'd really appreciate to get some users review/testing during this week, and thus I allow myself to kindly ping @mkuzmin, @maspwr, @devlucas, @QWp6t (please announce if you can have a look at this before next week). Most important goal is to ensure that the proposed behaviour is well thought for your needs and also possible evolutions...
Notes for the possible reviewers:
* The relevant commit to check is c1f3d114f52654e9f285499dd548409edc0c99fe
* The `galaxy_role_file` and `galaxy_roles_path` might sound incoherent, but I preferred to mimic the names used by `ansible-galaxy` command to avoid …
> Add support for Ansible Galaxy

- plugins/guests/linux/cap/remove_public_key.rb
This PR fixes an error introduced by GH-6565:
```
$ vagrant up
...
==> centos: Waiting for machine to boot. This may take a few minutes...
centos: SSH address: 10.211.55.235:22
centos: SSH username: vagrant
centos: SSH auth method: private key
centos: Warning: Connection refused. Retrying...
centos:
centos: Vagrant insecure key detected. Vagrant will automatically replace
centos: this with a newly generated keypair for better security.
centos:
centos: Inserting generated public key within guest...
centos: Removing insecure key from the guest if it's present...
centos: Key inserted! Disconnecting and reconnecting using new SSH key...
centos: Warning: Authentication failure. Retrying...
centos: Warning: Authentication failure. Retrying...
centos: Warning: Authentication failure. Retrying... …
```
> linux/cap/remove_public_key: Fix permissions on "~/.ssh/authorized_keys"

- lib/vagrant/action/builtin/mixin_synced_folders.rb
- lib/vagrant/action/builtin/synced_folders.rb
- test/unit/vagrant/action/builtin/mixin_synced_folders_test.rb
- test/unit/vagrant/action/builtin/synced_folders_test.rb
Fixes #6198 
This prunes items from the synced folder cache that come from the Vagrantfile and are no longer present in the Vagrantfile. Unit tests are here to help us.
> core: remove saved synced folders not from Vagrantfile

- plugins/kernel_v2/config/vm.rb
- test/unit/plugins/kernel_v2/config/vm_test.rb
Without this change a custom "winrm-ssl" port forwarding rule
could be wrongly shadowed in absence of a "winrm" custom rule.
It also fix little issues in the related unit tests:
* remove the misleading usage of inexistent `:winrmssl` connector (see https://github.com/mitchellh/vagrant/pull/4236/files#r24350557)
* forward to correct guest ports instead of ssh/22 (probable copy-paste errors)
Review request to @sneal
> "Split" the handling of WinRM port forwarding rules (plaintext, ssl)

- lib/vagrant/bundler.rb
Recent change broke bundler.rb due to incorrect scope resolution (the
error is: uninitialized constant Vagrant::Bundler::SafeEnv
(NameError).
> Fix the resolution of SafeEnv.

- plugins/commands/port/command.rb
- plugins/commands/port/locales/en.yml
- plugins/commands/port/plugin.rb
- plugins/providers/virtualbox/cap.rb
- test/unit/plugins/commands/port/command_test.rb
- test/unit/plugins/providers/virtualbox/cap_test.rb
- website/docs/source/layouts/layout.erb
- website/docs/source/v2/cli/port.html.md
This is still a :construction: but I have some questions around structure for @mitchellh 
- - -
- Fixes #1415
- Fixes #2826
- Fixes #3009
- Fixes #5650
> Add `vagrant port` command

- test/acceptance/provider-virtualbox/linked_clone_spec.rb
- test/acceptance/skeletons/linked_clone/Vagrantfile
This is a port of the similar test for "parallels" provider: https://github.com/Parallels/vagrant-parallels/blob/master/test/acceptance/provider/linked_clone_spec.rb
It passes successfully:
```console
$ bundle exec vagrant-spec test --components=provider/virtualbox/linked_clone
#...
provider/virtualbox/linked_clone
it should behave like provider/linked_clone
creates machine as linked clone
Execute: vagrant box add basic /path/to/box
Test: machine is created successfully
Execute: vagrant up --provider=virtualbox
Test: master VM is created
Test: machine is a master VM clone
Test: machine is available by ssh
Execute: vagrant ssh -c echo foo
Execute: vagrant destroy --force
creates machine as linked clone
Finished in 53.77 seconds
```
> Add acceptance test for linked clones

- plugins/provisioners/ansible/provisioner/host.rb
- test/unit/plugins/provisioners/ansible/provisioner_test.rb
With this change, the Vagrant machines configured with the `:winrm` communicator will be accordingly configured in the auto-generated Ansible inventory.
Solve #5086.
Known Issues:
* when `force_remote_user = false`, the vagrant ssh username is used as default username (via the `--user` argument). This could be improved, but it sounds to me to be an an additional burden to something that can easily be fixed by setting `config.ssh.username` to the same value as `config.winrm.username`. See de96b54272f0d7eb717df0f5d7d2c065cd8b1786
@sneal @sethvargo @mitchellh review + merge please :)
> Add WinRM support to Ansible provisioner

- plugins/commands/provision/command.rb
- plugins/commands/up/start_mixins.rb
Just a quick fix to issue #6512
working on `vagrant provision --help` and `vagrant up --help`
> update help message on --provision-with to add by provisioner name

- plugins/provisioners/ansible/provisioner/base.rb
- templates/locales/en.yml
- test/unit/plugins/provisioners/ansible/provisioner_test.rb
- website/docs/source/v2/provisioning/ansible_intro.html.md
Please verify and review language in docs, locales file as well as code syntax / logic! 
Thoughts and suggestions are welcome! Thanks!
> fixes #3539 - Can't use alphanumeric patterns for box names in ansible.groups

- plugins/commands/powershell/command.rb
This is a fix for `vagrant powershell` command, with fails with such exception:
```
C:\Users\michael.kuzmin\Projects\forks\vagrant>bundle exec vagrant powershell
DL is deprecated, please use Fiddle
Vagrant appears to be running in a Bundler environment. Your
existing Gemfile will be used. Vagrant will not auto-load any plugins
installed with `vagrant plugin`. Vagrant will autoload any plugins in
the 'plugins' group in your Gemfile. You can force Vagrant to take over
with VAGRANT_FORCE_BUNDLER.
You appear to be running Vagrant outside of the official installers.
Note that the installers are what ensure that Vagrant has all required
dependencies, and Vagrant assumes that these dependencies exist. By
running outside of the installer environment, Vagrant may not function
properly. To remove …
```
> Fix `uninitialized constant` error in `vagrant powershell` command

- plugins/providers/virtualbox/action/network.rb
- test/unit/plugins/providers/virtualbox/action/network_test.rb
Set the IPv6 adapter IP to be <prefix>::1. Otherwise, guest to host
communication over IPv6 is not routed correctly. This means that
consumers should not specify <prefix>::1 IP addresses to VirtualBox,
which should be a reasonable restriction.
Fixes #6658
> Use <prefix>::1 as the IPv6 adapter IP.

- lib/vagrant/errors.rb
- plugins/hosts/darwin/cap/provider_install_virtualbox.rb
- plugins/hosts/windows/cap/provider_install_virtualbox.rb
- templates/locales/en.yml
Use Vagrant::Util::FileChecksum to validate the downloaded VirtualBox
installers.
SHA-256 checksums for VirtualBox files are available at
https://www.virtualbox.org/download/hashes/5.0.10/SHA256SUMS.
Fixes #6611.
> Add checksum validation for the VirtualBox installs on Windows and OS X

- lib/vagrant/util/platform.rb
- plugins/providers/hyperv/provider.rb
- test/unit/plugins/providers/hyperv/provider_test.rb
Add method to detect if a Windows user is a member of the "Hyper-V Administrators" group.
Modify Hyper-V provider to require a user to either be an Administrator or a member of "Hyper-V Administrators"
Fixes #4503
> Fix for 4503

- plugins/synced_folders/smb/synced_folder.rb
This may have been due to a recent Windows Update? When doing a "vagrant up" on Windows 8.1, it was crashing due to the expected list of IPs returned from the host_info.ps1 script coming back as a string instead of a list.
> Fix for problem where the host_info.ps1 script returns a string instead of a list of IPs

- website/docs/source/v2/virtualbox/configuration.html.md
I'm assuming this got changed during development, but the documentation refers to an setting which doesn't work:
```
There are errors in the configuration of this machine. Please fix
the following errors and try again:
VirtualBox Provider:
* The following settings shouldn't exist: use_linked_clone
```
> v.use_linked_clone should be v.linked_clone

- plugins/provisioners/docker/cap/debian/docker_install.rb
Docker provisioning fails on Debian Jessie without the apt-transport-https package installed.
> Fix Docker provisioning for Debian/Jessie box

- website/docs/source/v2/virtualbox/configuration.html.md
To void this message on pre Vagrant 1.8
```bash
There are errors in the configuration of this machine. Please fix
the following errors and try again:
VirtualBox Provider:
* The following settings shouldn't exist: linked_clone
```
> linked_clone if Vagrant::VERSION =~ /^1.8/

- plugins/commands/up/command.rb
Fixes #6708 
This takes into account the forced provider (`--provider`) as well as the machine index (already created machines' provider) into what provider to install instead of always installing the default.
> Take into account machine index and forced provider for provider install

- plugins/provisioners/ansible/config/guest.rb
> Fix for ansible local provisioner error under Windows. `playbook` does not exist on the guest (#6740)

- plugins/provisioners/puppet/provisioner/puppet.rb
Fixes error "The term '$?' is not recognized as the name of a cmdlet, function, script"
@lmayorga1980 This should fix your issues with Puppet and setting a current working directory.
> Fix issue 6762

- plugins/provisioners/ansible/provisioner/guest.rb
At least for ansible 2.0.0.1 the command `ansible-galaxy --help` is inappropriate for testing if ansible is installed, as it yields an error:
```
vagrant@vagrant-ubuntu-trusty-64:~$ ansible-galaxy --help && echo "OK"          
Usage: ansible-galaxy [delete|import|info|init|install|list|login|remove|search|setup] [--help] [options] ...
Options:
-h, --help     show this help message and exit
-v, --verbose  verbose mode (-vvv for more, -vvvv to enable connection
debugging)
--version      show program's version number and exit
ERROR! Missing required action
```
> fixing incorrect missing ansible error

- website/docs/source/v2/synced-folders/nfs.html.md
Closes #6872
Adds a warning to the [synced folders docs](https://docs.vagrantup.com/v2/synced-folders/nfs.html) about using `visudo` vs any other editor as syntax errors can leave you stuck without privileges.
> Update nfs docs

- plugins/communicators/winrm/shell.rb
Removing call to method deprecated in v1.3. This will also prevent v1.5+ from leaking deprecation warning.
cc @sneal
> remove call to deprecated toggle_nori_type_casting in winrm

- website/source/docs/synced-folders/nfs.html.md
Copied the configuration to my own machine and noticed I was still getting prompted for my password. Looking at the command, I realize that sed is called on /tmp/exports, not /etc. Quick change, and everything is automatic as expected!
Updating the documentation so others don't have the same hassle. :)
> Update nfs sudo configuration for Fedora

- plugins/provisioners/puppet/provisioner/puppet.rb
As explained here http://stackoverflow.com/questions/11009598/whats-the-cmd-powershell-equivalent-of-which-on-bash in PS may be necessary to use "where.exe" instead of "where" to avoid call "Where-Object"
The change is compatible with CMD also.
> Fixed an issue locating puppet binary. Issue-6876

- plugins/guests/freebsd/cap/rsync.rb
Old pkg_* is now EOL: https://lists.freebsd.org/pipermail/freebsd-ports-announce/2014-February/000077.html
> Change to use pkgng

- CHANGELOG.md
- plugins/communicators/winrm/communicator.rb
- plugins/communicators/winrm/config.rb
- plugins/communicators/winrm/shell.rb
- test/unit/plugins/communicators/winrm/shell_test.rb
- vagrant.gemspec
- website/source/docs/vagrantfile/winrm_settings.html.md
Here are the major improvements:
* Winrm 1.6 just released and supports cross platform encrypted NTLM/Negotiate authentication. This makes this the default for vagrant boxes.
* winrm 1.5 allows multiple commands to be executed from the same shell yielding improved performance
* winrm-fs 0.3.0 Changes file/directory upload behavior to be more in line with the ssh communicator (see the note to the changelog regarding this).
cc @sneal
> upgrade to latest winrm and winrm-fs versions

- plugins/commands/login/client.rb
we're using rest_client 1.6.9, which doesn't use proxy passed in
to the RestClient::Request.execute.  Must set RestClient.proxy
instead
Fixes #6898
> fix login behind proxy (#6898)

- plugins/commands/up/command.rb
Fixes GH-6908
Pass names through `with_target_vms` to get regular expression expansion rather than iterating over names directly.
> Fix `vagrant up --install-provider` regular expression handling

- plugins/guests/freebsd/cap/change_host_name.rb
Use double quotes around the `hostname` value in `/etc/rc.conf`
> FreeBSD: Use quotes around hostname in rc.conf

- plugins/hosts/windows/cap/ps.rb
`Subprocess` sets up the process in such a way that pressing the up/down arrows does not cycle through command history in the `powershell` command. Using `SafeExec` instead as the `ssh` command does seems to fix this.
> use SafeExec to capture history via up/down keys in powershell command

- plugins/provisioners/chef/omnibus.rb
The double sudo in `plugins/provisioners/chef/omnibus.rb:11` lost the env like proxy settings. All commands see (plugins/provisioners/chef/cap/*/chef_install.rb) have allready sudo so no need to pipe it to sudo.
See also #6804
> remove double sudo

- plugins/guests/trisquel/guest.rb
- plugins/guests/trisquel/plugin.rb
Since Trisquel is a direct derivative of Ubuntu the only thing needed to change is the distribution detection. The rest of the capabilities should work with no issue through normal inheritance.
> Add trisquel guest plugin as derivative of ubuntu - Issue #6842

- plugins/guests/coreos/cap/configure_networks.rb
Re-factor and repair regular expression attempting to match present interfaces.
The re-factored regular expression will match on enp* ens* eth* variants.
Vagrant Cannot Detect CoreOS interface names #6608
> Vagrant Issue #6608

- website/source/docs/cli/destroy.html.md
The word "command" was enclosed in a code block despite not being part of the actual command you would run at the CLI.
> Changed "`destroy command`" to "`destroy` command"

- website/source/docs/other/debugging.html.md
During dev I needed to get the detailed logs into a file.  The debug info goes to stderr, my redirect was only catching stdout. Quick fix to the docs, and per http://unix.stackexchange.com/questions/244343/where-is-vagrants-log-file I may not be the only one who questioned this in the past.
The `--debug` option could be added to the CLI.  That was the first place I looked, and not seeing anything I googled. If I can get a quick pointer where to look in the code, I'll submit another small PR so ppl are aware of this option.
> Add debugging log docs.

- plugins/provisioners/chef/config/base.rb
- test/unit/plugins/provisioners/chef/config/base_test.rb
- website/source/docs/provisioning/chef_common.html.md
Previously the default channel was "current", but after discussion with
@coderanger on GH-6979, it seems like this was a poor design decision.
Instead, we should use the stable channel and allow users to opt-in to
prerelease versions.
Fixes GH-6979
> Use "stable" as the default Chef channel

- plugins/provisioners/chef/cap/linux/chef_installed.rb
- plugins/provisioners/chef/cap/omnios/chef_installed.rb
- plugins/provisioners/chef/cap/windows/chef_installed.rb
- plugins/provisioners/chef/installer.rb
Currently if one sets `chef.product = 'chefdk'`, it gets successfully installed but then exits out with `Vagrant could not detect Chef on the guest! Even after Vagrant
attempted to install Chef, it could still not find Chef on the system.`
With this fix, chef runs
> Correctly detect chefdk install

- plugins/provisioners/docker/client.rb
#7074 - Docker provisioner doesn't allow provisioning when container name is specified
We will be using the full container ID from now on since the Docker version is newer than 0.7.0
#7085 is partly fixing the grep issue with the -notrunc comand which was failing here.
> #7074 - fixes does not allow provisioning when container name is specified

- plugins/commands/snapshot/command/pop.rb
- plugins/commands/snapshot/command/push_shared.rb
- plugins/commands/snapshot/command/restore.rb
In our test environments, it's good to be able to roll back to the same,
anonymous, snapshot repeatedly.  This patch adds a `--no-delete` option
to the `snapshot pop` command allowing this.
This makes the new core snapshot behaviour more consistent with what we
were doing with [vagrant-multiprovider-snap](https://github.com/scalefactory/vagrant-multiprovider-snap) which I intend to deprecate eventually.
> Add missing features to snapshot restore/pop

- plugins/providers/hyperv/scripts/import_vm.ps1
The Hyper-V `New-VM` cmdlet on powershell version 3 (v8/2012) and lower do not support the `Generation` parameter. This detects if the parameter is supported and only specifies the generation if it is.
- Fixes GH-7098
> only specify Hyper-V generation if the parameter is supported

- plugins/guests/fedora/cap/configure_networks.rb
Fixed sorting of interface names in centos7
> Fixed centos 7 networks if using more than 3 ethernet adapters.

- website/source/docs/provisioning/shell.html.md
The description of binary option for shell is not correct.
- Fixes GH-7121
- As per http://stackoverflow.com/q/28651275/55075 thread, this seems to be confusing.
> CRLFs are changed to LFs if this is set to true.
> Fixes #7121: Corrected binary logic description.

- plugins/guests/arch/cap/configure_networks.rb
Restart network device on arch linux after reconfiguration (and to ensure that the device is actually up).
- Fixes GH-7119
- References GH-5737
> Restart network after reconfiguration

- website/source/docs/boxes/base.html.md
- website/source/docs/boxes/format.html.md
- website/source/docs/boxes/versioning.html.md
- website/source/docs/cli/login.html.md
- website/source/docs/getting-started/share.html.md
- website/source/docs/other/atlas.html.md
- website/source/docs/other/index.html.md
- website/source/docs/push/atlas.html.md
- website/source/docs/share/index.html.md
- website/source/docs/vagrantfile/machine_settings.html.md
This adds a page to describe Atlas as Atlas no longer has an easy to understand homepage.
> website: add a page to send folks to get to a signup link for atlas

- website/source/docs/plugins/providers.html.md
On https://www.vagrantup.com/docs/plugins/providers.html
> This class and the methods that need to be implemented are [very well documented](https://github.com/mitchellh/vagrant/blob/master/lib/vagrant/plugin/docs/provider.rb).
> fix dead link in plugins/providers documentation

- plugins/guests/debian/cap/configure_networks.rb
Ubuntu versions prior to 16.04 always returned a successful exit status, even if one tried to down an interface that does not exist. This behavior changed in Ubuntu 16.04 to return an error. This commit preserves the old behavior.
- Fixes GH-7155
- Fixes GH-6871
> Do not return an error if ifdown fails

- website/source/docs/other/environmental-variables.html.md
* Updates grammar to remove a superfluous article.
* Fixes spelling of `VAGRANT_SKIP_SUBPROCESS_JAILBREAK` such that it includes the required number of `S`-es.
> Minor grammar/spelling error in Environment Variables.

- website/source/docs/installation/uninstallation.html.md
Uninstall steps refer to `/usr/bin/vagrant` rather than `/usr/local/bin/vagrant`.
Fixes #7205
Do we need to include both potential paths to support removal of old versions?
> fix path in OSX vagrant uninstallation steps

- lib/vagrant/action/builtin/box_add.rb
I'm going to do some more testing on this, but this should fix the issue where private boxes can be downloaded, but not updated. We previously were not adding the access token to the private box URLs during update, only during adding. This fixes that.
- Fixes #6776 
/cc @mitchellh @phinze @kikitux
> Authenticate metadata box urls

- website/scripts/deploy.sh
Should fix occassional issues with application/octet-stream mime type
assets breaking things on the site.
> website: force mime-types for some assets on deploy

- plugins/providers/hyperv/action/import.rb
- plugins/providers/hyperv/config.rb
- plugins/providers/hyperv/scripts/clone_vhd.ps1
- website/source/docs/hyperv/configuration.html.md
Allow Hyper-V users use differencing disks instead of copying whole image each time to save space and time.
Creating differencing disk takes less than second and it does not matter how big is original disk
Added `differencing_disk` (Boolean) (optional, default is false) switch for hyperv.
Usage example:
```ruby
Vagrant.configure(2) do |config|
config.vm.provider "hyperv"
config.vm.box = "hashicorp/precise64"
config.vm.provider :hyperv do |hv|
hv.differencing_disk = true
end
end
```
- Fixes #7089
- References #7089
> hyperv differencing disk

- website/source/docs/provisioning/puppet_apply.html.md
This had caused me some issues and I don't want others to get stuck trying to follow the docs.
> Fixed typo: incorrect key name for environment_path option.

- plugins/provisioners/ansible/config/base.rb
- plugins/provisioners/ansible/config/host.rb
- plugins/provisioners/ansible/helpers.rb
- plugins/provisioners/ansible/provisioner/base.rb
- plugins/provisioners/ansible/provisioner/guest.rb
- plugins/provisioners/ansible/provisioner/host.rb
- templates/locales/en.yml
- test/unit/plugins/provisioners/ansible/config_test.rb
- test/unit/plugins/provisioners/ansible/provisioner_test.rb
When the `extra_vars` option is a hash, the `ansible_local` provisioner must quote the generated JSON parameter. 
I also propose here that the two other quoted parameters (`limit` and `start_at_task`) also rely on double quotes (for output consistency and content flexibility).
- Fixes GH-6726
- Replaces GH-6820
> ansible_local: use double quoting for 'extra-vars', 'limit' and 'start-at-task' options

- website/source/docs/plugins/development-basics.html.md
Because Vagrant requires certain versions of Bundler in order to work properly, the correct version of Bundler must be installed manually.  I gathered this information from a couple of sources.
It's handy to have this information in this specific guide :)
> Adds instructions concerning Bundler versions

- templates/locales/en.yml
Although the current message does tell you that the forwarded port can't be auto corrected due to the current state of the machine, it does not provide a clear solution. This happens to me all the time and after changing my vagrant file I've found out that I could just do a `vagrant reload`! 
Could it be nice to add this do the docs?
> Added 'vagrant reload' info on collision_error

- plugins/providers/hyperv/action.rb
- plugins/providers/hyperv/action/snapshot_delete.rb
- plugins/providers/hyperv/action/snapshot_restore.rb
- plugins/providers/hyperv/action/snapshot_save.rb
- plugins/providers/hyperv/cap/snapshot_list.rb
- plugins/providers/hyperv/driver.rb
- plugins/providers/hyperv/plugin.rb
- plugins/providers/hyperv/scripts/create_snapshot.ps1
- plugins/providers/hyperv/scripts/delete_snapshot.ps1
- plugins/providers/hyperv/scripts/list_snapshots.ps1
- plugins/providers/hyperv/scripts/restore_snapshot.ps1
- website/source/docs/hyperv/limitations.html.md
This PR is a port of the Hyper-V snapshot support from https://github.com/scalefactory/vagrant-multiprovider-snap into Vagrant core.  It supports all of the snapshot behaviour supplied by the Virtualbox and VMWare providers.
Restored VMs using SMB shared folders may error as they boot, during the mounting of those shared folders, though in the cases I've observed, the pre-snapshot mounts are still functional inside the guest.  
Presumably this is down to the filesystem and network state in the guest taking a trip back in time, but the host not going along for the ride.
I believe this to be bug-compatible with the other providers, and with my original implementation, but this may be a concern here since the default folder sharing mechanism on Hyper-V hosts is SMB.
- Fixes GH-7109
> Add snapshot support to Hyper-V provider

- plugins/provisioners/chef/command_builder.rb
- plugins/provisioners/chef/config/chef_solo.rb
- plugins/provisioners/chef/provisioner/chef_solo.rb
- templates/provisioners/chef_solo/solo.erb
Chef Solo by default will be using the same code path as chef-client in local mode, and we're adding a legacy mode to retain the previous behavior.
This PR adds support for legacy mode, and also fixes a bug where the node_path was getting set to an empty array, rather than simply being unset - which caused solo-in-local-mode to break.
Fixes: chef/chef#4948 cc @sethvargo
> Support Chef Solo local + legacy modes

- plugins/providers/hyperv/scripts/get_vm_status.ps1
On `vagrant status` for HyperV users, we catch an exception to determine the status of the machine.  This changed in order to support Windows 10, but this broke compatibility with powershell 4. This PR makes the exception we're looking for conditional on PS version.
A comment on https://github.com/mitchellh/vagrant/commit/587c88e65ae294c4f2939937c2079c545efd17cb shows that this commit broke back-compat with PowerShell 4.
> HyperV: Reinstate compatibility with PowerShell 4

- website/source/docs/plugins/action-hooks.html.md
Fixes misspelled word in `machine_action_up` description: 'caled' to 'called'
> Fix typo in list of action hooks

- website/source/docs/provisioning/chef_common.html.md
Without the two spaces on line 62, the docs look like this:
This is confusing, because it looks like the second paragraph is wrapping up the "ALL CHEF PROVISIONERS" section. Instead, we should indent the second paragraph so it is clear it is talking about the `version` attribute.
I also fixed the broken `install` link.
> Fixing second paragraph indentation and link.

- website/source/docs/synced-folders/basic_usage.html.md
For issue https://github.com/mitchellh/vagrant/issues/7343
For what it's worth, `man mount` mentions that `mount` is only maintained for backward compatibility. The  recommended alternative `findmnt` doesn't seem to list the `id` value.
> Documentation for synced_folder's 'id' argument

- lib/vagrant/action/builtin/box_add.rb
- website/source/docs/cli/box.html.md
This commit bumps the box resume delay time to 24h and makes it a constant because I had a bugger of a time actually finding this in the code :frowny:.
Fixes GH-7272
> Bump box resume delay to 24h

- plugins/commands/resume/command.rb
- website/source/docs/cli/resume.html.md
Do not ignore the sentinal file when running resume and prevent running provisioners again.
- Fixes #6787 
The sentinal file was always being ignored when running the resume command. This is fixed along with allowing provision options to be used with resume. The code added aligns with the implementation in the reload command.
BTW, I did a ```git bisect``` to track it back to issue #5815 and commit 6f3ed13f75a1be66ed22f9bdcaa262e8077e458e. In the case of a resume command there was no options array passed into the ```machine.action``` call which caused the ```env.key?(:provision_ignore_sentinel)``` check in lib/vagrant/action/builtin/provision.rb to fail and ```ignore_sentinal``` defaulted to true.
> Do not ignore the sentinal file when running resume

- lib/vagrant/action/general/package.rb
- plugins/providers/virtualbox/action.rb
- plugins/providers/virtualbox/action/package.rb
- plugins/providers/virtualbox/action/package_setup_files.rb
- plugins/providers/virtualbox/action/package_setup_folders.rb
- plugins/providers/virtualbox/action/setup_package_files.rb
- templates/locales/en.yml
This commit separates the scratch and output directory creation from the main package middleware into its own PackageSetupFolders middleware. Additionally, the validation that ensures an output file does not exist is moved into a validation function that can be shared across multiple methods.
This refactor permits a pre-flight check to ensure box packaging would be successful before actually stopping the VM.
Fixes GH-7351
> Move pre-flight package validation to middleware

- plugins/providers/docker/provider.rb
The assumption that Docker is only native on Linux is no longer true with Docker for Mac/Windows and other efforts. :)
> Change: disable the linux switch (Docker for Mac/Windows, etc.)

- plugins/providers/virtualbox/action/prepare_nfs_settings.rb
- test/unit/plugins/providers/virtualbox/action/prepare_nfs_settings_test.rb
Vagrant was not behaving correctly in configurations where there was
a static IP on a VirtualBox `intnet` interface and a DHCP `:hostonly`
interface configured.
Since `machine_ip` attempted to get static addresses `||` dynamic
addresses, it would simply use the static machine address and
continue.
This commit corrects this behaviour by collecting all static and
dynamic addresses into the `machine_ip` array instead of just one or
the other.
The result of this is a correctly generated `/etc/exports` on the
host machine, allowing NFS mounts to work correctly in this type of
environment.
- GH-7289
> prepare_nfs_settings: Try harder to get all machine IPs.

- plugins/hosts/windows/cap/rdp.rb
This change cmdkey arguments are ok.
No need to manually enter credentials. Tested with different RDP ports on the same machine.
Please consider adding this improvement to vagrant code base.
> add RDP auto login with password

- lib/vagrant/bundler.rb
- plugins/commands/ssh/command.rb
This fixes a leak that occurs when interacting with Vagrant's bundler instance. Each call to Tempfile creates and generates a tempfile, but they are not cleaned up unless GC runs. Additionally, we were not deleting a few of the files.
This adds a new helper that creates a tmp path using `Dir::Tmpname`, and then returns a new open file handle for that path.
- Fixes #6301 
- Fixes #3469
- Fixes #6231
> Fix file leaking in bundler

- plugins/providers/virtualbox/driver/base.rb
- templates/locales/en.yml
Updated ./plugins/providers/virtualbox/driver/base.rb file, set max_network_adapters to 36 for Virtualbox so all 36 adapters are cleared prior to programming interfaces. This fix is per issue 7286 --> https://github.com/mitchellh/vagrant/issues/7286
Performed limited testing on the provided vagrantfile in issue 7286. To compare performance timing before and after the change. No Difference.
Performed Vagrant up on leaf1 5 times in a row and averaged the completion times using the following commands.
time vagrant up leaf1
vagrant destroy -f leaf1
time vagrant up leaf1
vagrant destroy -f leaf1
time vagrant up leaf1
vagrant destroy -f leaf1
time vagrant up leaf1
vagrant destroy -f leaf1
time vagrant up leaf1
vagrant destroy -f leaf
Vagrant up 1: 39.073 sec
Vagrant up 2: 37.678 sec
Vagrant up …
> Set max_network_adapters to 36 for Virtualbox

- plugins/kernel_v2/config/vm.rb
- test/unit/plugins/kernel_v2/config/vm_test.rb
As per the details in #7202 this has been fixed before by @mitchellh in 8655d21 but was regressed in 3e8fdc0.
This re-implements the changes, and adds a test that explicitly defines this behaviour.
All the unit tests still pass, and I have tested creating a Windows vagrant box with this change
> [#7202] Always forward SSH on Windows

- website/source/docs/synced-folders/nfs.html.md
Add section in sync folder documentation on how to modify sudoers file to not require a password when user's system utility location(s) are non-standard.
> Add section to NFS sync folder docs for non-standard system utility locations

- plugins/providers/virtualbox/action/import_master.rb
When using linked_clones, If the master VM is manually removed from VirtualBox a user will get a Box with UUID xxx-xxx-xxx Not Found error when trying to run `vagrant up` on a new machine.
This is because the master_id file exists `action/import_master.rb` sets ` env[:clone_id] = master_id_file.read.chomp if master_id_file.file?`
The `action/import.rb` code assumes if `env[:clone_id]` is set then it does not need to import the box, it can just clone it.  This is not true when the master VM has manually been removed.
The `action/import_master.rb` code  seemed to be setup to handle this situation with a nice `if` statement.  All the if statement did though was log a message.
```
if env[:clone_id] && env[:machine].provider.driver.vm_exists?(env[:clone_id])
@logger.info(
"Master VM for …
```
> Fixed linked clone failure when master VM is missing

- plugins/commands/init/command.rb
- templates/commands/init/Vagrantfile.erb
- test/unit/plugins/commands/init/command_test.rb
- website/source/docs/cli/init.html.md
This also adds a test suite for that particular command, updates the documentation, and adds some examples.
Fixes GH-5004
> Add --box-version to `vagrant init`

- plugins/providers/docker/action/create.rb
- test/unit/plugins/providers/docker/action/create_test.rb
This commit changes the way ports are aggregated in the Docker provider. Previously ports were aggregated by their "number", but that is not a truly unique representation. Instead, the protocol is now taken into account when generating the port map.
Fixes GH-5527
> providers/docker: Allow TCP and UDP ports on same number

- templates/commands/init/Vagrantfile.erb
This is unneeded because, by default, provisioners run as a privileged user.
Fixes GH-7295
> Remove sudo from generated Vagrantfile

- lib/vagrant/util/platform.rb
- test/unit/vagrant/util/platform_test.rb
This commit changes Vagrant::Util::Platform to cache the result of some common operations. These values are highly unlikely to change over the course of a single Vagrant run and they are only cached for that run.
> Cache the results of common operations

- lib/vagrant/bundler.rb
Revert 3f9fb2ef03a78bc9177a52d4629a5e80e6e42b2e from GH-2769
- For compatibility with ba77d4b533e449fa610531a7832b8fd1837eb9db
Fixes GH-7073
> Don't restore Gem::Specification.all if it's not being replaced

- contrib/bash/completion.sh
- plugins/providers/docker/command/exec.rb
- plugins/providers/docker/errors.rb
- plugins/providers/docker/plugin.rb
- templates/locales/providers_docker.yml
- test/unit/plugins/providers/docker/command/exec_test.rb
- website/source/docs/cli/non-primary.html.md
- website/source/docs/docker/commands.html.md
This adds a new core command, `docker-exec`, which allows the user to exec into an already-running container.
- Fixes #6566
- Fixes #5193
- Fixes #4904
- Fixes #4057
- Fixes #4179
- Fixes #4903
> Add docker-exec

- plugins/commands/box/command/update.rb
Vagrant's environment (which includes the known list of boxes and versions) is established at the start of the Vagrant run. This means that box downloads which occur during the run are not contained in the
set until the next run. This causes duplicate box downloads to raise an error in multi-machine Vagrantfiles.
This commit fixes that issue by pre-processing the machines by provider and version, creating a unique set of boxes to update.
Fixes GH-6042
> core/boxes: Do not update the same box twice

- contrib/sudoers/linux-fedora
- plugins/hosts/arch/cap/nfs.rb
- plugins/hosts/gentoo/cap/nfs.rb
Call it with "--no-pager"
Without it, if the user has a pager (more/less/etc.) configured and
call vagrant up with NFS shares, systemctl would use the pager, and
that would probably require an unnecessary key press from the user.
> Do not let NFS systemctl status use a pager

- plugins/providers/virtualbox/driver/version_4_1.rb
- plugins/providers/virtualbox/driver/version_4_2.rb
- plugins/providers/virtualbox/driver/version_4_3.rb
- plugins/providers/virtualbox/driver/version_5_0.rb
It seems that multiple parallel calls to `vboxmanage showvminfo` for the same VM can cause VBoxManage to fail with this type of error:
```
VBoxManage.exe: error: The object is not ready
VBoxManage.exe: error: Details: code E_ACCESSDENIED (0x80070005), component SessionMachine, interface IMachine, callee IUnknown
VBoxManage.exe: error: Context: "get_Groups((array).__asOutParam())" at line 513 of file VBoxManageInfo.cpp
```
(I am getting this on a Windows 10 host with VirtualBox 5.)
This can in turn cause `vm_exists?` to return false even though the VM might actually exist...
I propose that in order to detect missing VM, we look for `VBOX_E_OBJECT_NOT_FOUND` in the VBoxManage output and keep retrying when we get any other type of error.
This should make the fix to #2479 more resilient.
> Make virtualbox vm_exists? more resilient to VirtualBox transient failures

- plugins/provisioners/salt/provisioner.rb
This makes the masterless config setting more integrated with the other highstate logic by making it control a string (--local) instead of a separate code block.  In doing so, it also avoids the masterless section overriding the highstate setting.
This was essential for fixing masterless configurations on Windows, because the separate code block for masterless config did not include Windows logic.
Closes #6924
Fixes #6915
If you can point me to tests, I'm happy to try to work some in with this PR.  I have to warn you, though, I'm a Python-head, and not very good with Ruby.
> Salt: move masterless config to apply to all platforms

- lib/vagrant/action/general/package.rb
This is a hotfix for the issue introduced by GH-7353
It fixes the following error (reproduced with acceptance test in [vagrant-parallels](https://github.com/Parallels/vagrant-parallels) plugin):
```
...
Failures:
1) provider/parallels/package it should behave like provider/package with a running machine can package and bring the box back up
Failure/Error: expect(execute('vagrant', 'package')).to exit_with(0)
expected command to exit with 0 but got exit code: 1
stdout: You appear to be running Vagrant outside of the official installers.
Note that the installers are what ensure that Vagrant has all required
dependencies, and Vagrant assumes that these dependencies exist. By
running outside of the installer environment, Vagrant may not function
properly. To remove this warning, install …
```
> Require "vagrant/util/presence" in package action

- lib/vagrant/machine.rb
- plugins/provisioners/ansible/provisioner/host.rb
Combined, these two changes should reduce the number of race issues when bringing up multiple machines in parallel and using the ansible provisioner to configure each guest.
The state lock is required any time active_machines is used and anything that can trigger a state check on the other machines occurs. Currently the machine index assumes that it will only be updated by itself, however if you skip syncing of the current directory to the machine, it's possible to get to the ansible provisioner checking all the other machines for ssh_info while they are in the process of changing state, which will trigger a Locked Machine exception.
The use of a temp file to write out the inventory and then replace should ensure that if the contents have changed that ansible will only ever see the old or …
> Ansible parallel race

- .travis.yml
- vagrant.gemspec
This commit removes any ambiguity about how and why bundler is locked to a specific constraint. It also updates to a version of Bundler that is known to work (all plugin commands verified).
- Fixes #7415 
/cc @mitchellh
> Lock bundler to 1.12.5

- plugins/providers/virtualbox/driver/base.rb
- templates/locales/en.yml
Reverts mitchellh/vagrant#7293
Fixes https://github.com/mitchellh/vagrant/issues/7417
> Revert "Set max_network_adapters to 36 for Virtualbox"

- plugins/provisioners/ansible/provisioner/base.rb
- plugins/provisioners/ansible/provisioner/guest.rb
- plugins/provisioners/ansible/provisioner/host.rb
- test/unit/plugins/provisioners/ansible/provisioner_test.rb
Changes:
- systematically set ANSIBLE_ROLES_PATH environment variable when
galaxy_roles_path is defined.
- slightly refactor to introduce the concept of "provisioning working
directory" (possible usage in the future for resolving GH-7195)
- fix a bug in ansible-galaxy execution by the ansible_local provisioner
if the paths contains blank characters.
Fix #7269
Pull request created only to trigger the Travis CI checks
> provisioners/ansible: honor galaxy_roles_path when running ansible-playbook

- plugins/guests/redhat/cap/flavor.rb
- test/unit/plugins/guests/redhat/cap/flavor_test.rb
Hello,
that pull-request fixes the  #7427 issue: [CloudLinux](https://cloudlinux.com/) 7 is a RHEL 7 derivative distribution, so "rhel_7" flavor should be used for it.
[/etc/redhat-release](http://repo.cloudlinux.com/cloudlinux/7/os/x86_64/Packages/cloudlinux-release-7.2-1.el7.x86_64.rpm) content:
```
CloudLinux release 7.2 (Valeri Kubasov)
```
Thank you!
> Add CloudLinux 7 to RHEL 7 flavors.

- website/source/docs/boxes/base.html.md
Discovered while reviewing the markdown at BSDCan.
> Doc fix: Flesh out the list of base box guides.

- .travis.yml
- vagrant.gemspec
This Fixes GH-7441 by bumping the listen gem to a version that supports older OSX. The problem is that that older version does not support older Ruby, so we need to bump the Ruby version too.
> Bump listen gem

- plugins/guests/redhat/cap/configure_networks.rb
- test/unit/plugins/guests/redhat/cap/configure_networks_test.rb
This specifically addresses Red Hat/CentOS 7 guests were /sbin/ifconfig has been marked as deprecated. The 'net-tools' package is no longer part of the core group and is not installed by default.  As with the Debian guest, the /sbin/ip command is now favoured.
> Use ip instead of deprecated ifconfig for Red Hat/CentOS guests

- plugins/guests/linux/cap/insert_public_key.rb
The change to this file [10 days ago](https://github.com/mitchellh/vagrant/commit/e2b7e28082a4b5e546655526773477e8df833bdd#diff-715ea9eefd185460afff2f7cf7eb0c3b) removed a newline character at the end of each ssh public key added to the `authorized_keys` file. This meant that when another key was added, it continued on the same line as the one before and thus wasn't being detected/able to be used when a ssh connection came in with a key file.
With regards to https://github.com/mitchellh/vagrant/issues/7455 this is an (ugly) fix.
I'm sure someone knows a better command to concat a file and a string and append it to the `authorized_keys` file. But this does fix the problem.
> Append newline to each key added

- plugins/kernel_v2/config/vm.rb
- test/unit/plugins/kernel_v2/config/vm_test.rb
- website/source/docs/other/environmental-variables.html.md
This adds a new environmental variable `VAGRANT_BOX_UPDATE_CHECK_DISABLE`, which instructs Vagrant to not check for box updates when running regular Vagrant commands. This behaves the same as the existing `config.vm.box_update_check` configuration option, but can be set globally. Vagrantfile-supplied options will take precedence.
Fixes GH-7479
> core: Provide a way to globally disable box update checking

- plugins/providers/hyperv/scripts/get_vm_status.ps1
Use the version of Hyper-V instead of Powershell to determine which
exception is thrown by Get-VM. Also fixing an invalid catch statement,
since Powershell can not use variables to match thrown exceptions in
catch.
> Fixing version check and catch statement in get_vm_status

- lib/vagrant/box_collection.rb
The docs for Ruby say Pathname#rmtree will recursively delete, but apparently that is a lie, at least on Windows (see GH-7496). Switch to using FileUtils to ensure the directory is deleted.
Fixes GH-7496
> core/box_collection: Ensure removal

- vagrant.gemspec
Hi,
I want to use rest-client latest version 2.0 as vagrant's dependency.
https://rubygems.org/gems/rest-client
Is it possible?
I checked to pass the test suite by Ruby 2.2.5 and 2.3.1 by myself after I updated.
> Support rest-client 2.x as a dependency

- lib/vagrant/action/builtin/handle_forwarded_port_collisions.rb
Currently, the supported way (see GH#1922) to disable the default port
2222 port forward is:
config.vm.network :forwarded_port, guest: 22, host: 2222, disabled: true
However, the port collision detection runs on all ports, regardless of
the `disabled` flag.  This leads it to attempt to connect to port
2222, notice it is taken, and abort with a port conflict -- even
though it will not be attempting to use the port at all.
Skip disabled ports when doing port conflict detection.
A workaround that does not require a Vagrant upgrade to one containing
this fix is to instead set `auto_correct` on the disabled port:
config.vm.network :forwarded_port, guest: 22, host: 2222, disabled: true, auto_correct: true
This allows the disabled port to be reshuffled off to some other
unused port.
> Skip checking for conflicts on ports that are disabled

- lib/vagrant/plugin/state_file.rb
This makes updates atomic, so it's useful generally.  However
I'm making this change specifically to support rpm-ostree.
For more information, see:
https://bugzilla.redhat.com/show_bug.cgi?id=1352152
> plugin: Write out state file via create-new-then-rename

- plugins/guests/ubuntu/guest.rb
`lsb_release` command is included in lsb-release package. Sometimes this is not installed; ex: Docker official Ubuntu image.
```sh
$ docker run --rm -it ubuntu:precise bash -l -c 'lsb_release -i'
bash: lsb_release: command not found
$ docker run --rm -it ubuntu:trusty bash -l -c 'lsb_release -i' 
Distributor ID: Ubuntu
$ docker run --rm -it ubuntu:xenial bash -l -c 'lsb_release -i'
bash: lsb_release: command not found
```
`/etc/os-release` is included in base-files package, so this is more reliable than lsb_release.
```sh
$ docker run --rm -it ubuntu:precise bash -l -c '. /etc/os-release && echo $ID'  
ubuntu
$ docker run --rm -it ubuntu:trusty bash -l -c '. /etc/os-release && echo $ID' 
ubuntu
$ docker run --rm -it ubuntu:xenial bash -l -c '. /etc/os-release && echo $ID'
ubuntu
```
This …
> A more reliable way to detect Ubuntu

- plugins/synced_folders/rsync/helper.rb
Resolves #6702 without reverting #6568 
- Fixes GH-6702
- Fixes GH-7046
> translate windows path

- lib/vagrant/action/builtin/box_add.rb
> Strip leading slash left in front of drive letter by uri.path

- plugins/guests/linux/cap/public_key.rb
- test/unit/plugins/guests/linux/cap/remove_public_key_test.rb
This fixes the issue reported in https://github.com/mitchellh/vagrant/issues/7610.  I'm not sure if any additional test cases are necessary to cover this; I can certainly write some if they are.
> fix for #7610 (incorrect permissions on ~/.ssh/authorized_keys causes authentication failure after insecure keypair replacement)

- plugins/hosts/arch/cap/nfs.rb
Fixes #7629.
nfs-server.service seems to load kernel modules it needs itself, while nfsd appears in `/proc/filesystems` only after the kernel module has been loaded, so vagrant fails to detect NFS server until it's started first time after the system has booted. The updated command checks if the NFS service actually exists and hopes that it'll figure the stuff out itself.
`list-unit-files` is utilized rather than `list-units` because systemd seems to not list units that are disabled: https://lists.fedoraproject.org/pipermail/devel/2011-November/159117.html
The issue appeared at d29acc8982323b6f9e98b08d60ff4b8b5f0b9938. The fix wasn't wrong as checking nfs doesn't really make sense because it's client-side capability but insufficiend because it fails until the kernel module is loaded which …
> Detect NFS server by service name on Arch

- plugins/guests/ubuntu/guest.rb
This fixes Ubuntu guest detection to fallback to the old detection method.
- Reverts GH-7524 (mostly)
- Fixes GH-7625
> guests/ubuntu: Revert detection

- plugins/guests/bsd/cap/public_key.rb
- test/unit/plugins/guests/bsd/cap/remove_public_key_test.rb
This is an extension of a6760dd8e7743e048cb2f38c474e05889356e8ac, applied to BSD guests.
Related to #7610
> Fix `authorized_keys` permissions for BSDs

- Vagrantfile
While looking into adding some tests for PR #7623 I noticed that the development vagrant VM doesn't install the proper version of Ruby neither does it install the necessary dependencies to immediately run the test suite.
These changes fix this.
> Update development vagrant VM

- vagrant.gemspec
Prevents recent version of ruby_dep from being used to satisfy the listen gem dependency as it requires a minimum ruby version of 2.2.5
> Constrain ruby_dep gem versions to prevent constraints on ruby versions

- plugins/hosts/darwin/cap/rdp.rb
- test/unit/plugins/hosts/darwin/cap/rdp_test.rb
Changes introduced in 982af05 caused the RDP configuration file to be written
with all settings on one line instead of one setting per line. The Microsoft
Remote Desktop client for OS X rejects these configuration files as being
malformed. This patch restores the configuration to one line per setting and
adds tests to guard against regression.
> Fix RDP connections on OS X

- plugins/guests/bsd/guest.rb
- plugins/guests/dragonflybsd/guest.rb
- plugins/guests/dragonflybsd/plugin.rb
- plugins/guests/openbsd/cap/halt.rb
- plugins/guests/openbsd/plugin.rb
- test/unit/plugins/guests/openbsd/cap/halt_test.rb
Adds guest detection for DragonFly BSD. Removes Darwin from matching base BSD guest. Provide custom halt behavior for OpenBSD which requires `-h` option to be used on versions prior to 5.7.
http://cvsweb.openbsd.org/cgi-bin/cvsweb/src/sbin/shutdown/shutdown.8?rev=1.40&content-type=text/x-cvsweb-markup
http://cvsweb.openbsd.org/cgi-bin/cvsweb/src/sbin/shutdown/shutdown.c?rev=1.40&content-type=text/x-cvsweb-markup
> guests/bsds: shutdown fixes and dragonfly detection

- plugins/communicators/ssh/communicator.rb
- test/unit/plugins/communicators/ssh/communicator_test.rb
Fixes issues reported in #7613. Filters command stdout output to remove any output that may be been previously generated while setting up the shell. This also adds test coverage to the SSH communicator.
> Filter command output in SSH communicator

- plugins/guests/linux/cap/network_interfaces.rb
- test/unit/plugins/guests/linux/cap/network_interfaces_test.rb
Ensure the order of discovered network interfaces is always consistent. Addresses issue described in #7668
> guests/linux: Always order discovered network interfaces

- lib/vagrant/environment.rb
- test/unit/vagrant/environment_test.rb
- website/source/docs/other/environmental-variables.html.md
These changes allow the VAGRANT_DOTFILE_PATH variable to contain paths relative to the Vagrantfile's location. This allows setting this variable globally in a `.bashrc` to avoid conflicts in Dropbox-shared directories while still allowing Vagrant commands to be issued from any project subdirectory.
This seems to be a common request and sidesteps the usual hack of setting the variable at the top of the Vagrantfile and reinvoke itself.
A placeholder `{}` at the start of the path is replaced by the path to the Vagrantfile. I'm personally using this to have non-conflicting `.vagrant` directories like so:
```
export VAGRANT_DOTFILE_PATH="{}/.vagrant-${USER}@${HOSTNAME}"
```
> Support Vagrantfile-relative VAGRANT_DOTFILE_PATHs

- plugins/guests/bsd/cap/halt.rb
- plugins/guests/darwin/cap/halt.rb
- plugins/guests/esxi/cap/halt.rb
- plugins/guests/linux/cap/halt.rb
- plugins/guests/smartos/cap/halt.rb
- plugins/guests/solaris/cap/halt.rb
- plugins/guests/solaris11/cap/halt.rb
- plugins/guests/suse/cap/halt.rb
- plugins/guests/tinycore/cap/halt.rb
- test/unit/plugins/guests/bsd/cap/halt_test.rb
- test/unit/plugins/guests/esxi/cap/halt_test.rb
- test/unit/plugins/guests/linux/cap/halt_test.rb
- test/unit/plugins/guests/openbsd/cap/halt_test.rb
- test/unit/plugins/guests/smartos/cap/halt_test.rb
- test/unit/plugins/guests/solaris/cap/halt_test.rb
- test/unit/plugins/guests/solaris11/cap/halt_test.rb
- test/unit/plugins/guests/suse/cap/halt_test.rb
- test/unit/plugins/guests/tinycore/cap/halt_test.rb
When halting the VM the sshd may be stopped before the ssh connection in use has been closed. This causes an SSHDisconnected error to bubble up and the UI to display an error message. Change rescues out the SSHDisconnected exception to prevent error message from surfacing.
> guests: Prevent ssh disconnect from causing error on halt

- plugins/guests/linux/cap/mount_virtualbox_shared_folder.rb
- test/unit/plugins/guests/linux/cap/mount_virtual_box_shared_folder_test.rb
Current usage of `id -g` incorrectly uses group name instead of owner name. Pulling the effective group of the user should only be used in cases where a special group has not been requested. This issue was referenced in https://github.com/mitchellh/vagrant/issues/7616#issuecomment-239135781 and an issue was created #7662
This PR adjusts the use of the effective group to only happen when the group matches the user and the group is not found.
Additional updates: 
* allow owner and group IDs to be provided as integers or strings
* tests 
_NOTE: Replaces #7683_
> Only use effective group when appropriate

- plugins/commands/package/command.rb
- test/unit/plugins/commands/package/command_test.rb
Fixes an issue referenced in #5070 by providing a temporary machine data directory. Includes some initial basic tests on the `package` command that includes testing for a valid machine data directory when using `--base` option.
> Machine data directory for base box package

- plugins/guests/darwin/cap/rsync.rb
- plugins/guests/freebsd/cap/rsync.rb
- plugins/guests/linux/cap/rsync.rb
- plugins/guests/netbsd/cap/rsync.rb
- plugins/guests/openbsd/cap/rsync.rb
- plugins/guests/smartos/cap/rsync.rb
- plugins/guests/solaris/cap/rsync.rb
- plugins/guests/solaris11/cap/rsync.rb
- plugins/synced_folders/rsync/default_unix_cap.rb
- test/unit/plugins/guests/linux/cap/rsync_test.rb
- test/unit/plugins/guests/smartos/cap/rsync_test.rb
This address #5256 by ignoring any files that are excluded from the rsync when changing the owner. This PR includes the initial refactoring of rsync capability implementations and also includes the `:chown` option where it was missing before. Also updates `find | xargs` to POSIX compat `find -exec`.
> Ignore files excluded from sync on chown

- plugins/synced_folders/nfs/synced_folder.rb
- templates/locales/en.yml
- website/source/docs/synced-folders/nfs.html.md
Include warning when mounting synced folder using NFS with possibly invalid options. Adds note to documentation about NFSv4 and UDP.
> Add NFSv4 warning and information

- lib/vagrant/util/subprocess.rb
- test/unit/vagrant/util/subprocess_test.rb
Previously, there was no way to close the STDIN stream of a subprocess,
so commands that read from stdin in a subprocess would hang forever,
such as `/bin/sh -s`. If one tried to close the stdin, the
IO.select() call in Subprocess#execute would raise an error for calling
select() on a closed IO.
Here's a concrete example of a command that needs to close STDIN to work
properly:
```ruby
script = SOME_VERY_LONG_STRING
command = %w(ssh foo.example.com /bin/sh -s foo bar)
result = ::Vagrant::Util::Subprocess.execute(*command) do |type, data_or_io|
if type == :stdin
data_or_io.write(script)
data_or_io.write("\n")
data_or_io.close
next
end
puts "Remote: #{data_or_io}"
end
```
> Allow closing a Vagrant::Util::Subprocess's STDIN

- plugins/communicators/winrm/shell.rb
- test/unit/plugins/communicators/winrm/shell_test.rb
This ensures that all winrm commands open a new connection and close it after the command. While the previous shell code is "mostly" leak proof, it keeps a connection open for each `WinRMShell` instance and does not close them until the vagrant process exits. Thats generally a more efficient approach and reduces connection startup overhead for multiple commands. In the case of Windows 2008 R2, the default maximum open shells is 5. So if one uses multiple vagrant plugins, it may be easy to exceed this maximum and errors will ensue.
The cost savings of openning new connections really does not outweigh the error scenarios possible here on Windows 2008R2 (and Windows 7).
> fix #7489 preventing winrm connection leakage

- lib/vagrant/util/safe_exec.rb
Detects Windows platform within `SafeExec.exec` and uses `Subprocess` instead of `fork`. Related to #6938. 
I am curious if there's actually a need for two code paths here. Always running through `Subprocess` when using `Kernel.exec` directly fails seems like a more consistent implementation. Any thoughts?
> [windows] Use subprocess for safe_exec on windows

- plugins/guests/linux/cap/network_interfaces.rb
- test/unit/plugins/guests/linux/cap/network_interfaces_test.rb
Always provide sorted ethernet devices at the start of the network devices list.
Fixes #7844
> guests/linux: Place ethernet devices at start of device list

- plugins/communicators/winrm/communicator.rb
- test/unit/plugins/communicators/winrm/communicator_test.rb
As of the RTM release of Windows Nano, the initial availability check of the winrm communicator hangs. Not just on RTM but all previous technical previews of nano, the version of the winrm gem used by vagrant cannot speak powershell to nano. I plan to refactor the communicator code later touse the newer winrm that can talk to nano. This PR switches the initial availability check to `:cmd` so that at least a basic `vagrant up` with `--no-provision` can succeed. If vagrant releases before the new winrm refactor, this small change will get other tools like Test-Kitchen working with vagrant on Windows Nano.
> Use the cmd shell to check winrm availability to fix `vagrant up --no-provision` on nano

- plugins/guests/redhat/cap/configure_networks.rb
`vagrant version - 1.8.5`
`VirtualBox version - 5.1.4r110228`
assuming a scenario - vagrant up -> power off -> vagrant up
vagrant will stuck on the network configuration
`DEBUG ssh: stdout: mv: overwrite '/etc/sysconfig/network-scripts/ifcfg-eth0'?`
`DEBUG ssh: Sending SSH keep-alive...`
> Fix CentOS7 network config - do not prompt before overwriting

- plugins/guests/linux/cap/nfs.rb
I ran into a very weird bug when trying to run openwrt (x86) machines on vagrant, they locked when mounting nfs, even when it mounted successfully.
I discovered it was because the `/sbin/init` binary in openwrt ignores the `--version` parameter and open a menu, stoping the box creation process.
This fix should work for any non upstart (and the ones that use upstart) Linux distros.
> Fix non upstart linux nfs mounts

- plugins/providers/docker/driver.rb
See: https://github.com/mitchellh/vagrant/issues/7597.
Due to the childprocess gem setting STDIN to a pipe, Docker will fail as it requires STDIN to be a TTY if run with --interactive.
> Remove --interactive flag from Docker command

- lib/vagrant/environment.rb
- test/unit/vagrant/environment_test.rb
Fixes #7135: config.vm.provider not setting provider in multi-machine Vagrantfile
Steps to reproduce:
1. Make `Vagrantfile`
2. Configure only one provider using `config.vm.provider`.
3. `vagrant up`
4. Default provider may get used instead of configured one.
I tracked the bug to these lines in lib/vagrant/environment.rb:
```
root_config.vm.__providers.reverse.each_with_index do |key, idx|
config[key] = idx
end
```
Later in the same function it increases the provider's priority if the provider was mentioned in the config:
```
priority = config[key] + max_priority if config.key?(key)
```
However, if the index of the provider in the `__providers` list is 0, as it would be if it's the only one, priority ends up being set to the max priority instead of to the max priority + 1. That means there …
> Fix Vagrant not prioritizing configured providers correctly

- plugins/guests/linux/cap/network_interfaces.rb
- test/unit/plugins/guests/linux/cap/network_interfaces_test.rb
Always pull ordered ethernet devices to the head of the list. Ensure
aliases are not included.
Fixes: #7858
Fixes: #7458
Fixes: #7876
> guests/linux: Update network interface sorting implementation

- plugins/provisioners/ansible/provisioner/guest.rb
For the local Ansible provisioner, I would like to suggest a more robust way of Ansible guest detection. The current way of [checking return values](https://github.com/mitchellh/vagrant/blob/a4f45a18a653bd5b157a00c5ffaa3ba0c74ea5f5/plugins/provisioners/ansible/provisioner/guest.rb#L55-L60) has already caused trouble for the Ansible 2.0 detection (#6869). Future changes to the Ansible CLI and the return codes may break the detection suggested in #6869 again. Therefore, this PR changes the detection behavior to check that `ansible-galaxy` and `ansible-playbook` are both included in `$PATH` and executable. What do you think?
> More robust Ansible detection for local Ansible provisioner

- plugins/provisioners/ansible/config/base.rb
- plugins/provisioners/ansible/provisioner/base.rb
- plugins/provisioners/ansible/provisioner/host.rb
- test/unit/plugins/provisioners/ansible/config/guest_test.rb
- test/unit/plugins/provisioners/ansible/config/host_test.rb
- test/unit/plugins/provisioners/ansible/config/shared.rb
- test/unit/plugins/provisioners/ansible/provisioner_test.rb
- website/source/docs/provisioning/ansible_common.html.md
The ansible-playbook command is currently hardcoded for the ansible and
ansible_local provisioners. This patch adds the config option
playbook_command to allow the user to change the command.
This may come in handy for people who want to use some kind of wrapper around ansible-playbook.
For example, I want to use vagrant to build an OpenStack test environment using openstack-ansible (see https://github.com/openstack/openstack-ansible). openstack-ansible installs a script at `/usr/local/bin/openstack-ansible` which acts as a wrapper around ansible-playbook and sets some environment variables and adds some arguments to ansible-playbook.
Having the possibility to specify openstack-ansible as playbook_command would make provisioning much more comfortable in this case.
> Make ansible-playbook command configurable

- plugins/guests/redhat/cap/flavor.rb
Virtuozzo linux is based on RHEL and needs the same type of network configuration.
> Add Virtuozzo Linux 7 to list of RHEL flavors

- plugins/provisioners/salt/config.rb
- plugins/provisioners/salt/provisioner.rb
- website/source/docs/provisioning/salt.html.md
Makes the salt provisioner act as documentation states. Due to provisioner behavior, default values are conditionally set if local path exists.
Fixes #6624
> provisioners/salt: Synchronize config defaults with documentation

- lib/vagrant/errors.rb
- plugins/guests/openbsd/cap/rsync.rb
- templates/locales/en.yml
- test/unit/plugins/guests/openbsd/cap/rsync_test.rb
The `pkg_add` command will return `0` when a package requested for
installation is not found. This adds a validation check to ensure
the rsync package is actually installed on the guest.
Fixes: #7898
> guests/openbsd: Check package installation after installing package

- plugins/guests/redhat/cap/configure_networks.rb
- test/unit/plugins/guests/redhat/cap/configure_networks_test.rb
When configuring network devices force NetworkManager to reload new
configuration files as they appear. This prevents NetworkManager from
attempting to continue managing devices on initial start up.
> guests/redhat: Force NetworkManager to reload device configurations

- plugins/guests/arch/cap/change_host_name.rb
- plugins/guests/arch/cap/configure_networks.rb
- plugins/guests/arch/cap/nfs.rb
- plugins/guests/arch/cap/rsync.rb
- plugins/guests/atomic/cap/change_host_name.rb
- plugins/guests/bsd/cap/nfs.rb
- plugins/guests/bsd/cap/public_key.rb
- plugins/guests/darwin/cap/change_host_name.rb
- plugins/guests/debian/cap/change_host_name.rb
- plugins/guests/debian/cap/configure_networks.rb
- plugins/guests/debian/cap/nfs.rb
- plugins/guests/debian/cap/rsync.rb
- plugins/guests/gentoo/cap/change_host_name.rb
- plugins/guests/linux/cap/nfs.rb
- plugins/guests/linux/cap/public_key.rb
- plugins/guests/netbsd/cap/change_host_name.rb
- test/unit/plugins/guests/bsd/cap/nfs_test.rb
- test/unit/plugins/guests/linux/cap/mount_nfs_test.rb
Also preserves some backwards compatibilities that are ineffective when `set -e` is in use.
Fixes #7739
> Remove `set -e` usage for better shell compatibility

- plugins/provisioners/puppet/config/puppet.rb
- plugins/provisioners/puppet/provisioner/puppet.rb
- website/source/docs/provisioning/puppet_apply.html.md
Completes #7252 which did not include actual usage of configuration defined environment variables.
Fixes: #2270
> Puppet environment variables

- lib/vagrant/errors.rb
- lib/vagrant/util.rb
- plugins/hosts/linux/cap/nfs.rb
- templates/locales/en.yml
- test/unit/plugins/hosts/linux/cap/nfs_test.rb
This builds on #7939 and refactors the implementation to utilize the StringBlockEditor and unify how modifications are applied to the /etc/exports file within the capability.
Fixes: #7938
> Refactor host linux nfs capability

- plugins/commands/box/command/prune.rb
- plugins/commands/box/command/root.rb
- test/unit/plugins/commands/box/command/prune_test.rb
- website/source/docs/boxes/versioning.html.md
- website/source/docs/cli/box.html.md
As discussed in #6863 with @chrisroberts a clean branch for the command. Silly rebase. :)
**Command: `vagrant box prune`**
This command removes old versions of installed boxes. If the box in currently in use vagrant will ask you if you to confirm.
* `--provider PROVIDER` - The specific provider type for the boxes to destroy.
* `--dry-run` - Only print the boxes that would be removed.
* `--name NAME` - The specific box name to check for outdated versions.
* `--force` - Destroy without confirmation even when box is in use.
Fixes: #4412 #5633
> Feature command box prune

- plugins/kernel_v2/config/vm.rb
- test/unit/plugins/kernel_v2/config/vm_test.rb
This builds off #6836 to make the `guestpath` parameter optional and includes test coverage on named usage.
Fixes: #6836
> Named synced folders

- plugins/provisioners/salt/provisioner.rb
- test/unit/plugins/provisioners/salt/provisioner_test.rb
> Fix Hash constant construction in Salt provisioner

- plugins/guests/linux/cap/network_interfaces.rb
- test/unit/plugins/guests/linux/cap/network_interfaces_test.rb
As pointed out in referenced fixed issue, the alias naming is not consistent and filtering via `:` character alone is insufficient. This updates to only match interfaces that lack special characters when filtering sorted interfaces to the top of the list.
Fixes: #7988
> Only match interfaces without special characters

- lib/vagrant/errors.rb
- lib/vagrant/util/downloader.rb
- plugins/provisioners/shell/config.rb
- plugins/provisioners/shell/provisioner.rb
- templates/locales/en.yml
- test/unit/plugins/provisioners/shell/provisioner_test.rb
- test/unit/vagrant/util/downloader_test.rb
- website/source/docs/provisioning/shell.html.md
Allows checksum validation on downloaded files via Util::Downloader
using MD5 and/or SHA1 checksums. This also integrates checksum validation
support with the shell provisioner for downloaded remote files.
Fixes: #6323
> Add md5 and sha1 checksum support to Downloader.

- lib/vagrant.rb
- lib/vagrant/bundler.rb
- lib/vagrant/plugin/manager.rb
- lib/vagrant/shared_helpers.rb
- plugins/commands/plugin/command/mixin_install_opts.rb
- test/unit/vagrant/plugin/manager_test.rb
Updates to plugin handling:
* Support plugin auto-loading with fallback to `/` style name loading
* Restrict valid Gem sources to only list provided
* Properly install local gems with remote dependencies
* Remove deprecated `--plugin-prerelease` option
* Add debug logging output to `Vagrant::Bundler`
> Plugin handling updates

- CHANGELOG.md
- plugins/providers/hyperv/action/import.rb
- plugins/providers/hyperv/driver.rb
- plugins/providers/hyperv/scripts/import_vm_vmcx.ps1
- plugins/providers/hyperv/scripts/import_vm_xml.ps1
Added an import script that reads the new vmcx format with powershell. It uses native commands to read the format and create the machine the same way as it does right now with the XML's. This way there is no need anymore to hack an XML to get Hyper-V boxes to work.
As Hyper-V support seems to get close in packer, we really need this small feature added so we can start using those boxes as quickly as possible.
This should fix: #7706 and #6102
> Add support for vmcx (Hyper-V binary config format) to the Hyper-V import script

- plugins/provisioners/ansible/config/base.rb
- plugins/provisioners/ansible/provisioner/base.rb
- plugins/provisioners/ansible/provisioner/guest.rb
- plugins/provisioners/ansible/provisioner/host.rb
- test/unit/plugins/provisioners/ansible/config/guest_test.rb
- test/unit/plugins/provisioners/ansible/config/host_test.rb
- test/unit/plugins/provisioners/ansible/config/shared.rb
- test/unit/plugins/provisioners/ansible/provisioner_test.rb
- website/source/docs/provisioning/ansible_common.html.md
- website/source/docs/provisioning/ansible_intro.html.md
With this new option defined, the `ansible-galaxy` and `ansible-playbook` commands generated by the Ansible provisioners will be executed with the `ANSIBLE_CONFIG` environment variable set accordingly.
Resolve GH-7195
> Add config_file option to both Ansible provisioners

- lib/vagrant.rb
- lib/vagrant/bundler.rb
- templates/locales/en.yml
Include extra logging during initialization to display error if encountered
and solution set prior to performing activations.
> Provide nice error output when plugin initialization fails

- bin/vagrant
- lib/vagrant.rb
- lib/vagrant/bundler.rb
- lib/vagrant/errors.rb
- lib/vagrant/plugin/manager.rb
- lib/vagrant/plugin/state_file.rb
- plugins/commands/plugin/action/update_gems.rb
- test/unit/plugins/commands/plugin/action/update_gems_test.rb
- test/unit/vagrant/plugin/manager_test.rb
- test/unit/vagrant/plugin/state_file_test.rb
Provides better update support due to delayed activation which prevents overly restrictive constraints being applied. Includes better internal management to clean non-required gems as needed. Some refactoring cleanup to reduce code duplication. More logging output.
> Plugins internal state

- .travis.yml
- lib/vagrant/bundler.rb
Include detection of running context (within Bundler or not) and
load the "builtin" gems based on that context.
> Always apply builtin constraints within dependency restrictions

- website/source/docs/cli/up.html.md
Found that some info on the cli documentation did not line up (other mentions of no- usage, but not on provision, which is an option.)
Was also considering adding links to the in depth pages so users could find information quicker, similar to "providers", as the cli documentation is usually a hub for first-time users. Please let me know if you would like me to add this as well.
> Vagrant: Modifying CLI Documentation.

- website/source/docs/cli/snapshot.html.md
Prior to this commit, the snapshot save command did not have the vm_name as part of the command.  
After this commit, the snapshot save command docs match the CLI --help.
> Update snapshot save documentation

- website/source/docs/multi-machine/index.html.md
Users learning about multi-machine definitions will likely be interested in the linked tip...this connects the two pages.
> link to tip section about looping over VM definitions

- plugins/providers/hyperv/scripts/import_vm_vmcx.ps1
When you set the memory of a HyperV machine to something lower than the original range it fails. 
This is because it sets the current memory before adjusting the range, which makes the command invalid.
> Hyper-V VMCX: Setting memory too low or high makes the import script fail.

- lib/vagrant.rb
- plugins/commands/plugin/action/repair_plugins.rb
- templates/locales/en.yml
Provide better error messages and context around plugin errors. Include original exception information and full backtrace in logger output.
> Logger and error outputs

- website/source/docs/cli/plugin.html.md
There were two sections for `Plugin Repair` but the last one's content was erroneous (contained `Plugin Update` docs).
> deleted redundant and erroneous text in Plugins documentation

- lib/vagrant/bundler.rb
This does not get automatically loaded before usage so ensure
it is properly loaded for plugin usage.
Fixes: #8069
> Explicitly require name_tuple

- lib/vagrant/bundler.rb
Installation solution sets in 2.2.5 can end up out of order (not seen
in 2.3.1) causing LoadErrors when the specification is in the solution
set during validation. This detects the missing spec within the solution
and if found will move spec to the start of the solution set and retry
solution activation.
> Detect load failure within solution set and retry if found

- plugins/guests/redhat/cap/change_host_name.rb
- plugins/guests/redhat/cap/configure_networks.rb
RHEL-7 / Current Fedora versions tend to use NetworkManager for configuring the networks, and `service network restart` might fail.
If the `NetworkManager` service is running, we should restart it, otherwise we try restarting `network`.
The issue was introduced in `v1.8.7`.
See #7994.
> Fix `service network restart` on RHEL-7 / Fedora

- plugins/guests/linux/cap/mount_smb_shared_folder.rb
- plugins/guests/linux/cap/mount_virtualbox_shared_folder.rb
- plugins/guests/linux/cap/nfs.rb
This resolves vagrant issue #7368 as "/sbin/init --version" outputs error message if the "--version" command line option is not known, but as there is no tty the error message mentioned in #7368 is shown.
> redirect any output to stderr by /sbin/init to /dev/null when checking for upstart capability

- lib/vagrant/action/general/package_setup_files.rb
- lib/vagrant/action/general/package_setup_folders.rb
- plugins/providers/hyperv/action.rb
- plugins/providers/hyperv/action/export.rb
- plugins/providers/hyperv/action/package.rb
- plugins/providers/hyperv/action/package_metadata_json.rb
- plugins/providers/hyperv/action/package_setup_files.rb
- plugins/providers/hyperv/action/package_setup_folders.rb
- plugins/providers/hyperv/action/package_vagrantfile.rb
- plugins/providers/hyperv/driver.rb
- plugins/providers/hyperv/scripts/export_vm.ps1
- plugins/providers/hyperv/scripts/get_network_mac.ps1
- plugins/providers/virtualbox/action/package_setup_files.rb
- plugins/providers/virtualbox/action/package_setup_folders.rb
First draft of packaging of Hyper-V boxes. Uses the same logic as the Virtualbox package command./
Need to refactor the `package_*.rb` files since right now they are copies of the virtualbox versions, might just put them in general and extend them.
Currently in my dev enviroment i run into the problem that bsdtar is not doing its job. It doesn't tar all the files for some weird reason when they are given as seperate arguments.
From the log:
`"C:\\HashiCorp\\Vagrant\\embedded\\gnuwin32\\bin/bsdtar.EXE", "-czf", "G:/laragon/www/devlocal/package.box", "./Vagrantfile", "./vagrant_private_key", "./Virtual Hard Disks", "./Virtual Machines"]`
Add or remove `--base` switch to select any existing virtual machine?
> Package Hyper-V boxes

- plugins/guests/linux/guest.rb
We use boot2docker.
Succeed in Vagrant 1.8.6.
```
DEBUG guest: Trying: tinycore
DEBUG ssh: Re-using SSH connection.
INFO ssh: Execute: cat /etc/issue | grep 'Core Linux' (sudo=false)
DEBUG ssh: Exit status: 0
INFO guest: Detected: tinycore!
```
Fails in Vagrant 1.9.0 and 1.8.7.
```
DEBUG guest: Trying: tinycore
DEBUG ssh: Re-using SSH connection.
INFO ssh: Execute: if test -r /etc/os-release; then
source /etc/os-release && test xCore Linux = x$ID && exit
fi
if test -x /usr/bin/lsb_release; then
/usr/bin/lsb_release -i 2>/dev/null | grep -qi Core Linux && exit
fi
if test -r /etc/issue; then
cat /etc/issue | grep -qi Core Linux && exit
fi
exit 1
(sudo=false)
DEBUG ssh: stderr: sh: Linux: unknown operand
DEBUG ssh: stderr: grep: Linux: No such file or directory
DEBUG ssh: Exit status: 1
``` …
> Fix quotes

- plugins/guests/redhat/cap/change_host_name.rb
- plugins/guests/redhat/cap/configure_networks.rb
Fix theses bugs : 
https://github.com/mitchellh/vagrant/issues/8142 https://github.com/mitchellh/vagrant/issues/8096
For RHEL7 and Fedora 25 `/etc/init.d/network restart` already  shutdown interfaces and restart NM if needed.
In start() :
```
if [ "$(LANG=C nmcli -t --fields running general status 2>/dev/null)" = "running" ]; then
nmcli connection reload
fi
```
In stop() :
```
for i in $vpninterfaces $xdslinterfaces $bridgeinterfaces $vlaninterfaces $remaining; do
unset DEVICE TYPE
(. ./ifcfg-$i
if [ -z "$DEVICE" ] ; then DEVICE="$i"; fi
if ! check_device_down $DEVICE; then
action $"Shutting down interface $i: " ./ifdown $i boot
[ $? -ne 0 ] && rc=1
fi
)
done
```
Where $remaining include all "others" interfaces including eth*
It work for `NM_CONTROLLED=X` where X = yes or no 
This reverts …
> Revert "Fix `service network restart` on RHEL-7 / Fedora"

- website/source/docs/other/debugging.html.md
The command "vagrant up --debug &> vagrant.log" is not valid on Windows.
On Windows, you need to do: vagrant up --debug > vagrant.log 2>&1
> Debug Documentation - &> is not valid on Windows

- plugins/providers/hyperv/action/import.rb
- plugins/providers/hyperv/scripts/has_vmcx_support.ps1
Vagrant now checks if your Windows version has support for VMCX and then uses the VMCX file.
The reason for this is because the support for [HyperV in Packer is now merged](https://github.com/mitchellh/packer/pull/2576), but, it always creates an XML file, I assume for backwards compatibility, which does make sense especially for Windows versions before 10 which are still used. Vagrant should prefer using the newer format when supported, even when the old XML format is available.
The check consists of checking if the Windows version is greater or equal to 10, since Windows 10, and Windows Server 2016 both use the binary format, and they won't change back to the old config in future releases I assume.
To test, I loaded up about 5 of the HyperV boxes on Atlas with 1.9.1 and with this …
> Harden VMCX support

- lib/vagrant.rb
- test/unit/vagrant/util/env_test.rb
> Prevent generating environment variables with invalid empty names

- lib/vagrant/bundler.rb
This adjustment allows for extensions to be properly discovered after
plugin gem specifications have been activated and prevent warning messages.
Fixes: #8190, #8147
> Set base directory to parent directory within plugin specs

- website/source/docs/virtualbox/configuration.html.md
The previous code only worked on Vagrant 1.8.x, but not on 1.9.x or newer.
> website: make linked clones work w/ 1.8.0 & newer

- plugins/guests/arch/cap/configure_networks.rb
Vagrant fails to configure multiple network interfaces for Arch Linux guests due to the syntax error in the generated command for the network configuration:
```
mv '/tmp/vagrant-network-eth1-1483336033-0' '/etc/netctl/eth1' &&
ip link set 'eth1' down &&
netctl restart 'eth1' &&
netctl enable 'eth1'
&&
mv '/tmp/vagrant-network-eth2-1483336034-1' '/etc/netctl/eth2' &&
ip link set 'eth2' down &&
netctl restart 'eth2' &&
netctl enable 'eth2'
ln -s '/etc/systemd/system/netctl@eth1.service' '/etc/systemd/system/multi-user.target.wants/netctl@eth1.service'
bash: line 9: syntax error near unexpected token `&&'
bash: line 9: ` && '
```
This PR strips the newline before `&&` that causes the syntax error.
> guests/arch: fix configuring multiple network interfaces fails

- website/source/docs/provisioning/salt.html.md
Since the verbose-attribute isn't explicitly mentioned in the salt-provisioner it is hard to find out it can (and must) be set to get the result of the salt highstate-command.
> Add hint for .verbose-attribute

- website/source/docs/synced-folders/nfs.html.md
Unfortunately I was unable to figure out the exact commit until now but some time ago the method of changing `/etc/exports` on Linux has changed. It now uses proper temporary files instead of `/tmp/exports` and thus breaks the `sudoers` rules given in the documentation.
Since I don’t run Fedora I was unable to test the change there but confirmed everything is working on Debian with the rules given for Ubuntu.
This should fix #8218.
> Reflect NFS setup changes in documentation

- website/source/docs/networking/forwarded_ports.html.md
To identify rules, we can name them using the id parameter.
It prevent from adding lots of comments in the Vagrant file and to have un-named rules in your VirtualBox port lists.
It is very important when you have a lot ogf rule to identify witch one you want to edit.
For example:
config.vm.network "forwarded_port", guest: 80  , host: 8080 , id:"http-proxy"
> port forwarding rule name

- lib/vagrant/environment.rb
- test/unit/vagrant/environment_test.rb
This allows custom paths that include special characters like `~`
to be properly expanded instead of resulting in joined root path
with special characters included.
Fixes: #8108
> Allow VAGRANT_DOTFILE_PATH to be expanded as expected.

- lib/vagrant/action/builtin/handle_forwarded_port_collisions.rb
- plugins/kernel_v2/config/vm.rb
- plugins/providers/virtualbox/driver/version_5_0.rb
- plugins/providers/virtualbox/util/compile_forwarded_ports.rb
Added support for Port forwarding in an IP aliased environment where the **same host port but different host IP addresses** are used. The change makes the following forwarding rule(s) possible.
Ex: `eth0` on the host is ip aliased to have a range of IP addresses `10.20.30.0/24.`
In the Vagrant file, we can now have an entry like the following and
it will just work! Note the host port `8081` is same for both .1 and .2.
```
config.vm.network "forwarded_port", guest: 80, host: 8080
config.vm.network "forwarded_port", guest: 81, host: 8081, host_ip: 10.20.30.1
config.vm.network "forwarded_port", guest: 82, host: 8081, host_ip: 10.20.30.2
end
```
> Fix for #4608: Support for port forwarding in an IP aliased environment

- templates/locales/en.yml
Hi,
I was trying to set up Laravel using vagrant 1.9.0 on a Windows 7 64-bit system (command vagrant box add laravel/homestead).
I then was faced with the following error message:
The box failed to unpackage properly. Please verify that the box
file you're trying to add is not corrupted and then try again. 
The output from attempting to unpackage (if any):
...
My problem was that I didn't have enough disk space.
So my suggestion is to extend the above message to contain a hint that the user also has to check the system space. This might save users some hassle on trying to track down the problem.
(See also issue 3869)
> enhance untar_failure message

- plugins/commands/plugin/action/install_gem.rb
I was unable to test it locally because I can't manage to build Vagrant.
The problem mentioned by Vagrant is supposed to be fixed on Ruby side for a very long time: https://bugs.ruby-lang.org/issues/7036
> Remove requirements on path without space as issue was fixed in Ruby

- plugins/communicators/winrm/helper.rb
- test/unit/plugins/communicators/winrm/helper_test.rb
Helper now throws WinRMNotReady exception is host ip is reported as an empty string
This was causing issues when provisioning win2012 r2 boxes in hyper-v. Sometimes hyper-v would report and empty string as the host address #in the winrm data to vagrant then vagrant would try to winrm to the machine with an ip of 0.0.0.0. This would cause sporadic failures when provisioning.
See #7983 for more information.
> HyperV inaccurate winrm address - issue-7983

- plugins/guests/linux/cap/mount_smb_shared_folder.rb
- plugins/guests/linux/cap/mount_virtualbox_shared_folder.rb
- plugins/guests/linux/cap/nfs.rb
- plugins/guests/tinycore/cap/mount_nfs.rb
- plugins/synced_folders/unix_mount_helpers.rb
- test/unit/plugins/guests/linux/cap/mount_nfs_test.rb
- test/unit/plugins/guests/linux/cap/mount_virtual_box_shared_folder_test.rb
- website/source/docs/synced-folders/basic_usage.html.md
This also extracts the gid/uid detection and upstart actions into
reusable module to provide consistent behavior.
Fixes: #8064, #7859
> Use uid/gid from mount_options if provided for synced folders.

- lib/vagrant/bundler.rb
- test/unit/vagrant/util/subprocess_test.rb
When installing a plugin from a local file and a plugin with the same name/version is available via remote source, it can end up as preferred for installation. Force the local path to always be preferred.
> Force path as preferred source on local install

- lib/vagrant/bundler.rb
- lib/vagrant/shared_helpers.rb
- test/unit/vagrant/shared_helpers_test.rb
Adds a `Vagrant.prerelease?` helper and supports matching the vagrant spec when running within a prerelease version. This allows plugins to be installed properly when they impose a constraint on the vagrant version itself.
> Support spec prerelease matching

- contrib/bash/completion.sh
Using bash completion in a path that have spaces, for instance _*/User/pmaques/My_ Vagrant/*_ will fails with some lines of folder not found.
> Fix vagrant bash completion when path have spaces

- website/Gemfile
- website/Gemfile.lock
- website/Makefile
- website/packer.json
- website/source/assets/javascripts/application.js
- website/source/assets/stylesheets/_global.scss
- website/source/assets/stylesheets/_home.scss
- website/source/assets/stylesheets/application.scss
- website/source/layouts/_header.erb
- website/source/layouts/layout.erb
🚧 WIP. Don't merge until final approval
HashiCorp is adding a high-level element to provide navigation and visibility to OSS project sites. We like to call it Mega Nav :zap:. Mega Nav is pulled in from [middleman-hashicorp](https://github.com/hashicorp/middleman-hashicorp) and is positioned above the local nav in the site. It looks like this: 
cc/ @pearkes @hashicorp/design
> Website: Add Meganav

- lib/vagrant/action/builtin/handle_forwarded_port_collisions.rb
- plugins/providers/docker/action/create.rb
- test/unit/vagrant/action/builtin/handle_forwarded_port_collisions_test.rb
Allows the handle port collisions action to continue accepting an Array of extra in use ports and automatically converts them into the expected Hash structure to allow for host IP constraints. Also includes the start of test coverage on the action.
> Handle port collisions action fixes

- website/source/docs/synced-folders/nfs.html.md
Typo missing out the V on VAGRANT_EXPORTS_CHOWN
> Fixed Typo in Fedora commands on /etc/sudoers

- lib/vagrant/action/builtin/provision.rb
- test/unit/vagrant/action/builtin/provision_test.rb
This updates the behavior of the provision action to never run a provisioner
that is specified to "never" run unless it has been explicitly requested. Also
adds test coverage to the provision action.
Fixes: #8016
> Fix provision action for provisioners set to never.

- plugins/provisioners/docker/cap/linux/docker_installed.rb
Include `/bin/docker` path to check for installation.
> Add /bin/docker to path list for installation verification

- lib/vagrant/util/safe_exec.rb
- lib/vagrant/util/subprocess.rb
Fixes some errors caused by encoding issues when executing remote commands.
Fixes: #8380 #8212 #8207 #7516
> Fix issues with Windows encoding

- lib/vagrant/action/builtin/handle_forwarded_port_collisions.rb
- test/unit/vagrant/action/builtin/handle_forwarded_port_collisions_test.rb
> Use 127.0.0.1 for host IP when unset and 0.0.0.0 is not available

- plugins/commands/validate/command.rb
- plugins/commands/validate/plugin.rb
- templates/locales/en.yml
- test/unit/plugins/commands/validate/command_test.rb
- website/source/docs/cli/validate.html.md
- website/source/layouts/docs.erb
The `validate` command simply validates your `Vagrantfile`:
Successful validation:
```ruby
config.vm.box = "debian/jessie64"
end
```
```sh
$ vagrant validate
Vagrantfile validated successfully.
```
Failed validation:
```ruby
config.vm.bix = "debian/jessie64"
end
```
```sh
$ vagrant validate
There are errors in the configuration of this machine. Please fix
the following errors and try again:
vm:
* The following settings shouldn't exist: bix
* A box must be specified.
```
This command is added in response to issue #8151.
> Add validate command

- plugins/provisioners/ansible/cap/guest/arch/ansible_install.rb
- plugins/provisioners/ansible/cap/guest/debian/ansible_install.rb
- plugins/provisioners/ansible/cap/guest/fedora/ansible_install.rb
- plugins/provisioners/ansible/cap/guest/freebsd/ansible_install.rb
- plugins/provisioners/ansible/cap/guest/pip/pip.rb
- plugins/provisioners/ansible/cap/guest/redhat/ansible_install.rb
- plugins/provisioners/ansible/cap/guest/suse/ansible_install.rb
- plugins/provisioners/ansible/cap/guest/ubuntu/ansible_install.rb
- plugins/provisioners/ansible/config/guest.rb
- plugins/provisioners/ansible/provisioner/guest.rb
- test/unit/plugins/provisioners/ansible/config/guest_test.rb
- website/source/docs/provisioning/ansible_local.html.md
This is first the "final" review and follow up of GH-8170.
With , I also propose the addition of `pip_args_only` installation mode, which was originally motivated by the following use case:
```ruby
config.vm.provision "ansible_local" do |ansible|
ansible.playbook = "playbook.yml"
ansible.install_mode = "pip_args_only"
ansible.pip_args = "http://releases.ansible.com/ansible/ansible-2.3.0.0-0.1.rc1.tar.gz"
end
```
**Attention:** Don't use `2.3.0.0-0.1.rc1` with Vagrant, as inventory management is broken in Ansible 2.3.0RC1 (#8391)
Note that I first though about an even more generic install mode (kind of "custom" allowing to execute any command the user want). But I preferred the `pip_args_only`, with the following argumentation:
- "full custom setup" is easily and better achieved with an …
> Add the "pip_args" option and a new "pip_args_only" install mode

- plugins/commands/box/command/list.rb
Boxes are already correctly sorted as a result of PRs #7956 and #8334. The extra sort here breaks.
> Correct box version sorting in box list command's output.

- plugins/guests/windows/cap/mount_shared_folder.rb
- test/unit/plugins/guests/windows/cap/mount_shared_folder_test.rb
Currently synched folders of Windows guests are mounted via WinRM only. This PR adds support for  executing the mount script as encoded command via PowerShell from within the OpenSSH shell.
fixes #6220
> Add support for mounting synched folders on windows guest via ssh

- vagrant.gemspec
Alot of other gems (train, kitchen, etc depend on net-scp ~>1.2.0) and will not work without this one being bumped. net-scp 1.1.0 is _extremely_ old.
> Update vagrant gem dependencies

- plugins/provisioners/salt/bootstrap-salt.ps1
e.g. 2016.11.3 won't deploy with current match
> Salt ver year.month can have 2-digit month

- plugins/guests/gentoo/cap/change_host_name.rb
- plugins/guests/gentoo/cap/configure_networks.rb
- templates/guests/gentoo/network_systemd.erb
- test/unit/templates/guests/gentoo/systemd_network_test.rb
The current Gentoo guest plugin assumes that the init system is OpenRC. This adds support for systemd as well. (bug #8406)
> Add support for gentoo guests that use systemd

- lib/vagrant/util/platform.rb
- lib/vagrant/util/powershell.rb
Improve detection of admin and hyper-v admin rights via using SIDs and powershell
Fixes #4503 and improves on PR #6662
Tested using the following:
- Windows 10
- `ruby 2.2.5p319 (2016-04-26 revision 54774) [x64-mingw32]`
- Vagrant box: `hashicorp/precise64 (hyperv, 1.1.0)`
> Improve user permission detection on Windows

- plugins/communicators/ssh/communicator.rb
- test/unit/plugins/communicators/ssh/communicator_test.rb
Prevent sending empty data strings to defined blocks handling
stderr and stdout output. These can occur when the garbage
marker is identified and collected data pruned, but no remaining
data is left to send.
Fixes #8259
> communicator/ssh: Do not pass empty data to registered blocks

- lib/vagrant/action/builtin/handle_forwarded_port_collisions.rb
- test/unit/vagrant/action/builtin/handle_forwarded_port_collisions_test.rb
When calling the port_checker an arity check is done to determine
if the helper accepts the host_ip and host_port or only the host_port.
Fixes #8423
> Support port checker methods which only accept the host port

- lib/vagrant/action/builtin/box_add.rb
> Unescape url to provide actual local path when adding box

- lib/vagrant/util/platform.rb
- test/unit/vagrant/util/platform_test.rb
While VirtualBox has commented that they do not support UNC remote
paths (but do for long paths) it seems that remote paths can work.
If user provides UNC path, allow it to be used as-is.
Fixes #7011
> Do not prefix Windows paths if UNC prefix already exists

- lib/vagrant/errors.rb
- plugins/communicators/ssh/communicator.rb
- templates/locales/en.yml
In some cases the SSH connection may be aborted while waiting
for setup. This includes aborted connections in the list of
applicable exceptions to retry on while waiting for the connection
to become available.
Fixes #8520
> Retry SSH connection on Errno::ECONNABORTED

- plugins/providers/hyperv/scripts/import_vm_vmcx.ps1
Fix the error 
```homestead-7: Creating and registering the VM...
An error occurred while executing a PowerShell script. This error
is shown below. Please read the error message and see if this is
a configuration error with your system. If it is not, then please
report a bug.
Script: import_vm_vmcx.ps1
Error:
At C:\Program Files
(x86)\HashiCorp\Vagrant\embedded\gems\gems\vagrant-1.9.4\plugins\providers\hyper                    v\scripts\import_vm_vmcx.ps1:18 char:37
+     [string]$differencing_disk=$null
+                                     ~
Missing ')' in function parameter list.
At C:\Program Files
(x86)\HashiCorp\Vagrant\embedded\gems\gems\vagrant-1.9.4\plugins\providers\hyper                    v\scripts\import_vm_vmcx.ps1:20 char:1
+ )
+ ~
Unexpected token ')' in expression or …
```
> Fix crash when using HyperV

- plugins/provisioners/shell/provisioner.rb
Call cmd.exe explicitly when running batch files to easily
manage special characters that may be within the path.
Fixes #8535
> Fix shell provisioner to execute batch files correctly

- plugins/providers/virtualbox/synced_folder.rb
That PR fixes invalid share names in Windows guests, where backward slash character is
used as a path separator.
_Details:_
Currently, if we define the synced folder this way (for Windows guest):
```ruby
config.vm.synced_folder "../", 'C:\Users\vagrant\my_share'
```
then the share id will be this string: `'C:\Users\vagrant\my_share'`
In the guest it will be exposed as `\\VBOXSRV\C:\Users\vagrant\my_share`, which is an invalid path, so the share will not be available.
This Pull-Request adds `\` to the regex, so this char will be replaced with `_`.
The result share id will be `'C:_Users_vagrant_my_share'` and it will be available at `\\VBOXSRV\C:_Users_vagrant_my_share` without any issues.
The similar PR has been sent to Parallels provider: …
> virtualbox: Fix invalid share names in Windows guests

- plugins/providers/docker/action.rb
- plugins/providers/docker/errors.rb
- plugins/providers/hyperv/action.rb
- templates/locales/providers_docker.yml
This makes the behavior of the docker and hyperv provider consistent with the
virtualbox provider by raising an error on ssh actions if the machine is not
created or not running.
Fixes #8508
> Update hyperv and docker providers to raise exception on SSH when machine is not ready

- plugins/providers/docker/provider.rb
If ssh information cannot be properly extracted from within
the NetworkSettings data, fallback to original ssh information
implementation
Fixes #8552
> Fall back to old style ssh info lookup in docker provider

- plugins/communicators/winssh/communicator.rb
- plugins/guests/windows/cap/configure_networks.rb
- plugins/guests/windows/cap/mount_shared_folder.rb
- plugins/guests/windows/scripts/mount_volume.ps1.erb
Allows the #execute method on the communicator to accept custom shell values. Also enables mounting of shared folders and network configuration.
> Enable capabilities for winssh communicator

- vagrant.gemspec
Removes the nokogiri dependency to prevent resolution conflicts
with plugins that may require earlier or later versions than what
Vagrant constrains to.
Fixes #8550
> Remove nokogiri from explicit dependency list

- plugins/providers/docker/action/build.rb
- plugins/providers/docker/config.rb
- plugins/providers/docker/driver.rb
- plugins/providers/docker/driver/compose.rb
- plugins/providers/docker/errors.rb
- plugins/providers/docker/provider.rb
- templates/locales/providers_docker.yml
- test/unit/plugins/providers/docker/driver_compose_test.rb
- website/source/docs/docker/configuration.html.md
This adds an optional driver to the docker provider to use `docker-compose` to manage the container environment/lifecycle.
> Add optional compose driver

- website/source/docs/vagrant-cloud/boxes/catalog.html.md
- website/source/docs/vagrant-cloud/boxes/create-version.html.md
- website/source/docs/vagrant-cloud/boxes/create.html.md
- website/source/docs/vagrant-cloud/boxes/distributing.html.md
- website/source/docs/vagrant-cloud/boxes/index.html.md
- website/source/docs/vagrant-cloud/boxes/lifecycle.html.md
- website/source/docs/vagrant-cloud/boxes/private.html.md
- website/source/docs/vagrant-cloud/boxes/release-workflow.html.md
- website/source/docs/vagrant-cloud/boxes/using.html.md
- website/source/docs/vagrant-cloud/index.html.md
- website/source/docs/vagrant-cloud/organizations/authentication-policy.html.md
- website/source/docs/vagrant-cloud/organizations/create.html.md
- website/source/docs/vagrant-cloud/organizations/index.html.md
- website/source/docs/vagrant-cloud/organizations/migrate.html.md
- website/source/docs/vagrant-cloud/request-limits.html.md
- website/source/docs/vagrant-cloud/support.html.md
- website/source/docs/vagrant-cloud/users/authentication.html.md
- website/source/docs/vagrant-cloud/users/index.html.md
- website/source/docs/vagrant-cloud/users/recovery.html.md
- website/source/docs/vagrant-cloud/vagrant-cloud-migration.html.md
- website/source/layouts/docs.erb
This extracts (most of) the Vagrant Enterprise docs from their current location at https://atlas.hashicorp.com/help/vagrant
```
vagrant-cloud
├── index.html.md ✅
├── features.html.md 🚮 Moved to index
├── request-limits.html.md ✅
├── glossary.html.md 🚮 Not enough content
├── support.html.md ✅
├── vagrant-cloud-migration.html.md ✅
├── boxes
│   ├── index.html.md ✅
│   ├── catalog.html.md ✅
│   ├── create-version.html.md ✅
│   ├── create.html.md ✅
│   ├── distributing.html.md ✅
│   ├── lifecycle.html.md ✅
│   ├── private.html.md ✅
│   ├── release-workflow.html.md ✅
│   ├── using.html.md ✅
│   └── what.html.md 🚮 No contents
├── organizations
│   ├── index.html.md ✅
│   ├── authentication-policy.html.md ✅
│   ├── create.html.md ✅
│   ├── credit-card.html.md 🚮 No billing right now
│   ├── …
```
> Vagrant Enterprise docs

- lib/vagrant/errors.rb
- plugins/commands/snapshot/command/save.rb
- templates/locales/en.yml
- test/unit/plugins/commands/snapshot/command/save_test.rb
Prior to this commit, the vagrant snapshot plugin would save snapshots
with existing names which lead to duplicate snapshot names being saved.
This commit fixes that by checking to see if the given snapshot name
already exists and if so, fails telling the user the given snapshot name
already exists. If a user passes a --force flag, vagrant will first
delete the existing snapshot, and take a new one with the given name.
Fixes #7810
> Enforce unique snapshot names

- lib/vagrant/errors.rb
- plugins/commands/snapshot/command/list.rb
- plugins/commands/snapshot/command/save.rb
- templates/locales/en.yml
- test/unit/plugins/commands/snapshot/command/list_test.rb
- test/unit/plugins/commands/snapshot/command/save_test.rb
This pull request changes the behavior of the snapshot command in that it will raise an exception if the `snapshot/save` and `snapshot/list` commands are invoked on an unsupported provider. It also introduces a new test for the `snapshot/list` command.
> Raise exception for unsupported snapshot providers and improve snapshot plugin testing

- lib/vagrant/action/builtin/box_add.rb
- templates/locales/en.yml
- test/unit/vagrant/action/builtin/box_add_test.rb
Prior to this commit, if a user set a URL for the name of a box, vagrant
would not warn the user about using box_url instead. This would lead to
some difficult user experiences around the various box commands due to
the box name being a full URL. This commit introduces a warning to the
user and lets them know to instead use box_url.
> Handle box names that are URLs

- templates/locales/en.yml
I've been trying out the new Vagrant feature which now supports the Windows Subsystem for Linux on Windows 10, I've had an error which pointed me to the documentation, but the documentation link was missing the ".html", which returned a 404 page for me.
This fixes the link to the documentation and points to the right one.
This is my first PR ever on GitHub so please if I missed something, please tell me.
> Fixes typo in broken link to documentation

- lib/vagrant/action/builtin/ssh_run.rb
- plugins/commands/ssh/command.rb
- test/unit/vagrant/action/builtin/ssh_run_test.rb
Prior to this commit, if a user ran the `vagrant ssh -c CMD` command, it
would not allow the user to configure pseudo-terminal allocation. This
commit introduces a -t flag for the `vagrant ssh` command which defaults
to true if not specified.
Fixes: #6827
> Introduce tty flag for ssh command execution

- lib/vagrant/machine.rb
- templates/locales/en.yml
- test/unit/vagrant/machine_test.rb
If an existing machine moves locations on disk, vagrant should warn the user about this and inform them to change the name of the machine. This warning is to inform users that if they copy a Vagrantfile to a new location, they are still managing the same vm and not two different vms with the same name.
This PR introduces a new internal state file to keep track of a machines location. Then for each machine action, it will check this state file to see if the location of the machine has changed, and if it has warn the user about this new location.
Replaces #8188 
Fixes #3921
> Warn about changes to cwd for every machine action

- lib/vagrant/errors.rb
- plugins/commands/snapshot/command/delete.rb
- plugins/commands/snapshot/command/restore.rb
- plugins/providers/virtualbox/action.rb
- templates/locales/en.yml
- test/unit/plugins/commands/snapshot/command/delete_test.rb
- test/unit/plugins/commands/snapshot/command/restore_test.rb
This commit adds some better handling around the snapshot restore
command for the virtualbox provider. If a user attempts to restore from
a vm that does not exist, instead of exiting 0 it will raise an
exception saying the virtual machine has not been created yet.
Addtionally, if a user attempts to restore from a snapshot id that does
not exist, instead of printing a complicated exception from the
virtualbox cli tool, it prints a more useful error message telling the
user that the snapshot does not exist.
Fixes #7188
> Clean up vagrant snapshot restore/delete error messages

- plugins/communicators/ssh/communicator.rb
- test/unit/plugins/communicators/ssh/communicator_test.rb
Prior to this commit, the ssh communicator would use the default cipher
list in Net::SSH to negociate which ciphers it should use between hosts.
Due to a bug in Net::SSH and the position of the `none` cipher in its
default cipher list, if a host supported the none cipher, but also
only supported other ciphers that came after none in the default list,
it would accept none and attempt to use that cipher instead of the other
supported ciphers. This commit fixes that behavior by copying the
default cipher list from Net::SSH and placing none last in the list so
that other ciphers can be used in the negotiation before attempting to
use the unsecure none cipher.
Fixes #6640
> Use default cipher list for ssh communicator

- website/source/docs/vagrant-cloud/vagrant-cloud-migration.html.md
When using multiple builders, the post-processor could yield different results for the `{{timestamp}}` interpolation.
By using a variable instead, the version will be consistent across all builders.
https://github.com/hashicorp/packer/issues/4973
> website: Packer box version should be variable

- plugins/kernel_v2/config/vm.rb
- plugins/kernel_v2/config/vm_provisioner.rb
- test/unit/plugins/kernel_v2/config/vm_test.rb
Prior to this commit, Vagrant had no way internally to determine if a
provisioner object was unique if the `name` property was not set.
Because of this, when vagrant went to merge configs it would duplicate
an existing unnamed provisioner since it had no way of determining if a
user actually had added the same provisioner twice. This commit fixes
that by introducing an id which will default to `name` if its set, but
if not will be set by `SecureRandom.uuid`.
Fixes #7685
> Add a unique identifier to provision objects

- website/source/docs/cli/box.html.md
Fixes the website's anchors for the box subcommands as they currently have invalid targets
> Use proper box subcommand anchors

- plugins/providers/docker/driver/compose.rb
Although `docker-compose` was executable and on the `PATH` the `docker` provider outputted an error indicating that it couldn't find it.
```
Vagrant has been instructed to use to use the Compose driver for the
Docker plugin but was unable to locate the `docker-compose` executable.
Ensure that `docker-compose` is installed and available on the PATH.
```
`vagrant` incorrectly checked for `vagrant-compose` instead of `docker-compose`.
> fix `docker-compose` check on `PATH`

- plugins/guests/smartos/cap/halt.rb
- plugins/guests/smartos/cap/insert_public_key.rb
- plugins/guests/smartos/cap/remove_public_key.rb
- plugins/guests/smartos/plugin.rb
- test/unit/plugins/guests/smartos/cap/halt_test.rb
- test/unit/plugins/guests/smartos/cap/insert_public_key_test.rb
- test/unit/plugins/guests/smartos/cap/remove_public_key_test.rb
This commit adds/changes the following for SmartOS guests:
- modifies the "Halt" capability to use /usr/sbin/poweroff in preference to /usr/sbin/shutdown with parameters, and modifies the associated test.
- adds an "InsertPublicKey" capability and tests.
- adds a "RemovePublicKey" capability and tests.
With this commit applied, the vast majority of typical Vagrant workflow is available to SmartOS global zone guests (provided NFS mounts are used rather than VMWare shared folders).
> guests/smartos: Add/fix various guest capabilities

- plugins/guests/windows/cap/rsync.rb
- test/unit/plugins/guests/windows/cap/rsync_test.rb
Fix a problem with rsync folders on windows guests with cygwin & ssh enabled.
Before the patch this error will happen if the original directory already exists
-------------------------------------------------------------------------------------------------
==> windows: Rsyncing folder: /vhosts/oxfamshop.com.au/ => /cygdrive/c/inetpub/wwwroot
==> windows:   - Exclude: [".vagrant/", ".git/", "target/", "node_modules/"]
==> windows: Showing rsync output...
mkdir '/cygdrive/c/inetpub/wwwroot'
mkdir: cannot create directory ‘/cygdrive/c/inetpub/wwwroot’: File exists
----------------------------------------------------------------- …
> Fix a problem when using rsync folders on windows clients

- plugins/guests/kali/guest.rb
- plugins/guests/kali/plugin.rb
Adds OS Detection support for [Kali Linux](https://www.kali.org/)
Kali is a popular pen testing distribution, and is currently a [Debian derivative](https://wiki.debian.org/Derivatives/Census/Kali)
I'm surprised this hasn't been added yet!
Signed-off-by: Brian Dwyer <bdwyer@IEEE.org>
> Add support for Kali Linux

- plugins/provisioners/salt/provisioner.rb
Changes introduced in #7207 removed the logic to handle the
`minion_id` configuration. This commit addresses that regression
by including the `--id #{@config.minion_id}` flag everywhere that
`--local` is used (as it had done before).
I'm not totally in love with the `get_masterless` abstraction here,
so if someone has a better suggestion I'll happily change it.
Fixes #7454
> Fix minion_id config for salt provisioner

- lib/vagrant/machine.rb
- lib/vagrant/util/ssh.rb
- plugins/kernel_v2/config/ssh_connect.rb
- test/unit/vagrant/util/ssh_test.rb
- website/source/docs/vagrantfile/ssh_settings.html.md
This commit allows the user to configure two additional options that
were previously not configurable: Compression and DSAAuthentication.
Each config option is set as a boolean, and if left out of the config
will default to its previous behavior which is included and set to
"yes". If the user explicitly sets it to false, it will not be included
as an ssh option.
Fixes #7855
> Introduce more ssh options for machines

- website/source/docs/cli/snapshot.html.md
Fixes the website's anchors for the snapshot subcommands as they currently have invalid targets
> Use proper snapshot subcommand anchors

- lib/vagrant/machine.rb
- test/unit/vagrant/machine_test.rb
Prior to this commit, if a user ran a vagrant command within a subdir,
it would warn about the cwd changing which is not actually the case.
This commit adds an additional check to see if vagrant is being invoked
within a subdirectory so that it doesn't warn the user.
> Fix vagrant_cwd warnings

- plugins/providers/hyperv/action/import.rb
Fixes #8677
This was found on a windows 2012 R2 box when upgrading to 1.9.5. It's not correctly using the output of the has_vmcx_support check so is trying to use it and giving a very cryptic error message:
Compare-VM : A parameter that is not valid was passed to the operation.
> Fixes #8677 - Detect the result of the has_vmcx_support.ps1 properly

- website/source/docs/boxes/format.html.md
- website/source/docs/boxes/info.html.md
- website/source/layouts/docs.erb
This commit adds a new page to vagrants docs around supplying an
`info.json` file for vagrant boxes.
Fixes #7045
> Add information about extra box info

- test/unit/vagrant/util/ssh_test.rb
This commit properly mocks out the ChildProcess library for testing the
`util/ssh` class when subprocess is enabled.
> Fixup util/ssh unit tests

- lib/vagrant/config/loader.rb
- test/unit/vagrant/config/loader_test.rb
Prior to this commit, if a user set the env var VAGRANT_HOME to be the
same directory where the project home is, Vagrant would load that file
twice and merge its config. This caused various provisioner and other
provider blocks to unexpectedly run twice. This commit updates the
config loader to look and see if the `:root` and `:home` procs are
equal, and if so, removes the `:home` object so that it isn't loaded and
duplicated. This commit however does not prevent duplicate loading if an
identical Vagrantfile exists in the home and project dir if those
locations are different.
Fixes #7743
> Disable loading identical Vagrantfile twice from same dir

- lib/vagrant/bundler.rb
- lib/vagrant/shared_helpers.rb
Prevent generating solution sets requiring different versions of gems shipped with/in use by Vagrant.
> Support strict enforcement of internal dependency constraints

- plugins/provisioners/docker/config.rb
- plugins/provisioners/docker/installer.rb
- plugins/provisioners/docker/provisioner.rb
- templates/locales/en.yml
- test/unit/plugins/provisioners/docker/config_test.rb
- test/unit/plugins/provisioners/docker/provisioner_test.rb
- website/source/docs/provisioning/docker.html.md
Prior to this commit, if a user attempted to configure
`/etc/default/docker` through vagrant prior to installation, the package
manager would not override an existing configuration and installing
docker would then fail. This commit fixes this by introducing a
`post_install_provisioner` that allows users to define a provisioner
block that will run after docker has been installed, allowing users to
configure `/etc/default/docker` how they want.
Fixes #7139
> Add post-install provisioner to docker provisioner

- plugins/hosts/bsd/cap/nfs.rb
This commit updates the use of `tee` to use an explicit path when
invoked rather than relying on where `tee` has been defined in a users
PATH.
Fixes #6913
> Invoke tee from specific path

- lib/vagrant/util/platform.rb
- test/unit/vagrant/util/platform_test.rb
Detecting cygwin via PATH contents can result in false positives
resulting in errors when using Vagrant on Windows outside of a
cygwin shell. Use environment based detection instead.
Fixes #6788
> Remove PATH based cygwin detection

- lib/vagrant/environment.rb
- test/unit/vagrant/environment_test.rb
This PR comes from discussion at https://bugzilla.redhat.com/show_bug.cgi?id=1444492
Fedora distributes and supports the libvirt and docker providers, and does not distribute or support Virtualbox. This implies a different set of priorities from those in upstream Vagrant, meaning the priorities called out by the individual provider plugins.
With the existing code in Vagrant, the only way for Fedora to express system-level provider priorities is to set `VAGRANT_DEFAULT_PROVIDER`, but that has the undesired effect of short-circuiting the rest of Vagrant's [nuanced algorithm for choosing a provider](https://www.vagrantup.com/docs/providers/basic_usage.html#default-provider):
> 1. The --provider flag on a vagrant up is chosen above all else, if it
>    is present.
> 
> 2. If the …
> RFC: VAGRANT_PREFERRED_PROVIDERS

- plugins/synced_folders/rsync/command/rsync_auto.rb
- templates/locales/en.yml
- test/unit/plugins/synced_folders/rsync/command/rsync_auto_test.rb
Prior to this commit, when users invoked the `rsync-auto` command using
the docker provider with boot2docker, vagrant would rsync all known
containers using the boot2docker vm rather than the current working dir.
This commit updates that behavior to ensure that only the current
working dirs vagrant machines will be rsynced.
Fixes #5160
> Only rsync-auto current working dir with docker provider

- plugins/communicators/winssh/communicator.rb
- plugins/communicators/winssh/config.rb
- plugins/guests/windows/cap/public_key.rb
- plugins/guests/windows/errors.rb
- plugins/guests/windows/plugin.rb
- templates/locales/guest_windows.yml
- test/unit/plugins/communicators/winssh/communicator_test.rb
- test/unit/plugins/guests/windows/cap/insert_public_key_test.rb
- test/unit/plugins/guests/windows/cap/remove_public_key_test.rb
- test/unit/vagrant/util/subprocess_test.rb
- website/source/docs/vagrantfile/winssh_settings.html.md
Allow upload directory used by winssh communicator to be configurable. Add public_key capabilities to Windows guests using winssh communicator.
> WinSSH communicator updates

- website/source/docs/installation/uninstallation.html.md
Fix location of Vagrant directory in OSX uninstall doc.
> Docs: fix path of Vagrant location for OSX

- plugins/synced_folders/rsync/command/rsync_auto.rb
- test/unit/plugins/synced_folders/rsync/command/rsync_auto_test.rb
Prior to this commit, rsync-auto would not properly rsync realtive dirs
outside the cwd if defined in the Vagrantfile. This commit updates that
to ensure that the command looks at the Vagrant config to ensure that
folder was intended to be rsync'd to the machine even if outside the
current working dir.
Fixes #8770
> rsync-auto relative dirs from vagrantfile

- plugins/provisioners/puppet/provisioner/puppet.rb
- test/unit/plugins/provisioners/puppet/provisioner/puppet_test.rb
Prior to this commit, the puppet provisioner would use the manifest dir
flag when running `puppet apply`. Not only is this flag redundant due to
how puppet apply works, but it is also deprecated in Puppet 4 and
removed in Puppet 5. This commit simply removes the flag when invoking
`puppet apply`.
Fixes #8743 #8072
> Fix puppet provisioner by removing manifestdir flag

- website/source/docs/networking/forwarded_ports.html.md
Following up on issue #8803:  Change "exemple" typo to "example".
> Fix minor typo in website documentation

- plugins/guests/freebsd/cap/configure_networks.rb
- test/unit/plugins/guests/freebsd/cap/configure_networks_test.rb
When attempting to start a new FreeBSD-11.1-RC1 box you are given the following error:
```
ifconfig -a | grep -o ^[0-9a-z]* | grep -v '^lo'
```
I ssh'd into the box to make sure the code changes work:
```
vagrant@:~ % ifconfig -a | grep -o ^[0-9a-z]*
grep: No match.
vagrant@:~ % ifconfig -a | grep -o '^[0-9a-z]*'
em0
em1
lo0
```
Sample Vagrantfile:
```
config.vm.guest = :freebsd
config.vm.box = "freebsd/FreeBSD-11.1-RC1"
config.vm.box_check_update = true
config.ssh.shell = "sh"
config.vm.network :private_network, ip: "192.168.10.10"
config.vm.base_mac = "0800270CA7EB" …
```
> Fix vagrant not being able to list network devices on some FreeBSD boxes.

- lib/vagrant/util/safe_exec.rb
Instead of forcing the encoding of the command + command arguments prior to running the exec, simply encode each item. If the encoding fails, log the conversion failure so it can be inspected later if required, and use the original string value.
> Update safe_exec argument encoding

- plugins/provisioners/chef/config/chef_zero.rb
- plugins/provisioners/chef/provisioner/chef_solo.rb
- plugins/provisioners/chef/provisioner/chef_zero.rb
- templates/locales/en.yml
- test/unit/plugins/provisioners/chef/config/chef_zero_test.rb
If you chef.node_path does not exist locally, the Chef provision generates an error related a chef_server_url instead say the real reason:
==> myvm: Resource Not Found:
==> myvm: -------------------
==> myvm: The server returned a HTTP 404. This usually indicates that your chef_server_url is incorrect.
I wrote a couple of lines for manage this error and warn the user for creating the folder locally.
> Added exception if chef.node_path is defined on Vagrantfile but the directory does not exist locally

- plugins/provisioners/chef/cap/debian/chef_install.rb
- plugins/provisioners/chef/cap/freebsd/chef_install.rb
- plugins/provisioners/chef/cap/omnios/chef_install.rb
- plugins/provisioners/chef/cap/redhat/chef_install.rb
- plugins/provisioners/chef/cap/suse/chef_install.rb
- plugins/provisioners/chef/cap/windows/chef_install.rb
- plugins/provisioners/chef/config/base.rb
- plugins/provisioners/chef/installer.rb
- plugins/provisioners/chef/omnibus.rb
- plugins/provisioners/chef/provisioner/base.rb
- test/unit/plugins/provisioners/chef/config/base_test.rb
- test/unit/plugins/provisioners/chef/omnibus_test.rb
- website/source/docs/provisioning/chef_common.html.md
This option is useful for internal setups, where own customized
omnibus installation script is used (e.g. to get chef from a mirror)
> Add config option omnibus_url for chef provisioners

- plugins/provisioners/salt/bootstrap-salt.sh
Prior to this commit, because of how the bootstrap salt shell file
worked, if github could not be resolved, the installer script would fail
silently with an exit code 0 because `sh` would evalute without any
errors and the curl exit code would be ignored. This commit splits out
the installer to first attempt to save the bash installer, and if it
exists, execute it.
Fixes #8789
> Remove curl pipe bash install for salt provisioner

- plugins/commands/login/client.rb
- plugins/commands/login/command.rb
- test/unit/plugins/commands/login/client_test.rb
This adds a prompt for a token description, which is now supported in
Vagrant Cloud. Pressing enter on the prompt uses the default description
of `"Vagrant login"`.
$ vagrant login
In a moment we will ask for your username and password to HashiCorp's
Vagrant Cloud. After authenticating, we will store an access token locally on
disk. Your login details will be transmitted over a secure connection, and
are never stored on disk locally.
If you do not have an Vagrant Cloud account, sign up at
https://www.vagrantcloud.com
Vagrant Cloud Username: justincampbell
Password (will be hidden):
Token description (Defaults to "Vagrant login"):
You are now logged in.
$
Which created a token with the default description of "Vagrant login":
Entering a description:
Token description (Defaults to "Vagrant …
> command/login: Add description to created token

- plugins/commands/box/command/update.rb
- test/unit/plugins/commands/box/command/update_test.rb
Prior to this commit, if a state was reached where the action_box_add
command needed a force flag, it would fail requesting the user to
provide that flag to override adding a new box. However that flag did
not exist on the box update command, and could not be passed onto the
action_box_add action. This commit updates that to include a force flag,
and if used, pass that value onto the action_box_add action.
Fixes #8719
> Add force flag for box upgrade command

- plugins/guests/darwin/cap/shell_expand_guest_path.rb
- plugins/guests/freebsd/cap/shell_expand_guest_path.rb
- plugins/guests/linux/cap/shell_expand_guest_path.rb
- plugins/guests/netbsd/cap/shell_expand_guest_path.rb
- plugins/guests/openbsd/cap/shell_expand_guest_path.rb
- plugins/provisioners/file/provisioner.rb
- test/unit/plugins/guests/darwin/cap/shell_expand_guest_path_test.rb
- test/unit/plugins/guests/freebsd/cap/shell_expand_guest_path_test.rb
- test/unit/plugins/guests/linux/cap/shell_expand_guest_path_test.rb
- test/unit/plugins/guests/netbsd/cap/shell_expand_guest_path_test.rb
- test/unit/plugins/guests/openbsd/cap/shell_expand_guest_path_test.rb
- test/unit/plugins/provisioners/file/provisioner_test.rb
Prior to this commit, if a file provisioner block was ran twice with a
folder on a remote host, due to how scp works, it would first copy over
that folder, and then on the second action it would copy an identical
folder nested within the first one. While this is 'intended' behavior
with scp, it is unexpected behavior for the file provisioner. This
commit updates the file provisioner to first ensure that the directory
to be copied exists on the remote host prior to copying, and then the
destination dir has been changed to the directory that the destination
will be copied to, rather than the exact directly that includes the
folder from the host to prevent the nested folder behavior.
Fixes #8603
> Ensure remote folder exists prior to scp in file provisioner

- plugins/provisioners/shell/provisioner.rb
- test/unit/plugins/provisioners/shell/provisioner_test.rb
Prior to this commit, if a user passed in a script that was frozen,
the shell provisioner would fail to modify the script to replace line
endings for windows because the string was immutable. This commit fixes
that by checking to see if the script is frozen, and if so dup it so
that it can have its line endings replaced.
Fixes #8716
> Dup string if frozen for line endings

- plugins/commands/validate/command.rb
- test/unit/plugins/commands/validate/command_test.rb
Prior to this commit, the `vagrant validate` command would only validate
the first machine in a vagrant file. This commit improves that by
validating all known machines in the environment. If one is not found,
it will properly throw an exception instead of a stacktrace.
Fixes #8864
> Improve `vagrant validate` command

- plugins/providers/hyperv/action/wait_for_ip_address.rb
- plugins/providers/hyperv/scripts/get_network_config.ps1
Powershell helper script now returns error when guest IP address
cannot be discovered. When reading addresses from a network
device both IPv4 and IPv6 are stored and the IPv4 address has
precedence on returned address.
Fixes #8759
> Update guest IP address discovery for hyper-v guests.

- lib/vagrant/errors.rb
- lib/vagrant/util/powershell.rb
- templates/locales/en.yml
Adds powershell validation to ensure powershell is available on
the PATH and checks powershell version to ensure meets the
defined minimum powershell version.
> Validate powershell prior to powershell use

- lib/vagrant/machine.rb
- lib/vagrant/util/ssh.rb
- plugins/kernel_v2/config/ssh_connect.rb
- test/unit/vagrant/machine_test.rb
- test/unit/vagrant/util/ssh_test.rb
- website/source/docs/vagrantfile/ssh_settings.html.md
Prior to this commit, there was no way to add additional ssh arguments
within a Vagrantfile for a given vagrant machine. This commit introduces
a new option extra_args that allows users to pass in a single argument
or an array of flags that will be added onto the ssh command.
Fixes #8697
> Introduce extra_args setting for ssh configs

- plugins/commands/up/command.rb
- test/unit/plugins/commands/up/command_test.rb
Prior to this commit, when using a global id to bring up a vagrant vm,
vagrant would fail during the "install provider" step due to the fact
that the global vagrant machine was not configured for the local vagrant
environment. Since this global vm exists elsewhere, we disable the
install provider step so that vagrant can just bring up the global
vagrant machine.
Fixes #8479
> Disable install providers when using global id on vagrant up

- plugins/guests/darwin/cap/shell_expand_guest_path.rb
- plugins/guests/freebsd/cap/shell_expand_guest_path.rb
- plugins/guests/linux/cap/shell_expand_guest_path.rb
- plugins/guests/netbsd/cap/shell_expand_guest_path.rb
- plugins/guests/openbsd/cap/shell_expand_guest_path.rb
- test/unit/plugins/guests/darwin/cap/shell_expand_guest_path_test.rb
- test/unit/plugins/guests/freebsd/cap/shell_expand_guest_path_test.rb
- test/unit/plugins/guests/linux/cap/shell_expand_guest_path_test.rb
- test/unit/plugins/guests/netbsd/cap/shell_expand_guest_path_test.rb
- test/unit/plugins/guests/openbsd/cap/shell_expand_guest_path_test.rb
Prior to this commit, when the guest capability attempted to expand a
path with spaces it would quote the path passed in. However if the path
also had a relative path those quotes would end up making `printf`
ignore it and not properly expand the path fully. This commit updates
that to first escape the quotes of a path and then pass in the new path
to be expanded.
Fixes #8917
> Fix shell_expand_guest_path capability

- lib/vagrant/util/platform.rb
- plugins/commands/ssh_config/command.rb
- test/unit/plugins/commands/ssh_config/command_test.rb
- test/unit/vagrant/util/platform_test.rb
Prior to this commit, if the ssh-config command was invoked within
cygwin or msys2, it would show a regular windows style path for private
keys rather than a path that could be used within msys2 or cygwin. This
commit updates that behavior by converting all of the private key paths
to the proper msys2 or cygwin path if the platform is windows and the
command was invoked from one of those two shells.
Fixes #6656
> Format windows paths for ssh_config command

- plugins/provisioners/salt/provisioner.rb
This PR addresses https://github.com/mitchellh/vagrant/issues/8747 by hiding duplicate stdout and stderr output from failed salt runs when verbose mode is on.
> Remove duplicate stdout, stderr output from salt

- lib/vagrant/util/ssh.rb
- test/unit/vagrant/util/ssh_test.rb
Prior to this commit, a change to how the IdentityFile setting for the
ssh command broke when a path with a space was used. This commit fixes
that by quoting the path used to set the IdentityFile so that it uses
the full path instead of part of the path after the space.
Fixes #8923
> Quote path passed into IdentityFile for ssh command

- plugins/provisioners/salt/config.rb
- plugins/provisioners/salt/provisioner.rb
- templates/locales/en.yml
- test/unit/plugins/provisioners/salt/config_test.rb
- test/unit/plugins/provisioners/salt/provisioner_test.rb
- website/source/docs/provisioning/salt.html.md
This config option for the salt provisioner allows you to pass
additional arguments to the salt-call executable.
This PR also introduces the `salt_args` config option to allow users to pass in additional flags to the `salt` tool.
This overrides #7836
> Introduce salt_call_args and salt_args option for salt provisioner

- plugins/commands/login/client.rb
- plugins/commands/login/command.rb
- plugins/commands/login/errors.rb
- plugins/commands/login/locales/en.yml
- test/unit/plugins/commands/login/client_test.rb
This adds support for two-factor authentication to `vagrant login`.
Previously, when a user attempted to login and 2FA was enabled on Vagrant Cloud, we returned an error stating to create a token manually in the web UI. This changed code looks for an additional field in the failed login response to detect that 2FA is required, and present the appropriate options to the user. The server changes are backwards-compatible with existing Vagrant versions, as the response code and error text have not changed when 2FA is enabled.
In addition to supporting TOTP application codes via the login endpoint, there is now an additional endpoint to request a code via another method (only SMS is supported as of now within Vagrant Cloud).
Using a TOTP app:
When 2FA default is app but SMS is enabled:
When …
> `vagrant login` 2FA support for Vagrant Cloud

- plugins/communicators/winrm/shell.rb
- plugins/provisioners/file/provisioner.rb
- test/unit/plugins/communicators/winrm/shell_test.rb
- test/unit/plugins/provisioners/file/provisioner_test.rb
- website/source/docs/provisioning/file.html.md
This commit aligns how the file provisioner should work on all host
machines. It ensures that a `/.` is only applied if the user intended
to upload a folder to a destination under a different name. It ensures
that if uploading to a windows guest with a different destination folder
name, it does not nest the source folder under that name so that it
works the same as it does on linux platforms. It also updates the
behavior of the winrm upload communicator by allowing an array of paths
to be uploaded instead of a single file or folder to allow for this new
functionality for windows guests.
Fixes #8933
> Align file provisioner functionality on all platforms

- lib/vagrant/errors.rb
- plugins/hosts/linux/cap/nfs.rb
- templates/locales/en.yml
- test/unit/plugins/hosts/linux/cap/nfs_test.rb
Prior to this commit, if you set up multiple folders to export with NFS
on linux with the exact same hostpath, the template used to write
/etc/exports would end up placing the same path with the same IP in
/etc/exports and cause an error preventing the folders from being
properly mounted. This commit fixes that by first looking at which
folders are being exported and if there are any duplicates. If so,
remove the duplicates and only export 1 hostpath folder. If these
duplicate folders have differing nfs linux options, an exception must be
thrown because we cannot assume which options the user intended to
export with.
Fixes #4666
> Remove duplicate export folders before writing /etc/exports

- plugins/providers/virtualbox/driver/version_4_0.rb
- plugins/providers/virtualbox/driver/version_4_1.rb
- plugins/providers/virtualbox/driver/version_4_2.rb
- plugins/providers/virtualbox/driver/version_4_3.rb
- plugins/providers/virtualbox/driver/version_5_0.rb
This pull request fixes up and rebases PR #8525
It also brings in the changes from this PR: #8464
Fixes #8468
> Improving resilience of some VirtualBox commands fixup

- lib/vagrant/util/platform.rb
- test/unit/vagrant/util/platform_test.rb
This commit splits out the msys2 and cygwin path functions for
expanding a path with the cygpath tool. It also ensures that the tool
itself exists when the Which class is called so that it doesn't attempt
to escape slashes on nil.
Fixes #8960
> Split out cygwin path and ensure bin exists

- plugins/provisioners/shell/provisioner.rb
Output format of ui.info method (bold text) makes reading long script outputs really heavy on the eyes. ui.detail is a better match for this type of output.
> provisioners/shell: Use ui.detail for displaying output

- lib/vagrant/plugin/v2/command.rb
In case a user (perhaps inadvertently, or for particular reasons) has POSIXLY_CORRECT
set in their environment, make sure to clear it before calling optparse.optparse!() since
we don't really want POSIXLY_CORRECT argument parsing.
> Clear POSIXLY_CORRECT when using optparse

- plugins/providers/virtualbox/synced_folder.rb
- test/unit/plugins/providers/virtualbox/synced_folder_test.rb
It should be valid to allow paths with spaces for the synced folder
guest path but since the guest path is used to generate the ID (if one
isn't provided), this will err out in VirtualBox because it doesn't
allow spaces for the --name argument. We should simply convert ' ' to
'_' as we do with other special characters.
> Allow synced folders to contain spaces in the guest path

- website/source/docs/hyperv/configuration.html.md
As noted in #8877, auto start and stop action is missing from the docs. 
Please merge #9000 also though, since it is currently bugged for binary HyperV VM files.
> Add auto_start_action and auto_stop_action to docs.

- plugins/guests/windows/scripts/reboot_detect.ps1
- plugins/provisioners/chef/provisioner/chef_client.rb
- plugins/provisioners/chef/provisioner/chef_solo.rb
- plugins/provisioners/chef/provisioner/chef_zero.rb
Handle Chef provisioner requests to reboot. A request to reboot is not a convergence failure, so don't treat it like a convergence failure.
Wait for the machine to reboot before trying to continue the provisioning.
> Handle chef provisioner reboot request

- plugins/communicators/ssh/communicator.rb
This commit adds an additional exception to retry ssh on when bringing
up a machine and attempting to ssh into the guest.
Fixes #8974
> Add Errno::EPIPE exception to ssh communicator

- plugins/providers/docker/driver.rb
- plugins/providers/docker/executor/local.rb
- plugins/providers/docker/executor/vagrant.rb
Fixes issue #8608. The existing `windows?` expression applies only when it's a local
machine. When it's a VM, it's always set to `false`.
> fix for issue #8608/Windows hosts

- plugins/guests/windows/cap/public_key.rb
This commit requires the winssh communicator class wihtin the public_key
capability for Windows. Prior to this commit users could run into a
situation where Vagrant would check if the machine could speak in WinSSH
and fail on an uninitialized constant.
Fixes #8941
> Include WinSSH Communicator

- plugins/provisioners/salt/bootstrap-salt.sh
On Debian installations, `fetch`, `curl` and `python` commands may not exist. Only `wget` is guaranteed as explained in the commit message.
This fixes the following error on minimal Debian images, and possibly other distributions and operating systems.
```
==> default: Running provisioner: salt...
Copying salt minion config to vm.
Checking if salt-minion is installed
salt-minion was not found.
Checking if salt-call is installed
salt-call was not found.
Using Bootstrap Options:  -X -F -c /tmp stable
Bootstrapping Salt... (this may take a while)
stdin: is not a tty
/tmp/bootstrap_salt.sh: 9: /tmp/bootstrap_salt.sh:
python: not found
Salt successfully configured and installed!
run_overstate set to false. Not running state.overstate.
Calling state.highstate... (this may take a while)
stdin: …
```
> Attempt fetching salt bootstrap script with wget

- lib/vagrant/util/downloader.rb
- test/unit/vagrant/util/downloader_test.rb
When running within the installer, use an environment variable for setting the CURL_CA_BUNDLE instead of generating the path. This allows the launcher to define the path _if_ the user has not already provided a custom bundle to be used.
> Use environment variable for CURL_CA_BUNDLE

- plugins/commands/login/middleware/add_authentication.rb
- test/unit/plugins/commands/login/middleware/add_authentication_test.rb
This should allow users setting `VAGRANT_SERVER_URL=https://app.vagrantup.com` to authenticate to private boxes.
> Add app.vagrantup.com to allowed auth hosts

- website/source/docs/vagrant-cloud/api.html.md.erb
When using Turbolinks to navigate between docs pages, the document ready event never fired and all language examples were shown. This should fix the issue without needed a refresh/example menu click.
> website: Fix Vagrant Cloud API examples

- plugins/provisioners/salt/bootstrap-salt.ps1
- plugins/provisioners/salt/provisioner.rb
Fixes #8991.
1. When remote executing scripts one should always call powershell with
1a. "-NonInteractive", in order to prevent interactive prompts from leading to an endless waiting time for the script to return
1b. "-NoProfile", in order to prevent the loading of unknown custom profiles before execution of the script which could have unintended side effects
2. During my tests I constantly ran into 408 timeouts when downloading the salt binaries. I've prevented that by adding a simple retry mechanism and an error exit in case of multiple failures. Without this change the bootstrap script never returned (and neither did vagrant up)
> provisioners/salt: Fixes timeout issue in salt bootstrapping for windows

- plugins/guests/dragonflybsd/plugin.rb
Reuse FreeBSD guest code for installing rsync, etc., as dragonfly- and freebsd are very similar, especially with regard to package management.
> dragonflybsd: extend FreeBSD

- lib/vagrant/errors.rb
- plugins/commands/init/command.rb
- templates/locales/en.yml
- test/unit/plugins/commands/init/command_test.rb
- test/unit/templates/commands/init/Vagrantfile.erb
This pull request adds a `--template` option to the `init` command, allowing users to override the default `Vagrantfile` template with their own custom template. When omitted, `init` falls back to the default `Vagrantfile` or `Vagrantfile.min` templates. 
Given the following custom template (also included in the repository for use within the unit tests):
```erb
config.vm.hostname = "vagrant.dev"  
config.vm.box = "<%= box_name %>"
<% if box_version -%>
config.vm.box_version = "<%= box_version %>"
<% end -%>
<% if box_url -%>
config.vm.box_url = "<%= box_url %>"
<% end -%>
end
```
Executing a standard `vagrant init` command with the `--template` option included will result in a new `Vagrantfile` using the provided template (both absolute and relative …
> Support for custom Vagrantfile templates

- bin/vagrant
- lib/vagrant.rb
Enable log message output to be prefixed with the date and time.
Include CLI flag to optionally enable `--timestamp` and a
convenience flag to enable debug logging with timestamps at
the same time `--debug-timestamp`.
> Provide optional timestamp on log output

- plugins/provisioners/ansible/config/host.rb
- test/unit/plugins/provisioners/ansible/config/host_test.rb
- test/unit/plugins/provisioners/ansible/config/shared.rb
- test/unit/plugins/provisioners/ansible/provisioner_test.rb
This bug is a regression introduced in Vagrant 2.0.0. It hasn't been caught by unit tests because
Vagrant::Plugin::V2::Config [catches all invalid/bad configuration calls](https://github.com/hashicorp/vagrant/blob/master/lib/vagrant/plugin/v2/config.rb#L70-L83)
and save them for generating error messages later.
The `ask_sudo_pass=(value)` method was therefore not interrupted when calling the undefined `show_deprecation_warning` method and the
`@ask_become_pass` attribute was (surprisingly) correctly set (allowing
the related unit tests to pass).
In order to avoid similar problem to happen again:
* the deprecation message output is now fully verified (e47deb7)
* we now ensure that the provisioner configurations used by the unit tests have no errors …
> Ansible Provisioner: Fix broken 'ask_sudo_pass' option

- lib/vagrant/config/loader.rb
- lib/vagrant/errors.rb
- templates/locales/en.yml
- test/unit/vagrant/config/loader_test.rb
This commit adds some additional handling for when Vagrant loads config
files. Instead of showing the basic ruby exception, it prints a more
helpful error message and tries to direct the user to the line number
and file where the exception is occuring.
Fixes #9055
Example:
```
brian@localghost:vagrant-sandbox % vagrant validate
There was an error loading a Vagrantfile. The file being loaded
and the error message are shown below. This is usually caused by
an invalid or undefined variable.
Path: /Users/brian/code/vagrant-sandbox/Vagrantfile
Line number: 14
Message: undefined local variable or method `vagrant'
```
> Print more helpful error message for NameEror exceptions

- lib/vagrant.rb
- lib/vagrant/ui.rb
- lib/vagrant/util.rb
- lib/vagrant/util/credential_scrubber.rb
- lib/vagrant/util/logging_formatter.rb
- test/unit/vagrant/ui_test.rb
- test/unit/vagrant/util/credential_scrubber_test.rb
This provides a simple wrapper around all output to
scrub any strings that have been registered as sensitive
before being output. Also included is a small change
to the initial debug output to only show vagrant specific
environment variables and not the full user environment.
> Scrub sensitive information prior to message output

- lib/vagrant/errors.rb
- plugins/providers/virtualbox/action/network.rb
- templates/locales/en.yml
- test/unit/plugins/providers/virtualbox/action/network_test.rb
This PR addresses issue #9166 by throwing a user-friendly error message whenever an invalid address error is thrown by `IPAddr`. Given the following Vagrantfile:
```ruby
Vagrant.configure(2) do |config|
config.vm.box = "ubuntu/trusty64"
config.vm.network "private_network", ip: "192.168.33.06"
end
```
Instead of a stack trace that can be difficult to read for newer developers, the following error will be thrown:
> Add a clean error message for invalid IP addresses

- plugins/commands/destroy/command.rb
- test/unit/plugins/commands/destroy/command_test.rb
This commit reverts the behavior of `vagrant destroy` to exit 0 if no
running vms were found when the destroy command is run.
Fixes #9137
> Exit 0 if vagrant destroy finds no running vms

- plugins/providers/hyperv/scripts/check_hyperv.ps1
- plugins/providers/hyperv/scripts/clone_vhd.ps1
- plugins/providers/hyperv/scripts/create_snapshot.ps1
- plugins/providers/hyperv/scripts/delete_snapshot.ps1
- plugins/providers/hyperv/scripts/delete_vm.ps1
- plugins/providers/hyperv/scripts/export_vm.ps1
- plugins/providers/hyperv/scripts/file_sync.ps1
- plugins/providers/hyperv/scripts/get_network_config.ps1
- plugins/providers/hyperv/scripts/get_network_mac.ps1
- plugins/providers/hyperv/scripts/get_switches.ps1
- plugins/providers/hyperv/scripts/get_vm_status.ps1
- plugins/providers/hyperv/scripts/import_vm_vmcx.ps1
- plugins/providers/hyperv/scripts/import_vm_xml.ps1
- plugins/providers/hyperv/scripts/list_snapshots.ps1
- plugins/providers/hyperv/scripts/restore_snapshot.ps1
- plugins/providers/hyperv/scripts/resume_vm.ps1
- plugins/providers/hyperv/scripts/set_network_mac.ps1
- plugins/providers/hyperv/scripts/set_network_vlan.ps1
- plugins/providers/hyperv/scripts/set_vm_integration_services.ps1
- plugins/providers/hyperv/scripts/start_vm.ps1
- plugins/providers/hyperv/scripts/stop_vm.ps1
- plugins/providers/hyperv/scripts/suspend_vm.ps1
+ This disambuguates calls to the Hyper-V functions for the Hyper-V provider.
The ambiguity of some commands - such as `Get-VM` - causes the Hyper-V provider
to fail on systems where VMware PowerCLI is installed. This change ensures that
all calls to Hyper-V specific cmdlets or functions are prepended by `Hyper-V\`.
This ensures the correct cmdlet calls are being made.
+ Resolves  #8862.
> Ensure Hyper-V cmdlets are fully qualified

- lib/vagrant/machine.rb
- lib/vagrant/util/ssh.rb
- plugins/commands/ssh_config/command.rb
- plugins/communicators/ssh/communicator.rb
- plugins/kernel_v2/config/ssh_connect.rb
- plugins/synced_folders/rsync/helper.rb
- templates/commands/ssh_config/config.erb
- templates/locales/en.yml
- test/unit/plugins/commands/ssh_config/command_test.rb
- test/unit/plugins/communicators/ssh/communicator_test.rb
- test/unit/plugins/communicators/winssh/communicator_test.rb
- test/unit/plugins/synced_folders/rsync/helper_test.rb
- test/unit/vagrant/machine_test.rb
- test/unit/vagrant/util/ssh_test.rb
- vagrant.gemspec
- website/source/docs/vagrantfile/ssh_settings.html.md
As of `net-ssh` version 4.2.0, the key :paranoid has been deprecated in
favor of using :verify_host_key. This commit updates Vagrants ssh config
to use the new key, and deprecates the use of :paranoid.
Fixes #9062
> Deprecate :paranoid in favor of :verify_host_key

- lib/vagrant/action/builtin/box_check_outdated.rb
- plugins/commands/box/command/outdated.rb
- templates/locales/en.yml
Prior to this commit, when the `--global` flag was used with the
`vagrant box outdated` command, it would ignore box providers and not
inform the user of all outdated boxes. This commit fixes that by
displaying each box within the users environment, and includes the
provider of the box in the message.
Fixes #9044
> Show all box providers in command outdated

- plugins/providers/virtualbox/driver/version_4_1.rb
- plugins/providers/virtualbox/driver/version_4_2.rb
- plugins/providers/virtualbox/driver/version_4_3.rb
- plugins/providers/virtualbox/driver/version_5_0.rb
- plugins/providers/virtualbox/synced_folder.rb
- test/unit/plugins/providers/virtualbox/driver/version_5_0_test.rb
- test/unit/plugins/providers/virtualbox/synced_folder_test.rb
- website/source/docs/other/environmental-variables.html.md
- website/source/docs/synced-folders/virtualbox.html.md
Prior to this commit, the virtualbox synced folder option
`SharedFoldersEnableSymlinksCreate` was always enabled. This commit
introduces a config option and an environment variable which allows
users to configure the option globally or per synced_folder in their
Vagrantfile.
> Introduce flag for SharedFoldersEnableSymlinksCreate

- test/unit/vagrant/action/builtin/box_add_test.rb
this commit removes the webserver block within the box add unit test.
It's not actually needed since the test is just ensuring that if a user
adds a box name as a URL it prints a warning to the user.
> Fix sticky Travis CI test

- plugins/guests/amazon/guest.rb
When we use amazon linux 2 virtual box image, we can't detect guest operating system
So, change the matching pattern to search guest operating system for amazon linux
Issue #9306 
Amazon Linux
```
$ cat /etc/os-release
NAME="Amazon Linux AMI"
VERSION="2017.03"
ID="amzn"
ID_LIKE="rhel fedora"
VERSION_ID="2017.03"
PRETTY_NAME="Amazon Linux AMI 2017.03"
ANSI_COLOR="0;33"
CPE_NAME="cpe:/o:amazon:linux:2017.03:ga"
HOME_URL="http://aws.amazon.com/amazon-linux-ami/"
```
Amazon Linux 2 
```
$ cat /etc/os-release
NAME="Amazon Linux"
VERSION="2.0 (2017.12)"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2.0"
PRETTY_NAME="Amazon Linux 2.0 (2017.12) LTS Release Candidate"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2.0"
HOME_URL="https://amazonlinux.com/"
```
> Modify the matching pattern of guest os for amazon linux

- plugins/guests/solaris11/guest.rb
As the Solaris project is dead, recognize that Solaris alternatives like DilOS and SmartOS feature a Solaris compatible kernel and capabilities.
> recognize solaris alternatives

- .gitignore
- test/vagrant-spec/Vagrantfile.spec
- test/vagrant-spec/readme.md
- test/vagrant-spec/scripts/ubuntu-setup.virtualbox.sh
- test/vagrant-spec/scripts/windows-run.virtualbox.ps1
- test/vagrant-spec/scripts/windows-setup.virtualbox.ps1
This PR updates vagrant-spec to run with windows platforms and updated linux boxes. It also
adds a readme to give more information on how to run the vagrant-spec
suite.
> Update vagrant-spec to include Windows platforms and updated linux boxes

- plugins/guests/linux/cap/mount_smb_shared_folder.rb
- test/unit/plugins/guests/linux/cap/mount_smb_shared_folder.rb
This also updates the default `sec` mount option from `ntlm` to `ntlmssp`.
> Support SMB mount option overrides

- plugins/hosts/windows/cap/smb.rb
- plugins/hosts/windows/plugin.rb
- plugins/hosts/windows/scripts/check_credentials.ps1
- plugins/synced_folders/smb/errors.rb
- plugins/synced_folders/smb/synced_folder.rb
- templates/locales/synced_folder_smb.yml
- test/unit/plugins/synced_folders/smb/synced_folder_test.rb
This is an update of #9253 
Since the SMB implementation has been refactored, the original commit was cherry picked in and then modified to extract the functionality into a host capability that can be utilized when available.
> Check SMB credentials

- plugins/provisioners/shell/config.rb
- test/unit/plugins/provisioners/shell/config_test.rb
- website/source/docs/provisioning/shell.html.md
Adds the value of environment variables defined in the shell provisioner to the credential scrubber to prevent them from being displayed.
> Allow hiding environment variable values in shell provisioner

- plugins/guests/linux/cap/read_ip_address.rb
So use "ip addr" and fallback to ifconfig. This function fails in the Debian stretch images where ifconfig command is not installed
> ifconfig is replaced by ip command suite. So use "ip addr" and failback

- plugins/providers/virtualbox/synced_folder.rb
- templates/locales/en.yml
- test/unit/plugins/providers/virtualbox/synced_folder_test.rb
Display warning to user about the VirtualBox SharedFoldersEnableSymlinksCreate
option with link to VirtualBox documentation and instructions on how the
setting can be disabled.
> Add warning message for VirtualBox shared folders option.

- lib/vagrant/util/ssh.rb
- lib/vagrant/util/which.rb
- test/unit/vagrant/util/ssh_test.rb
- test/unit/vagrant/util/which_test.rb
Provides support for `Util::Which` to search for executables using the original PATH if Vagrant has configured a modified PATH (running from the launcher). This update also searches the original path first when looking for an ssh executable, falling back to checking within the modified PATH only if no ssh is found.
> Allow which to use original path. Prefer native ssh.

- plugins/provisioners/salt/bootstrap-salt.sh
Avoids leaving confusing files in the working directory (probably ~vagrant).  Fixes #9350
> Change to a temporary directory before downloading script files

- plugins/guests/openbsd/cap/configure_networks.rb
This fixes an issue when the interface being configured is the
interface through which ssh traffic is forwarded.
In a complex scenario, one needs to disable the default interface for
NAT, and use other interface for ssh. In this case, when vagrant run
`ifconfig #{ifname} inet delete`, the second ifconfig that is supposed
to restore interface settings will never be called. This might be a rare
need, but it is also strongly recommended to use `netstart` when
reconfiguring interfaces after updating `hostname.if(5)`.
The issue can be triggered when ssh connection has issues between two
`ifconfig` commands.
> Atomically apply new hostname.if(5)

- plugins/guests/smartos/plugin.rb
- plugins/guests/solaris11/guest.rb
SmartOS is a distribution of illumos which is the successor of OpenSolaris before it was closed down by Oracle. SmartOS as distribution is similar to OmniOS which is already inherit by solaris.
The problem here is that SmartOS and OmniOS are between Solaris 10 and Solaris 11 so the `uname -sr` already return 5.11 also if it's not the same as Oracle Solaris 11. For that reason we need an more explicit check on solaris11 guests, so checking the `/etc/release` file make more sense.
> More explicit Solaris 11 and inherit SmartOS from Solaris

- lib/vagrant/errors.rb
- lib/vagrant/util/platform.rb
- plugins/providers/virtualbox/driver/base.rb
- templates/locales/en.yml
- test/unit/vagrant/util/platform_test.rb
This commit adds a function on windows for the VirtualBox provider to
check if Hyper-V is enabled. If so, exit and display a warning to the
user that going forward will result in a system crash.
Fixes #9258
> Exit if Hyper-V is enabled and VirtualBox provider is used

- lib/vagrant/util/guest_inspection.rb
- test/unit/plugins/guests/debian/cap/configure_networks_test.rb
Prior to this commit, the regex matcher used with grep to determine if a
system was using systemd? was failing on systems that did not exactly
match the old regex. This commit updates that communications test to use
a different method of determining if systemd is in use with the ps
command.
Fixes #9428
> Update systemd? check for guest inspection

- lib/vagrant/vagrantfile.rb
- test/unit/vagrant/vagrantfile_test.rb
Prior to this commit if an override was given for a box version, it
would be ignored. This commit ensures that the box_version override is
used when specified in a Vagrantfile.
Fixes #9452
> Use provider override for box_version if given

- website/source/docs/synced-folders/smb.html.md
Pretty straightforward change--just a small typo to fix the syntax in the macOS sudoers additions.
> Fix typo in macOS sudoers line

- lib/vagrant/util/downloader.rb
- test/unit/vagrant/util/downloader_test.rb
When the downloader encounters redirects and the final destination is a different host than the original source, display notification to user of the new host.
> Notify when host changes on redirect

- lib/vagrant/shared_helpers.rb
- plugins/commands/login/locales/en.yml
- plugins/commands/login/middleware/add_authentication.rb
- test/unit/plugins/commands/login/middleware/add_authentication_test.rb
Always remap old hosts to target host when encountered. When custom
vagrant server is defined, warn when tokens may be attached and allow
time for user to cancel.
Fixes #9442
> Update behavior of the authentication middleware

- plugins/synced_folders/nfs/synced_folder.rb
This fixes the warning
==> default: WARNING: Invalid NFS settings detected!
==> default: 
==> default: Detected UDP enabled with NFSv4. NFSv4 does not support UDP.
==> default: If folder mount fails disable UDP using the following option:
==> default: 
==> default:   nfs_udp: false
When synced folder is configured as
config.vm.synced_folder "/home", "/home", type: "nfs", nfs_version: 4
(without explicit nfs_udp: false)
> nfs_udp is false by default if using NFS v4

- plugins/providers/virtualbox/action/check_virtualbox.rb
- plugins/providers/virtualbox/driver/base.rb
Prior to this commit, the hyper-v and virtualbox system crash check
existed within the initialize function of the virtualbox provider. That
caused an issue when running with other providers, because the
virtualbox provider still gets initialized even if not used. This commit
changes that by placing the check inside of one of the virtualbox
provider actions that checks if virtualbox is installed and ready to
use. This action is action is used by the main vbox provider actions,
and should not be called when other providers are being used with
Vagrant.
> Fix Hyper-v and VirtualBox check

- plugins/providers/virtualbox/action/export.rb
Prior to this commit, the incorrect path was used when determining where
to export an ovf file during the `vagrant package` step. This commit
updates that by checking if vagrant is within WSL, and if so, convert
the path to a proper windows path to be used during the export.
Fixes #9059
> Convert to windows path if on WSL during vbox export

- .gitignore
- lib/vagrant/errors.rb
- lib/vagrant/util/platform.rb
- lib/vagrant/util/powershell.rb
- templates/locales/en.yml
- test/unit/vagrant/util/platform_test.rb
- vagrant.gemspec
This is an extension of great work provided by @BR0kEN- in #9300. Updated to support the old lxrun generated WSL instances as well as the new store installed instances. Included some spec coverage on the behavior as well.
> Support updated WSL implementation

- .github/CONTRIBUTING.md
- Gemfile
- templates/locales/en.yml
- test/unit/plugins/synced_folders/rsync/command/rsync_auto_test.rb
- website/source/community.html.erb
- website/source/docs/boxes/base.html.md
- website/source/docs/cli/machine-readable.html.md
- website/source/docs/docker/basics.html.md
- website/source/docs/hyperv/boxes.html.md
- website/source/docs/installation/source.html.md
- website/source/docs/installation/upgrading.html.md
- website/source/docs/plugins/development-basics.html.md
- website/source/docs/plugins/index.html.md
- website/source/docs/plugins/packaging.html.md
- website/source/docs/plugins/providers.html.md
- website/source/docs/plugins/provisioners.html.md
- website/source/docs/provisioning/ansible.html.md
- website/source/docs/synced-folders/virtualbox.html.md
- website/source/docs/vagrant-cloud/support.html.md
- website/source/docs/vmware/boxes.html.md
- website/source/intro/getting-started/install.html.md
- website/source/intro/vs/index.html.md
- website/source/layouts/_sidebar.erb
- website/source/layouts/layout.erb
Currently the URLs on the website and in the repo point to the old repo URLs under mitchellh's account. This updates the links to point directly to the Hashicorp repo(s).
> Update URLs for the repo

- plugins/providers/virtualbox/action/network.rb
- test/unit/plugins/providers/virtualbox/action/network_test.rb
Force a string type for comparison to prevent false positives when
the name is unset (resulting in a nil value).
> When matching hostonly adapter name, force common types

- plugins/guests/windows/cap/change_host_name.rb
- test/unit/plugins/guests/windows/cap/change_host_name_test.rb
The current code waits for the entire value of machine.config.vm.graceful_halt_timeout when rebooting due to a hostname change.  This is not the intended use of this configuration parameter.  Graceful_halt_timeout is the amount of time to wait for a machine to respond to a graceful halt request before forcefully halting.  This change removes machine.config.vm.graceful_halt_timeout for the module in favor of using the existing wait_for_reboot code, thereby correcting issue #8486.
Fixes #8486
> Fix graceful_halt_timeout issue #8486

- website/source/docs/provisioning/shell.html.md
In the $script variable definition there appears to be a typo of "<<SCRIPT" when it should be "<<-SCRIPT". I ran into this issue while editing the Vagrant file on a Fedora variant with ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-linux].
> Fix missing "-" $script variable definition.

- website/source/docs/cli/up.html.md
[#9605]( https://github.com/hashicorp/vagrant/pull/9605)
Proposes add `name|id` to `Options` to define the ability to use `id` from any directory.
> Update options to define id can be used in any directory

- plugins/guests/coreos/guest.rb
If the the value of ID= is not recognised, identify the OS if it is a derivative of CoreOS
https://www.freedesktop.org/software/systemd/man/os-release.html#ID_LIKE=
This change is done to support [Flatcar Linux](https://www.flatcar-linux.org/)
> Identify operating systems closely related to CoreOS

- plugins/guests/debian/cap/configure_networks.rb
This adjusts the priority of the network configuration file from 99
to 50 making it easier for customized configuration.
Fixes #9592
> Adjust priority of network configuration file for debian guests

- lib/vagrant/util/ssh.rb
- website/source/docs/other/environmental-variables.html.md
Allow `VAGRANT_PREFER_SYSTEM_BIN=0` to disable using installed system ssh executable on windows.
Fixes #9433
> Fix ssh binary selection on windows

- lib/vagrant/util/checkpoint_client.rb
- test/unit/vagrant/util/checkpoint_client_test.rb
The checkpoint update missed the environment variable check for
disabling the checks so this adds in the check and properly
disables checks when requested.
> Properly respect environment variable on checkpoint setup

- lib/vagrant.rb
- lib/vagrant/alias.rb
- lib/vagrant/cli.rb
- lib/vagrant/environment.rb
- lib/vagrant/errors.rb
- templates/locales/en.yml
- test/unit/vagrant/alias_test.rb
- website/source/docs/cli/aliases.html.md
- website/source/docs/other/environmental-variables.html.md
- website/source/layouts/docs.erb
This pull request is an initial attempt at creating CLI alias functionality as described in issue #9357. 
Aliases are configured via a new `$VAGRANT_HOME/aliases` file in the following format:
```
start = up
stop = halt
die = halt -f
restart-nginx = ssh -c "sudo service nginx restart"
eradicate = !vagrant destroy && rm -rf .vagrant
```
The aliases file, inspired by git's own alias functionality, is relatively simplistic by design, with lines starting with `#` being ignored as comments, and aliases themselves being defined as a `key = value` pair. In a nutshell, there are two possible aliases: internal command aliases and external command aliases.
Internal command aliases call the `CLI` class directly, allowing the user to alias one Vagrant command to another Vagrant comment:
```
start = …
```
> WIP Vagrant aliases

- plugins/communicators/winrm/command_filters/mkdir.rb
- plugins/communicators/winrm/command_filters/rm.rb
- plugins/communicators/winrm/command_filters/test.rb
- plugins/communicators/winrm/command_filters/which.rb
- test/unit/plugins/communicators/winrm/command_filter_test.rb
Use shellwords for original command splitting. Add path quoting in replacement commands to prevent issues with spaces in paths.
Fixes #9390
> Fix windows command filters

- lib/vagrant/util/platform.rb
- test/unit/vagrant/util/platform_test.rb
Using the --version flag keeps Vagrant from doing a full startup
and prevents the Vagrantfile from being parsed. This makes the
version check faster, and stops things like syntax errors within
a Vagrantfile from causing an unexpected error.
Fixes #9635
> Check Windows installed Vagrant version using --version

- lib/vagrant.rb
- plugins/communicators/ssh/communicator.rb
- test/unit/plugins/communicators/ssh/communicator_test.rb
- vagrant.gemspec
This updates the permissions on the automatically generated private
key file to only be readable by the user. Includes support for file
permission modification on Windows platform.
Fixes #9520 #9511
> Update generated ssh private key file permissions on create

- plugins/provisioners/salt/config.rb
- plugins/provisioners/salt/provisioner.rb
- test/unit/plugins/provisioners/salt/provisioner_test.rb
- website/source/docs/provisioning/salt.html.md
Fixes #9417 
* Allow use of -j/-J bootstrap options for configuring master/minion
> Add master_json_config & minion_json_config options to salt provisioner

- plugins/provisioners/puppet/config/puppet.rb
- test/unit/plugins/provisioners/puppet/provisioner/puppet_test.rb
This commit sets the structured_facts option to nil if its still
UNSET_VALUE at the finalize step. This was causing a bug when the facter
config was set but was not using structured facts.
Fixes #9718
> Properly finalize structured_facts config option

- lib/vagrant/errors.rb
- lib/vagrant/machine.rb
- lib/vagrant/plugin/v2.rb
- lib/vagrant/plugin/v2/command.rb
- lib/vagrant/plugin/v2/trigger.rb
- lib/vagrant/util/powershell.rb
- plugins/kernel_v2/config/trigger.rb
- plugins/kernel_v2/config/vm_trigger.rb
- templates/locales/en.yml
- test/unit/plugins/kernel_v2/config/trigger_test.rb
- test/unit/plugins/kernel_v2/config/vm_trigger_test.rb
- test/unit/vagrant/plugin/v2/trigger_test.rb
- website/source/docs/triggers/configuration.html.md
- website/source/docs/triggers/index.html.md
- website/source/docs/triggers/usage.html.md
- website/source/layouts/docs.erb
This pull request integrates the community plugin [vagrant-triggers](https://github.com/emyl/vagrant-triggers) functionality as a core feature of Vagrant. It is a complete rewrite of the plugin.
Resolves #3849 
Related issue: https://github.com/emyl/vagrant-triggers/issues/85 /cc @emyl 
Related pull request: https://github.com/hashicorp/vagrant-spec/pull/28
Related demo environment: [briancain/vagrant-triggers-demo](https://github.com/briancain/vagrant-triggers-demo)
> Integrate vagrant-triggers plugin functionality into core Vagrant

- plugins/provisioners/chef/provisioner/chef_zero.rb
The pull request #6561 added the support for arrays for data_bags_path
in chef-solo and chef-zero, but missed a `.first` in chef-zero (which
only keeps the first data bag path). The documentation and the template
for chef-zero are already good (since #6561).
Fixes #9668.
> Support arrays for data_bags_path in chef-zero

- lib/vagrant/util/downloader.rb
- test/unit/vagrant/util/downloader_test.rb
This pull request will continue when encountering an HTTP 416 error code in the downloader. It is a rebase/improvement of the PR #7885 to simplify the code a bit.
Fixes #7886
> Don't raise error if response is HTTP 416

- plugins/commands/login/middleware/add_authentication.rb
- test/unit/plugins/commands/login/middleware/add_authentication_test.rb
Due to the behavior of URI.parse on Ruby < 2.5 returning the string
value of the parsed URI object may modify the original URL. Specifically
it will remove the `//` prefix characters from SMB paths. When no
host modifications are being made, always return the original value.
Fixes #9636
> Return original URL value when unmodified

- plugins/kernel_v2/plugin.rb
- website/source/docs/other/environmental-variables.html.md
To allow users to continue to use the community plugin, this commit adds
a switch that will not load the core trigger feature if it detects the
community plugin is installed. It also allows the user to disable the
warning so they can continue to use the plugin without extra output.
> Add warning if vagrant-triggers plugin is installed

- lib/vagrant/util/platform.rb
If you use wsl and the vagrantfile is located under the home of root than i get a wrong root_path:
wrong:
"\\?\C:\Users\%User%\AppData\Local\lxss\rootfs\root\...\..."
correct:
"\\?\C:\Users\%User%\AppData\Local\lxss\root\...\..."
> fix rootpath if the vagrantfile is located under the root directory (WSL)

- plugins/communicators/winrm/command_filters/rm.rb
- plugins/provisioners/docker/cap/windows/docker_daemon_running.rb
- plugins/provisioners/docker/client.rb
- plugins/provisioners/docker/plugin.rb
- test/unit/plugins/communicators/winrm/command_filter_test.rb
This commit rebases #9353. It introduces a windows capability for the docker provisioner to check of the docker daemon is running. It also fixes the behavior of the `rm` filter for winrm. `rm -f dir` on linux does not result in an error, thus the winrm filter was updated since `rm`'ing a directory that doesn't exist on windows is an error.
Fixes #9339
Fixes #9280
> Update docker provisioner for windows, fix command filter behavior for `rm`
