hashicorp/vagrant

plugins/pushes/ftp/adapter.rb
plugins/pushes/ftp/push.rb
test/unit/plugins/pushes/ftp/adapter_test.rb
test/unit/plugins/pushes/ftp/push_test.rb

Fixes https://github.com/mitchellh/vagrant/issues/5095

Various fixes for FTP

---

lib/vagrant/machine.rb
plugins/commands/package/command.rb
test/unit/plugins/pushes/ftp/push_test.rb
test/unit/vagrant/machine_test.rb

@mitchellh these are some remaining fixes from #4962 that users have reported

Symbolize and stringify keys in options hash

---

lib/vagrant/shared_helpers.rb
plugins/pushes/atlas/push.rb

Turn on Atlas debug logging if Vagrant is logging

---

plugins/commands/package/command.rb

Do not use keyword arguments for string keys

---

lib/vagrant/util/env.rb

Make with_clean_env a class method

---

README.md

A trivial improvement of wording in the README.
Thanks for consideration...
Michael

README: improve wording.

---

website/docs/source/v2/vmware/installation.html.md

Improve the documentation around install VMware plugins + FAQ

---

website/docs/source/v2/provisioning/shell.html.md

Add a note to the "external script" section how to run existing scripts

---

lib/vagrant/action/builtin/box_add.rb
test/unit/vagrant/action/builtin/box_add_test.rb

Use the new Atlas APIs for downloading boxes

---

plugins/commands/push/command.rb
plugins/pushes/atlas/push.rb
test/unit/plugins/pushes/atlas/push_test.rb

Add extra metadata information to Atlas pushes

---

website/docs/source/v2/push/local-exec.html.md

fix sample to scp -r . server:/var/ww/website

fix command on vagrant push website sample script

---

plugins/provisioners/chef/config/base_runner.rb
plugins/provisioners/chef/config/chef_zero.rb
plugins/provisioners/chef/provisioner/base.rb
plugins/provisioners/chef/provisioner/chef_zero.rb
templates/provisioners/chef_zero/zero.erb
test/unit/plugins/provisioners/chef/config/base_runner_test.rb
test/unit/plugins/provisioners/chef/config/chef_zero_test.rb
website/docs/source/v2/provisioning/chef_common.html.md
website/docs/source/v2/provisioning/chef_zero.html.md

Support real chef-zero/local mode with version constraint

Chef Provisioner : Support real chef-zero/local mode

---

plugins/providers/docker/action/host_machine_build_dir.rb

I'm sorry is this has already been discussed and rejected, but i run into issue 3680 and got it fixed with this change, so thought i could at least make a PR for it, to see what's going on.

Fixes https://github.com/mitchellh/vagrant/issues/3680

---

plugins/guests/windows/cap/change_host_name.rb

This is causing Windows server to crash

Revert "Rename Windows guest without reboot"

---

plugins/guests/solaris/cap/insert_public_key.rb
plugins/guests/solaris/cap/remove_public_key.rb
plugins/guests/solaris/plugin.rb

Implementation identical to linux; tested on omnios 151012

Add insert/remove public key guest capability for solaris

---

plugins/synced_folders/rsync/helper.rb

Added IdentiesOnly=yes to avoid "Too Many Authentication Failures" error

synced/folders/rsync Add 'IdentitiesOnly=yes'

---

plugins/guests/photon/cap/change_host_name.rb
plugins/guests/photon/cap/configure_networks.rb
plugins/guests/photon/cap/docker.rb
plugins/guests/photon/guest.rb
plugins/guests/photon/plugin.rb
test/unit/plugins/guests/photon/cap/change_host_name_test.rb
test/unit/plugins/guests/photon/cap/configure_networks_test.rb
test/unit/plugins/guests/photon/cap/docker_test.rb

Support for [Photon](https://vmware.github.io/photon).

Add Guest support for VMware Photon.

---

plugins/provisioners/salt/config.rb
templates/locales/en.yml

When you can't find the salt minion or master config, say what you were looking for.

Provide path to missing file.

---

plugins/provisioners/docker/cap/debian/docker_install.rb

https://github.com/mitchellh/vagrant/issues/5748

change to https in sources.list.d

---

plugins/guests/fedora/cap/configure_networks.rb
plugins/guests/redhat/cap/configure_networks.rb

Fix for #5590. This changes has created `/etc/sysconfig/network-script/ifcfg-# {interface}` to enable.
I used https://atlas.hashicorp.com/chef/boxes/centos-7.1

Reload iface connection by NetworkManager

---

plugins/provisioners/chef/cap/windows/chef_installed.rb
plugins/provisioners/chef/plugin.rb
plugins/provisioners/chef/provisioner/base.rb
plugins/provisioners/chef/provisioner/chef_apply.rb
plugins/provisioners/chef/provisioner/chef_client.rb

Use powershell syntax for Chef provisioner when using windows guest

Use powershell syntax for Chef provisioner when using windows guest

---

plugins/guests/fedora/cap/flavor.rb
plugins/guests/fedora/cap/nfs_client.rb
plugins/guests/fedora/plugin.rb

Closes https://github.com/mitchellh/vagrant/pull/4847

Add nfs and flavor cap to Fedora

---

plugins/provisioners/ansible/provisioner.rb
test/unit/plugins/provisioners/ansible/provisioner_test.rb

Sets `ANSIBLE_NOCOLOR=true` if vagrant has no color. See #5531

Disable color if in ansible provisioner if Vagrant has no color

---

plugins/communicators/ssh/communicator.rb

This allows `shell_cmd` to be overridable by plugins/patches without having to override the entire (large) `shell_execute` method.
Our use case is specifically to allow us to patch this method in a plugin to get around the change here https://github.com/mitchellh/vagrant/commit/9cd9e6e55d802553fa90e63d966b302006b45de5 which I understand in non-revertable. This gives us a simple way to make the patch without having to run a separate fork or have major impact on the codebase (this actually changes nothing about default behavior and is really just moving code into a method).

Move shell_cmd to a method in SSH::Communicator

---

website/docs/source/v2/hyperv/index.html.md

The step to click on "Turn Windows features on or off" was missing.

website: Improve description to enable Hyper-V on Windows 8.1

---

website/docs/source/v2/vagrantfile/ssh_settings.html.md

Fix a typo in ssh_settings.html.md

---

plugins/provisioners/salt/provisioner.rb

resolves bug introduced in 74d22069d41b35bae50e32c1c68a92a4958afebb

bugfix: undefined local variable or method `dir'

---

plugins/providers/docker/communicator.rb

Use the same method as upload, in the other direction
Fixes #4864 cassianoleal/vagrant-butcher#55

Implement docker download method

---

plugins/provisioners/chef/command_builder.rb
plugins/provisioners/chef/provisioner/base.rb
plugins/provisioners/chef/provisioner/chef_client.rb
plugins/provisioners/chef/provisioner/chef_solo.rb
plugins/provisioners/chef/provisioner/chef_zero.rb
templates/locales/en.yml
test/unit/plugins/provisioners/chef/command_builder_test.rb

This refactors the Chef provisioners to be less coupled with each other, and fixes issues where Chef Zero behaved like Chef Solo and not Chef Client.

Refactor Chef provisioners

---

lib/vagrant/shared_helpers.rb
test/unit/support/shared/base_context.rb

@mitchellh @sethvargo @phinze this is an humble attempt to solve the broken unit tests, but I can imagine that there is more elegant way to achieve this (see my code comments/questions)

core: plugin management requires bundler

---

plugins/provisioners/docker/client.rb

Otherwise this gets all jumbled with previous options :frowning:

Add a space before args

---

plugins/guests/linux/cap/read_ip_address.rb

Use sudo for read_ip_address capability

---

plugins/guests/ubuntu/cap/change_host_name.rb

Fix setting hostname in 12.04

---

plugins/guests/redhat/cap/nfs_client.rb

Detect "systemd" on guest instead of host

---

plugins/hosts/linux/cap/nfs.rb

- Fixes https://github.com/mitchellh/vagrant/pull/5773#issuecomment-120793492
- Fixes https://github.com/mitchellh/vagrant/issues/5951

Fallback to /tmp if $TMPDIR is not set

---

plugins/provisioners/puppet/provisioner/puppet.rb

Fix automatic puppet path detection on windows

Fix custom puppet.binary_path to work properly on windows and fix puppet detection on windows.

---

website/docs/source/v2/provisioning/salt.html.md

Clarified windows guest machine support for salt provisioner in documentation.

---

lib/vagrant/action/builtin/ssh_run.rb

Fixes https://github.com/mitchellh/vagrant/issues/4986

Use the same ssh args for ssh with a command as ssh exec

---

website/docs/source/v2/boxes/base.html.md

website/docs: Link to Atlas docs for base boxes

---

scripts/website_push_docs.sh
scripts/website_push_www.sh

Faster deploys

---

website/docs/source/v2/cli/plugin.html.md
website/docs/source/v2/provisioning/salt.html.md
website/www/source/vmware/index.html.erb

Hello! Did a quick spell check of the documentation and fixed anything I found wrong. 
Thanks for an awesome platform!

fixed simple spelling errors

---

website/www/source/layouts/layout.erb

website/www: Fix logos/copyright alignment

---

plugins/communicators/winrm/communicator.rb
plugins/communicators/winrm/scripts/elevated_shell.ps1.erb
plugins/communicators/winrm/shell.rb
plugins/provisioners/shell/config.rb
plugins/provisioners/shell/provisioner.rb
templates/locales/en.yml
test/unit/plugins/communicators/winrm/communicator_test.rb
test/unit/plugins/provisioners/shell/config_test.rb
website/docs/source/v2/provisioning/shell.html.md

Add option to allow interactive elevated scripts in Windows.

Elevated interactive

---

plugins/guests/fedora/cap/configure_networks.rb

- Rest of https://github.com/mitchellh/vagrant/pull/5931/files
- Closes https://github.com/mitchellh/vagrant/pull/6519
- Closes https://github.com/mitchellh/vagrant/pull/6508

Check if the network manager is before reloading

---

plugins/guests/linux/cap/mount_nfs.rb
plugins/guests/linux/cap/mount_smb_shared_folder.rb
plugins/guests/linux/cap/mount_virtualbox_shared_folder.rb

- Fixes https://github.com/mitchellh/vagrant/issues/6074
- Closes https://github.com/mitchellh/vagrant/pull/6522

Fix upstart detection and event emit

---

plugins/providers/virtualbox/provider.rb

Reverts mitchellh/vagrant#6406

Revert "#5186: Warning: Authentication failure. Retrying... after packaging box"

---

plugins/providers/virtualbox/action/network.rb
website/docs/source/v2/networking/private_network.html.md

Fixes https://github.com/mitchellh/vagrant/pull/6325
Rebase with a few fixes

Make DHCP IP configurable

---

website/docs/source/layouts/layout.erb
website/docs/source/stylesheets/_mixins.less
website/docs/source/stylesheets/_pages.less
website/docs/source/stylesheets/_sidebar.less

Before (Timeline):
After (Timeline):
Before (paint):
After (paint):

Avoid full-screen repaints on scroll. Fixes #6520

---

plugins/provisioners/chef/command_builder.rb
test/unit/plugins/provisioners/chef/command_builder_test.rb

Only force the formatter if we are on Chef 11 or higher

---

plugins/provisioners/chef/provisioner/chef_solo.rb

Only append folder suffixes if we are sharing host folder paths

---

plugins/provisioners/chef/provisioner/chef_solo.rb
templates/provisioners/chef_solo/solo.erb
templates/provisioners/chef_zero/zero.erb
website/docs/source/v2/provisioning/chef_solo.html.md
website/docs/source/v2/provisioning/chef_zero.html.md

Support arrays for data_bags_path

---

lib/vagrant/machine.rb
lib/vagrant/util/ssh.rb
plugins/commands/ssh_config/command.rb
plugins/communicators/ssh/communicator.rb
plugins/kernel_v1/config/ssh.rb
plugins/kernel_v2/config/ssh.rb
website/docs/source/v2/vagrantfile/ssh_settings.html.md

Add support for forwarding host environment variables via SSH

---

plugins/pushes/local-exec/push.rb
test/unit/plugins/pushes/local-exec/push_test.rb

Use subprocess as a poor-man's exec for local-exec

---

plugins/provisioners/docker/cap/debian/docker_install.rb
plugins/provisioners/docker/cap/fedora/docker_install.rb
plugins/provisioners/docker/cap/redhat/docker_install.rb
plugins/provisioners/docker/config.rb
plugins/provisioners/docker/installer.rb
plugins/provisioners/docker/provisioner.rb
templates/locales/en.yml
test/unit/plugins/provisioners/docker/config_test.rb
website/docs/source/v2/provisioning/docker.html.md

- Closes https://github.com/mitchellh/vagrant/pull/6112
- Fixes #6075

Always install latest docker, deprecate version

---

plugins/providers/hyperv/scripts/get_vm_status.ps1

This fixes error for issue https://github.com/mitchellh/vagrant/issues/6117

Fix Win 10 Enterprise Vagrant Error

---

plugins/providers/virtualbox/cap/public_address.rb
plugins/providers/virtualbox/plugin.rb
test/unit/plugins/providers/virtualbox/cap/public_address_test.rb

Add public_address cap for VirtualBox

---

plugins/guests/fedora/guest.rb

Signed-off-by: Lalatendu Mohanty <lmohanty@redhat.com>

Making the Fedora guest detection search string generic

---

plugins/providers/virtualbox/action/network_fix_ipv6.rb
test/unit/plugins/providers/virtualbox/action/network_fix_ipv6_test.rb

Skip nil IP addresses in ipv6 fix

---

plugins/provisioners/shell/config.rb
plugins/provisioners/shell/provisioner.rb
templates/locales/en.yml
test/unit/plugins/provisioners/shell/config_test.rb
test/unit/plugins/provisioners/shell/provisioner_test.rb
website/docs/source/v2/provisioning/shell.html.md

Add :env option to shell provisioner

---

templates/commands/ssh_config/config.erb
test/unit/plugins/commands/ssh_config/command_test.rb

Escape identify file path

---

plugins/commands/login/client.rb
test/unit/plugins/commands/login/client_test.rb

Respect proxy envvars for login command

---

lib/vagrant/action/builtin/box_add.rb
test/unit/vagrant/action/builtin/box_add_test.rb

Ignore case when comparing checksums

---

plugins/providers/virtualbox/action/network_fix_ipv6.rb
test/unit/plugins/providers/virtualbox/action/network_fix_ipv6_test.rb

Only consider the VM interfaces in the IPv6 fixup

---

plugins/pushes/local-exec/config.rb
plugins/pushes/local-exec/locales/en.yml
plugins/pushes/local-exec/push.rb
test/unit/plugins/pushes/local-exec/config_test.rb
test/unit/plugins/pushes/local-exec/push_test.rb
website/docs/source/v2/push/local-exec.html.md

pushes/local-exec: add args config

---

website/docs/source/v2/cli/package.html.md

Clarify package documentation regarding providers

---

lib/vagrant/action/builtin/provisioner_cleanup.rb
test/unit/vagrant/action/builtin/provisioner_cleanup_test.rb

This helps with some confusion caused in GH-2538, since the output says:
> Running cleanup tasks for 'shell' provisioner...
But that's actually not true. It is running the cleanup tasks iff the provisioner defined a cleanup task. This commit changes the provisioner_cleanup middleware to only run cleanup tasks if the subclass defines a cleanup task.
The reason we can't just check if the provisioner `respond_to?` the `cleanup` method is because the parent provisioner base class (which all provisioners inherit from) defines a blank cleanup method. This is important because it means we never risk calling an unimplemented cleanup function, and it also helps define the public API for a provisioner.

Only run cleanup tasks when they are defined on the provisioner

---

plugins/provisioners/cfengine/cap/debian/cfengine_install.rb
plugins/provisioners/cfengine/config.rb

#6674 CFEngine Provisioner Broken on Debian (http > https)

---

plugins/provisioners/chef/command_builder.rb

Convert Chef Version to a string before comparison

---

plugins/provisioners/shell/provisioner.rb

Fixes https://github.com/mitchellh/vagrant/issues/6707#issuecomment-166704292

Convert env values to strings before escaping

---

website/docs/source/v2/provisioning/ansible_local.html.md

Fixed typo

---

website/docs/source/v2/synced-folders/nfs.html.md

http://www.fileformat.info/info/unicode/char/05bb/index.htm
This prevented me from a quick copy-paste solution for the Ubuntu sudo-less vagrant up:
- https://docs.vagrantup.com/v2/synced-folders/nfs.html

Removed a tiny strange char `U+05BB`

---

website/www/source/vmware/index.html.erb

Unfortuantely -> Unfortunately

---

website/docs/source/v2/vagrantfile/tips.html.md

See https://github.com/mitchellh/vagrant/issues/6794 for details

#6794 Add to doc trick how to define locale for SSH session in Vagrant

---

plugins/provisioners/chef/cap/suse/chef_install.rb
plugins/provisioners/chef/plugin.rb

Add chef install guest capability for suse.
Tested with sles12

add chef installer for suse

---

website/source/docs/getting-started/up.html.md

I just noticed this typo after reading the docs; please let me know if there's anything I missed with this PR.

Fixed typo in docs

---

website/source/docs/provisioning/docker.html.md

Fix typo in docker.html.md

---

templates/commands/ssh_config/config.erb
test/unit/plugins/commands/ssh_config/command_test.rb

Reverts mitchellh/vagrant#6589
Fixes https://github.com/mitchellh/vagrant/issues/6929

Revert "Escape identify file path"

---

templates/commands/init/Vagrantfile.erb
templates/commands/init/Vagrantfile.min.erb
test/unit/plugins/pushes/atlas/push_test.rb
test/unit/vagrant/config_test.rb
website/Vagrantfile
website/source/docs/provisioning/ansible.html.md
website/source/docs/provisioning/ansible_intro.html.md
website/source/docs/provisioning/ansible_local.html.md
website/source/docs/vagrantfile/tips.html.md
website/source/docs/vagrantfile/version.html.md
website/source/docs/vmware/kernel-upgrade.html.md
website/source/docs/vmware/usage.html.md

Fixes https://github.com/mitchellh/vagrant/issues/6961

Always use a string for Vagrantfile version

---

lib/vagrant/box_collection.rb
test/unit/vagrant/box_collection_test.rb

This should fix https://github.com/mitchellh/vagrant/issues/6892

Prerelease version fix

---

plugins/hosts/darwin/cap/rdp.rb
test/unit/plugins/hosts/darwin/cap/rdp_test.rb
website/source/docs/cli/rdp.html.md

Add extra_args cap for darwin rdp

---

website/source/docs/provisioning/chef_apply.html.md

Minor gramatical fix

---

website/source/docs/getting-started/synced_folders.html.md

Addresses https://github.com/mitchellh/vagrant/issues/6945

Clarifying synced folders docs.

---

website/source/docs/plugins/provisioners.html.md

Fixes https://github.com/mitchellh/vagrant/issues/7023

Fixed provisioner broken link

---

plugins/providers/hyperv/action/import.rb

Keep the disk name that is in the box file rather than copying to disk.*

Fix for #7040 to Preserve disk name

---

website/source/docs/cli/connect.html.md

If something complEments something, it completes it. ComplIment means
praise or free.

Typo: "complEments" for making it complEte.

---

website/source/docs/cli/snapshot.html.md

Adds website documentation for new snapshot CLI options.
Relates to #6879 (already merged)

Update website docs for #6879

---

plugins/providers/virtualbox/driver/version_4_1.rb

Fixes GH-7049
Another fixed error remains in other versions:
```ruby
return [] if e.extra_data[:stdout].include?("does not have")
```
should be
```ruby
return [] if e.extra_data[:stderr].include?("does not have")
```
Many methods are the same in different version_X, and should be moved to Base class.

Adds snapshot commands in VirtualBox 4.1

---

plugins/providers/virtualbox/driver/version_4_1.rb
plugins/providers/virtualbox/driver/version_4_2.rb
plugins/providers/virtualbox/driver/version_4_3.rb
plugins/providers/virtualbox/driver/version_5_0.rb

Different vbox versions print this to different streams, so check both just to be sure

Check both stderr and stdout

---

plugins/provisioners/chef/provisioner/base.rb
plugins/provisioners/chef/provisioner/chef_client.rb
templates/locales/en.yml
test/unit/plugins/provisioners/chef/provisioner/base_test.rb

Use hostname if no node_name is set

---

plugins/pushes/ftp/adapter.rb

Closes https://github.com/mitchellh/vagrant/pull/6316

Create parent directories during ftp push

---

website/source/docs/getting-started/up.html.md

Suggestion: How to exit the session: http://superuser.com/questions/704032/how-to-exit-ssh-of-vagrant-in-terminal

Exit the SSH session before vagrant destroy

---

lib/vagrant/util/is_port_open.rb

Rescue Errno::ENOTCONN

---

plugins/commands/login/client.rb
test/unit/plugins/commands/login/client_test.rb

Print a warning when token and envvar are set

---

contrib/bash/completion.sh

Add command: snapshot
Add Sub command for snapshot: delete list pop push restore save

update bash completion(snapshot)

---

website/source/downloads.html.erb

http://mathiasbynens.github.io/rel-noopener/

Do not allow referrer modification

---

website/source/docs/provisioning/basic_usage.html.md

I couldn't really understand how to use this feature.... I might be dumb, didn't rtfm, I dunno.  Here is a PR anyway to help clarify by example.

Adding example of using the preserve_order flag

---

plugins/commands/destroy/command.rb
plugins/commands/halt/command.rb
plugins/commands/package/command.rb
plugins/commands/port/command.rb
plugins/commands/rdp/command.rb
plugins/commands/ssh/command.rb
plugins/commands/ssh_config/command.rb
plugins/commands/status/command.rb
plugins/commands/suspend/command.rb
plugins/commands/up/command.rb
website/source/docs/cli/destroy.html.md
website/source/docs/cli/halt.html.md
website/source/docs/cli/package.html.md
website/source/docs/cli/port.html.md
website/source/docs/cli/provision.html.md
website/source/docs/cli/reload.html.md
website/source/docs/cli/resume.html.md
website/source/docs/cli/ssh.html.md
website/source/docs/cli/ssh_config.html.md
website/source/docs/cli/status.html.md
website/source/docs/cli/suspend.html.md
website/source/docs/cli/up.html.md

Make it clear that you can run commands on machine IDs too

---

website/source/docs/provisioning/puppet_apply.html.md

Hi,
just a small typo fix on the Puppet apply page.
Thanks for Vagrant :)

puppet_apply doc: small typo fix

---

plugins/provisioners/ansible/config/guest.rb
test/unit/plugins/provisioners/ansible/config/guest_test.rb
test/unit/plugins/provisioners/ansible/config/host_test.rb
test/unit/plugins/provisioners/ansible/config/shared.rb

This is a "dummy" self-assigned pull request, which single purpose is to trigger the travis-ci build against master branch (instead of a "wild" direct push to master).

provisoners/ansible: improve config test coverage

---

bin/vagrant
website/source/docs/other/environmental-variables.html.md

Allow users to force color

---

website/source/docs/other/environmental-variables.html.md

Document VAGRANT_NO_PARALLEL

---

website/source/docs/getting-started/boxes.html.md

Document how to specify explicit version of box

---

plugins/commands/box/command/remove.rb

Maybe better remove, not destroy the box?

Fix box remove --force help message

---

lib/vagrant/util/platform.rb

Check stdout instead of process output

---

plugins/guests/linux/cap/mount_nfs.rb
test/unit/plugins/guests/linux/cap/mount_nfs_test.rb

guests/linux: Ensure NFS retries when mounting

---

lib/vagrant/bundler.rb

Thanks to @mitchellh's excellent bisecting skilz
Fixes GH-7493

core/bundler: Reset specs in a way that works with new Rubygems

---

plugins/providers/virtualbox/driver/meta.rb
plugins/providers/virtualbox/driver/version_5_1.rb
plugins/providers/virtualbox/plugin.rb

Fixes #7411
Not sure why nobody has submitted a PR yet.

Add VirtualBox 5.1 driver

---

lib/vagrant/action/builtin/box_add.rb

Use RFC- and cURL-friendly file:/// URI. Fixes #7568.

---

Vagrantfile

Quieted the apt-get installs to reduce terminal output chaos.
Changed the rvm GPG key server to remove the expired key warning
when the rvm public key is used to verify the rvm download. Command
used conforms to that specified by rvm.io.
Ruby and bundler versions are read from Vagrant's gemspec and used
with rvm to download the latest Ruby version that complies with
the version constraint. Exact bundler version is installed according
to gemspec.
Rubygems is upgraded to latest version through rvm.
If you consider these changes as helpful to your "vagrant up" as I did, please consider accepting this pull request. I'm happy to amend any problems you may see.

Updated Vagrantfile to automatically install more recent versions of software.

---

lib/vagrant/util/platform.rb

See the discussions in both threads, this pull request fixes the incomplete fix of #6598 (which has its own issue, #6761 )

Fix for #6761 (fixes incomplete #6598)

---

.gitignore
lib/vagrant/action/builtin/ssh_run.rb
lib/vagrant/machine.rb
lib/vagrant/util/ssh.rb
plugins/commands/ssh_config/command.rb
plugins/communicators/ssh/communicator.rb
plugins/synced_folders/rsync/helper.rb
templates/commands/ssh_config/config.erb
test/unit/plugins/commands/ssh_config/command_test.rb
test/unit/plugins/synced_folders/rsync/helper_test.rb
test/unit/vagrant/machine_test.rb
website/source/docs/vagrantfile/ssh_settings.html.md

This is a continuation of #7621 to include a couple cleanups and rsync fix before merge.

ssh-agent interaction fix

---

README.md

Update required Ruby in the readme

---

plugins/commands/ssh_config/command.rb

Fix incorrect ssh-config output when '--host' is defined

---

plugins/kernel_v2/config/vm.rb
test/unit/plugins/kernel_v2/config/vm_test.rb

config/vm: cast box version to string before string operations

---

bin/vagrant

core: Rescue EINVAL exceptions when loading bundler

---

plugins/guests/netbsd/cap/rsync.rb

guests/netbsd: Use full path to pkg_add command

---

plugins/synced_folders/rsync/default_unix_cap.rb
test/unit/plugins/guests/linux/cap/rsync_test.rb

synced_folders/rsync: Quote exclude paths

---

website/source/layouts/_footer.erb
website/source/layouts/about.erb
website/source/security.html.erb

Add security page

---

plugins/communicators/ssh/communicator.rb
plugins/kernel_v2/config/ssh.rb
test/unit/plugins/communicators/ssh/communicator_test.rb
website/source/docs/vagrantfile/ssh_settings.html.md

Allow custom generation of environment variable exports

---

website/source/docs/virtualbox/configuration.html.md

Just a typo fix.
Hope you're having a great weekend! :)

Fix a typo in configuration.html.md

---

website/source/docs/cli/plugin.html.md
website/source/docs/installation/source.html.md
website/source/docs/plugins/development-basics.html.md

Also update version information and remove bundler instructions.

Update plugin docs. 

---

website/source/docs/cli/reload.html.md

shouldn't it be `reload` instead of `provision` ? :-/

fix reload command in docs

---

bin/vagrant

Prevent loading local Vagrantfile when disabling plugins for global actions

---

lib/vagrant/bundler.rb

Prevent interaction when removing plugin gems

---

lib/vagrant/util/env.rb

Remove direct bundler usage within Env util

---

plugins/commands/package/command.rb
website/source/docs/cli/package.html.md
website/source/docs/hyperv/limitations.html.md

Update documentation and package command to reflect support for Hyper-V.

Hyper-V package documentation

---

website/source/docs/vagrantfile/ssh_settings.html.md

Add missing config.ssh.keep_alive docs [GH-516]

---

website/source/layouts/_header.erb

Adds Google Tag Manager to the website per Hashicorp's request in https://app.asana.com/0/102877007168505/211895671335145
@captainill

Add Google Tag Manager #GTM-NR2SD7C

---

website/source/docs/networking/forwarded_ports.html.md

Added auto_correct to list of options in Docs. See issue #8245.

[Docs] Added auto_correct to list of options

---

website/source/docs/provisioning/salt.html.md

Add note about vagrant-salt plugin

---

website/source/docs/vagrantfile/ssh_settings.html.md

Add note on output behavior when pty enabled.

---

plugins/commands/plugin/action/expunge_plugins.rb
plugins/commands/plugin/command/expunge.rb

Display default on expunge command questions.

---

lib/vagrant/environment.rb
test/unit/vagrant/environment_test.rb

Fix environment gems_path location

---

lib/vagrant/bundler.rb

See https://github.com/mitchellh/vagrant/issues/8253.

Add gem_version to plugin_info for local installs

---

lib/vagrant/util/subprocess.rb
test/unit/vagrant/util/subprocess_test.rb

Adds `Util::Subprocess#stop` and `Util::Subprocess#running?` methods

Add new methods to Subprocess

---

lib/vagrant/bundler.rb

Prefer given source if available when installing plugin

---

templates/commands/init/Vagrantfile.min.erb

Missing box-version for Vagrantfile.min.erb

---

lib/vagrant/action/builtin/box_add.rb
lib/vagrant/util.rb
lib/vagrant/util/credential_scrubber.rb
test/unit/vagrant/action/builtin/box_add_test.rb

Scrub credentials from box URLs

---

lib/vagrant/errors.rb
lib/vagrant/util.rb
lib/vagrant/util/command_deprecation.rb
plugins/commands/push/command.rb
templates/locales/en.yml
test/unit/plugins/commands/push/command_test.rb
test/unit/vagrant/util/command_deprecation_test.rb

Add utility module to provide consistent means of command deprecation.

Command deprecation module

---

plugins/communicators/ssh/communicator.rb
test/unit/plugins/communicators/ssh/communicator_test.rb

This PR is an extension of #7676 and discards any information received on stderr prior to the command being run.
Fixes: #8288

Discard initial stderr data

---

lib/vagrant/box_collection.rb

This PR fixes issue #7955.
`bundle exec rake` tests run successfully.

Fix box sorting in box_collection

---

lib/vagrant/box_collection.rb
test/unit/vagrant/box_collection_test.rb

Sort the result of BoxCollection#all and add test coverage for sorting behavior on BoxCollection#all and BoxCollection#find

Sort box list results

---

.gitignore
test/acceptance/provider-virtualbox/linked_clone_spec.rb
test/acceptance/provider-virtualbox/network_intnet_spec.rb
test/vagrant-spec/Vagrantfile.spec
test/vagrant-spec/configs/vagrant-spec.config.virtualbox.rb
test/vagrant-spec/scripts/ubuntu-run.virtualbox.sh
test/vagrant-spec/scripts/ubuntu-setup.virtualbox.sh

Adds Vagrantfile and supporting files for running black box testing on built packages using vagrant-spec.

Add initial setup for package testing

---

plugins/providers/hyperv/action/import.rb
plugins/providers/hyperv/config.rb
plugins/providers/hyperv/scripts/import_vm_xml.ps1
website/source/docs/hyperv/configuration.html.md
website/source/docs/hyperv/index.html.md

This is simply a cleaned up version of this PR: #7738

Nested Hyper-V

---

templates/guests/debian/network_dhcp.erb
test/unit/templates/guests/debian/network_dhcp_test.rb

Remove hardcoded interface name from template

---

plugins/commands/up/command.rb
test/unit/plugins/commands/up/command_test.rb

Prevent other provider install attempts when explicit provider given

---

lib/vagrant.rb

Warn when failing to require plugin instead of hard failure

---

plugins/guests/linux/cap/mount_smb_shared_folder.rb
test/unit/plugins/guests/linux/cap/mount_smb_shared_folder.rb

Fix linux guest mount smb capability

---

plugins/providers/docker/provider.rb

Do better at finding ssh_info for Docker

---

plugins/providers/docker/config.rb

Do not force docker host VM on Darwin or Windows

---

templates/commands/init/Vagrantfile.erb

Add note on forwarded_port and include host_ip configuration

---

vagrant.gemspec

Update gem dependency constraints

---

lib/vagrant/bundler.rb

Force wrappers to be generated to prevent invalid version parsing

---

plugins/communicators/ssh/communicator.rb
plugins/communicators/winssh/communicator.rb
plugins/communicators/winssh/config.rb
plugins/communicators/winssh/plugin.rb
plugins/provisioners/shell/provisioner.rb
test/unit/plugins/communicators/winssh/communicator_test.rb
website/source/docs/vagrantfile/winssh_settings.html.md
website/source/layouts/docs.erb

Provide support for SSH communication to Win32-OpenSSH on Windows guests.

Add winssh communicator

---

plugins/provisioners/shell/provisioner.rb

Quote exec_path to properly handle spaces in path

---

plugins/guests/arch/cap/change_host_name.rb
plugins/guests/atomic/cap/change_host_name.rb
plugins/guests/darwin/cap/change_host_name.rb
plugins/guests/debian/cap/change_host_name.rb
plugins/guests/freebsd/cap/change_host_name.rb
plugins/guests/gentoo/cap/change_host_name.rb
plugins/guests/omnios/cap/change_host_name.rb
plugins/guests/openbsd/cap/change_host_name.rb
plugins/guests/photon/cap/change_host_name.rb
plugins/guests/pld/cap/change_host_name.rb
plugins/guests/redhat/cap/change_host_name.rb
plugins/guests/slackware/cap/change_host_name.rb
plugins/guests/suse/cap/change_host_name.rb

Remove comment removal from /etc/hosts file on guests

---

lib/vagrant/util/platform.rb

Fixed admin test to verify an elevated shell

---

website/source/docs/hyperv/configuration.html.md

Update docs to reflect correct setting for key_value_pair_exchange

---

plugins/providers/hyperv/scripts/import_vm_vmcx.ps1
plugins/providers/hyperv/scripts/import_vm_xml.ps1

Update conditional check to use string equality

---

plugins/guests/debian/cap/configure_networks.rb
templates/guests/debian/network_dhcp.erb
test/unit/templates/guests/debian/network_dhcp_test.rb

Fetch first network device and pass to template for rendering

---

bin/vagrant
lib/vagrant/errors.rb
lib/vagrant/util/platform.rb
lib/vagrant/util/ssh.rb
lib/vagrant/util/which.rb
plugins/providers/virtualbox/driver/base.rb
plugins/providers/virtualbox/provider.rb
templates/locales/en.yml
website/source/docs/other/wsl.html.md
website/source/layouts/docs.erb

Add support for running within WSL

---

bin/vagrant
lib/vagrant/errors.rb
lib/vagrant/util.rb
lib/vagrant/util/platform.rb
plugins/providers/docker/driver.rb
plugins/providers/virtualbox/driver/base.rb
plugins/providers/virtualbox/driver/version_5_0.rb
templates/locales/en.yml
website/source/docs/other/wsl.html.md

Provide better auto-detection when initializing WSL support and allow user enablement via flag environment variable. Updates vbox usage to properly setup when being run from within the WSL.

Update WSL integration

---

website/source/docs/boxes.html.md

Fix #8598 : example in docs for box usage.

---

plugins/provisioners/ansible/provisioner/host.rb
test/unit/plugins/provisioners/ansible/provisioner_test.rb

fix `config.ssh.keys_only = false` for ansible

---

plugins/synced_folders/unix_mount_helpers.rb

Chomp lookup gid

---

plugins/providers/docker/provider.rb

Fixing vagrant issue https://github.com/mitchellh/vagrant/issues/8705. It survived 2 minor versions. Makes me think I'm the only one using this code-path :)

Fixing vagrant ssh issue 8705 - vagrant ssh with docker provider failing

---

lib/vagrant/bundler.rb
lib/vagrant/plugin/manager.rb
test/unit/vagrant/plugin/manager_test.rb

Updates plugin management to be more conservative on updates and removes restrictions currently imposed on system plugins.

Adjustments to internal plugin handling

---

website/source/docs/other/environmental-variables.html.md

Fix typo in docs

---

lib/vagrant/action/builtin/box_add.rb
test/unit/vagrant/action/builtin/box_add_test.rb

Prevent URI parse errors when checking box name

---

lib/vagrant/util/ssh.rb
plugins/provisioners/ansible/provisioner/host.rb
test/unit/plugins/provisioners/ansible/provisioner_test.rb
test/unit/vagrant/util/ssh_test.rb

Rebased #7862 and fixed up the tests based on the latest changes from master.
Fixes #7863

Use '-o IdentityFile=' instead of '-i'

---

website/source/docs/synced-folders/nfs.html.md

Improve documentation.
Fix https://github.com/mitchellh/vagrant/issues/8801

add note about groups for sudoers

---

contrib/bash/completion.sh

add box prune command to completion.sh

add box prune to contrib bash completion

---

website/source/intro/vs/docker.html.md

Update Vagrant vs Docker description

---

plugins/providers/virtualbox/action/prepare_nfs_settings.rb
test/unit/plugins/providers/virtualbox/action/prepare_nfs_settings_test.rb

When preparing the NFS settings on VirtualBox the guest IP addresses
are pulled from VirtualBox directly and any static addresses are
pulled as well. This can lead to aquiring a host IP and machine IP
but results in a failure of NFS mount because the IPs are not on
the same network. This filters the machine IP result to validate
it is within the host adapter IP range.

Filter any machine_ip when preparing the NFS settings

---

website/source/docs/other/environmental-variables.html.md
website/source/docs/other/wsl.html.md

Update documentation to include more environment variable information

---

templates/locales/en.yml

Include plugin update option to vagrant upgrade error.

---

contrib/sudoers/linux-ubuntu

This commit updates the Ubuntu sudoers file in contrib to be up to date
with the documentation.
Fixes #8842

(#8842) Update contrib sudoers file for Ubuntu

---

plugins/providers/docker/driver/compose.rb
test/unit/plugins/providers/docker/driver_compose_test.rb

Split compose links if string values

---

plugins/providers/docker/driver/compose.rb
test/unit/plugins/providers/docker/driver_compose_test.rb

Expand relative volume paths for compose on current cwd

---

plugins/synced_folders/rsync/helper.rb
test/unit/plugins/synced_folders/rsync/helper_test.rb

Format host address for rsync when IPv6

---

plugins/providers/docker/config.rb
templates/locales/providers_docker.yml
test/unit/plugins/providers/docker/config_test.rb

Resolves unexpected failure reported in #8823

Error when compose and force_host_vm are enabled together

---

lib/vagrant/util/guest_inspection.rb
lib/vagrant/util/platform.rb
plugins/hosts/gentoo/cap/nfs.rb
plugins/hosts/linux/cap/nfs.rb
plugins/hosts/redhat/cap/nfs.rb
test/unit/plugins/hosts/linux/cap/nfs_test.rb
test/unit/vagrant/util/platform_test.rb

Add support for systemd detection and using correct method
for starting/checking host nfs service.
Fixes #8689 #8658 #8430 #7173 #6304

Update linux host NFS capability

---

plugins/providers/virtualbox/driver/meta.rb
plugins/providers/virtualbox/driver/version_5_2.rb
plugins/providers/virtualbox/plugin.rb

This adds support for VirtualBox 5.2 (now in [beta](https://forums.virtualbox.org/viewtopic.php?f=15&t=84286))
I've modeled this changes here after #7574 and subsequent refactoring of the 5.1 addition in #8326

Virtualbox 5.2 support

---

plugins/providers/hyperv/scripts/import_vm_vmcx.ps1

There was an error in the HyperV import script which makes it impossible to set the auto_stop_action.

Auto stop action is configured wrongly

---

plugins/provisioners/puppet/provisioner/puppet.rb

Properly call the winssh communicator if needed in the puppet provisioner.
Fixes https://github.com/hashicorp/vagrant/issues/9013

Fix winssh communicator support in puppet provisioner

---

website/Gemfile
website/Gemfile.lock
website/Makefile
website/packer.json
website/source/docs/vagrant-cloud/api.html.md
website/source/docs/vagrant-cloud/api.html.md.erb
website/source/docs/vagrant-cloud/boxes/catalog.html.md
website/source/docs/vagrant-cloud/boxes/create-version.html.md
website/source/docs/vagrant-cloud/boxes/create.html.md
website/source/docs/vagrant-cloud/boxes/distributing.html.md
website/source/docs/vagrant-cloud/boxes/index.html.md
website/source/docs/vagrant-cloud/boxes/lifecycle.html.md
website/source/docs/vagrant-cloud/boxes/private.html.md
website/source/docs/vagrant-cloud/boxes/release-workflow.html.md
website/source/docs/vagrant-cloud/boxes/using.html.md
website/source/docs/vagrant-cloud/index.html.md
website/source/docs/vagrant-cloud/organizations/authentication-policy.html.md
website/source/docs/vagrant-cloud/organizations/create.html.md
website/source/docs/vagrant-cloud/organizations/index.html.md
website/source/docs/vagrant-cloud/organizations/migrate.html.md
website/source/docs/vagrant-cloud/request-limits.html.md
website/source/docs/vagrant-cloud/support.html.md
website/source/docs/vagrant-cloud/users/authentication.html.md
website/source/docs/vagrant-cloud/users/index.html.md
website/source/docs/vagrant-cloud/users/recovery.html.md
website/source/docs/vagrant-cloud/vagrant-cloud-migration.html.md
website/source/layouts/docs.erb
website/source/layouts/vagrant-cloud.erb

Adds API documentation for Vagrant Cloud, along with code examples in cURL and Ruby.

website: Vagrant Cloud API docs

---

.travis.yml
lib/vagrant/cli.rb
lib/vagrant/plugin/v2/communicator.rb
lib/vagrant/registry.rb
lib/vagrant/util/keypair.rb
plugins/provisioners/shell/config.rb
plugins/pushes/local-exec/config.rb
test/unit/plugins/provisioners/shell/config_test.rb
test/unit/plugins/pushes/local-exec/config_test.rb
vagrant.gemspec

Rebase of #8284 plus an additional update to the gemspec for ruby 2.4 and a gem upgrade for spec tests.

Introduce Ruby 2.4 to Vagrant

---

plugins/guests/windows/guest_network.rb

winssh communicator is not functional currently as it fails to configure the guest network.
Fixes 
https://github.com/hashicorp/vagrant/issues/9011

Fix guest network setup with winssh communicator

---

plugins/communicators/winrm/helper.rb
test/unit/plugins/communicators/winrm/helper_test.rb

See https://github.com/hashicorp/vagrant/issues/8996

Adding check for APIPA in winrm helper to fix #8996

---

lib/vagrant/util/platform.rb
test/unit/vagrant/util/platform_test.rb

Check for vagrant.exe path before validating versions

---

plugins/commands/destroy/command.rb
templates/locales/en.yml
test/unit/plugins/commands/destroy/command_test.rb
website/source/docs/cli/destroy.html.md

This commit introduces parallel destroy using the batch action class for
the destroy command.
This PR overrides #8202

Introduce parallel destroy for certain providers

---

lib/vagrant/action/general/package.rb
templates/locales/en.yml
test/unit/plugins/commands/package/command_test.rb

This pull request is in to resolve ticket
Fixes #9088

Fix --output path with specified folder

---

plugins/guests/haiku/cap/change_host_name.rb
plugins/guests/haiku/guest.rb
plugins/guests/haiku/plugin.rb

Adds support for the Haiku operating system.
See enhancement #7803

Add support for the Haiku operating system

---

.github/ISSUE_TEMPLATE.md

Add note about removing sensitive data from Vagrantfiles before pasting

Add note about removing sensitive data

---

plugins/providers/hyperv/action/import.rb

Removed rogue $ from string in hyperv import.rb

---

website/source/docs/other/debugging.html.md

By using `Tee-Object` you can ouput the debug log to the console and a file, which is way easier to use than just outputting to a logfile. This makes debugging a lot easier.

Update docs to use `Tee-Object` in PowerShell in Windows.

---

website/source/docs/provisioning/ansible_local.html.md

Hi,
I found a faulty parameter when reading the documentation.
-Ramon

correct pip argument

---

website/source/docs/vagrantfile/winrm_settings.html.md

fixes https://github.com/hashicorp/vagrant/issues/8365

update ssl to :ssl

---

vagrant.gemspec

Update Ruby version constraint

---

plugins/guests/suse/cap/change_host_name.rb
test/unit/plugins/guests/suse/cap/change_host_name_test.rb

Possible fix for [this issue](https://github.com/hashicorp/vagrant/issues/9211)

Use basename for setting hostname on Suse

---

lib/vagrant/cli.rb
lib/vagrant/environment.rb
lib/vagrant/util.rb
lib/vagrant/util/checkpoint_client.rb
plugins/commands/version/command.rb
templates/locales/en.yml
test/unit/vagrant/cli_test.rb
test/unit/vagrant/util/checkpoint_client_test.rb
vagrant.gemspec

Update checkpoint integration to provide user notification on new version availability. Also adds notification support.

Update checkpoint integration

---

RELEASE.md
website/source/docs/cli/plugin.html.md
website/source/docs/provisioning/ansible_common.html.md
website/source/docs/synced-folders/nfs.html.md
website/source/docs/synced-folders/rsync.html.md
website/source/intro/vs/index.html.md
website/source/vmware/index.html.erb

Propose fix some typos

---

plugins/guests/debian/cap/change_host_name.rb

Debian: Renew DHCP lease on hostname change

---

plugins/guests/debian/cap/change_host_name.rb

Debian: Point hostname to 127.0.1.1 in /etc/hosts

---

lib/vagrant/util/powershell.rb

Prior to this commit, the function used to determine the version of
Powershell would loop forever inside the Subprocess.execute function
because the process would never exit. This commit fixes that by passing
in a ruby block to capture the version from stdout instead of trying to
capture it from the returned process when it exits.
Fixes #9056

Pass ruby block to capture stdout when determining PS version

---

lib/vagrant/util/credential_scrubber.rb
test/unit/vagrant/util/credential_scrubber_test.rb

Ignore empty strings registered as sensitive

---

website/source/docs/other/wsl.html.md

Add explicit steps to add VirtualBox binaries to the PATH

Add VirtualBox PATH export to WSL docs

---

test/unit/vagrant/util/is_port_open_test.rb

Use 127.0.0.1 instead of localhost

---

website/Gemfile
website/Gemfile.lock
website/source/index.html.erb

As requested by Mitchell & Armon ✨

Some small website fixes

---

website/source/docs/hyperv/index.html.md

Rebase of #9077. Putting back the information about installation instructions

Clarify Hyper-V documentation

---

website/source/docs/vagrant-cloud/api.html.md.erb

Creating a usable box from scratch
- api only accepts puts no push when uploading the file
- the final step of actually releasing the version was missing from ruby example

ruby ex missing a step & upload use wrong verb

---

plugins/guests/photon/guest.rb

less specific string grep to fix PhotonOS 2.0 detection

---

README.md

This allows developers to find the IRC community more easily.

Updating README.md with #vagrant IRC channel information.

---

lib/vagrant/util/checkpoint_client.rb

Prevent exceptions from being raised by checkpoint

---

lib/vagrant.rb
lib/vagrant/shared_helpers.rb
lib/vagrant/util/platform.rb
test/unit/vagrant/shared_helpers_test.rb
test/unit/vagrant/util/platform_test.rb

Suppress errors from invalid path encoding and carry on with best effort

---

lib/vagrant/action.rb

Add missing action autoloads

---

plugins/guests/windows/cap/mount_shared_folder.rb
test/unit/plugins/guests/windows/cap/mount_shared_folder_test.rb

Noted here: https://github.com/mitchellh/vagrant/issues/4593#issuecomment-236812537

Fix virtualbox shared folders path

---

website/source/docs/share/index.html.md

Include installation information for vagrant share plugin

---

lib/vagrant.rb

Fix require for ffi-win32-extensions

---

plugins/provisioners/chef/config/chef_zero.rb
plugins/provisioners/chef/provisioner/chef_zero.rb

This commit ensures that all paths are properly file path expanded for
each config option in chef_zero.
Fixes #9383

File path expand all chef_zero config path options

---

plugins/hosts/windows/cap/smb.rb
plugins/hosts/windows/plugin.rb
test/unit/plugins/hosts/windows/cap/smb_test.rb

Default SMB version to 2.0 for linux guest mounts on Windows hosts

---

website/source/assets/stylesheets/_global.scss

Prevents page from rendering blank half way through initial loading.

Remove CSS for FOUT prevention

---

bin/vagrant

Disable report on exception by default

---

plugins/commands/login/middleware/add_authentication.rb
test/unit/plugins/commands/login/middleware/add_authentication_test.rb

Ignore URLs which cannot be parsed in the authentication middleware

---

plugins/provisioners/chef/provisioner/chef_solo.rb
test/unit/plugins/provisioners/chef/provisioner/chef_solo_test.rb

Trim drive letter prefix from path

---

plugins/communicators/ssh/communicator.rb
test/unit/plugins/communicators/ssh/communicator_test.rb

Log error and proceed when private key permissions fail

---

plugins/providers/hyperv/action/import.rb

Update script parameter name in option to switchid

---

plugins/hosts/windows/cap/smb.rb
test/unit/plugins/hosts/windows/cap/smb_test.rb

Use net.exe to fetch SMB shares when Get-SmbShare is not available

---

plugins/guests/debian/cap/configure_networks.rb
test/unit/plugins/guests/debian/cap/configure_networks_test.rb

Prior to this commit, when setting up private networks on Ubuntu using
netplan, it assumed that the guest was using systemd, the suggested
default tool to manage networking, and did not take into account devices
that could be managed with NetworkManager. This commit fixes that by
looking at the devices managed on the guest to see if its managed by
NetworkManager, and if so, use that renderer for netplan instead of
networkd.
Fixes #9726

Update netplan config generation to detect NetworkManager

---

.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE.md
README.md
website/README.md

Motivated by https://twitter.com/mitchellh/status/996381507756294144
@mitchellh @chrisroberts @briancain this is an attempt to cherry-pick some good parts from Packer and Terraform contributing guide lines, trying to adapt them to my vision/understanding on how Vagrant development dynamics work. I hope it fits with your perspectives as well. But if it is not the case, please close and start a new topic branch, I won't be offended at all ;-)
For english-quality and project-ownership reason, I'd appreciate if Chris or Brian could take the lead to polish and adapt the changes proposed here... Many thanks in advance!

Update CONTRIBUTING.md (and related stuff)

---

CHANGELOG.md

Missed to be part of #9879. Sorry...

Update CHANGELOG about #9879 and #9796

---

plugins/guests/debian/cap/configure_networks.rb

https://github.com/hashicorp/vagrant/issues/9570

Fix for ubuntu 17.10+ netplan

---

website/source/downloads.html.erb

Add link to CHANGELOG for current release on downloads page

---

lib/vagrant/util/powershell.rb
plugins/hosts/windows/cap/smb.rb
plugins/providers/hyperv/scripts/check_hyperv.ps1
plugins/providers/hyperv/scripts/clone_vhd.ps1
plugins/providers/hyperv/scripts/configure_vm.ps1
plugins/providers/hyperv/scripts/create_snapshot.ps1
plugins/providers/hyperv/scripts/delete_snapshot.ps1
plugins/providers/hyperv/scripts/delete_vm.ps1
plugins/providers/hyperv/scripts/export_vm.ps1
plugins/providers/hyperv/scripts/file_sync.ps1
plugins/providers/hyperv/scripts/get_network_config.ps1
plugins/providers/hyperv/scripts/get_network_mac.ps1
plugins/providers/hyperv/scripts/get_switches.ps1
plugins/providers/hyperv/scripts/get_vm_status.ps1
plugins/providers/hyperv/scripts/has_vmcx_support.ps1
plugins/providers/hyperv/scripts/import_vm.ps1
plugins/providers/hyperv/scripts/list_snapshots.ps1
plugins/providers/hyperv/scripts/restore_snapshot.ps1
plugins/providers/hyperv/scripts/resume_vm.ps1
plugins/providers/hyperv/scripts/set_name.ps1
plugins/providers/hyperv/scripts/set_network_mac.ps1
plugins/providers/hyperv/scripts/set_network_vlan.ps1
plugins/providers/hyperv/scripts/set_vm_integration_services.ps1
plugins/providers/hyperv/scripts/start_vm.ps1
plugins/providers/hyperv/scripts/stop_vm.ps1
plugins/providers/hyperv/scripts/suspend_vm.ps1
plugins/providers/hyperv/scripts/utils/VagrantMessages/VagrantMessages.psm1
test/unit/vagrant/util/powershell_test.rb

Handful of PowerShell cleanup things:
* Update messaging functions in Hyper-V provider to use proper naming format
* Remove buffer resizing as it caused undesired UX results
* Use `Out-String` to prevent wrapping where issues are known to exist

Misc. PowerShell cleanup

---

lib/vagrant/box_collection.rb
lib/vagrant/util/platform.rb
lib/vagrant/util/powershell.rb
plugins/providers/hyperv/action/delete_vm.rb
plugins/providers/hyperv/action/export.rb
plugins/providers/hyperv/action/import.rb
plugins/providers/hyperv/driver.rb
plugins/providers/hyperv/provider.rb
plugins/providers/hyperv/scripts/utils/VagrantVM/VagrantVM.psm1
templates/locales/synced_folder_smb.yml
test/unit/plugins/providers/hyperv/action/delete_vm_test.rb
test/unit/plugins/providers/hyperv/driver_test.rb
test/unit/plugins/providers/hyperv/provider_test.rb
test/unit/vagrant/util/powershell_test.rb

Support Hyper-V provider within WSL

---

plugins/providers/hyperv/action.rb
plugins/providers/hyperv/action/check_access.rb
plugins/providers/hyperv/errors.rb
plugins/providers/hyperv/scripts/check_hyperv_access.ps1
plugins/providers/hyperv/scripts/utils/VagrantVM/VagrantVM.psm1
templates/locales/providers_hyperv.yml

Also includes updated function name to prevent naming warnings and adds missing flag when cloning.
Fixes #9633

Add Hyper-V access check on data directory

---

bin/vagrant
test/unit/bin/vagrant_test.rb

Disable vagrantfile with plugin commands

---

lib/vagrant/util/platform.rb
test/unit/vagrant/util/platform_test.rb

Always force string type conversion of path

---

plugins/providers/hyperv/action.rb
plugins/providers/hyperv/action/configure.rb
plugins/providers/hyperv/config.rb
plugins/providers/hyperv/scripts/configure_vm.ps1
plugins/providers/hyperv/scripts/create_snapshot.ps1
test/unit/plugins/providers/hyperv/action/configure_test.rb
test/unit/plugins/providers/hyperv/config_test.rb

Also prevents provision/configure of guest when restoring snapshot.
Fixes #9977

Enable checkpoints for snapshots if disabled

---

plugins/providers/hyperv/scripts/check_hyperv_access.ps1
plugins/providers/hyperv/scripts/utils/VagrantVM/VagrantVM.psm1

Removes localization dependency from Hyper-V access check.
Fixes #9973

Fix Hyper-V access check

---

lib/vagrant/util/downloader.rb
website/source/docs/other/environmental-variables.html.md

Added option to add to User-Agent

---

website/source/docs/installation/index.html.md

This is a continuation of the pull request #9919 that includes information about what to do if on Windows with Hyper-V.

Update installation docs with multi-hypervisor warning

---

website/source/docs/plugins/development-basics.html.md
website/source/docs/plugins/guests.html.md
website/source/docs/plugins/hosts.html.md
website/source/docs/plugins/providers.html.md
website/source/docs/providers/configuration.html.md
website/source/docs/provisioning/ansible.html.md
website/source/docs/provisioning/chef_solo.html.md
website/source/docs/provisioning/file.html.md
website/source/docs/virtualbox/configuration.html.md

https://www.vagrantup.com/docs/provisioning/file.html
https://www.vagrantup.com/docs/provisioning/ansible.html#force-paramiko-connection-mode
https://www.vagrantup.com/docs/provisioning/chef_solo.html#custom-json-data
https://www.vagrantup.com/docs/plugins/development-basics.html#plugin-components
https://www.vagrantup.com/docs/plugins/guests.html#implementation
https://www.vagrantup.com/docs/plugins/hosts.html#implementation
https://www.vagrantup.com/docs/plugins/providers.html#configuration
https://www.vagrantup.com/docs/providers/configuration.html#overriding-configuration
https://www.vagrantup.com/docs/virtualbox/configuration.html#gui-vs-headless

Colorize ruby commands

---

lib/vagrant/util/ssh.rb
plugins/kernel_v2/config/ssh_connect.rb
test/unit/plugins/kernel_v2/config/ssh_connect_test.rb
test/unit/vagrant/machine_test.rb
vagrant.gemspec
website/source/docs/vagrantfile/ssh_settings.html.md

Also includes mapping of verify_host_key value to new values
introduced in 5.0.0

Update net-ssh constraint

---

plugins/communicators/winrm/plugin.rb
test/unit/plugins/communicators/winrm/plugin_test.rb
website/source/docs/other/environmental-variables.html.md

Add warning when vagrant-winrm is found

---

lib/vagrant/util/subprocess.rb
test/unit/vagrant/util/subprocess_test.rb

If starting a process while running from within AppImage adjust
the LD_LIBRARY_PATH of the subprocess when the executable exists
outside of the AppImage. This prevents issues of invalid dynamic
library lookups when the AppImage contains common named libraries.
Works with: hashicorp/vagrant-installers#140
Fixes: #10052

Detect AppImage and update executable environment if required

---

plugins/providers/docker/driver.rb
test/unit/plugins/providers/docker/driver_test.rb

Fixes #9085 
This pull request brings in the PR #9531 and adds a unit test for its behavior.

Convert windows paths for volume mounts on docker driver

---

website/source/docs/vagrantfile/machine_settings.html.md

Add note about /etc/hosts for guest hostname setting

---

lib/vagrant/environment.rb
test/unit/vagrant/environment_test.rb

Fix local plugin prompt and add coverage

---

CHANGELOG.md

Seems in the rush to get a new version out, the changelog wasn't updated?

Changelog missing version

---

website/source/docs/synced-folders/rsync.html.md

Add note about rsync__auto option

---

plugins/provisioners/salt/bootstrap-salt.sh

This makes it silent (no progress information), which would otherwise
result in output like the following (when the output from the bootstrap
script is displayed in verbose mode):
% Total    % Recei
ved % Xferd  Avera
ge Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0
0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  244k  100
244k    0     0
458k      0 --:--:-- --:--:-- --:--:--  458k
*  INFO: Running version: 2017.12.13
…

salt: bootstrap-salt.sh: use -s with curl

---

plugins/provisioners/salt/provisioner.rb
test/unit/plugins/provisioners/salt/provisioner_test.rb
website/source/docs/provisioning/salt.html.md

Fixes #8328, includes pull request #8328 but adds unit tests for behavior.

Salt pillar configuration on Windows guests

---

lib/vagrant/vagrantfile.rb
plugins/kernel_v2/config/vm.rb
test/unit/vagrant/vagrantfile_test.rb
website/source/docs/vagrantfile/machine_settings.html.md

This pull request is a fixup and rebase of the pull request https://github.com/hashicorp/vagrant/pull/8181. It also includes a test for this new option.

Add config option `ignore_box_vagrantfile`

---

plugins/providers/virtualbox/action/match_mac_address.rb
plugins/providers/virtualbox/driver/version_5_0.rb
templates/locales/en.yml
test/unit/plugins/providers/virtualbox/action/match_mac_address_test.rb
test/unit/plugins/providers/virtualbox/driver/version_5_0_test.rb

Allow automatic mac address assignment with virtuabox provider

---

website/source/docs/triggers/configuration.html.md

This commit provides a bit more context to using the new Ruby trigger
option.

Add more information about Ruby trigger option

---

plugins/providers/hyperv/scripts/configure_vm.ps1

Wrap automatic checkpoint enable to prevent inadvertent execution

---

plugins/providers/hyperv/scripts/configure_vm.ps1

Only configure CheckpointType if available to be configured.

---

lib/vagrant/environment.rb
test/unit/vagrant/environment_test.rb

Provide rgloader for project local plugins

---

website/source/docs/cli/ssh.html.md

Add information on using pageant with ssh

---

plugins/provisioners/ansible/provisioner/guest.rb

@ #10258 | BUG: should not create /tmp/vagrant-ansible/inventory/vagrant_ansible_local_inventory/vagrant_ansible_local_inventory

---

plugins/providers/docker/action/host_machine_sync_folders.rb
test/unit/plugins/providers/docker/action/host_machine_sync_folders_test.rb

This pull request includes the changes from @MartinMystikJonas in #10286 as well as some missing unit tests for the given class.
Fixes #10282

Deterministic host VM synced folder location for Docker provider

---

website/source/docs/vmware/boxes.html.md

Update vmware_desktop in boxes.html.md

---

website/source/docs/vagrant-cloud/boxes/create.html.md

Link to generate token is broken. Fixed it.

fix broken link to token

---

plugins/providers/virtualbox/driver/meta.rb
plugins/providers/virtualbox/driver/version_5_2.rb
plugins/providers/virtualbox/driver/version_6_0.rb
plugins/providers/virtualbox/plugin.rb

Adds driver for VirtualBox 6.0. Also updates the 5.2 driver to inherit from the 5.0 driver since no changes have been required since that point.

Add support for VirtualBox 6.0

---

lib/vagrant/vagrantfile.rb
test/unit/vagrant/vagrantfile_test.rb

The project local metadata file may contain invalid information to properly
lookup the configured box. This may occur if the file has been moved,
modified, or the backing box has been removed. In those cases, fall back
to the configuration defined in the Vagrantfile to load the box.
Fixes #10338

Fallback to Vagrantfile configuration when local metadata lookup fails

---

lib/vagrant/util/powershell.rb

Update powerup to handle spaces properly in arguments

---

plugins/providers/hyperv/scripts/get_network_config.ps1

Fix typo in hyper-v network configuration detection script

---

plugins/commands/snapshot/command/root.rb
test/unit/plugins/commands/snapshot/command/root_test.rb

snapshot plugin: Raise error for bad subcommand.

---

lib/vagrant/machine.rb
lib/vagrant/util/ssh.rb
plugins/commands/ssh_config/command.rb
plugins/communicators/ssh/communicator.rb
plugins/kernel_v2/config/ssh.rb
plugins/kernel_v2/config/ssh_connect.rb
plugins/synced_folders/rsync/helper.rb
templates/commands/ssh_config/config.erb
templates/locales/en.yml
test/unit/plugins/commands/ssh_config/command_test.rb
test/unit/plugins/communicators/ssh/communicator_test.rb
test/unit/plugins/kernel_v2/config/ssh_connect_test.rb
test/unit/plugins/kernel_v2/config/ssh_test.rb
test/unit/plugins/synced_folders/rsync/helper_test.rb
test/unit/vagrant/machine_test.rb
test/unit/vagrant/util/ssh_test.rb
website/source/docs/vagrantfile/ssh_settings.html.md

This PR is extended from #10245 to provide option validation,
documentation, and test coverage for the new options.

Add support for config and remote_user to SSH options

---

lib/vagrant/errors.rb
plugins/synced_folders/rsync/command/rsync_auto.rb
plugins/synced_folders/rsync/default_unix_cap.rb
plugins/synced_folders/rsync/helper.rb
templates/locales/en.yml
test/unit/plugins/synced_folders/rsync/command/rsync_auto_test.rb
test/unit/plugins/synced_folders/rsync/helper_test.rb

This PR is based on #10461 with the non-merge commits cherry-picked
out and updates to make the implementation more generic applied. Also
includes test coverage on things which have been updated.
Fixes #10460

Prevent rsync-auto crashes

---

test/unit/vagrant/util/checkpoint_client_test.rb

Use `env.ui` for expectations instead of custom double. Fix upgrade
notification test and ensure upgrade notifications are sent to the
error channel.

Update checkpoint client tests

---

plugins/provisioners/salt/bootstrap-salt.ps1

Upgrade default Salt version from 2017.7.1 to 2018.3.3

---

website/source/docs/virtualbox/index.html.md

As mentioned in `CHANGELOG.md` for v2.2.2.

Add VirtualBox version 6.0.x to docs.

---

plugins/communicators/ssh/communicator.rb
test/unit/plugins/communicators/ssh/communicator_test.rb

Fix garbage detection within SSH communicator

---

website/source/docs/vmware/installation.html.md

Vagrant requires internet access

add note to FAQ for internet requirement - license

---

lib/vagrant/util/platform.rb
test/unit/vagrant/util/platform_test.rb

I changed it to convert between WSL path and Windows path using `wslpath` command in `wsl_rootfs` `wsl_to_windows_path` `wsl_windows_accessible_path`.
leaving the original code as a fallback.
Fixes #10568

Use wslpath command for customized root on WSL

---

plugins/kernel_v2/config/vm.rb
test/unit/plugins/kernel_v2/config/vm_test.rb

Add base_address to core vagrant vm config

---

lib/vagrant/util/subprocess.rb
test/unit/vagrant/util/subprocess_test.rb

Use ld path with appimage libs on suffix

---

lib/vagrant/action/runner.rb

This prevents a ThreadError exception being raised on sigint which
resulted in a stacktrace being dumped.
Fixes #10603

Wrap output in thread when being called from within trap-context

---

plugins/guests/solaris11/cap/configure_networks.rb

This is the fix in Pull Request form.
Fixes #10594

- FIX for #10594

---

website/source/docs/other/wsl.html.md

- Insert underline to fix **bold** formatting
- Remove grave accent to fix `code` highlighting

Fix formatting issues on WSL docs

---

plugins/communicators/ssh/communicator.rb

Remove require of net/sftp library

---

lib/vagrant/util/guest_inspection.rb
plugins/guests/coreos/cap/change_host_name.rb
plugins/guests/coreos/cap/configure_networks.rb
test/unit/plugins/guests/coreos/cap/change_host_name_test.rb
test/unit/plugins/guests/coreos/cap/configure_networks_test.rb

Updates the network configuration and hostname setting
for coreos guests. Updates include moving to using cloudinit
for configuration of networks and hostname.

Update guest capabilities for coreos

---

website/source/docs/cli/snapshot.html.md

Add vm-name option to snapshot documentation

---

website/source/layouts/docs.erb

Link to the "upload" docs page from the docs sidebar

---

website/source/docs/provisioning/ansible_local.html.md

This change will fix formatting of the code blocks on page https://www.vagrantup.com/docs/provisioning/ansible_local.html

website/docs: fix code formatting

---

website/source/docs/vagrant-cloud/boxes/catalog.html.md

Proposed minor re wording on website boxes catalog page.

minor word change re box availability explanation

---

website/source/docs/provisioning/ansible_local.html.md

Fix code block indentation on website page.

 Review ansible_local.html.md

---

plugins/provisioners/chef/cap/freebsd/chef_install.rb

No functional change intended.

FreeBSD: Remove APT-ism

---

plugins/guests/windows/cap/reboot.rb

fix https://github.com/hashicorp/vagrant/issues/11092

retry the wait for a windows reboot on connect timeout errors

---

website/source/docs/vagrant-cloud/boxes/catalog.html.md

This includes initial fix from #11034 as well as updates
addressing other items brought up within that pull request.

Update docs page for Vagrant Cloud catalog

---

plugins/providers/docker/action/prepare_networks.rb
test/unit/plugins/providers/docker/action/prepare_networks_test.rb

This pull request adds some unit tests for the pull request https://github.com/hashicorp/vagrant/pull/10993

Only return interfaces where addr is not nil

---

website/source/docs/provisioning/ansible_intro.html.md

Hi all,
This PR attempts to address https://github.com/hashicorp/vagrant/issues/9689
Please let me know if it can be improved.
Fixes https://github.com/hashicorp/vagrant/issues/9689

docs: Add clarification about ansible.limit in static inventory usecase

---

test/unit/plugins/providers/docker/action/prepare_networks_test.rb

The test "generates a network name and configuration" calls at the end `process_public_network()`, which can return an empty list if the currently executing machine has no usable network interfaces (this is typically the case for workers that build rpm packages in OBS or Koji). This results in an exception of type `Errors::NetworkNoInterfaces` to be thrown and causing this test to fail.
This commit wraps this call in a rescue block to suppress this failure.

Catch NetworkNoInterfaces error in docker prepare_networks_test

---

plugins/provisioners/ansible/cap/guest/arch/ansible_install.rb
plugins/provisioners/ansible/cap/guest/debian/ansible_install.rb
plugins/provisioners/ansible/cap/guest/fedora/ansible_install.rb
plugins/provisioners/ansible/cap/guest/freebsd/ansible_install.rb
plugins/provisioners/ansible/cap/guest/pip/pip.rb
plugins/provisioners/ansible/cap/guest/redhat/ansible_install.rb
plugins/provisioners/ansible/cap/guest/suse/ansible_install.rb
plugins/provisioners/ansible/cap/guest/ubuntu/ansible_install.rb
test/unit/plugins/provisioners/ansible/cap/guest/arch/ansible_install_test.rb
test/unit/plugins/provisioners/ansible/cap/guest/debian/ansible_install_test.rb
test/unit/plugins/provisioners/ansible/cap/guest/freebsd/ansible_install_test.rb
test/unit/plugins/provisioners/ansible/cap/guest/pip/pip_test.rb
test/unit/plugins/provisioners/ansible/cap/guest/shared/pip_ansible_install_examples.rb
test/unit/plugins/provisioners/ansible/cap/guest/suse/ansible_install_test.rb
test/unit/plugins/provisioners/ansible/cap/guest/ubuntu/ansible_install_test.rb

This pull request is a fixup of https://github.com/hashicorp/vagrant/pull/11227, and also includes fixes from https://github.com/hashicorp/vagrant/pull/11061. Please refer to #11227 for more information about this changeset.
Thanks to the original authors for making this PR possible! This new PR is mostly just so that Circle-CI actually runs the tests so that we can properly merge this patch.
In the process of reviewing this code, I tested the changes on the following platforms:
- ubuntu - (hashicorp/bionic64) both pip and apt
- debian (bento/debian-10) both pip and apt
- archlinux (archlinux/archlinux) both pip and pacman
- freebsd (generic/freebsd11) just pkg

Fixup: ansible_local: Add `cap` bug fixes and related RSpec coverage

---

website/source/docs/hyperv/configuration.html.md

Update docs to reflect change made in
8aa74a03a09bfab203d1866fc5f3e4476bb1657f.

Fixes #11269: enable_checkpoints defaults to true

---

.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE.md
README.md

Update README and new issue templates to point to discuss.

Documentation and template updates

---

lib/vagrant/action/builtin/cleanup_disks.rb
lib/vagrant/action/builtin/disk.rb
lib/vagrant/util/numeric.rb
plugins/kernel_v2/config/disk.rb
plugins/kernel_v2/config/vm.rb
plugins/providers/virtualbox/cap/cleanup_disks.rb
plugins/providers/virtualbox/cap/configure_disks.rb
plugins/providers/virtualbox/cap/validate_disk_ext.rb
plugins/providers/virtualbox/driver/meta.rb
plugins/providers/virtualbox/driver/version_5_0.rb
plugins/providers/virtualbox/plugin.rb
templates/locales/en.yml
test/unit/plugins/kernel_v2/config/disk_test.rb
test/unit/plugins/kernel_v2/config/vm_test.rb
test/unit/plugins/providers/virtualbox/cap/cleanup_disks_test.rb
test/unit/plugins/providers/virtualbox/cap/configure_disks_test.rb
test/unit/vagrant/action/builtin/cleanup_disks_test.rb
test/unit/vagrant/action/builtin/disk_test.rb
website/source/docs/disks/configuration.html.md
website/source/docs/disks/index.html.md
website/source/docs/disks/usage.html.md
website/source/docs/disks/virtualbox/common-issues.html.md
website/source/docs/disks/virtualbox/index.html.md
website/source/docs/disks/virtualbox/usage.html.md
website/source/layouts/docs.erb

This pull request introduces a new experimental feature for managing virtual disks with the VirtualBox provider.
It allows uses to be able to resize the primary disk of a guest, as well as attach additional disks to guests.

[FEATURE] Disk management with the VirtualBox provider

---

.github/ISSUE_TEMPLATE/vagrant-feature-request.md

Add feature request issue template

Update issue templates

---

.github/workflows/testing.yml

Also include `./bin` directory contents

Add path filtering to pull requests

---

lib/vagrant/util/platform.rb
plugins/communicators/ssh/communicator.rb
plugins/communicators/winssh/communicator.rb
plugins/communicators/winssh/config.rb
plugins/guests/windows/cap/public_key.rb
plugins/provisioners/shell/config.rb
plugins/provisioners/shell/provisioner.rb
test/unit/plugins/communicators/winssh/communicator_test.rb
test/unit/plugins/guests/windows/cap/insert_public_key_test.rb
test/unit/plugins/guests/windows/cap/remove_public_key_test.rb
test/unit/plugins/provisioners/shell/config_test.rb
test/unit/plugins/provisioners/shell/provisioner_test.rb
test/unit/vagrant/util/platform_test.rb
website/source/docs/boxes/base.html.md
website/source/docs/provisioning/shell.html.md
website/source/docs/vagrantfile/winssh_settings.html.md

This a rebased version of #11310 with some added updates to force
PowerShell environment when running remote ssh commands.

Fix issues with Windows SSH provisioner (continued...)

---

plugins/providers/docker/driver.rb
test/unit/plugins/providers/docker/driver_test.rb

address https://github.com/hashicorp/vagrant/issues/11393

Get correct docker image from build output

---

plugins/guests/redhat/cap/smb.rb
plugins/guests/redhat/plugin.rb
test/unit/plugins/guests/redhat/cap/smb_test.rb

addresses https://github.com/hashicorp/vagrant/issues/11412

Add suport for SMB on redhat

---

plugins/guests/linux/cap/reboot.rb
test/unit/plugins/guests/linux/cap/reboot_test.rb

Addresses the `reboot` part of this issue #11407

Use systemd to rebot system if available

---

plugins/guests/linux/cap/halt.rb
test/unit/plugins/guests/linux/cap/halt_test.rb

Addresses the `halt` part of this issue https://github.com/hashicorp/vagrant/issues/11407

Use systemd to halt system if available

---

plugins/synced_folders/smb/synced_folder.rb

fixes https://github.com/hashicorp/vagrant/issues/8931 (adding some docs)

Clarify SMB username format

---

lib/vagrant/errors.rb
lib/vagrant/util/guest_inspection.rb
plugins/guests/debian/cap/configure_networks.rb
templates/locales/en.yml
test/unit/plugins/guests/debian/cap/configure_networks_test.rb

fixes https://github.com/hashicorp/vagrant/issues/11378

Choose netplan renderer based on network config and available tools

---

plugins/providers/hyperv/driver.rb
plugins/providers/hyperv/scripts/set_vm_integration_services.ps1
plugins/providers/hyperv/scripts/utils/VagrantVM/VagrantVM.psm1
test/unit/plugins/providers/hyperv/driver_test.rb

fixes https://github.com/hashicorp/vagrant/issues/11039
ref:
https://github.com/PlagueHO/LabBuilder/issues/183
ref service name to id:
https://social.technet.microsoft.com/Forums/de-DE/154917de-f3ca-4b1e-b3f8-23dd4b4f0f06/getvmintegrationservice-sprachabhngig?forum=powershell_de

Use service id for enabling/disabling vm integration services

---

plugins/guests/linux/cap/mount_smb_shared_folder.rb
templates/locales/en.yml
test/unit/plugins/guests/linux/cap/mount_smb_shared_folder.rb
website/source/docs/other/environmental-variables.html.md

Smb symlinks

---

website/source/docs/provisioning/shell.html.md

This commit updates the shell provisioner docs to be more descriptive
about the kinds of extensions you can use with Windows

Fixes #9142 Add more information about shell script extensions

---

plugins/provisioners/ansible/provisioner/base.rb
test/unit/plugins/provisioners/ansible/provisioner_test.rb

fixes https://github.com/hashicorp/vagrant/issues/11419

Don't warn on ansible compatability mode

---

plugins/communicators/winrm/config.rb
website/source/docs/vagrantfile/winrm_settings.html.md

Fixes https://github.com/hashicorp/vagrant/issues/11539

Update winrm config docs

---

plugins/provisioners/docker/plugin.rb

fixes GH issue #11580

---

plugins/guests/esxi/cap/public_key.rb

esxi guest: only create the ssh directory when needed

---

.github/CONTRIBUTING.md

This pull request fixes issue #11648

Fixed broken link in CONTRIBUTING.md file.

---

website/pages/vagrant-cloud/api.mdx

Fixes hashicorp/vagrant_cloud#57

Include checksum options in vagrantcloud API documentation

---

website/pages/vmware/downloads/index.jsx

Missed a little piece from the last PR. Oops!

Website: fix vmware downloads page

---

plugins/provisioners/shell/provisioner.rb
test/unit/plugins/provisioners/shell/provisioner_test.rb

fixes https://github.com/hashicorp/vagrant/issues/11643

Shell provisioner gets extension specified in path config if exists

---

lib/vagrant/action/builtin/set_hostname.rb
plugins/kernel_v2/config/vm.rb
templates/locales/en.yml
test/unit/plugins/kernel_v2/config/vm_test.rb
test/unit/vagrant/action/builtin/set_hostname_test.rb
website/pages/docs/vagrantfile/machine_settings.mdx

Add `config.vm.allow_hosts_modification` configuration as per https://github.com/hashicorp/vagrant/issues/11508

Add option to disable modification of /etc/hosts on guest

---

.github/ISSUE_TEMPLATE/bug-report.md

Provide more instructions within template on providing
a minimal configuration to ensure local reproduction and
debugging/assistance is possible.

Update issue template

---

lib/vagrant/util/guest_hosts.rb
plugins/guests/suse/cap/change_host_name.rb
test/unit/plugins/guests/suse/cap/change_host_name_test.rb

fixes https://github.com/hashicorp/vagrant/issues/11317
depends on https://github.com/hashicorp/vagrant/pull/11566
addresses the suse host cap as per https://github.com/hashicorp/vagrant/issues/11508

Set hostname according to hostname flag and ip for suse

---

lib/vagrant/machine.rb
lib/vagrant/machine_index.rb
lib/vagrant/plugin/v2/command.rb
test/unit/vagrant/machine_index_test.rb
test/unit/vagrant/machine_test.rb

fixes https://github.com/hashicorp/vagrant/issues/11214

Add local machine to global index of machines if it does not exist

---

plugins/kernel_v2/config/vm.rb

fixes https://github.com/hashicorp/vagrant/issues/9495

Error nfs on win

---

lib/vagrant/plugin/v2/command.rb
test/unit/vagrant/plugin/v2/command_test.rb

fixes https://github.com/hashicorp/vagrant/issues/11743

Print help message if user provides and ambiguous option

---

website/pages/vagrant-cloud/api.mdx

dont escape expanding $VAR in shell

doc-fix dont escape  $

---

lib/vagrant/cli.rb
lib/vagrant/util/install_cli_autocomplete.rb
plugins/commands/autocomplete/command/install.rb
plugins/commands/autocomplete/command/root.rb
plugins/commands/autocomplete/plugin.rb
templates/locales/en.yml
test/unit/plugins/commands/autocomplete/commands/install_test.rb
test/unit/vagrant/util/install_cli_autocomplete_test.rb
website/pages/docs/cli/index.mdx

fixes https://github.com/hashicorp/vagrant/issues/8987
relies on https://github.com/hashicorp/vagrant/pull/11520 (or some file in `contrib/zsh`)

Install zsh autocomplete

---

plugins/guests/alpine/cap/change_host_name.rb
test/unit/plugins/guests/alpine/cap/change_host_name_test.rb

ref: https://github.com/hashicorp/vagrant/issues/11508

Make alpine guest respect 'hostname' network config option

---

lib/vagrant/util/guest_hosts.rb
plugins/guests/darwin/cap/change_host_name.rb
plugins/guests/freebsd/cap/change_host_name.rb
plugins/guests/openbsd/cap/change_host_name.rb
test/unit/plugins/guests/darwin/cap/change_host_name_test.rb
test/unit/plugins/guests/freebsd/cap/change_host_name_test.rb
test/unit/plugins/guests/openbsd/cap/change_host_name_test.rb
test/unit/vagrant/util/guest_hosts_test.rb

ref: https://github.com/hashicorp/vagrant/issues/11508

Make darwin + openbsd +freebsd guest respect 'hostname' network config option

---

plugins/communicators/ssh/communicator.rb
test/unit/plugins/communicators/ssh/communicator_test.rb

fixes https://github.com/hashicorp/vagrant/issues/11737

Allow file provisioner to copy empty folders

---

plugins/guests/alt/cap/change_host_name.rb
plugins/guests/arch/cap/change_host_name.rb
plugins/guests/atomic/cap/change_host_name.rb
plugins/guests/debian/cap/change_host_name.rb
plugins/guests/gentoo/cap/change_host_name.rb
plugins/guests/linux/cap/change_host_name.rb
plugins/guests/linux/plugin.rb
plugins/guests/omnios/cap/change_host_name.rb
plugins/guests/photon/cap/change_host_name.rb
plugins/guests/pld/cap/change_host_name.rb
plugins/guests/redhat/cap/change_host_name.rb
plugins/guests/slackware/cap/change_host_name.rb
plugins/guests/suse/cap/change_host_name.rb
test/unit/plugins/guests/alt/cap/change_host_name_test.rb
test/unit/plugins/guests/arch/cap/change_host_name_test.rb
test/unit/plugins/guests/atomic/cap/change_host_name_test.rb
test/unit/plugins/guests/debian/cap/change_host_name_test.rb
test/unit/plugins/guests/gentoo/cap/change_host_name_test.rb
test/unit/plugins/guests/linux/cap/change_host_name_test.rb
test/unit/plugins/guests/omnios/cap/change_host_name_test.rb
test/unit/plugins/guests/photon/cap/change_host_name_test.rb
test/unit/plugins/guests/pld/cap/change_host_name_test.rb
test/unit/plugins/guests/redhat/cap/change_host_name_test.rb
test/unit/plugins/guests/slackware/cap/change_host_name_test.rb
test/unit/plugins/guests/suse/cap/change_host_name_test.rb

ref: https://github.com/hashicorp/vagrant/issues/11508

Make alt + arch + atomic-host +debian + gentoo + slackware + pld + photon + rhel +suse guests respect hostname network config option

---

lib/vagrant/util/subprocess.rb
plugins/hosts/linux/cap/rdp.rb
plugins/hosts/windows/cap/rdp.rb
test/unit/vagrant/util/subprocess_test.rb

fixes https://github.com/hashicorp/vagrant/issues/9163
supersedes https://github.com/hashicorp/vagrant/pull/11691
depends on https://github.com/hashicorp/vagrant/pull/11717

Detach from subprocess

---

plugins/providers/hyperv/scripts/utils/VagrantVM/VagrantVM.psm1

Docs for powershell:
https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_logical_operators?view=powershell-7

Fix if statement to use '-and' syntax

---

vagrant.gemspec

Relax constraint on listen dependency

---

website/data/intro-navigation.js

fixes https://github.com/hashicorp/vagrant/issues/11841

Add 'Vagrant vs Other Software' section to docs navigation

---

lib/vagrant/action/builtin/synced_folders.rb
test/unit/vagrant/action/builtin/synced_folders_test.rb

fixes https://github.com/hashicorp/vagrant/issues/11895

Catch error for when guest is not available

---

plugins/guests/linux/cap/persist_mount_shared_folder.rb
test/unit/plugins/guests/linux/cap/persist_mount_shared_folder_test.rb

fixes https://github.com/hashicorp/vagrant/issues/11894

Add check for /etc/fstab

---

plugins/guests/debian/cap/change_host_name.rb
test/unit/plugins/guests/debian/cap/change_host_name_test.rb

fixes https://github.com/hashicorp/vagrant/issues/11884

Set hostname in /etc/hosts as first step to changing hostname

---

plugins/guests/redhat/cap/change_host_name.rb

fixes https://github.com/hashicorp/vagrant/issues/11875 and https://github.com/hashicorp/vagrant/issues/11873

Check for existence of network files before trying to update them

---

lib/vagrant/machine_index.rb
lib/vagrant/plugin/v2/command.rb
test/unit/vagrant/machine_index_test.rb
test/unit/vagrant/plugin/v2/command_test.rb

fixes https://github.com/hashicorp/vagrant/issues/11856

Include index

---

plugins/guests/redhat/cap/change_host_name.rb

This will pervent running sed if there are no results passed to xargs

Use '-r' xargs argument

---

test/unit/plugins/commands/port/command_test.rb
test/unit/plugins/commands/push/command_test.rb
test/unit/plugins/commands/validate/command_test.rb

fixes https://github.com/hashicorp/vagrant/issues/11879

Remove rsync dep from tests

---

plugins/guests/darwin/cap/mount_smb_shared_folder.rb
plugins/guests/linux/cap/mount_smb_shared_folder.rb
plugins/guests/linux/cap/mount_virtualbox_shared_folder.rb
plugins/guests/linux/cap/persist_mount_shared_folder.rb
plugins/providers/hyperv/action.rb
plugins/providers/virtualbox/cap/mount_options.rb
plugins/synced_folders/smb/cap/mount_options.rb
plugins/synced_folders/smb/plugin.rb
test/unit/plugins/guests/linux/cap/mount_smb_shared_folder_test.rb
test/unit/plugins/guests/linux/cap/persist_mount_shared_folder_test.rb
test/unit/plugins/synced_folders/smb/caps/mount_options_test.rb
test/unit/plugins/synced_folders/unix_mount_helpers_test.rb

fixes https://github.com/hashicorp/vagrant/issues/11589

Persist smb

---

website/pages/vagrant-cloud/boxes/using.mdx

The old link points to an user profile.

Update discover link

---

contrib/zsh/_vagrant
contrib/zsh/generate_zsh_completion.rb

fixes https://github.com/hashicorp/vagrant/issues/11958

Remove new line from beginning of completion script

---

plugins/kernel_v2/config/vm.rb
test/unit/plugins/kernel_v2/config/vm_test.rb

fixes https://github.com/hashicorp/vagrant/issues/11944

Replace :nfs option with :type for synced folders

---

plugins/guests/suse/cap/change_host_name.rb
test/unit/plugins/guests/suse/cap/change_host_name_test.rb

fixes https://github.com/hashicorp/vagrant/issues/11983

Don't use hostnamectl if not on system

---

lib/vagrant/action/builtin/cloud_init_setup.rb
lib/vagrant/util/mime.rb
plugins/kernel_v2/config/cloud_init.rb
test/unit/vagrant/action/builtin/cloud_init_setup_test.rb
test/unit/vagrant/util/mime_test.rb
vagrant.gemspec

fixes https://github.com/hashicorp/vagrant/issues/11857

Update mime gem

---

plugins/providers/virtualbox/provider.rb
test/unit/plugins/providers/virtualbox/provider_test.rb

Fixes check for usability of VirtualBox provider upon initialization [Fix for #11929 issue](https://github.com/hashicorp/vagrant/issues/11929)

Detection of availability of VirtualBox provider #11929

---

lib/vagrant/bundler.rb
test/unit/vagrant/bundler_test.rb

Maintain the solution file persisting dependency information on
disk but update the runtime representation to
Gem::Resolver::DependencyRequest instances which are expected
by the sets when locating matches.
Properly abide by prerelease setting in customized sets and
force prerelease matching when in the builtin set. If a request
is matched on a prerelease, and the request itself is not set
to allow prereleases, update it to ensure successful resolution.

Update solution file to use DependencyRequests and allow prerelease

---

website/pages/docs/synced-folders/nfs.mdx

Add nfs exports troubleshoot hint to help people to deal with nfs problems on linux.

Add nfs exports troubleshoot hint

---

lib/vagrant/util/platform.rb

Fixes shared folder on WSL2 based on #11705

Update filesystem type match for WSL2

---

website/package-lock.json
website/package.json

I accidentally removed it with a previous PR - sorry! 😞

Restore docs search to website

---

website/redirects.next.js

Adding some new redirects based on recent 404s.

website: add new redirects based on recent 404s

---

website/next.config.js
website/package-lock.json
website/package.json

Upgrading next to v10 and nextjs-scripts to v15.

website: update next and nextjs-scripts

---

vagrant.gemspec

fixes https://github.com/hashicorp/vagrant/issues/12120

Bump vagrant cloud version

---

lib/vagrant/util/guest_hosts.rb
test/unit/vagrant/util/guest_hosts_test.rb

fixes https://github.com/hashicorp/vagrant/issues/12133

Make shell script for loop shell agnostic

---

lib/vagrant/action/builtin/box_add.rb
test/unit/vagrant/action/builtin/box_add_test.rb

fixes https://github.com/hashicorp/vagrant/issues/12144

Raise error if downloading box metadata fails

---

plugins/guests/linux/cap/persist_mount_shared_folder.rb
plugins/providers/virtualbox/cap/mount_options.rb
plugins/providers/virtualbox/plugin.rb
plugins/synced_folders/smb/cap/mount_options.rb
test/unit/plugins/guests/linux/cap/persist_mount_shared_folder_test.rb
test/unit/plugins/providers/virtualbox/cap/mount_options_test.rb
test/unit/plugins/synced_folders/smb/caps/mount_options_test.rb

fixes https://github.com/hashicorp/vagrant/issues/12171

Extract os friendly mount name for vbox shared folders

---

plugins/guests/alpine/cap/configure_networks.rb
test/unit/plugins/guests/alpine/cap/configure_networks_test.rb

fixes https://github.com/hashicorp/vagrant/issues/12134

Check if interface exists before shutting it down

---

lib/vagrant/action/builtin/box_check_outdated.rb
test/unit/vagrant/action/builtin/box_check_outdated_test.rb

fixes https://github.com/hashicorp/vagrant/issues/12146

Apply download options to metadata requests

---

lib/vagrant/machine_index.rb
test/unit/plugins/commands/destroy/command_test.rb
test/unit/vagrant/machine_index_test.rb

fixes https://github.com/hashicorp/vagrant/issues/12179

Don't try to find "" by prefix in the machine index

---

plugins/commands/destroy/command.rb
test/unit/plugins/commands/destroy/command_test.rb

fixes https://github.com/hashicorp/vagrant/issues/12141

Don't count not created machines as declined when destroying

---

plugins/guests/fedora/guest.rb

fixes https://github.com/hashicorp/vagrant/issues/12228

Detect fedora using os-releases id

---

lib/vagrant/vagrantfile.rb

Fix typo in vagrantfile.rb

---

templates/locales/en.yml

Fix typo in en.yml

---

test/unit/plugins/commands/cloud/publish_test.rb

Fix typo in publish_test.rb

---

lib/vagrant/action/builtin/box_add.rb
test/unit/vagrant/action/builtin/box_add_test.rb

fixes https://github.com/hashicorp/vagrant/issues/12261

Add box directly with authed urls

---

plugins/guests/fedora/guest.rb

Import guest detection module

---

.github/workflows/build.yml
.github/workflows/code.yml
.github/workflows/release.yml
.github/workflows/testing.yml

actions/setup-ruby is deprecated

Use ruby/setup-ruby gh action

---

website/content/docs/disks/hyperv/usage.mdx

Fix typo in usage.mdx

---

plugins/provisioners/ansible/provisioner/base.rb
test/unit/plugins/provisioners/ansible/provisioner_test.rb

fixes https://github.com/hashicorp/vagrant/issues/12404

Strip whitespace from ansible version

---

test/unit/plugins/providers/docker/action/connect_networks_test.rb

Fix typo in connect_networks_test.rb

---

plugins/hosts/windows/scripts/check_credentials.ps1

fixes: https://github.com/hashicorp/vagrant/issues/12058

Check Domain and Application Directory contexts for credentials when validating SMB creds

---

lib/vagrant/util/powershell.rb

Resolves https://github.com/hashicorp/vagrant/issues/12432

Get powershell path in %WINDIR%/System32

---

plugins/guests/rocky/cap/flavor.rb
plugins/guests/rocky/guest.rb
plugins/guests/rocky/plugin.rb
test/unit/plugins/guests/rocky/cap/flavor_test.rb

Adds proper guest detection and support for Rocky Linux

Add Rocky Linux guest support

---

plugins/providers/docker/driver.rb
test/unit/plugins/providers/docker/driver_compose_test.rb
test/unit/plugins/providers/docker/driver_test.rb

fixes: https://github.com/hashicorp/vagrant/issues/12447

Pass in docker command opts as a map

---

plugins/providers/hyperv/scripts/get_network_config.ps1

Use detected device when iterating over available addresses

---

website/pages/downloads/index.jsx

Thanks to @kpenfound for calling out this bug!

Fix homebrew command on downloads page

---

plugins/commands/upload/command.rb

Fix typo in command.rb

---

website/content/intro/index.mdx
website/content/intro/vs/cli-tools.mdx

ref:
https://github.com/hashicorp/vagrant/pull/12467
https://github.com/hashicorp/vagrant/pull/12466

Grammatical fixes

---

go.mod
go.sum
lib/vagrant/ui/remote.rb
plugins/commands/serve/client/terminal.rb
plugins/synced_folders/smb/cap/mount_options.rb
test/unit/plugins/synced_folders/smb/caps/mount_options_test.rb

depends on https://github.com/hashicorp/vagrant-plugin-sdk/pull/188

Pass in echo/secret ui input setting

---

website/content/docs/boxes/base.mdx
website/content/docs/boxes/format.mdx
website/content/docs/boxes/versioning.mdx
website/content/docs/cli/cloud.mdx
website/content/docs/cli/login.mdx
website/content/docs/cli/non-primary.mdx
website/content/docs/cli/plugin.mdx
website/content/docs/providers/docker/index.mdx
website/content/docs/providers/vmware/vagrant-vmware-utility.mdx
website/content/docs/provisioning/docker.mdx
website/content/docs/vagrantfile/machine_settings.mdx
website/content/vagrant-cloud/boxes/create.mdx
website/content/vagrant-cloud/boxes/distributing.mdx
website/content/vagrant-cloud/boxes/index.mdx
website/content/vagrant-cloud/boxes/release-workflow.mdx
website/content/vagrant-cloud/index.mdx
website/content/vagrant-cloud/organizations/authentication-policy.mdx
website/content/vagrant-cloud/support.mdx
website/content/vagrant-cloud/users/index.mdx
website/data/docs-nav-data.json
website/data/intro-nav-data.json

This PR updates links to redirected paths so they may resolve properly in the dev portal context.

content: link updates for dev portal

---

.github/ISSUE_TEMPLATE/bug-report.md

My goal was to make the template easier to complete. I again borrowed some ideas from Nomad. Hopefully, bug reporst will now be automatically labeled. 
Fixes: #12830

Bug Report Template Updates

---

website/content/docs/providers/docker/configuration.mdx
website/data/vagrant-cloud-nav-data.json

At @tunzor's request, I've removed a link and updated some headings so that they will appear in the side nav.

Devdot updates

---

go.mod
go.sum
internal/core/box.go

Fixes https://github.com/hashicorp/vagrant/issues/12915
Depends on https://github.com/hashicorp/vagrant-plugin-sdk/pull/194

Return errors when box metadata is unavailable or invalid

---

website/content/docs/installation/index.mdx
website/content/docs/installation/upgrading.mdx

Updates the install and upgrade pages to adhere to our style guides.

Docs Updates to Follow Style Guides. 

---

.ci/build.sh
.ci/release.sh
.github/CONTRIBUTING.md
.github/workflows/build.yml
.github/workflows/code.yml
.github/workflows/go-spectest.yml
.github/workflows/go-testing.yml
.github/workflows/lock.yml
.github/workflows/release.yml
.github/workflows/spectesting.yml
.github/workflows/testing.yml

Cleans up some of the ci scripts and workflows.
Includes removal of comments on issues/PR locks and adds 
a note in the CONTRIBUTING document about locking.
Addresses issue: #12964

CI updates

---

website/content/docs/provisioning/ansible_intro.mdx

Updates a broken link to inventory file documentation.

docs: updates link to inventory file documentation

---

plugins/providers/virtualbox/driver/version_7_0.rb
test/unit/plugins/providers/virtualbox/driver/version_7_0_test.rb

Provide an overrride for the #read_network_interfaces in the VirtualBox
driver that is utilized when host only networks are in use. This properly
adjusts the information to identify the interface as being on a host
only network as well as properly includes the network name.
This fixes NFS synced folder usage which requires successfully identifying
a private network on the guest for configuration.

VirtualBox read networks support with hostonlynets

---

contrib/bash/completion.sh

Closes: https://github.com/hashicorp/vagrant/issues/12894

Make bash completion for "vagrant box add"

---

website/content/docs/providers/virtualbox/index.mdx

Tested with Version 7.0.4 r154605 (Qt5.15.2) on Mac OS 13.0.1 (22A400) as 6.1.x was not working

add VirtualBox version 7.0.x 

---

website/README.md
website/package-lock.json
website/package.json

This updates the generated docs for the new [mdx inline alert component](https://github.com/hashicorp/dev-portal/pull/1517). See [docs on dev portal here.](https://developer.hashicorp.com/swingset/components/mdxinlinealert)

[website] chore: updates generated docs

---

plugins/commands/box/command/outdated.rb

"that are you are using" to "that you are using"

Fix sentense

---

plugins/providers/hyperv/driver.rb
plugins/providers/hyperv/scripts/set_enhanced_session_transport_type.ps1

HyperV enhanced sessionmode crash on Windows Server 2012R2

---

plugins/hosts/arch/host.rb

Greetings,
As expressed in the issue #13050 I've had a bit of niggling issues using Vagrant out of the box on Artix Linux.
Hopefully this pull request successfully adds support for it, or at least can be a launchpad for something coded in a better, more reliable way.
This is my first contribution to Vagrant, as well as my first contribution in Ruby, coded by reading documentation about the init systems, the code of Vagrant itself and intuition.
This is still untested, I'll try to test it as much as possible on my Artix-OpenRC machine.
Thanks for your attention.

Artix Linux Host Support

---

.github/workflows/spectesting.yml

Fixes https://github.com/hashicorp/vagrant/issues/13063

Update spectesting to use secrets stored in vault

---

website/README.md
website/package-lock.json
website/package.json

Adds a new `content-check` npm script to run our content conformance checks locally, also adds some related documentation to the README.
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1204070028171958
- https://app.asana.com/0/0/1204070028171954

website: adds content-check command and README update

---

.ci/dev-build
.ci/nightly-build
.ci/release
.github/workflows/dev-build.yml
.github/workflows/nightlies.yml
.github/workflows/release.yml

- Be explicit with tag and commit ID on release
- Add build triggers

build workflows

---

.ci/dev-build
.github/workflows/dev-appimage-build.yml
.github/workflows/dev-arch-build.yml
.github/workflows/dev-debs-build.yml
.github/workflows/dev-macos-build.yml
.github/workflows/dev-rpms-build.yml
.github/workflows/dev-windows-build.yml

Support triggering development builds for specific platforms
when changes may not apply to the full list of packages.

Support development builds for specific host

---

lib/vagrant/action/builder.rb
lib/vagrant/action/warden.rb
lib/vagrant/cli.rb
lib/vagrant/machine.rb
plugins/kernel_v2/config/vm.rb
plugins/providers/hyperv/cap/cleanup_disks.rb
plugins/providers/hyperv/cap/configure_disks.rb
plugins/providers/virtualbox/cap/cleanup_disks.rb
plugins/providers/virtualbox/cap/configure_disks.rb
website/content/docs/cloud-init/index.mdx
website/content/docs/cloud-init/usage.mdx
website/content/docs/disks/hyperv/index.mdx
website/content/docs/disks/hyperv/usage.mdx
website/content/docs/disks/index.mdx
website/content/docs/disks/usage.mdx
website/content/docs/disks/virtualbox/index.mdx
website/content/docs/disks/virtualbox/usage.mdx
website/content/docs/disks/vmware/index.mdx
website/content/docs/disks/vmware/usage.mdx
website/content/docs/experimental/index.mdx
website/content/docs/provisioning/basic_usage.mdx
website/content/docs/triggers/configuration.mdx
website/content/docs/vagrantfile/machine_settings.mdx

Removes experimental checks on existing experimental features.

Remove experimental checks

---

website/content/docs/provisioning/ansible.mdx

The install link for ansible was broken.

Update ansible install link

---

.copywrite.hcl
LICENSE

Updates LICENSE file and copywrite bot config to 2024.

[DO NOT MERGE UNTIL EOY] EOY license updates

---

.ci/generate-licenses
.github/workflows/code.yml
.github/workflows/dev-appimage-build.yml
.github/workflows/dev-arch-build.yml
.github/workflows/dev-build.yml
.github/workflows/dev-debs-build.yml
.github/workflows/dev-macos-build.yml
.github/workflows/dev-rpms-build.yml
.github/workflows/dev-windows-build.yml
.github/workflows/go-spectest.yml
.github/workflows/go-testing.yml
.github/workflows/initiate-release.yml
.github/workflows/lock.yml
.github/workflows/nightlies.yml
.github/workflows/release.yml
.github/workflows/testing.yml

Updates pinned actions in workflows to latest allowed version. Also includes CI script update to generate plain text version of license file.

Update pinned actions

---

website/content/docs/provisioning/ansible_intro.mdx

Change ansible playbooks best practices URL

---

website/content/docs/providers/hyperv/index.mdx

Closes #13262
Hyper-V works well along side VirtualBox and VMWare,
The warning becomes redundant in this case and we must remove it

Fixed Documentation regarding Hyper-V

---

.github/workflows/testing-skipped.yml
.github/workflows/testing.yml

Remove 3.0 from testing matrix as it is now EOL.

Remove Ruby 3.0 from test matrix

---

plugins/guests/debian/cap/nfs.rb

Make installation of NFS client on Debian non-interactive to prevent the process from being stuck

---

vagrant.gemspec

Upgrade grpc to 1.62.0

---

.github/workflows/testing-skipped.yml
.github/workflows/testing.yml
vagrant.gemspec

Include Ruby 3.4 versions within allowed Ruby versions and include within testing matrix.

Include Ruby 3.4

---

plugins/providers/hyperv/cap/cleanup_disks.rb
plugins/providers/hyperv/cap/configure_disks.rb
plugins/providers/hyperv/driver.rb
plugins/providers/hyperv/scripts/add_dvd.ps1
plugins/providers/hyperv/scripts/get_scsi_controller.ps1
plugins/providers/hyperv/scripts/remove_dvd.ps1
test/unit/plugins/providers/hyperv/cap/cleanup_disks_test.rb
test/unit/plugins/providers/hyperv/cap/configure_disks_test.rb

Adds dvd disk support to the Hyper-V provider.
Fixes #8387

Add dvd disk support to Hyper-V provider

---

lib/vagrant/machine.rb
plugins/commands/destroy/command.rb

Adds extra debug statements as described in #13638
Fixes #13638

Add some helpful debug logs for more context

---

plugins/commands/autocomplete/command/root.rb
plugins/commands/box/command/root.rb
plugins/commands/cloud/auth/root.rb
plugins/commands/cloud/box/root.rb
plugins/commands/cloud/provider/root.rb
plugins/commands/cloud/root.rb
plugins/commands/cloud/version/root.rb
plugins/commands/plugin/command/root.rb

Remove service mode checks from command roots.
Fixes #13656

Remove server mode checks

---

plugins/providers/hyperv/action.rb

Adds the required actions to support cloud-init when using
the hyperv provider.

Add cloud-init support to hyperv provider
