- lib/vagrant/util/platform.rb
Checks only if the Hyper-V hypervisor is enabled instead of all
Hyper-V features. This will allow detection where Hyper-V is in
use for things like ApplicationGuard.
Uses both Get-WindowsOptionalFeature and Get-WindowsFeature to
support check on server and non-server version.
> Update Windows Hyper-V check

- plugins/providers/hyperv/action/import.rb
- plugins/providers/hyperv/scripts/get_switches.ps1
- plugins/providers/hyperv/scripts/import_vm_vmcx.ps1
Keep track of selected Hyper-V switch using the ID instead of name
to prevent any encoding issues that may occur switching between
PowerShell and Ruby. With the IDs staying consistent, the switch
name can be fetched from the provided ID.
Fixes #9679 #8794 #9451
> Reference Hyper-V switch by ID instead of name

- plugins/providers/hyperv/scripts/get_network_config.ps1
If the guest address is unavailable via Hyper-V inspection, extract
MAC address of network adapters and check neighbor information for
any currently matching known address.
> Check neighbors for valid guest address when default lookup fails

- plugins/providers/docker/command/exec.rb
- test/unit/plugins/providers/docker/command/exec_test.rb
Fixes #9622
Rebase/Fixup of #9704
> Use Util::SafeExec if docker-exec is run with `-t` option

- lib/vagrant/action/builtin/box_check_outdated.rb
- templates/locales/en.yml
- test/unit/vagrant/action/builtin/box_check_outdated_test.rb
Prior to this commit, vagrant would halt if it could not parse the
metadata file for a box to check for updates with. This commit changes
that to behave like when vagrant fails to download a metadata file and
continue on but warn the user it failed to check for box updates.
Fixes #7076
> Continue on if vagrant fails to parse metadata box for update

- plugins/hosts/linux/cap/rdp.rb
Running `vagrant rdp` in WSL only tries to run the Linux RDP clients `xfreerdp` or `rdesktop`. 
I've added the code from the Windows RDP capability into the Linux `rdp.rb`.
It recognizes that Vagrant is running in WSL and then uses `mstsc.exe` as fallback if the user hasn't installed the other Linux RDP clients. So WSL users have the chance to use the Linux RDP client, but it also just works with the Windows RDP client.
Improves #9628
> Call mstsc.exe Windows RDP client in WSL

- lib/vagrant/errors.rb
- plugins/providers/virtualbox/driver/base.rb
- templates/locales/en.yml
At the moment Linux Vagrant running in WSL often complains that `VBoxManage.exe` could not be found.
Using Vagrant with cloud providers or with VMware this message is confusing.
```
$ vagrant status
The "VBoxManage.exe" command or one of its dependencies could not
be found. Please verify VirtualBox is properly installed. You can verify
everything is okay by running "VBoxManage.exe --version" and verifying
that the VirtualBox version is outputted.
If you just installed VirtualBox, you have to log out and log back in for
the new environmental variables to take effect. Using the VirtualBox
provider within the WSL requires VirtualBox executables to be available
on the system PATH.
~/code/tst/ub
$ vagrant plugin list
nokogiri (1.8.2)
vagrant-reload (0.0.1)
- Version Constraint: > 0 …
```
> Allow other providers in WSL

- website/source/docs/triggers/index.html.md
I either got:
`syntax error, unexpected ':', expecting '}` or `wrong number of arguments (given 1, expected 0) (ArgumentError)` until I added the `=` in.
> Syntax error for running remote script

- bin/vagrant
- lib/vagrant.rb
- lib/vagrant/bundler.rb
Fixes Vagrant plugin loading to prevent error suppression on failed plugin loading. Also ensures plugins are loaded for help requests so custom commands are provided in the output.
Updates the installation process to remove activation requests for already installed gem specifications that are not located within the target installation directory.
Fixes #9701
> Vagrant plugin updates

- plugins/kernel_v2/config/vm.rb
- templates/locales/en.yml
- test/unit/plugins/kernel_v2/config/vm_test.rb
Make sure `options[:guestpath]` is not inadvertently set. Resolves #9691
> propagate unset guestpath

- lib/vagrant/errors.rb
- plugins/commands/suspend/command.rb
- templates/locales/en.yml
- test/unit/plugins/commands/suspend/command_test.rb
This commit introduces a new flag to the suspend command,
`--all-global`, which will suepend all vms both locally and globally.
Fixes #7221
> Introduce flag for suspending all machines

- templates/locales/en.yml
It's not obvious from the old explanation, how to get
rid of get rid of data that "may not be completely
up-to-date".
I had to google for the solution myself and found it from an old issue: https://github.com/hashicorp/vagrant/issues/4412
> global status informs about --prune

- plugins/provisioners/ansible/cap/guest/ubuntu/ansible_install.rb
- website/source/docs/provisioning/ansible_local.html.md
- Fix #9796: Failing installation on bionic (18.04 LTS)
- Remove support for precise (12.04 LTS), which is out of public support
(On this version, the package python-software-properties contained
the add-apt-repository tool)
- Reduce the number of SSH calls, and avoid unnecessary apt-get calls.
This patch has been validated against the following base boxes:
> ansible_local: Improve installation from PPA

- plugins/providers/hyperv/scripts/set_vm_integration_services.ps1
I noticed that the refactored hyper-v provider fails if any `vm_integration_services` are given. This is due to a typo in the PowerShell script that sets the actual values.  I'm not sure how to implement a test for this so I am submitting this pull-request with just the minimal changes.
> Fix: Correct  typo in hyperv provider, $Enable instead of $enabled

- plugins/guests/debian/cap/configure_networks.rb
The PR #9646 did not fix the isue. It changed the priority of the "netplan" YAML file, not the priority of the  network file in /etc/systemd/network directory used by systemd-networkd. My PR fixes the issue for real.
> Fix issue 9592 when systemd-networkd is used by Debian guest

- plugins/provisioners/salt/provisioner.rb
- test/unit/plugins/provisioners/salt/provisioner_test.rb
Replaces the masterless? attributes in favor of the already additional available masterless (without question mark) attribute. There is no obvious reason for the existence of the masterless? attribute and it causes issues as outlined in #9174.
> #9174 Remove masterless? config attribute

- plugins/provisioners/chef/provisioner/base.rb
- test/unit/plugins/provisioners/chef/provisioner/base_test.rb
The base chef provisioner class will set the node name automatically
if not provided in the configuration. Since the chef apply provisioner
does not provide a node_name option, setting it will invalidate the
configuration. This checks for the node name before attempting to
use it.
Fixes #9901
> Fix Chef apply provisioner to not set node_name

- .travis.yml
- lib/vagrant.rb
- lib/vagrant/util/powershell.rb
- plugins/communicators/ssh/communicator.rb
- plugins/hosts/bsd/cap/ssh.rb
- plugins/hosts/bsd/plugin.rb
- plugins/hosts/linux/cap/ssh.rb
- plugins/hosts/linux/plugin.rb
- plugins/hosts/windows/cap/ssh.rb
- plugins/hosts/windows/host.rb
- plugins/hosts/windows/plugin.rb
- plugins/hosts/windows/scripts/set_ssh_key_permissions.ps1
- plugins/hosts/windows/scripts/utils/VagrantSSH/VagrantSSH.psm1
- test/unit/plugins/communicators/ssh/communicator_test.rb
- test/unit/plugins/hosts/bsd/cap/ssh_test.rb
- test/unit/plugins/hosts/linux/cap/ssh_test.rb
- test/unit/plugins/hosts/windows/cap/ssh_test.rb
- test/unit/vagrant/util/powershell_test.rb
- vagrant.gemspec
Isolate SSH key file permissions/ownership with host capability. Replace win32 api based ownership/permission file modification on Windows with PowerShell commands to provide better stability across windows versions. User ownership on Windows is based on `whoami` output which includes domain when applicable.
Fixes #9900
> Update SSH key file permissions handling

- website/source/docs/triggers/configuration.html.md
`suspend` action is not listed, even though it can be used and it works.
```
$ vagrant --version
Vagrant 2.1.1
```
```
config.trigger.before [:suspend] do |trigger|
trigger.name = "Before suspend"
trigger.run = {inline: "..."}
end
````
> Add `suspend` into a list of available actions

- plugins/providers/hyperv/scripts/utils/VagrantVM/VagrantVM.psm1
When importing a Hyper-V VM ensure all adapters are disconnected from
switches that were used when the box was built.
Fixes  #9922
> Disconnect all configured network adapters

- plugins/providers/hyperv/scripts/utils/VagrantVM/VagrantVM.psm1
Forces an error if maxmemory value is less than the configured
minimum or startup memory.
Fixes #9477
> Validate maxmemory setting within Hyper-V provider

- plugins/providers/hyperv/scripts/utils/VagrantVM/VagrantVM.psm1
When importing a Hyper-V VM fails, attempt to manually build
a system definition and inspect the result to determine cause
of the failure.
> Attempt to provide helper error message on failed VM import

- plugins/pushes/ftp/errors.rb
- plugins/pushes/ftp/locales/en.yml
- plugins/pushes/ftp/push.rb
- test/unit/plugins/pushes/ftp/push_test.rb
When the configured directory for FTP push has too many files, it will
generate an exception and fail due to a stack overflow. When this happens
just rescue out the exception and re-raise a custom error to provide
some context to the user on the actual problem.
Fixes #9946
> Provide custom error when attempting to push too many files with FTP

- lib/vagrant/errors.rb
- lib/vagrant/plugin/v2/trigger.rb
- plugins/kernel_v2/config/vm_trigger.rb
- templates/locales/en.yml
- test/unit/vagrant/plugin/v2/trigger_test.rb
- website/source/docs/triggers/configuration.html.md
Prior to this commit, the run trigger option wouldn't catch for failures
outside of the #Subprocess.execute raising exceptions. This commit fixes
that by inspecting the exit code result of the subprocess and using the
new `exit_codes` option to determine how to move forward with the
trigger.
Fixes #9997 #9992
> Catch and allow for non-standard exit codes

- lib/vagrant/util/downloader.rb
When I was trying to set up a Vagrant project with a `box_url` pointing to a file on Dropbox, the download process kept failing with this exception:
```
/opt/vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/util/downloader.rb:118:in `block in download!': undefined method `split' for nil:NilClass (NoMethodError)
from /opt/vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/util/subprocess.rb:191:in `block in execute'
from /opt/vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/util/subprocess.rb:180:in `each'
from /opt/vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/util/subprocess.rb:180:in `execute'
from /opt/vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/util/subprocess.rb:22:in `execute'
from …
```
> Download causes exception when location header is not an absolute URL

- lib/vagrant/util/platform.rb
- plugins/kernel_v2/config/vm.rb
- plugins/synced_folders/rsync/synced_folder.rb
- templates/locales/en.yml
- test/unit/plugins/kernel_v2/config/vm_test.rb
- test/unit/vagrant/util/platform_test.rb
- website/source/docs/other/wsl.html.md
Disables synced folder implementations when running with the WSL and on a non-DrvFs file system. Provides the ability for synced folder implementations to flag support for non-DrvFs file systems (which is used by rsync).
Fixes #9934
> Disable synced folders on non-DrvFs

- lib/vagrant/util/downloader.rb
- test/unit/vagrant/util/downloader_test.rb
Prevent matching on custom headers that include the Location name
when checking for host redirection.
Fixes #9860
> Prevent matching on other Location headers

- lib/vagrant/util/guest_inspection.rb
- test/unit/plugins/guests/debian/cap/configure_networks_test.rb
`vagrant up` may hang at the "Configuring and enabling network
interfaces..." step when private networks and PTY allocation for SSH
are used.
The newer version of `nmcli` that is part of CentOS now will open a
pager (i.e. `less`) for certain commands if it finds a tty. This
causes the invocations of `nmcli` in `guest_inspection.rb` to hang.
`nmcli` disables the use of a pager in 'terse' (`-t`) output mode,
while still returning enough information for the uses in
`guest_inspection.rb`.
> Fix hang at nmcli call on CentOS 7.5 when ssh.pty is enabled

- plugins/providers/docker/synced_folder.rb
- test/unit/plugins/providers/docker/synced_folder_test.rb
- website/source/docs/docker/basics.html.md
This PR includes the work of #9812 and adds a test for the `#prepare` method and updates the documentation link for the docker feature.
Fixes #9811
> Support Docker volume consistency for synced folders

- plugins/providers/virtualbox/action/network_fix_ipv6.rb
- test/unit/plugins/providers/virtualbox/action/network_fix_ipv6_test.rb
This is #9639 with an extra commit that provides test coverage of behavior.
> Skip link-local addresses when fixing IPv6 route

- plugins/providers/hyperv/scripts/utils/VagrantVM/VagrantVM.psm1
Only enable ExposeVirtualizationExtensions if available within Hyper-V version
Fixes: #9962
> Enable ExposeVirtualizationExtensions only when available

- plugins/guests/solaris11/guest.rb
This commit adds back the `uname` test 93c571adbfab3c03fa2fa4cef406383eaf34d45d
removed to catch any solaris 11 derived guests like openindiana
Fixes #9614
> Add back check for Solaris derived guests

- website/source/docs/networking/forwarded_ports.html.md
In my opinion, port forwarding docs are missing information regarding `config.vm.usable_port_range` option. I was looking for it myself, knowing I've seen it somewhere, but couldn't quite find it. Only recently I've stumbled upon this when going over Vagrantfile configuration page.
Also, on a side note, is there an option to specify which `id` of forwarded port gets which port ranges?
I've got ssh and webserver port forwarding specified and their conflict resolution ranges would be great if they were separate. Just asking though.
> Add usable_port_range to port forwarding docs

- plugins/guests/windows/scripts/mount_volume.ps1.erb
Fixes https://github.com/hashicorp/vagrant/issues/9975
After installing msys2, there is another `cmd` on the path which prevents shared folders from being mounted. Explicitly calling `cmd.exe` fixes the issue
> Allow shared folders to be mounted after installing MSYS2

- lib/vagrant/environment.rb
- lib/vagrant/vagrantfile.rb
- plugins/commands/box/command/update.rb
- plugins/commands/up/middleware/store_box_metadata.rb
- plugins/commands/up/plugin.rb
- test/unit/plugins/commands/box/command/update_test.rb
- test/unit/plugins/commands/up/middleware/store_box_metadata_test.rb
- test/unit/vagrant/machine_test.rb
When a guest is created, the box metadata information is stored in the
machine data directory. This allows modifications to happen to the
Vagrantfile definition of the box in use (box name change, box version
change, etc) while still allowing the Machine instance of an active
guest successfully load the box currently backing it.
Fixes #9884
> Store box metadata of active guest

- plugins/hosts/linux/cap/nfs.rb
- test/unit/plugins/hosts/linux/cap/nfs_test.rb
Only move new exports file to destination without sudo when the
file has write access and the directory has write access. Always
use sudo when changing file ownership.
Fixes: #8610
> Fix sudo usage in exports write within linux host cap

- lib/vagrant/util/powershell.rb
- test/unit/vagrant/util/powershell_test.rb
Prior to this commit, the `Util::Powershell.execute_inline`
method didn't properly join the passed in command and instead attempted
to execute the array of strings. This commit updates that
behavior to join the command array prior to inserting it into the full
powershell command.
Fixes #10099
> Properly join commands from passed in array

- lib/vagrant/plugin/v2/trigger.rb
- test/unit/vagrant/plugin/v2/trigger_test.rb
Prior to this commit, if the args key was a string rather than an array
of strings, the `join` command would fail when appending the arguments
to the run command for a given script. This commit updates that by
ensuring the `args` option is an array prior to joining the arguments.
Fixes #10104
> Ensure trigger run args are an array prior to join

- website/source/docs/provisioning/puppet_apply.html.md
This commit updates the documentation for `module_path` to say that it
can be both a string or array of string paths.
Fixes #10091
> Documentation: Update `module_path` type for puppet apply provisioner

- plugins/commands/reload/command.rb
- test/unit/plugins/commands/reload/command_test.rb
This commit introduces the `--force` flag to the reload command. This
change means that if the flag is included, the halt step of the reload
will forcefully shutdown the virtual machine rather than a graceful
halt.
Fixes #9677
> Add `--force` flag to reload command

- lib/vagrant/plugin/v2/trigger.rb
- test/unit/vagrant/plugin/v2/trigger_test.rb
This pull request brings in  #9877 and updates the tests to account for when the path used has a space in it.
> Allow for spaces in `path` for trigger run option

- lib/vagrant/environment.rb
- test/unit/vagrant/environment_test.rb
Force the vagrantfile and configuration loader to be rebuilt after
plugins have been loaded to properly allow newly introduced plugin
configurations to be properly supported within the Vagrantfile.
Fixes #10153 #10150
> Reset internal environment after plugin load

- plugins/hosts/windows/cap/smb.rb
- test/unit/plugins/hosts/windows/cap/smb_test.rb
Since we are no longer extracting information based on key value due
to localization issues, use start and end locations to extract data.
This prevents errors when extra information is included like Scope.
Fixes #10151
> Extract smblist information based on position

- plugins/guests/linux/cap/network_interfaces.rb
- test/unit/plugins/guests/linux/cap/network_interfaces_test.rb
In some cases, the list of network interfaces collected in plugins/guest/linux/cap/network_interfaces.rb contains an empty string because of an additional appended newline which leads to an error during configuration. 
Also, when the interface list contains a value that does not have a numeric suffix (e.g. "lo"), the resulting sorted list contained an extra "" interface.
> [#10098] Filter out empty strings and loopback interfaces when constructing the list of network interfaces

- templates/guests/openbsd/network_static6.erb
The template for ipv6 was missing so far, which resulted in an error when trying to use IPv6 for a machine.
> Add IPv6 network template for OpenBSD machines

- plugins/provisioners/ansible/provisioner/guest.rb
When umask settings are restricted the Vagrant Ansible plugin fails on trying to copy files via `scp`.
```
Failed to upload a file to the guest VM via SCP due to a permissions
error. This is normally because the SSH user doesn't have permission
to write to the destination location. Alternately, the user running
Vagrant on the host machine may not have permission to read the file.
Source: /tmp/vagrant-ansible-local-inventory-default20180822-27107-1tw1r4z
Dest: /tmp/vagrant-ansible/inventory/vagrant_ansible_local_inventory
```
The ansible provisioner creates directory for the inventory in a tmp directory. It `chowns` the inventory directory to ensure the vagrant user can access it. However the parent directory is not necessarily accessible by non-root users.
If UMASK is set to 0077, the …
> Fix ansible_local provisioner permission bug

- lib/vagrant.rb
- lib/vagrant/plugin/manager.rb
- test/unit/vagrant/plugin/manager_test.rb
- test/unit/vagrant_test.rb
Due to the Vagrantfile being loaded prior to plugin loading to determine
project local plugin information the Vagrant.has_plugin? helper will always
return false when the Vagrantfile is first loaded. To prevent this behavior
we can check for plugins in the plugin data files prior to the plugins
being loaded, and after they have been loaded we can fallback to the
original specification based check.
Fixes #10161
> Update Vagrant.has_plugin? helper to function prior to plugin loading

- plugins/commands/powershell/command.rb
- plugins/commands/powershell/plugin.rb
- website/source/docs/cli/powershell.html.md
This pull request fixes up some of the doc strings around the `vagrant powershell` command. It also fixes a missing locales error for winrm.
> vagrant powershell command fixup

- lib/vagrant.rb
- test/unit/vagrant_test.rb
to check Vagrant for a version match without raising an error.
Sample:
```ruby
unless Vagrant.version?(">= 2.1.0") || Vagrant.has_plugin?("vagrant-triggers")
abort "We need triggers!"
end
```
> add `Vagrant.version?` helper method

- templates/commands/ssh_config/config.erb
- test/unit/plugins/commands/ssh_config/command_test.rb
> Check verify_host_key for falsey or :never values when generating ssh config

- plugins/providers/hyperv/scripts/configure_vm.ps1
The AutomaticCheckpointsEnabled option may not always be available
depending on the version in use. Check for support before applying
the configured value. If automatic checkpoints are to be enabled
and support is not available, force an error.
Fixes #10175
> Check for automatic checkpoint support before configuring

- plugins/commands/init/command.rb
- test/unit/plugins/commands/init/command_test.rb
- website/source/docs/other/environmental-variables.html.md
This is useful to save some typing when one regularly uses a custom template.
> vagrant init: Support VAGRANT_DEFAULT_TEMPLATE

- contrib/bash/completion.sh
for some reason there is currently no completion at all for the destroy
subcommand. like the other commands already present in that code block,
destroy acts on currently running VMs and so it makes sense to complete
those names.
> bash: complete running VM names for destroy subcommand

- lib/vagrant/util/guest_inspection.rb
- test/unit/plugins/guests/debian/cap/configure_networks_test.rb
If you have a vagrant box with proc mounted with
```
proc    /proc    proc    defaults,hidepid=2     0     0
```
ps output will be limited to owned process
`sudo` should extend an output
This should fix https://github.com/hashicorp/vagrant/issues/10197
> Hardened proc disallow systemd detection

- plugins/provisioners/salt/provisioner.rb
- website/source/docs/provisioning/salt.html.md
The salt bootstrap can now accept version arguments on non-windows
hosts, so this commit allows the Vagrant provisinoer to specify a
version.
Fixes #9802
> Allow non-windows hosts to pass along version

- lib/vagrant/environment.rb
- templates/locales/en.yml
- test/unit/vagrant/environment_test.rb
Reloading the Vagrantfile causes issue with multiple evaluations
where users expect single evaluation. Instead of allowing local
plugin installation to happen prior to command execution, force
halt after installation and the command to be re-run. This will
prevent multiple loads of the Vagrantfile within a single run.
Fixes #10186, #10193
> Force command to be re-run after installing local plugins

- contrib/bash/completion.sh
- Note that this does not cover additional options like --no-provision
- It is also a bit slow, as `vagrant snapshot list` is used to gather
the data
> Add completion for snapshot names for vagrant snapshot restore|delete

- lib/vagrant/machine.rb
- test/unit/vagrant/machine_test.rb
This commit brings in pull request https://github.com/hashicorp/vagrant/pull/10190 and adds a proper test to ensure that if two different file paths that are the same but have a different casing are not seen as different when checking for current working dir of a machine.
> Ensure file paths are identical when checking for cwd

- plugins/guests/windows/cap/mount_shared_folder.rb
- test/unit/plugins/guests/windows/cap/mount_shared_folder_test.rb
This commit brings in PR #10004 and adds a test to ensure that the users password is quoted to allow for special characters.
> Allow special characters in SMB password field

- plugins/provisioners/puppet/provisioner/puppet.rb
- test/unit/plugins/provisioners/puppet/provisioner/puppet_test.rb
Prior to this commit, the puppet provisioner would not properly set its
environment variables, if any were configured in the Vagrantfile. This
commit separates those properly with semicolons when calling out to
puppet apply.
> Fixes #8315: Properly set env variables for puppet provisioner

- website/source/intro/vs/docker.html.md
The docs indicate that most systems must use a VM for containerization. This is no longer the case as Docker For Mac now uses HyperKit.
See https://docs.docker.com/v17.12/docker-for-mac/docker-toolbox/
> Update Docker containerization docs

- contrib/sudoers/osx
The last line was all wrong. visudo couldn't even parse it.
> Fix the broken sudoers file for OS X

- lib/vagrant/plugin/v2/trigger.rb
- plugins/kernel_v2/config/vm_trigger.rb
- templates/locales/en.yml
- test/unit/plugins/kernel_v2/config/vm_trigger_test.rb
- test/unit/vagrant/plugin/v2/trigger_test.rb
- website/source/docs/triggers/configuration.html.md
This commit adds a new option `abort`, which when configured, will exit
the Vagrant process completely. If set to `true`, it will exit cleanly
with exit code 0. Otherwise, the exit code can be configured.
Fixes: #10095
> Add abort option to core triggers

- lib/vagrant/util/guest_inspection.rb
- plugins/guests/redhat/cap/change_host_name.rb
- test/unit/plugins/guests/debian/cap/configure_networks_test.rb
- test/unit/plugins/guests/redhat/cap/change_host_name_test.rb
This is built off the original work provided in #10214 Adds usage of the guest inspection module for testing the guest and executing the correct actions based on results. Guest inspection updated with better test commands and free form service check.
> Update restart logic in redhat change_host_name cap

- website/source/assets/javascripts/analytics.js
- website/source/downloads.html.erb
Vagrant download URLs are formatted a bit differently from the other products, so our analytics events weren't working correctly for product downloads. This PR fixes it!
> Fix download tracking analytics events

- website/source/docs/vagrantfile/machine_settings.html.md
This commit updates the documentation so that it is more clear that Windows guests need to change the `config.vm.guest` option along with the `config.vm.communicator` option.
> Add :windows to config.vm.guest in machine settings doc

- lib/vagrant/plugin/v2/trigger.rb
- plugins/kernel_v2/config/vm_trigger.rb
- templates/locales/en.yml
- test/unit/plugins/kernel_v2/config/vm_trigger_test.rb
- test/unit/vagrant/plugin/v2/trigger_test.rb
- website/source/docs/triggers/configuration.html.md
- website/source/docs/triggers/usage.html.md
This commit introduces a new option to the core trigger feature: `ruby`.
It can be defined to run ruby code when the trigger is configured to
fire. If you give the ruby block an env and machine argument, the
defined ruby code can use those variables internally.
> Fixes #9840: Introduce `ruby` option for trigger

- lib/vagrant/errors.rb
- plugins/commands/upload/command.rb
- plugins/commands/upload/plugin.rb
- plugins/commands/winrm/command.rb
- plugins/commands/winrm/plugin.rb
- plugins/commands/winrm_config/command.rb
- plugins/commands/winrm_config/plugin.rb
- plugins/guests/bsd/cap/file_system.rb
- plugins/guests/bsd/plugin.rb
- plugins/guests/linux/cap/file_system.rb
- plugins/guests/linux/plugin.rb
- plugins/guests/solaris/cap/file_system.rb
- plugins/guests/solaris/plugin.rb
- plugins/guests/windows/cap/file_system.rb
- plugins/guests/windows/plugin.rb
- templates/commands/winrm_config/config.erb
- templates/locales/en.yml
- test/unit/plugins/commands/upload/command_test.rb
- test/unit/plugins/commands/winrm/command_test.rb
- test/unit/plugins/commands/winrm_config/command_test.rb
- test/unit/plugins/guests/bsd/cap/file_system_test.rb
- test/unit/plugins/guests/linux/cap/file_system_test.rb
- test/unit/plugins/guests/solaris/cap/file_system_test.rb
- test/unit/plugins/guests/windows/cap/file_system_test.rb
- vagrant.gemspec
- website/source/docs/cli/upload.html.md
- website/source/docs/cli/winrm.html.md
- website/source/docs/cli/winrm_config.html.md
Adds a `winrm` and `winrm-config` command for use when using the winrm communicator (matching the ssh commands available when using the ssh communicator).
New `upload` command is also provided which allows for uploading arbitrary files or directories from the host to the guest (optionally using compression) using the currently configured communicator.
Fixes #10204
> Add winrm and upload commands

- lib/vagrant/util/platform.rb
- test/unit/vagrant/util/platform_test.rb
- website/source/docs/other/environmental-variables.html.md
Updates the hyper-v admin check to check if part of the hyper-v admin group, domain admin group, and falls back to checking if hyper-v commands are available and functioning. Also includes an environment variable a user can set to disable the check if these checks are insufficient for any reason.
Fixes: #8868
> Update Hyper-V admin check

- plugins/synced_folders/rsync/helper.rb
- test/unit/plugins/synced_folders/rsync/helper_test.rb
Prior to this commit, when creating the ControlPath tmp dir for
socket path, Vagrant would simply rely on `rand(1000)` for making unique
dirs for rsyncing files which could result in collisions. This commit
updates that be properly using `Dir.mktmpdir` with a `vagrant-rsync-`
prefix.
> Fixes #10289: Create proper tmp dir for ControlPath

- plugins/guests/debian/cap/change_host_name.rb
- test/unit/plugins/guests/debian/cap/change_host_name_test.rb
Prior to this commit, the hostname was set with one big bash script and
attempted to determine what tools are available. This commit changes
that by splitting out that tool check on the Vagrant side of things with
the GuestInspection class, and adds back restarting networking to get a
DHCP lease with the change rather than using `dhclient`. This pattern
matches how hostnames are set in the redhat capability.
Tested on very old guests like `hashicorp/precise64` (which had hostname issues because of `dhclient`) as well as new guests like `bento/ubuntu-18.04`.
> Fixes #9763, #10300: Split out how hostname is set with Debian hosts

- plugins/synced_folders/smb/synced_folder.rb
- test/unit/plugins/synced_folders/smb/synced_folder_test.rb
Prior to this commit, Vagrant would prompt for smb username and password
every time, even if only smb_username was defined. This commit changes
that by allowing a "default" username from the Vagrantfile, with the
option of overriding it.
> Fixes #9591: Allow for 'default' smb_username if set

- plugins/communicators/ssh/communicator.rb
- test/unit/plugins/communicators/ssh/communicator_test.rb
If the type of error changes on retry the messages will effectively
spam the user display with alternating messages. Log each message
sent and only re-display each message once within 10 seconds.
> Prevent overly verbose output from SSH communicator

- plugins/providers/virtualbox/driver/version_5_0.rb
- plugins/providers/virtualbox/synced_folder.rb
- test/unit/plugins/providers/virtualbox/driver/version_5_0_test.rb
- test/unit/plugins/providers/virtualbox/synced_folder_test.rb
- website/source/docs/synced-folders/virtualbox.html.md
This commit adds a new option to virtualbox synced_folders called
`automount`, where if set to true, will supply the `--automount` flag to
virtualbox.
> Fixes #10016: Add `automount` flag if specified with synced_folder

- plugins/guests/debian/cap/change_host_name.rb
- test/unit/plugins/guests/debian/cap/change_host_name_test.rb
This pull request adds some additional logic that falls back to using the
ifdown/ifup tools to restart networking. On Ubuntu 14.04, the init
script was designed to always fail to restart newtorking, so it needs
to use the ifdown/up tools instead.
This pull request also uses a workaround due to how older debian
and ubuntu systems fail to properly restart networking. Instead of
relying on the init scripts or ifup/down tools to restart each interface,
this commit instead restarts each interface individually.
Related PR #10301
Related issues:  #9763 #10300
Tested against this Vagrantfile: https://github.com/briancain/congenial-octo-palm-tree/blob/master/debian/Vagrantfile against these OS's:
- debian 7
- debian 8
- debian 9
- ubuntu 12
- ubuntu 14
- ubuntu 16
- ubuntu 18
> Reliably restart Debian and Ubuntu guests networking on setting hostname

- lib/vagrant/util/platform.rb
- test/unit/vagrant/util/platform_test.rb
Ignore PowerShell issues during Hyper-V enabled check. If PowerShell is required later (either by synced folders or a different provider) the PowerShell installation check will raise an error at that time.
> Prevent exception from raising on hyper-v check

- website/source/docs/vagrantfile/machine_settings.html.md
- website/source/docs/vagrantfile/ssh_settings.html.md
- website/source/docs/vagrantfile/vagrant_settings.html.md
- website/source/docs/vagrantfile/winrm_settings.html.md
- website/source/docs/vagrantfile/winssh_settings.html.md
Updates the `Vagrantfile` configuration to use list format so anchor links are auto-generated. Added type information for options and removed some stale information. Also included entries for `base_mac` and `base_address`.
> Update vagrantfile documentation content to use list

- lib/vagrant/action/builtin/config_validate.rb
- lib/vagrant/config/v2/root.rb
- plugins/commands/validate/command.rb
- plugins/kernel_v2/config/vm.rb
- templates/locales/en.yml
- test/unit/plugins/commands/validate/command_test.rb
- test/unit/plugins/kernel_v2/config/vm_test.rb
- test/unit/vagrant/config/v2/root_test.rb
This commit adds a new flag to the `vagrant validate` command which
allows users to completely ignore the provider block of a config file.
This is useful for when you are running `vagrant validate` in CI and
don't want to install a valid provider to check the syntax of your
Vagratnfile. When the flag is invoked, a warning will be displayed
saying that the provider block will be ignored and not validated.
> Fixes #10224: Allow validation of config while ignoring provider

- lib/vagrant/util/network_ip.rb
- test/unit/vagrant/util/network_ip_test.rb
`Vagrant::Util::NetworkIP#network_address` could be simplified significantly.
In fact, `IPAddr#mask` method supports string and integer arguments as well, so this PR also allows to set IPv6 masks in string notation, like `"ffff:ffff:ffff:ffff::"`
> util/network_ip: Simplify #network_address helper

- lib/vagrant/bundler.rb
- test/unit/vagrant/bundler_test.rb
In recent Rubies the first dependency to satisfy the constraint will
be used regardless if higher versions are available in subsequent
sources. Move custom source to start of list when resolving plugins
to provide desired behavior.
> Update ordering of gem sources to ensure proper resolution

- vagrant.gemspec
The net-ssh library supports ed25519 keys but only if the required
dependencies are available. This adds the required dependencies.
Fixes #9886
> Add support for ed25519 keys

- plugins/providers/hyperv/scripts/set_network_vlan.ps1
Write helpers are provided by the VagrantMessages modules. This local module import is an artifact from before the provider overhaul that should have been removed then.
Fixes #10320
> Remove module loading from vlan script

- plugins/providers/virtualbox/action/network.rb
- plugins/providers/virtualbox/config.rb
- test/unit/plugins/providers/virtualbox/action/network_test.rb
- test/unit/plugins/providers/virtualbox/config_test.rb
- website/source/docs/virtualbox/configuration.html.md
Provides support for defining the NIC type used for any guest adapter
which does not define an adapter type. This is defaulted to "virtio".
> Add support for specifying the default NIC type used for guest adapters

- lib/vagrant/util/ssh.rb
- test/unit/vagrant/util/ssh_test.rb
Prior to this commit, if a windows path contained a space, the ssh
utility could not properly find the private key path and the ssh command
would fail. This commit adds some additional logic to the ssh utility to
check if a path contains '%', and if so, use the IdentityFile argument.
Otherwise it will default to passing in the private key file with '-i',
which can support paths with spaces.
>  FIXES #9870: Allow for windows path spaces with ssh utility

- lib/vagrant/plugin/v2/communicator.rb
- plugins/communicators/ssh/communicator.rb
- plugins/communicators/winrm/communicator.rb
- plugins/provisioners/docker/cap/linux/docker_configure_vagrant_user.rb
- plugins/provisioners/shell/config.rb
- plugins/provisioners/shell/provisioner.rb
- test/unit/plugins/communicators/ssh/communicator_test.rb
- test/unit/plugins/communicators/winrm/communicator_test.rb
- test/unit/plugins/provisioners/shell/config_test.rb
- test/unit/plugins/provisioners/shell/provisioner_test.rb
- website/source/docs/provisioning/shell.html.md
Adds a `Communicator#reset!` method to allow resetting the communicator to force establishing a new connection. Fixes linux docker install to reset communicator after group updates so `vagrant` user has `docker` group available. Includes new option `:reset` to the shell provisioner to allow resetting the connection after a provisioner has completed. Also allows a provisioner to run without a `path` or `inline` defined simply to reset the connection.
Fixes #10388
> Add communicator reset

- plugins/providers/hyperv/scripts/utils/VagrantVM/VagrantVM.psm1
The default error action is to stop. When generating the initial
VM configuration during import, if the Compare-VM command fails
it results in a generic error message. Instead the error should
be ignored so the source VM can be inspected and a useful error
message can be returned to the user.
Fixes: #10384
> Ignore errors when generating new VM configuration

- plugins/providers/virtualbox/driver/version_5_0.rb
- test/unit/plugins/providers/virtualbox/driver/version_5_0_test.rb
Be more restrictive when matching the port forward used for
SSH. Allow matching simply on the guest port, but also include
extra matching criteria for cases where multiple results may
be returned.
Fixes #10407
> Update VirtualBox driver ssh_port helper

- plugins/providers/virtualbox/action.rb
- plugins/providers/virtualbox/action/network.rb
- plugins/providers/virtualbox/action/set_default_nic_type.rb
- plugins/providers/virtualbox/config.rb
- templates/locales/en.yml
- test/unit/plugins/providers/virtualbox/action/network_test.rb
- test/unit/plugins/providers/virtualbox/action/set_default_nic_type_test.rb
- test/unit/plugins/providers/virtualbox/config_test.rb
- website/source/docs/virtualbox/configuration.html.md
In some cases the E1000 NIC type is the only acceptable value. Since
defaulting causes breakages to existing boxes, leave the default value
as `nil` but check the VirtualBox version in use and print warning to
user if VirtualBox version is vulnerable and E1000 NIC types are
configured for use within defined network adapters.
Fixes: #10448
> Update default_nic_type implementation within VirtualBox provider

- lib/vagrant/errors.rb
- plugins/commands/cloud/publish.rb
- templates/locales/en.yml
- test/unit/plugins/commands/cloud/publish_test.rb
Prior to this commit, Vagrant would attempt to path expand a file that
didn't exist if it was left out of the passed in arguments and no
`--url` was used for external box uploading. This commit fixes that by
adding some additional validation for the passed in box file.
> Fixes #10432: Validate that provider file exists prior to upload

- plugins/provisioners/salt/config.rb
- templates/locales/en.yml
Prior to this commit, if you specified a `version` for the salt provider
but no `install_type` Vagrant would fail to pass the proper parameters
to the bootstrap install script. This commit fixes that by adding some
validation to the salt provider if `version` is specified but not
`install_type`. It also adds some extra context for certain config
validation error messages so that the user knows what option was
incorrect, rather than the message just referring to the option as
*this*.
> Fixes #10358: Add validation error in salt provider for certain options

- plugins/commands/package/command.rb
- test/unit/plugins/commands/package/command_test.rb
Prior to this commit, the package actions would create a temp dir in
the process of packaging and compressing a Vagrant box. This commit
ensures that the temp dir is removed once the command has completed so
that it doesn't leave around lots of temp directories.
> Fixes #9593: Ensure temp dir for package command is cleaned up

- lib/vagrant/util/checkpoint_client.rb
- test/unit/vagrant/util/checkpoint_client_test.rb
This commit updates the behavior of printing the checkpoint version
check for Vagrant. To allow users to filter out the message, it updates
the version check to go to stderr. It updates the UI class for printing
the version check to be a "basic" class, so that the message continues
to be the same color instead of a red error message.
> Fixes #10463: Display version update on stderr instead of stdout

- plugins/providers/virtualbox/action/set_default_nic_type.rb
- test/unit/plugins/providers/virtualbox/action/set_default_nic_type_test.rb
The changeset _did_ get included in the 5.2.22 release so adjust
the requirement to only warn on previous versions
Fixes #10481
> Adjust requirement on warnings for VirtualBox NIC

- plugins/hosts/windows/cap/smb.rb
- test/unit/plugins/hosts/windows/cap/smb_test.rb
When a large number of shares are defined it may cause the generated
command to exceed the maximum allowed length. To prevent this, only
allow 10 shares to be processed at a time.
Fixes #10483
> Only prepare 10 shares per command to prevent exceeding allowed command size

- website/source/intro/getting-started/project_setup.html.md
This commit ensures that a proper box is used during the project setup
tutorial. Otherwise later down the road uesrs will run into Vagrant
saying that the box `base` doesn't exist.
> Use specific Vagrant box in tutorial setup

- plugins/communicators/winrm/shell.rb
- test/unit/plugins/communicators/winrm/shell_test.rb
Elevated commands can fail via winrm under certain conditions like
the machine name being changed. Detect this by checking for a known
exit code combined with known output included within stderr. If found,
attempt to re-execute the command using a machine prefixed username
if possible.
> Only modify elevated username under specific conditions

- plugins/commands/snapshot/command/pop.rb
- plugins/commands/snapshot/command/restore.rb
- plugins/providers/virtualbox/action.rb
- test/unit/plugins/commands/snapshot/command/pop_test.rb
- test/unit/plugins/commands/snapshot/command/restore_test.rb
- website/source/docs/cli/snapshot.html.md
Both of these commands failed to default the options disabling
the provisioning from ignoring the sentinel file. This resulted
in different behavior than what was seen with the `up` and
`resume` commands which would only provision items with run set
to "always". This defaults the options to proper match the behavior
of `up` and `resume` to be consistent.
This also adds an extra `--no-start` flag to allow users to restore
a snapshot but not start the restored guest immediately.
Fixes #6752
> Update behavior of `snapshot restore` and `snapshot pop`

- lib/vagrant/util/guest_inspection.rb
When checking if the hostnamectl command should be used for configuring
the guest hostname, ensure the command returns a valid result. The
hostnamectl command relies on dbus and if dbus is not available the
command will simply fail.
Fixes #10501
> Validate hostnamectl command is in working state

- templates/guests/freebsd/network_static.erb
- templates/guests/freebsd/network_static6.erb
- test/unit/templates/guests/freebsd/network_static_test.rb
The rcvar should be `defaultrouter` instead:
https://www.freebsd.org/doc/handbook/network-routing.html
> FreeBSD: Fix rcvar in network_static templates

- plugins/hosts/void/cap/nfs.rb
- plugins/hosts/void/host.rb
- plugins/hosts/void/plugin.rb
- test/unit/plugins/hosts/void/cap/nfs_test.rb
Currently, NFS does not work correctly on void linux. This PR adds a new Void Linux host to fix this. An issue has been opened here: #10011
> Add void linux host support

- plugins/guests/alt/cap/configure_networks.rb
- plugins/guests/redhat/cap/configure_networks.rb
- test/unit/plugins/guests/alt/cap/configure_networks_test.rb
- test/unit/plugins/guests/redhat/cap/configure_networks_test.rb
Extra options are extracted from the machine configuration for the
network being configured to allow for customized network manager
behavior. The network entries must be filtered to remove non-network
entries (like port forwards) before accessing by index.
Related to #9546
> Fix guest network configuration by properly extracting extra options

- plugins/provisioners/salt/config.rb
- test/unit/plugins/provisioners/salt/config_test.rb
Salt provisioner will no longer require an unsupported argument on Windows when specifying `version`.
Fixes #10538
Note:  The Salt provisioner plugin does not currently support **winssh**.  I am matching the current convention for the plugin by only checking **winrm** to determine the guest OS.
> Disabled salt provision required install_type check on Windows

- plugins/provisioners/shell/config.rb
- plugins/provisioners/shell/provisioner.rb
- test/unit/plugins/provisioners/shell/config_test.rb
- test/unit/plugins/provisioners/shell/provisioner_test.rb
- website/source/docs/provisioning/shell.html.md
Adds a `reboot` option which allows the guest to be rebooted after
the completion of a shell provisioning task. The guest must support
the `:reboot` capability. Like the `reset` option, the `reboot`
option may be provided without defining `inline` or `file` options
when a reboot may be required between other provisioners.
Fixes #8639
> Add reboot option to shell provisioner

- plugins/synced_folders/rsync/command/rsync.rb
- plugins/synced_folders/rsync/command/rsync_auto.rb
- plugins/synced_folders/rsync/helper.rb
- test/unit/plugins/synced_folders/rsync/command/rsync_auto_test.rb
- test/unit/plugins/synced_folders/rsync/command/rsync_test.rb
- test/unit/plugins/synced_folders/rsync/helper_test.rb
- website/source/docs/cli/rsync-auto.html.md
- website/source/docs/cli/rsync.html.md
- website/source/docs/synced-folders/rsync.html.md
Adds a new `rsync__rsync_ownership` option to rsync based synced folders
which will allow rsync to use the `--chown` flag if it is available. The
`rsync` and `rsync-auto` commands have a new `--rsync-chown` flag which
can be used to force the option on folders when running the commands.
Fixes #7329 #7332 #6856
> Add support for using the `--chown` flag with rsync when available.

- plugins/provisioners/file/provisioner.rb
- templates/locales/en.yml
Prior to this commit, Vagrants output would only show that a file
provisioner was running, but had no detail as to what file was being
copied to where. This is especially confusing if a Vagrantfile has
multiple file provisioners. This commit updates that by showing the
source and destination of the file so that it's clearer what is being
copied and to where.
> Show source and destination locations with file provisioner

- plugins/guests/coreos/cap/configure_networks.rb
- test/unit/plugins/guests/coreos/cap/configure_networks_test.rb
Quote from https://github.com/hashicorp/vagrant/pull/6610#issuecomment-449678760,
> In #6608, the grep command is
> 
> `grep -E '(e[n,t][h,s,p][[:digit:]]([a-z][[:digit:]])?)'`
> 
> but in this PR, it is
> 
> `grep '(e[n,t][h,s,p][[:digit:]]([a-z][[:digit:]])?'`
> 
> No -E and no last close parenthesis.
> I think the former is correct one.
As written, the code is just copied from #6608, not my code.
> Fix grep command for network interface of CoreOS guest

- lib/vagrant/action/builtin/box_check_outdated.rb
- templates/locales/en.yml
This commit updates the output Vagrant displays when checking if a box
is out of date by adding the version.
> Fixes #10339: Show box version during outdated check

- test/unit/plugins/communicators/ssh/communicator_test.rb
- vagrant.gemspec
There is new net-ssh release [1] with a fix needed for vagrant-kubevirt.
Fixes: https://github.com/hashicorp/vagrant/issues/10421
[1] https://github.com/net-ssh/net-ssh/releases/tag/v5.1.0
> dependency: update net-ssh version

- plugins/commands/cloud/publish.rb
- vagrant.gemspec
This pull request adds a new rescue to the `publish` command for when the
client detects an invalid version prior to making the API request to
create that version.
It also bumps the version dependency of `vargant_cloud` to 2.0.2, which hasn't been released yet. This is required as the new error namespace is in that version.
Relies on this being merged/released: https://github.com/hashicorp/vagrant_cloud/pull/45
Fixes #10509
> Fixes #10509:  Catch InvalidVersion errors from vagrant_cloud client

- plugins/guests/debian/cap/configure_networks.rb
- test/unit/plugins/guests/debian/cap/configure_networks_test.rb
Prior to this commit, if a debian system requested an DHCP address using
systemd-network, Vagrant would ignore it and instead use the configured
IP from the virtualbox network action. This commit fixes that by instead
looking if DHCP was requested, and if so, use that option for an IP.
> Fixes #10585: Properly set DHCP for systemd-networkd ips

- plugins/providers/virtualbox/driver/version_6_0.rb
- test/unit/plugins/providers/virtualbox/driver/version_6_0_test.rb
Fixes import error on Windows due to non-matching path separators
when updating guest name for disk import.
Fixes #10623
Since this also applies to behavior in WSL it inadvertently fixes
pathing issues there as well.
Fixes #10582 #10533
> Fix import paths on Windows for the vbox 6 driver

- plugins/providers/docker/action/compare_synced_folders.rb
- test/unit/plugins/providers/docker/action/compare_synced_folders_test.rb
Prior to this pull request, the docker action would attempt to compare and
validate synced folders based on their string value, rather than their
actual path value. This commit updates that by path expanding the mounts
when comparing a containers synced folders.
> Expand paths on synced folder compare with docker provider

- lib/vagrant/action/builtin/after_trigger.rb
- lib/vagrant/action/builtin/before_trigger.rb
- lib/vagrant/action/runner.rb
- lib/vagrant/action/warden.rb
- lib/vagrant/cli.rb
- lib/vagrant/environment.rb
- lib/vagrant/errors.rb
- lib/vagrant/machine.rb
- lib/vagrant/plugin/v2/trigger.rb
- plugins/kernel_v2/config/trigger.rb
- plugins/kernel_v2/config/vm_trigger.rb
- templates/locales/en.yml
- test/unit/plugins/kernel_v2/config/vm_trigger_test.rb
- test/unit/vagrant/action/builder_test.rb
- test/unit/vagrant/action/builtin/call_test.rb
- test/unit/vagrant/action/runner_test.rb
- test/unit/vagrant/cli_test.rb
- test/unit/vagrant/machine_test.rb
- test/unit/vagrant/plugin/v2/trigger_test.rb
- website/source/docs/experimental/index.html.md
- website/source/docs/triggers/configuration.html.md
- website/source/docs/triggers/usage.html.md
- website/source/layouts/docs.erb
This pull request introduces a new option modifier named `:type` for the core trigger feature in Vagrant. It introduces the ability to write triggers that run before or after commands, as well as action hooks and action classes themselves. It is also guarded under the new experimental flag.
Valid types include:
- `:command`
+ Defined for any Vagrant subcommand.
- `:action`
+ Defined for any Vagrant `#Action` class executed through the core middleware
- `:hook`
+ Defined for any Vagrant hook that passes through the `#Action::Runner` class.
An example of a command trigger that would run _before_ running `vagrant status` could look like:
```ruby
config.trigger.before :status, type: "command" do |t|
t.info = "hello"
end
```
Fixes #9846 #9845 #8500
> Introduce :type option for Vagrant triggers

- plugins/kernel_v2/config/vagrant.rb
- templates/locales/en.yml
- test/unit/plugins/kernel_v2/config/vagrant_test.rb
Properly supports mixed types within arrays and adds
coverage on formatting different variations of values.
Fixes #10658
> Fix format finalization of plugins in Vagrantfile

- website/source/docs/vmware/vagrant-vmware-utility.html.md.erb
This updates the installation path described to be the default
location so that the vagrant-vmware-plugin will automatically
discover the certificates directory without requiring any
customization within the Vagrantfile.
> Update path for manual vagrant-vmware-utility installation

- lib/vagrant/box_collection.rb
- templates/locales/en.yml
- test/unit/vagrant/box_collection_test.rb
Prior to this commit, if a box some how got on disk that had an
incorrect or invalid version number that did not match Gem::Version,
Vagrant would throw an exception when attempting to generate a list of
the boxes on disk. This commit fixes that by looking at the version from
the path generated, and shows a warning to the user about the box and
skips it from the list so they at least know about the problematic box
and can still get a list of boxes.
> Fixes #10663: Ignore boxes in collection with malformed version numbers

- website/source/docs/cli/validate.html.md
The `vagrant validate` command has a parameter `-p`/ `--ignore-provider` which ignores when no provider is installed. This was submitted in #10351 but not documented. This is the only change in this PR.
> Add `vagrant validate` parameters to docs

- plugins/commands/box/command/add.rb
- plugins/commands/box/command/update.rb
- test/unit/plugins/commands/box/command/update_test.rb
This fixes issues with box add/update when self hosting boxes with client
cert authentication. The --cert option was not being added to the curl subprocess resulting in a 400 bad request response.
> Change remaining box_client_cert refs to box_download_client_cert

- plugins/commands/cloud/auth/middleware/add_authentication.rb
- plugins/commands/cloud/locales/en.yml
- plugins/commands/cloud/plugin.rb
- plugins/commands/login/plugin.rb
- test/unit/plugins/commands/cloud/auth/middleware/add_authentication_test.rb
Prior to this commit, the AddAuthentication hooks still existed in a
deprecated class LoginCommand. This commit fixes that by moving it over
to the vagrant cloud cli namespace instead.
> Fixes #10682: Move over AddAuthentication middleware and hooks

- plugins/communicators/ssh/communicator.rb
- plugins/communicators/winrm/shell.rb
- plugins/provisioners/file/provisioner.rb
- test/unit/plugins/communicators/ssh/communicator_test.rb
- test/unit/plugins/communicators/winrm/shell_test.rb
- test/unit/plugins/communicators/winssh/communicator_test.rb
- test/unit/plugins/provisioners/file/provisioner_test.rb
This update was prompted by updates in openssh to the scp behavior
making source directory paths suffixed with `.` no longer valid
resulting in errors on upload. The upload implementation within
the ssh communicator has been updated to retain the existing
behavior.
Included in this update is modifications to the winrm communicator
so the upload functionality matches that of the ssh communicator
respecting the trailing `.` behavior on source paths. With the
communicators updated to properly handle the paths, the file
provisioner was also updated to simply apply previously defined
path update rules only.
Fixes #10675 #10697
> Update communicator upload behavior to handle `/.` path directives

- plugins/synced_folders/rsync/helper.rb
- test/unit/plugins/synced_folders/rsync/helper_test.rb
This pull request ensures that the tmp folder created by rsync gets properly cleaned up on the host.
> Cleanup rsync tmp folders

- lib/vagrant/action/general/package.rb
- test/unit/vagrant/action/general/package_test.rb
If the provider does not include a metadata.json file prior to
compressing the box, determine current provider and write
metadata.json file before compressing.
> Write metadata file to box contents during package

- plugins/commands/cloud/box/create.rb
- plugins/commands/cloud/box/delete.rb
- plugins/commands/cloud/provider/create.rb
- plugins/commands/cloud/provider/delete.rb
- plugins/commands/cloud/provider/update.rb
- plugins/commands/cloud/provider/upload.rb
- plugins/commands/cloud/publish.rb
- plugins/commands/cloud/search.rb
- plugins/commands/cloud/version/create.rb
- plugins/commands/cloud/version/delete.rb
- plugins/commands/cloud/version/release.rb
- plugins/commands/cloud/version/revoke.rb
- plugins/commands/cloud/version/update.rb
This commit uses the correct instance variable for the optparse library
when reading in the command line flags for various Vagrant Cloud CLI
commands.
> Fixes #10723: Fix bug instance var in Vagrant Cloud CLI optparse

- lib/vagrant/machine.rb
- test/unit/vagrant/machine_test.rb
If the id file includes whitespace, remove it. If the content of
the id file is empty, do not set the machine id.
Fixes: #10722
> Remove whitespace from id file on load

- plugins/guests/bsd/cap/mount_virtualbox_shared_folder.rb
- plugins/guests/bsd/plugin.rb
- plugins/guests/freebsd/cap/mount_virtualbox_shared_folder.rb
- plugins/guests/freebsd/plugin.rb
- test/unit/plugins/guests/bsd/cap/mount_virtual_box_shared_folder_test.rb
- test/unit/plugins/guests/freebsd/cap/mount_virtual_box_shared_folder_test.rb
This is a follow-up of #10717 to use the same naming convention as on Linux guests, in order to reduce the diffs.
Also adds the missing capability to `unmount_virtualbox_shared_folder` on FreeBSD guests.
> BSD: VirtualBox shared folders naming convention

- website/source/intro/getting-started/share.html.md
Current version of vagrant-share works only with ngrok installed. Just added a note for the same.
> note for pre-requisite of ngrok package

- plugins/guests/freebsd/cap/configure_networks.rb
- test/unit/plugins/guests/freebsd/cap/configure_networks_test.rb
According to [ifconfig(8)], to list only Ethernet interfaces, excluding all other interface types, including the loopback interface, the command to use should be:
ifconfig -l ether
Related to: #8760
[ifconfig(8)]: https://www.freebsd.org/cgi/man.cgi?query=ifconfig&sektion=8
> FreeBSD: Simplify the listing of interfaces

- website/source/docs/provisioning/ansible.html.md
- website/source/docs/provisioning/ansible_local.html.md
- website/source/docs/provisioning/chef_zero.html.md
- website/source/docs/provisioning/shell.html.md
Removing I since it does not really make sense while reading the
documentation.
> Remove *I* from documentation

- plugins/commands/snapshot/command/pop.rb
- plugins/providers/virtualbox/cap.rb
- test/unit/plugins/providers/virtualbox/cap_test.rb
Prior to this pull request, if a snapshot restore was run on an entire
environment with some non-existent guests, Vagrant would attempt to list
their snapshots with a nil id. This commit fixes that by returning an
empty list of snapshots if the machine has not been created yet.
> Ensure non-existent machines do not attempt to list snapshots

- plugins/provisioners/ansible/cap/guest/debian/ansible_install.rb
- plugins/provisioners/ansible/cap/guest/fedora/ansible_install.rb
- plugins/provisioners/ansible/cap/guest/pip/pip.rb
- plugins/provisioners/ansible/cap/guest/redhat/ansible_install.rb
- plugins/provisioners/ansible/cap/guest/ubuntu/ansible_install.rb
- plugins/provisioners/ansible/config/guest.rb
- plugins/provisioners/ansible/provisioner/guest.rb
- test/unit/plugins/provisioners/ansible/cap/guest/pip/pip_test.rb
- test/unit/plugins/provisioners/ansible/config/guest_test.rb
- website/source/docs/provisioning/ansible_local.html.md
In keeping with the suggested fix discussed in the issue: an additional option for pip_install_cmd has been included. Default behavior is maintained and it is only if the additional option is provided in the config that it is used. Unit tests have been included. 
Fixes #9584
> Fix issue 9584

- website/source/docs/other/environmental-variables.html.md
Follow-up from #10790 @dentarg
> Reword documentation for VAGRANT_DISABLE_VBOXSYMLINKCREATE option

- lib/vagrant/bundler.rb
- test/unit/vagrant/bundler_test.rb
Prior to this pull request, when Vagrant attempted to use the rubygems library, it
would attempt to pass in a gemrc through an environment variable that
the rubygems library would try to split and parse. This is normally
fine, as the method in question would return empty if that file did not
exist. However if the user had a file that matches the drive that
Vagrant was installed on, rubygems would fail saying the folder was not
a file (or a gemrc, in this case).
This commit works around that by instead configuring the gemrc location
through ruby with `Gem.configuration`.
Related rubygems issue rubygems/rubygems#2733
Fixes #10800, Fixes #9148
> Set gemrc through configuration method rather than relying on environment variable

- website/source/intro/getting-started/share.html.md
This commit adds a note and link on how to install vagrant-share before
the vagrant share tutorial starts. This ensures that users know they
need the plugin installed since it no longer comes with Vagrant core.
> Fixes #10813: Add install link docs to Share tutorial

- plugins/providers/docker/driver/compose.rb
- templates/locales/providers_docker.yml
- test/unit/plugins/providers/docker/driver_compose_test.rb
Prior to this commit, the docker compose driver would _always_ path
expand a host volume no matter what. This is not always the correct
option, for example if that host volume is actually a reference to a key
inside a `volumes` hash instead of a path on disk. This commit changes
that by looking to see if the requested host volume is actually a
defined key inside the compose config, and if not, it will path expand
it like before. Otherwise it will leave the key "as is".
> Fixes #10798: Enhance how docker compose driver path expands

- lib/vagrant/plugin/v2/trigger.rb
- test/unit/vagrant/plugin/v2/trigger_test.rb
Prior to this commit, the `abort` option for triggers would just call
`exit`, which would end up raising a SystemExit exception, signaling
Vagrant to abort. This broke down however in a multithreaded context
like when running multiple guests at once on supported providers,
resulting in Vagrant failing to exit cleanly and instead raise an
exception. This commit changes that by instead using `Process.exit!` to
abort Vagrant.
> Fixes #10823: Use Process.exit! for abort trigger option

- plugins/commands/snapshot/command/list.rb
- test/unit/plugins/commands/snapshot/command/list_test.rb
Prior to this commit, Vagrant would list all machine snapshots in a flat
list, without showing which snapshots were associated with which guests.
This commit fixes that by placing some separation to make it clear which
snapshots belong to which guests.
> Separate snapshot names when listing snapshots

- plugins/commands/box/command/update.rb
- test/unit/plugins/commands/box/command/update_test.rb
Prior to this commit, if a user ran a `vagrant box update` on their
entire environment and one of the boxes did not have a metadata file,
the rest of the boxes in the update would be skipped. This commit fixes
that by providing an option to ingore those boxes, so that the rest of
the boxes could check for updates.
> Continue updating environment boxes if metadata not found

- website/source/docs/synced-folders/nfs.html.md
Vagrant sudoer entries need to be after `root` and `%admin` are set up. Adding the entries at the end by default ensures the order is correct.
If the order isn't correct, users will still have to type their password every time and might not understand why.
Example from macOS 10.14 Mojave sudoers:
```
root            ALL = (ALL) ALL
%admin          ALL = (ALL) ALL
```
> Prevent nopasswd issues, add vagrant entries at end of sudoers

- contrib/bash/completion.sh
otherwise it might catch a non-machine id, in my case, for hostmanager plugin
> Search for running_vm_list only in `machines` folder

- lib/vagrant/plugin/v2/trigger.rb
- plugins/kernel_v2/config/vm_trigger.rb
- test/unit/vagrant/plugin/v2/trigger_test.rb
Prior to this commit, if a guest name was given as a symbol, the
filter_triggers method would fail to properly match it with the only_on
option, as it is not a valid type to the #String.match method. This
commit fixes that by converting the parameter to a string so that it can
be properly matched on the guest.
Relates to https://github.com/hashicorp/vagrant/issues/10852
> Ensure guest names are string when filtering trigger configs

- website/source/layouts/docs.erb
This commit updates the provisioner nav bar on the docs website to
include the common chef configuration documentation. This makes these
options more discoverable, as before it was hidden in a URL link inside
of the other chef docs.
> Fixes #10856: Add common chef config options to nav bar

- website/source/intro/getting-started/providers.html.md
The vagrant-aws provider doesn't really make sense anymore to be
mentioned in the getting started guide for providers. Instead, replace
it with the Hyper-V provider.
> Replace AWS provider in getting started guide with Hyper-V

- lib/vagrant/action/builtin/mixin_synced_folders.rb
- plugins/synced_folders/smb/synced_folder.rb
- test/unit/plugins/synced_folders/smb/synced_folder_test.rb
- test/unit/vagrant/action/builtin/mixin_synced_folders_test.rb
- test/unit/vagrant/util/ssh_test.rb
Removes information from the SMB synced folder data configuration
before persisting details to local data store. Also includes
content scrubbing prior to writing content to file.
> Remove configuration information from SMB synced folder data

- plugins/providers/docker/provider.rb
- test/unit/plugins/providers/docker/provider_test.rb
- test/unit/plugins/providers/virtualbox/provider_test.rb
- test/unit/support/shared/virtualbox_context.rb
A cleanup pull request built off of https://github.com/hashicorp/vagrant/pull/10879
Adds proper unit tests for the docker and virtualbox provider class, and a little bit of cleanup for the `usable?` method for the docker provider.
> Add usability check for docker plus tests

- lib/vagrant/environment.rb
- test/unit/vagrant/environment_test.rb
- test/unit/vagrant/util/ssh_test.rb
Since plugin installation happens when the environment is first
initialized, attempt to determine the provider in use and load
any box provided Vagrantfiles to include any plugin configuration
they may include.
> Support loading plugin information from nested Vagrantfiles

- lib/vagrant/bundler.rb
- lib/vagrant/shared_helpers.rb
- templates/locales/en.yml
When installed outside of the official installer and not running
within a bundler environment, properly activate core dependencies
and properly enforce constraints.
> Handle strict dependency enforcement when installed within system

- website/source/docs/docker/configuration.html.md
- website/source/docs/experimental/index.html.md
- website/source/docs/installation/backwards-compatibility.html.md
- website/source/docs/triggers/configuration.html.md
`docker run    -v $(pwd):/scripts    --workdir=/scripts    nickg/misspell:latest    misspell -w -source=text website/`
> Minor spelling fixes

- plugins/synced_folders/rsync/default_unix_cap.rb
- test/unit/plugins/synced_folders/rsync/default_unix_cap_test.rb
Prior to this commit, if a user specified that their `rsync__excludes`
option was an empty array, Vagrant would treat that as if it included
options inside the array rather than ignoring it. This commit fixes that
by only adding the excludes option when it exists and is not empty.
> Fixes #10869: Remove excludes if array is empty

- plugins/synced_folders/rsync/command/rsync_auto.rb
- plugins/synced_folders/rsync/helper.rb
- test/unit/plugins/synced_folders/rsync/command/rsync_auto_test.rb
- test/unit/plugins/synced_folders/rsync/helper_test.rb
Prior to this commit, the rsync helper expanded all exclude paths that
should be ignored to be full qualified and regexp escaped. However the
Listen gem expects these ignore paths to be relative to the path passed
into the listener, not a full path. This commit fixes that by using the
path given by the user for the `rsync__exclude` option
> Fixes #10895: Use relative paths to machines folder path for Listener

- plugins/provisioners/chef/cap/freebsd/chef_installed.rb
- plugins/provisioners/chef/cap/linux/chef_installed.rb
- plugins/provisioners/chef/cap/omnios/chef_installed.rb
- plugins/provisioners/chef/cap/windows/chef_installed.rb
- plugins/provisioners/chef/provisioner/base.rb
- test/unit/plugins/provisioners/chef/cap/freebsd/chef_installed_test.rb
- test/unit/plugins/provisioners/chef/cap/linux/chef_installed_test.rb
- test/unit/plugins/provisioners/chef/cap/omnios/chef_installed_test.rb
- test/unit/plugins/provisioners/chef/cap/windows/chef_installed_test.rb
Prior to this commit, the chef_installed capability was looking for a
string that has recently changed in newer versions of chef. This commit
fixes that by instead just looking for the right version that was
configured for the chef client, rather than the specific string that
could change again in the future.
> Fixes #10912: Update chef install check for guests

- lib/vagrant/environment.rb
- test/unit/vagrant/environment_test.rb
Neither --provider=hyperv or --provider hyperv works in the latest head.
Provider name should be symbol in guess_provider.
> Fix provider name not work when specified

- lib/vagrant/environment.rb
- lib/vagrant/vagrantfile.rb
- test/unit/vagrant/vagrantfile_test.rb
Allow Vagrantfile#machine_config to load properly when the requested
provider may not be currently available. Update the Environment to
utilize this when searching for plugin information to properly allow
box provided Vagrantfiles to define required plugins.
> Support loading machine configuration without provider validation

- lib/vagrant/environment.rb
- test/unit/vagrant/environment_test.rb
If the local data directory is not available, there will be no
local file to reference. Asking the manager for the full list
of plugins will prevent errors when the local file is unset.
> Fix plugin discovery loading when no data directory is available

- website/source/docs/synced-folders/nfs.html.md
This commit includes the SUSE entry for passwordless sudo when mounting
shared folders with NFS.
> Fixes #10928: Include SUSE for sudoers entry with NFS

- CHANGELOG.md
Also referenced in [this issue](https://github.com/hashicorp/vagrant/issues/10930).
> Fix the date of 2.2.5 release in changelog

- README.md
- website/source/docs/boxes.html.md
- website/source/docs/boxes/base.html.md
- website/source/docs/boxes/format.html.md
- website/source/docs/boxes/info.html.md
- website/source/docs/boxes/versioning.html.md
- website/source/docs/cli/box.html.md
- website/source/docs/cli/init.html.md
- website/source/docs/cli/ssh.html.md
- website/source/docs/hyperv/usage.html.md
- website/source/docs/installation/source.html.md
- website/source/docs/providers/basic_usage.html.md
- website/source/docs/providers/configuration.html.md
- website/source/docs/provisioning/salt.html.md
- website/source/docs/vagrant-cloud/boxes/catalog.html.md
- website/source/docs/vagrant-cloud/boxes/release-workflow.html.md
- website/source/docs/vagrant-cloud/boxes/using.html.md
- website/source/docs/vmware/boxes.html.md
- website/source/docs/vmware/usage.html.md
- website/source/index.html.erb
- website/source/intro/getting-started/boxes.html.md
- website/source/intro/getting-started/index.html.md
- website/source/intro/getting-started/networking.html.md
- website/source/intro/getting-started/project_setup.html.md
- website/source/intro/getting-started/provisioning.html.md
- website/source/intro/getting-started/synced_folders.html.md
- website/source/intro/getting-started/up.html.md
This PR updates the documentation to use `hashicorp/bionic64`
https://app.vagrantup.com/hashicorp/boxes/bionic64
Fixes https://github.com/hashicorp/vagrant/issues/8888
>  Update docs with newly supported hashicorp/bionic64 box

- plugins/providers/docker/action/login.rb
- test/unit/plugins/providers/docker/action/login_test.rb
Prior to this commit, the docker login action assumed that if there was
a password to authenticate with, Vagrant was using a host vm to run
docker. This is likely due to some legacy decisions with how Vagrant
used to manage running docker. This commit fixes that by only grabbing a
host_vm lock if the host_vm is actually in use, otherwise login
normally.
> Fixes #11051: Only use host vm if specified

- lib/vagrant/action/builtin/box_remove.rb
- plugins/commands/box/command/prune.rb
- test/unit/vagrant/action/builtin/box_remove_test.rb
- website/source/docs/cli/box.html.md
Prior to this commit, `vagrant box prune --force` would not prompt a
user to prune Vagrant boxes, even if that box was in use. There was no
way to prune boxes, ignore the prompt, but keep in-use boxes. This
commit adds a new flag that can be combined with `--force`, that will
keep in-use boxes but prune older boxes without prompting the user.
> Fixes #10908: Preserve in-use boxes when force flag is used with prune

- lib/vagrant/action/builtin/mixin_provisioners.rb
- plugins/kernel_v2/config/vm.rb
- plugins/kernel_v2/config/vm_provisioner.rb
- templates/locales/en.yml
- test/unit/vagrant/action/builtin/mixin_provisioners_test.rb
- website/source/docs/experimental/index.html.md
- website/source/docs/provisioning/basic_usage.html.md
This pull request introduces two new experimental configuration options for all provisioners: `before` and `after`. Provisioners that specify one of these options are known as _dependency provisioners_, where as provisioners that don't specify these options are known as _root provisioners_. For a _dependency provisioner_ to run before or after a _root provisioner_, the _root provisioner_ must have a name.
These options allow a user to be explicit about _when_ a provisioner should run, before or after a **named** root provisioner. It also has two shortcut values: `:each` and `:all`.
> Introduce new Provisioner options: before and after

- Vagrantfile
Quick fix to #10484. Logs can be found [here](https://gist.github.com/aielo/d59f144256d80a6477ab071f0acb5ca0).
Summary of changes:
- Updated box to `ubuntu/bionic64`
- Removed `BUNDLER_VER_REQ` and `bundler` install
Its dependency is no longer in `vagrant.gemspec`. Using installation-provided version.
- RVM install via `apt-get` ([ubuntu_rvm](https://github.com/rvm/ubuntu_rvm))
- Next-to-last version of ruby installed
`vagrant.gemspec` sets max version `"< 2.7"`. Therefore, 2.7.0-preview1 was being used.
- Removed `curl` from basic dependencies
It was there just to download the RVM installer script.
- Suppressed `grep` error on `.bash_profile`
File is not expected to exist and will be created anyways.
- Box memory set to 2GB
8 tests were failing due to `Errno::ENOMEM: Cannot allocate …
> [#10484] Fixed Vagrantfile for Vagrant development

- plugins/providers/hyperv/scripts/utils/VagrantVM/VagrantVM.psm1
This is a simple check that may save some debugging time. I don't know whether the change should just encompass an error message here or if this should be another pre-flight check; please let me know if you have any suggestions.
I didn't see any Pester tests or anything similar for these scripts, so I'm assuming this logic isn't tested automatically, but if you think they'd be more helpful than painful to include I'd be happy to add some.
**FYI** - I ran tests locally and several broke, but the same ones broke when I ran them on the tip of `master`, so I'm assuming it's a problem with my local config. (Running them on Windows 10 WSL, Ubuntu 16.04.) The behavior was correct when I manually tested it against an updated local installation.
Error message before:
```
> vagrant up
Bringing …
```
> Fixes issue hashicorp#10973: checks that VMMS WMI reference is null & throws appropriately

- plugins/synced_folders/rsync/helper.rb
- test/unit/plugins/synced_folders/rsync/helper_test.rb
Prior to this commit, due to a fix that ignored `.vagrant` with rsync
helper, it broke the ability to watch for changes in subdirectories when
running the rsync-auto command. This commit puts back some of the helper
methods that were there previously for a given watcher path to ensure
that all files and subdirectories are properly watched and synced.
> Fixes #10966: Ensure all subdirectory files are watched

- plugins/commands/snapshot/command/save.rb
- test/unit/plugins/commands/snapshot/command/save_test.rb
Prior to this commit, if you tried to save a snapshot without giving it
a name, the hyper-v driver would not properly obtain a vm id to save a
snapshot on, resulting in an error. This commit updates the command
snapshot save to hold onto the machines ID in argv rather than `pop` it
off, so that the hyperv driver can obtain the guests id when saving a
snapshot.
> Fixes #11027: Ensure VM id is passed to list snapshots

- plugins/provisioners/ansible/cap/guest/pip/pip.rb
- plugins/provisioners/ansible/config/guest.rb
- plugins/provisioners/ansible/provisioner/guest.rb
- test/unit/plugins/provisioners/ansible/config/guest_test.rb
Prior to this commit, the `pip_install_cmd` option for ansible guest
config was not properly finalized. This commit ensures that if that
value is still UNSET_VALUE, it gets set to empty string in the finalize!
method.
> Fixes #10950: Ensure pip_install_cmd is finalized

- website/source/docs/provisioning/ansible_local.html.md
Need to use ansible_host these days. See https://docs.ansible.com/ansible/2.3/intro_inventory.html deprecation note (it was deprecated in 2.0 apparently)
> ansible_ssh_host in the example is deprecated

- plugins/providers/virtualbox/provider.rb
- test/unit/plugins/providers/virtualbox/provider_test.rb
If VirtualBox is installed but the kernel module is missing or the service is stopped, the usability test should fail without crashing so we can fall back to other providers.
> virtualbox: Fix usability test to reject bad installs without crashing

- plugins/provisioners/file/provisioner.rb
- test/unit/plugins/provisioners/file/provisioner_test.rb
Prior to this commit, if you ran Vagrant in a different current working
directory other than where a current guest machines location is, the
file provisioner would not take into account the machines local dir, and
would instead use the path where Vagrant was invoked to expand the
`source` path option for a file provisioner. This commit fixes that by
passing the root path `machine.env.cwd` when expanding the source dir.
> Ensure relative path for file provisioner is relative to machines cwd

- plugins/providers/docker/action/build.rb
- plugins/providers/docker/driver/compose.rb
- test/unit/plugins/providers/docker/driver_compose_test.rb
Prior to this commit, the docker compose build method would not properly
set build_args if given in a Vagrantfile. This commit fixes that by
using the passed in key `extra_args` from the docker build action.
> Ensure build_args are passed into docker compose config file

- plugins/guests/suse/cap/change_host_name.rb
- test/unit/plugins/guests/suse/cap/change_host_name_test.rb
`hostname` isn't part of the boxes openSUSE currently provides. As openSUSE and SLE are using `systemd` quite a while, setting the hostname using `hostnamectl` should be fine.
Without this fix, the _transient hostname_ will stay on localhost until the VM is restarted.
I've tested this change against openSUSE Leap 15.0, Leap 15.1 and Tumbleweed using this Vagrantfile:
```ruby
config.vm.define "Leap15-0" do |sut|
sut.vm.box = "Leap-15.0.x86_64"
sut.vm.box_url = "https://download.opensuse.org/repositories/Virtualization:/Appliances:/Images:/openSUSE-Leap-15.0/images/boxes/Leap-15.0.x86_64.json"
sut.vm.hostname = "leap15-0.example.com"
end
config.vm.define "Leap15-1" do |sut|
sut.vm.box = "Leap-15.1.x86_64"
sut.vm.box_url = …
```
> Use hostnamectl instead of hostname to set the hostname under SUSE

- lib/vagrant/action/builtin/box_add.rb
- lib/vagrant/util/downloader.rb
- lib/vagrant/util/file_checksum.rb
- plugins/commands/cloud/provider/create.rb
- plugins/commands/cloud/provider/update.rb
- plugins/commands/cloud/publish.rb
- plugins/provisioners/shell/config.rb
- plugins/provisioners/shell/provisioner.rb
- test/unit/plugins/commands/cloud/provider/create_test.rb
- test/unit/plugins/commands/cloud/provider/update_test.rb
- test/unit/plugins/provisioners/shell/provisioner_test.rb
- test/unit/vagrant/util/downloader_test.rb
- test/unit/vagrant/util/file_checksum_test.rb
- vagrant.gemspec
- website/source/docs/cli/box.html.md
- website/source/docs/provisioning/shell.html.md
- website/source/docs/vagrantfile/machine_settings.html.md
Consolidate all checksum usage within the FileChecksum utility
and provide all digests supported by the standard lib. Update
Downloader to use FileChecksum. Add support for setting checksum
information on boxes in Vagrant Cloud.
_NOTE:_ Requires release of vagrant_cloud update which includes
hashicorp/vagrant_cloud#51
> Extend checksum support for box validation and remote files

- plugins/guests/suse/cap/nfs_client.rb
- plugins/hosts/suse/cap/nfs.rb
- test/unit/plugins/guests/suse/cap/nfs_client_test.rb
- `nfs.service` got recently removed in openSUSE Tumbleweed and calling `service restart nfs` errors out on Tumbleweed. `nfs.service` has been an alias to `nfs-client.target` for a very long time and can thus be safely substituted.
- all actively supported versions of openSUSE & SLE are using systemd now => no reason not to use `systemctl`
Something comparable has to be done for the corresponding files in `RedHat` to address #10838. cc @pvalena
> Update nfs & service daemon names for suse based hosts

- plugins/providers/docker/action/prepare_networks.rb
- test/unit/plugins/providers/docker/action/prepare_networks_test.rb
Prior to this commit, the docker action was using the method `prefix` on
an IPv4 and IPv6 address. This works fine for ruby versions 2.5 and
newer, however the ruby shipped with Vagrant is before 2.5, and
therefore the IPv4 and IPv6 classes do not have the prefix method,
resulting in an error. This commit fixes that by using a different
method of determining the prefix.
> Fixes #11094: Determine prefix for docker public networks

- plugins/hosts/bsd/cap/nfs.rb
- plugins/hosts/bsd/cap/path.rb
- plugins/hosts/bsd/plugin.rb
- plugins/hosts/darwin/cap/path.rb
- plugins/hosts/darwin/plugin.rb
- test/unit/plugins/hosts/bsd/cap/nfs_test.rb
- test/unit/plugins/hosts/bsd/cap/path_test.rb
- test/unit/plugins/hosts/darwin/cap/path_test.rb
This is a continuation of the work started in #11105
The firmlinks defined on the system can be located within
a system file (/usr/share/firmlinks). This can be read to
generate a simple map that can then be used for updating
paths as required.
Added a new host capability (resolve_host_path) which is
used by the bsd host nfs_export capability. The bsd host
implements this capability as a no-op, and the darwin
host implements this capability to handle firmlinks.
> Fix NFS sharing in macOS 10.15 (based on #11105)

- website/source/intro/getting-started/provisioning.html.md
Some users have had trouble in the getting started guide as the provisioned web server returned a 404.
> update getting started guide - provision

- plugins/commands/snapshot/command/save.rb
- templates/locales/en.yml
- test/unit/plugins/commands/snapshot/command/save_test.rb
This commit fixes the original #11027 fix, which assumed that the
hyper-v provider just wasn't properly getting a VM id when it listed
snapshots. In reality, it was just that if you invoke the
`with_target_vm` method with no arguments, it runs on the entire environment.
This meant that the capability snapshot_list attempted to be invoked on
machines that didn't exist yet, which is the original cause for why the
list_snapshot method did not recieve a vm ID. This commit fixes that by
simply skipping the machine if it does not yet exist.
> Fixes #11139: Skip machines that haven't been created for snapshot save

- plugins/guests/suse/cap/change_host_name.rb
- test/unit/plugins/guests/suse/cap/change_host_name_test.rb
getent queries the system resolver for the hostname - but it's not
the resolver we're interested in. In fact, the hostname-to-be-set
may already exist in DNS (becuase DNS really is a nifty thing and
can do a lot of things which are not that possible with /etc/hosts
alone), in which case getent will "not fail" and vagrant will believe
the hostname had already been set.
Instead, query hostnamectl for the "static" hostname - that's the
one we will be setting, so we're ok IFF hostnamectl returns exactly
what we would be setting.
> explicitly test the hostname we'll be setting

- plugins/hosts/linux/cap/nfs.rb
- test/unit/plugins/hosts/linux/cap/nfs_test.rb
Check for `modinfo` in /sbin if it doesn't appear on the PATH -- this could be expanded to scan other directories as well.
If it's not found on the PATH or in /sbin, the command will default back to `modinfo` so the user sees the error message about adding it to their PATH.
> Fixes #10170: Check for modinfo in /sbin

- plugins/kernel_v2/config/vm.rb
- templates/locales/en.yml
This commit adds the machine guest name in the hostname validation error
message so that it's easier to see which guest in a Vagrantfile has the
validation error.
> Fixes #11173: Show guest name in hostname error message

- vagrant.gemspec
The RubyGems gemspec property `rubyforge_project` has been removed without a replacement.
> gemspec: drop rubyforge_project, it is EOL

- lib/vagrant/ui.rb
- test/unit/vagrant/ui_test.rb
When using a Prefixed UI instance prevent new line characters from
being removed when adding prefix formatting to output messages.
Fixes #11044
> Update UI to properly retain newlines when adding prefix

- lib/vagrant/action/builtin/box_check_outdated.rb
- test/unit/vagrant/action/builtin/box_check_outdated_test.rb
Check the local box collection to see if the latest box update has already been downloaded.  If it has, don't show the "run vagrant update" message.
> Fixes #10741: Check if update is available locally

- vagrant.gemspec
Loosen dependency constraints on the i18n library to allow
versions under 2.0.
> Update i18n dependency constraints

- vagrant.gemspec
rspec-its version 1.3.0 has been released, this PR updates the gemspec to use the latest version.
> Bump rspec-its dependency

- lib/vagrant/util/file_checksum.rb
- test/unit/vagrant/util/file_checksum_test.rb
Prior to this commit, the file_checksum class used the `Vagrant::Errors`
class as if it were apart of the Vagrant module. However, since the
file_checksum class is an interface and not part of the Vagrant module,
it doesn't have access to that Error class like other Vagrant modules.
This commit fixes that by ensuring the `"vagrant/errors"` class is
loaded, and that the proper namespace is used.
> Fixes #11179: Ensure Vagrant::Errors are loaded in file_checksum util

- plugins/commands/cloud/publish.rb
- test/unit/plugins/commands/cloud/publish_test.rb
Prior to this commit, if a user didn't supply a box file on disk or a
box url, Vagrant would crash and display a stacktrace with an invalid
file. This commit fixes that by adding some extra handling around the
arguments supplied to the publish command.
> Fixes #11137: Fixup how cloud publish handles its arguments

- vagrant.gemspec
https://github.com/advisories/GHSA-5m2v-hc64-56h6
~~Perhaps we should bump it to v2.0.0 instead?~~ https://rubygems.org/gems/rubyzip
> Bump rubyzip to v1.3.0 to fix CVE-2019-16892

- lib/vagrant/box_metadata.rb
- plugins/commands/box/command/outdated.rb
- test/unit/plugins/commands/box/command/outdated_test.rb
- test/unit/vagrant/box_metadata_test.rb
- website/source/docs/cli/box.html.md
This commit changes the behavior of `vagrant box outdated --global` so
it gets the latest version for the current machine's provider, rather
than the latest version for any provider.
> Fixes #11163: Get latest version for provider

- plugins/commands/box/command/outdated.rb
This commit fixes an issue where Gem::Version.new could recieve a nil
value if no addtional box updates are available. For some versions of
ruby, this is actually an error case. This commit fixes that by
converting it to an integer to prevent an exception.
Issue reference: https://github.com/rubygems/rubygems/issues/2359
> Fixup: Ensure Gem::Version.new does not receive nil value

- plugins/guests/linux/cap/reboot.rb
- plugins/guests/linux/plugin.rb
- test/unit/plugins/guests/linux/cap/reboot_test.rb
This commit adds support for setting `reboot: true` while using the
shell provisioner with Linux guests.
> Fixes #10753: Add reboot support for Linux guests

- website/source/docs/provisioning/shell.html.md
This commit adds an additional example for how to preserve quotes in a
script that uses heredocs.
> Fixes #11196: Add more examples for ruby heredoc shell scripts

- plugins/hosts/linux/cap/nfs.rb
- test/unit/plugins/hosts/linux/cap/nfs_test.rb
StringBlockEditor already adds the necessary newlines. That extra
newline was making /etc/exports longer and longer, full of empty lines,
because StringBlockEditor doesn't know about it and does not remove it.
> nfs: avoid adding extra newlines to /etc/exports

- plugins/guests/redhat/cap/nfs_client.rb
- test/unit/plugins/guests/redhat/cap/nfs_client_test.rb
This pull request is a fixup of the original pull request https://github.com/hashicorp/vagrant/pull/11133, which ensures that `nfs-server` is restarted when installing the nfs client on redhat guests, rather than `nfs`, which is no longer valid for redhat guests that use systemd with systemctl.
Fixes #10838
> Ensure `nfs-server` is restarted when installing nfs client for redhat guests

- lib/vagrant/action/builtin/box_add.rb
- lib/vagrant/util/file_checksum.rb
- templates/locales/en.yml
- test/unit/vagrant/action/builtin/box_add_test.rb
Prior to this commit, if Vagrant received checksum options from Vagrant
Cloud that were simply empty strings, it would try to validate its
checksum with those options. This commit fixes that by ignoring empty
string values.
> Fixes #11207: Do not validate checksums if options are empty string

- plugins/providers/docker/driver.rb
- plugins/providers/docker/errors.rb
- plugins/providers/docker/executor/local.rb
- templates/locales/providers_docker.yml
- test/unit/plugins/providers/docker/driver_test.rb
Prior to this pull request, docker would look for a container ID based on
"Successfully built" string. This output does not exist if a user has
enabled the experimental feature `buildkit`. This commit updates the build
behavior to match against both kinds of outputs, and instead of using
`scan`, it uses MatchData and groups the container id with match group
name `:id` instead of making hard assumptions with the matches being
contained inside arrays from scan.
This is an enhancement based off of https://github.com/hashicorp/vagrant/pull/11197
> Enhance docker build method for the Docker provider to include buildkit output

- lib/vagrant/action.rb
- lib/vagrant/action/builtin/disk.rb
- lib/vagrant/util/numeric.rb
- plugins/kernel_v2/config/disk.rb
- plugins/kernel_v2/config/vm.rb
- plugins/providers/virtualbox/action.rb
- templates/locales/en.yml
- test/unit/plugins/kernel_v2/config/disk_test.rb
- test/unit/plugins/kernel_v2/config/vm_test.rb
- test/unit/vagrant/util/numeric_test.rb
- website/source/docs/disks/configuration.html.md
- website/source/docs/disks/index.html.md
- website/source/docs/disks/usage.html.md
- website/source/layouts/docs.erb
This pull request adds a basic `disk` config option to Vagrant core that will allow providers to consume a config and manage a guests disk options. Similar to the provisioners, it has a few base options that all disks likely will need, but allows for more provider specific options with a `config` which will be implemented by each provider. Ideally in a Vagrantfile, a guests disk config block should be provider agnostic, unless there are some provider specific options that need to be set when configuring a disk.
By default, a new disk block is a non-primary disk that will be attached to the guest. If a user wishes to modify the primary disk attached to the guest, they can add the option `primary: true` to a disk config block.
```ruby
config.vm.define …
```
> Introduce disk management base config layer to core Vagrant

- plugins/hosts/darwin/cap/nfs.rb
- plugins/hosts/darwin/plugin.rb
- templates/nfs/exports_darwin.erb
- test/unit/plugins/hosts/darwin/cap/nfs_test.rb
- test/unit/templates/nfs/exports_darwin_test.rb
This PR implements the workaround for NFS issues with macOS Catalina mentioned here: https://github.com/hashicorp/vagrant/issues/11144#issuecomment-557085624.
Tested on macOS Mojave (10.14.6) and macOS Catalina (10.15.1).
It seems to resolve mount issues/timeouts in guests as well as `nfsd` service on host exiting due to SIGSEGV.
> Darwin: put each NFS export on its own line

- contrib/bash/completion.sh
I noted the `--provision` option which I currently needed (to retry an Ansible playbook that had failed) was missing, so I added this along with all other options I could find. They are ordered in the same order as they are listed in the `--help` output.
> completion.sh: add more up options

- templates/commands/init/Vagrantfile.erb
- website/source/index.html.erb
Having these provisioners not alphabitized on the website and
Vagrantfile, seemed odd. This reorders them to be consistent.
Signed-off-by: JJ Asghar <jjasghar@gmail.com>
> Alphabiztize the Website and template

- plugins/providers/virtualbox/driver/meta.rb
- plugins/providers/virtualbox/driver/version_6_1.rb
- plugins/providers/virtualbox/plugin.rb
- website/source/docs/virtualbox/index.html.md
This commit adds support for VirtualBox version 6.1.x. It simply
inherits from the base 6.0.x provider class.
> Fixes #11249: Add VirtualBox provider support for version 6.1.x

- lib/vagrant/action/builtin/box_check_outdated.rb
- plugins/commands/box/command/outdated.rb
- test/unit/plugins/commands/box/command/outdated_test.rb
- test/unit/vagrant/action/builtin/box_check_outdated_test.rb
- website/source/docs/cli/box.html.md
Prior to this commit, if a user had recently checked for updates, there
was no way to force Vagrant to re-check without manually deleting a
state file in the local `.vagrant` data dir. This commit fixes that by
giving users the ability to force check for updates for a given box with
a flag to the `vagrant box outdated` command.
> Fixes #11228: Allow to force check for box updates

- lib/vagrant/errors.rb
- plugins/providers/virtualbox/action/clean_machine_folder.rb
- templates/locales/en.yml
- test/unit/plugins/providers/virtualbox/action/clean_machine_folder_test.rb
- website/source/docs/other/macos-catalina.html.md
This commit catches the Errno::EPERM raised by the operating system if
the machine folder is inaccessible and displays it as a more friendly
error message.
This can be an issue on macOS Catalina if virtual machine files are kept
in a special directory (Documents/Downloads/Desktop) that Vagrant's
embedded Ruby is not allowed to access.
> Fixes #11128: Error if machine folder inaccessible

- plugins/provisioners/ansible/cap/guest/debian/ansible_install.rb
- plugins/provisioners/ansible/cap/guest/ubuntu/ansible_install.rb
Sets `DEBIAN_FRONTEND=noninteractive` and tells `dpkg` to take the old version of config files when installing Ansible, to prevent hangs waiting for user input.
Fixes #10914
I hope you don't mind my picking this up @gildegoma - I've had this branch sat around from a while ago when I happened to have some spare time and had figured out where the changes were
> Don't prompt for input when installing Ansible

- lib/vagrant/action/builtin/disk.rb
- test/unit/vagrant/action/builtin/disk_test.rb
Prior to this commit, even if a machine had no disk config, the disk action would print a warning saying the feature is unsupported. This commit fixes that by only checking the configure_disk capability if there are any disks to configure. Otherwise, it continues on the action stack and ignores any disk configuring steps.
> Return if no disk config

- lib/vagrant/action/warden.rb
- plugins/guests/darwin/cap/mount_vmware_shared_folder.rb
- test/unit/plugins/guests/darwin/cap/mount_vmware_shared_folder_test.rb
- test/unit/vagrant/action/warden_test.rb
Properly enables synced folders on APFS by creating
firmlinks when required to work around readonly root
file system.
> Update synced folder setup in darwin cap for vmware

- lib/vagrant/util/is_port_open.rb
- test/unit/vagrant/action/builtin/handle_forwarded_port_collisions_test.rb
- test/unit/vagrant/util/is_port_open_test.rb
This reverts commit 81553263ab812a7fd0a2ab0f627bee139ad6397c.
This fixes a regression with Windows port detection which led to port
collisions not being fixed on `vagrant up`.
PR #8517 changed `IsPortOpen#is_port_open?` to rescue
Errno::EADDRNOTAVAIL, but there is code
in `HandleForwardedPortCollisions#port_check` that depends on that
error bubbling up.
This PR also changes the port number in the HandleForwardedPortCollisions
tests to be a less common port number -- some of these tests will fail
if there is a local process running on port 8080.
> Fixes #11236: Windows port detection

- lib/vagrant/action/builtin/ssh_run.rb
- test/unit/vagrant/action/builtin/ssh_run_test.rb
- website/source/docs/vagrantfile/ssh_settings.html.md
- website/source/docs/vagrantfile/winssh_settings.html.md
This PR changes the behavior of the builtin `SSHRun` action to use a Windows shell if the WinSSH communicator is active.
By default, this will be `cmd`, but it can be overridden by setting the `config.winssh.shell` setting in a Vagrantfile.
Example usage:
```
vagrant ssh -c dir
```
```
vagrant ssh -c 'dir "c:\program files"'
```
> Use WinSSH shell for `vagrant ssh -c`

- lib/vagrant/action/builtin/mixin_provisioners.rb
- plugins/kernel_v2/config/vm_provisioner.rb
- test/unit/vagrant/action/builtin/mixin_provisioners_test.rb
- test/unit/vagrant/action/builtin/provision_test.rb
Prior to this commit, if a user had configured a provisioner that had a
config with a `name` option, it would not properly set the top level
provisioner classes name config option which would lead to some
understanibly confusing results when trying to `--provision-with`. This
commit fixes that by checking to see if the top level name isn't set,
look to see if that provisioners config defines a name, and use that
instead.
> Fixes #11287: Set top level provisioner name if set in provisioner config

- lib/vagrant/action/builtin/mixin_provisioners.rb
Prior to this commit, the check used to look for the config option
`name` in a provisioner config would accidentally create a "DummyConfig"
based on how vagrant handles missing config options. This commit fixes
that by instead using the `respond_to?` method to check for the
existance of the config option name.
> Check name config option with respond_to?

- website/source/docs/provisioning/ansible_intro.html.md
VagrantFile\` -> \`VagrantFile\`
Signed-off-by: 林博仁(Buo-ren, Lin) <Buo.Ren.Lin@gmail.com>
> Fix missing quoting for `VagrantFile`

- .hashibot.hcl
This commit adds Hashibot support to lock closed issues after 30 days.
~It also will automatically remove the `waiting-reply` tag if a user
replies to an issue with that tag.~
> Lock closed issues after 30 days

- website/source/docs/provisioning/ansible.html.md
- website/source/docs/provisioning/ansible_intro.html.md
- website/source/layouts/docs.erb
This commit adds some extra nav links for important Ansible
documentation that was burried in the other doc pages.
/cc @Lin-Buo-Ren
> Include important Ansible docs in side navbar

- .github/workflows/build.yml
This commit adds a check to see if push is happening against the main
Vagrant repo. If not, it will skip the build-gem job.  This prevents
people from getting failure notifications when they push to the master
branch of their Vagrant fork.
> Don't build gem on Vagrant forks

- plugins/kernel_v2/config/vm.rb
- templates/locales/en.yml
Prior to this commit, Vagrant wouldn't validate the `type` option for
any synced_folder configs defined. This commit updates that behavior to
look at the current list of installed synced_folder plugins, and ensure
if a type is defined, it's a valid plugin in that list.
> Fixes #11358: Actually validate synced_folder type options

- test/vagrant-spec/Vagrantfile.spec
- test/vagrant-spec/readme.md
- test/vagrant-spec/scripts/ubuntu-setup.virtualbox.sh
This pull request improves the README for how to run the acceptance tests with `vagrant-spec`. It also improves the Vagrantfile used to run these tests to allow for some looser requirements when using different Vagrant boxes. Finally, if the host is Ubuntu, it ensures that nfs-kernel-server is installed, as it is a requirement for several of the tests.
Related (but not blocking) PR: https://github.com/hashicorp/vagrant-spec/pull/30
> Update vagrant-spec docs and Vagrantfile

- website/Gemfile
- website/Gemfile.lock
- website/Makefile
Update middleman-hashicorp@0.3.43 to deploy copy change - “HashiCorp Suite” -> “HashiCorp Stack”
> Website: bump middleman version

- website/source/docs/vagrantfile/ssh_settings.html.md
This commit adds more detail to the documentation for `config.ssh.verify_host_key`. Currently, the documentation only mentions the default value but does not provide any hints as to what valid values exist, or where this value is being passed to. As I'm sure you know, this is ultimately passed to the `net-ssh` library. It would have saved me some time doing searches to have read this fact in the Vagrant docs directly.
Thanks for considering this expansion.
> Detail other valid values for `config.ssh.verify_host_key`.

- lib/vagrant/util/guest_inspection.rb
- test/unit/plugins/guests/debian/cap/configure_networks_test.rb
- test/unit/vagrant/util/guest_inspection_test.rb
This change allows the vagrant user to see the systemd process in the
event that the hidepid mount option is enabled.
> Fix #11396: Use sudo to detect if systemd in use

- plugins/providers/virtualbox/driver/version_6_1.rb
- test/unit/plugins/providers/virtualbox/base.rb
- test/unit/plugins/providers/virtualbox/driver/version_6_0_test.rb
- test/unit/plugins/providers/virtualbox/driver/version_6_1_test.rb
- test/unit/plugins/providers/virtualbox/support/shared/virtualbox_driver_version_6_x_examples.rb
This commit creates a custom `read_dhcp_servers` method in the
VirtualBox 6.1 driver to handle changes made in the ouput of
`VBoxManage list dhcpservers`.
Tests for VirtualBox 6.1+ can no longer use the shared examples for the
VirtualBox 4.x driver, because the `read_dhcp_servers` change is not
backwards compatible.
This commit also creates the boilerplate for a VirtualBox 6.x shared
example in case we want to put tests there in the future.
> Fix #11403: Parse `list dhcpservers` output on VirtualBox 6.1

- website/source/docs/docker/networking.html.md
Vagrant throws this error when I tried to run this block of code.
```
syntax error, unexpected tIDENTIFIER, expecting keyword_endate_network, type: "dhcp" name: "my-custom-network"
```
After I added a comma, all starts to work correctly.
> Missed comma in configuration file

- plugins/communicators/winrm/shell.rb
- test/unit/plugins/communicators/winrm/shell_test.rb
- vagrant.gemspec
Fixes hangs encountered when running elevated commands and updates
the exit code to match with ArgumentException.
Relies on: winrb/winrm-elevated#33
> Update exit code value used for retry check - ArgumentException

- website/source/docs/virtualbox/networking.html.md
Although it has been possible to specify a specific VirtualBox host-only network
to attach a machine's NIC to, this was never mentioned by the documentation in
the VirtualBox provider's networking section. I had to spelunk through the issue
tracker to find an example of this.
This patch adds a code example along with a short description of the ability in
human language prose, and a link to the relevant section in the VirtualBox User
Manual about "Host-Only Networking."
> Document ability to specify which host-only network.

- templates/nfs/exports_darwin.erb
- test/unit/templates/nfs/exports_darwin_test.rb
This commit changes the Darwin NFS template for /etc/exports to put each
exported directory in quotes.
This fixes an issue with directory names that have spaces in them.
Quotes were chosen (rather than escaping the spaces) in order to match
the template for Linux NFS exports.
> Fix #11439: Quote each exported directory

- lib/vagrant/action.rb
- lib/vagrant/action/warden.rb
- lib/vagrant/plugin/v2/manager.rb
- plugins/guests/darwin/cap/mount_vmware_shared_folder.rb
- plugins/guests/darwin/plugin.rb
- test/unit/plugins/guests/darwin/cap/mount_vmware_shared_folder_test.rb
- test/unit/vagrant/action/warden_test.rb
- test/unit/vagrant/plugin/v2/manager_test.rb
Updates dynamic action hooks implementation to fetch
defined action hooks and properly apply them to an
action which is to be run. This prevents the generation of
new actions and allows proper injection via the Hook
class.
Fixes #11401
> Update dynamic action hooks implementation

- plugins/guests/windows/cap/reboot.rb
- test/unit/plugins/guests/windows/cap/reboot_test.rb
This prevents any unexpected connection related error from breaking
the wait loop while windows reboots. If an underlying problem unrelated
to the guest is causing exceptions, the exception will still be raised
to the user, simply after the loop has exceeded the defined maximum
wait time.
Fixes #11238
> Catch any StandardError exception while waiting for Windows reboot

- lib/vagrant/util/downloader.rb
- test/unit/vagrant/util/downloader_test.rb
curl ignores -q if it's not the first option.  Thus, prior to this
change, curl configuration file is used while performing HEAD request.
> Fix use of -q option in curl invocation

- lib/vagrant/bundler.rb
- lib/vagrant/plugin/manager.rb
- test/unit/vagrant/bundler_test.rb
- test/unit/vagrant/plugin/manager_test.rb
This pull request adds an enhancement to the internal Bundler class
to cache solution sets. This prevents Vagrant from generating a
solution for configured plugins on every run. Modifications to
the configured plugin list (global or local) will result in the
cached solution being invalidatd and resolved again.
Initially reported in #11142, reproduction was difficult until
adding the `aws-sdk` which include a large number of dependencies.
Timing for initial run without solution set:
```
$ time vagrant
...
real    0m12.213s
user    0m11.285s
sys     0m0.617s
```
Timing for run with solution set:
```
$ time vagrant
...
real    0m2.483s
user    0m1.730s
sys     0m0.622s
```
Also included is the removal of the GEMRC modifications required
for Windows (won't be required for next release due to …
> Add support for caching solutions. Remove GEMRC modifications.

- lib/vagrant/bundler.rb
- lib/vagrant/errors.rb
- templates/locales/en.yml
- test/unit/vagrant/bundler_test.rb
This fixes an issue where the vagrant specification may not be
activated in certain cases (like using `github:` option for
gem entry in a Gemfile). When no vagrant specification is
currently activated, activate before loading runtime dependencies.
Fixes #10945
> Explicitly activate vagrant specification when not activated

- bin/vagrant
This will restrict output of warnings for things like method
deprections to only being visble while running a pre-release
version of Vagrant (typically in development)
> When not running as a pre-release version, disable verbose output

- plugins/providers/docker/driver.rb
- test/unit/plugins/providers/docker/driver_test.rb
Output from recent Docker has changed:
Stderr: Error response from daemon: conflict: unable to delete 0ba49dd235e5 (cannot be forced) - image is being used by running container 250bbe980448
Fixes #7245
> docker provider: Don't explode when removing an image if it is in use

- bin/vagrant
- lib/vagrant.rb
- lib/vagrant/plugin/v2/command.rb
- lib/vagrant/shared_helpers.rb
- test/unit/bin/vagrant_test.rb
- test/unit/vagrant/shared_helpers_test.rb
Adds method to shared helpers for adding procs to be evaluated
which can add default modifications to the option parser used
by commands. Customized option parser class within Vagrant
handles processing defined procs.
> Include default options in option parser

- plugins/hosts/linux/cap/nfs.rb
- test/unit/plugins/hosts/linux/cap/nfs_test.rb
This is a workaround to fix #10591.
I'm not completely sure if this is a proper one - there might be something wrong with my network setup / other code that propagates `ips` array with duplicate addresses - maybe that other code should be fixed instead, but at least this prevents Vagrant from creating duplicate entries in my `/etc/exports` file.
> Make sure that ips array contains unique values

- plugins/providers/docker/driver.rb
- test/unit/plugins/providers/docker/driver_test.rb
When user is using podman's docker CLI emulation the containers would
fail to enter running state because the docker driver could not catch
the container name. This commit fixes that by adding a check if podman
docker emulation is used and pick the container hash correctly from the
output.
> Docker provider: catch container name when using podman.

- lib/vagrant/action/builtin/handle_forwarded_port_collisions.rb
- lib/vagrant/errors.rb
- templates/locales/en.yml
- test/unit/vagrant/action/builtin/handle_forwarded_port_collisions_test.rb
This commit changes the behavior of the port check to check all possible
IPv4 network interfaces on a Windows host when the host IP is unset or
`0.0.0.0`.  This means that if the desired port is available on any
network interfaces, a forward from 0.0.0.0 will use that interface.
If the port is open (in use) on all interfaces, then it's treated as a
collision and will either throw an error or auto-correct the port, based
on the Vagrantfile configuration.
> Fix #11373: Check all interfaces for port collisions

- .hashibot.hcl
If the last activity on the issue is more than 180 days,
only lock the issue and do not leave comment.
> Do not comment when locking really old issues

- vagrant.gemspec
childprocess v 1.x includes a fix for encoding on Windows
https://github.com/enkessler/childprocess/pull/134
This was previously causing errors on Windows hosts
> Update childprocess gem

- bin/vagrant
- lib/vagrant/ui.rb
- lib/vagrant/util/curl_helper.rb
- plugins/providers/hyperv/action/export.rb
- plugins/providers/virtualbox/action/export.rb
- plugins/providers/virtualbox/action/import.rb
- plugins/providers/virtualbox/action/prepare_clone_snapshot.rb
- plugins/providers/virtualbox/action/snapshot_delete.rb
- plugins/providers/virtualbox/action/snapshot_restore.rb
- test/unit/bin/vagrant_test.rb
- test/unit/vagrant/ui_test.rb
- test/unit/vagrant/util/downloader_test.rb
fixes https://github.com/hashicorp/vagrant/issues/11414
Putting this up as an idea. Not sure if I really like the implementation. A couple of questions:
- should vagrant just throw out the whole output when the `--quiet` flag is used?
- are there any instances where the output should be "quiet" but there still needs to be information returned to the user?
- should the `--quiet` flag exist globally, or does it make sense for only some commands to have a quiet option
> Quiet cli option

- plugins/provisioners/ansible/cap/guest/alpine/ansible_install.rb
- plugins/provisioners/ansible/plugin.rb
- test/unit/plugins/provisioners/ansible/cap/guest/alpine/ansible_install_test.rb
This PR adds capability for Alpine guest for Ansible provisioner installation.
Some notes:
* Ansible version installed via Package manager depends on Alpine guest version
* Use Python3 for any installation mode
> Alpine capability for Ansbile support

- plugins/guests/darwin/plugin.rb
With the adjustments provided in #11455 the location of injecting
within the call stack has been changed slightly. With the entire
stack now being generated before execution instead of dynamic
hooks being wrapped around actions at run time, this update
ensures that the method is called correctly after the entirety of
the synced folders action has completed.
> Adjust when the hook action is performed

- plugins/providers/hyperv/scripts/utils/VagrantVM/VagrantVM.psm1
Some IdentityReferences cannot be translated to
[System.Security.Principal.SecurityIdentifier] because they don't map to
a SecurityIdentifier.
An example is:
`IdentityReference : APPLICATION PACKAGE AUTHORITY\ALL APPLICATION PACKAGES`
In such case, it is better to catch the exception and treat it as `$false.`
> Fix #11271: catch IdentityNotMappedException

- plugins/provisioners/salt/provisioner.rb
- test/unit/plugins/provisioners/salt/provisioner_test.rb
As the feature is supported by bootstrap-salt.sh
https://github.com/saltstack/salt-bootstrap#python-3-support
> Allow to specify python_version

- plugins/provisioners/shell/provisioner.rb
- test/unit/plugins/provisioners/shell/provisioner_test.rb
When using the winrm provisioner with the inline option, the default script created by Vagrant doesn't always get an extension. This will break execution on windows. For example, with the Vagrantfile:
```
config.vm.box = 'StefanScherer/windows_10'
config.vm.provision :shell, :inline => 'New-Item C:\testfile3.txt -ItemType file', :powershell_elevated_interactive => true
end
```
The result of running `vagrant up` is
```
==> default: Running provisioner: shell...
default: Running: inline PowerShell script
The following WinRM command responded with a non-zero exit status.
cmd /q /c "C:\tmp\vagrant-shell"
'C:\tmp\vagrant-shell' is not recognized as an …
```
> Ensure windows files get an extension

- plugins/providers/virtualbox/driver/version_5_0.rb
- test/unit/plugins/providers/virtualbox/support/shared/virtualbox_driver_version_5_x_examples.rb
If the VirtualBox guest property `/VirtualBox/GuestInfo/Net/1/V4/IP`
returns an IP address ending in .1, raise an exception.
This addresses an issue that was revealed as an NFS error, where Vagrant
was creating an exports file with the wrong IP address. This was thought
to be caused by the presence of a docker0 interface, but it manifested
itself even without Docker installed.
This issue is difficult to reproduce, but hopefully this PR will get us
closer to the root cause.
> Fix #8704: Raise an exception if the guest IP ends with .1

- lib/vagrant/machine.rb
- plugins/commands/ssh_config/command.rb
- plugins/communicators/ssh/communicator.rb
- plugins/kernel_v2/config/ssh_connect.rb
- templates/locales/en.yml
- test/unit/plugins/communicators/ssh/communicator_test.rb
- test/unit/plugins/kernel_v2/config/ssh_connect_test.rb
- test/unit/vagrant/machine_test.rb
- website/source/docs/vagrantfile/ssh_settings.html.md
Retains the original default value of 15 seconds for SSH connect
timeout. Allows users to modify this timeout via SSH communicator
option. Enforces integer values for timeout and validates custom
values are greater than 0.
Fixes #11442 
Possibly fixes #9104
> Add support for configuring SSH connect timeout

- website/source/docs/providers/default.html.md
The docs state that `vmware_desktop` is the common provider name when using the latest VMWare plugin. Updating this entry to match.
> Updated default provider variable to use latest

- plugins/guests/debian/cap/configure_networks.rb
- test/unit/plugins/guests/debian/cap/configure_networks_test.rb
This checks that systemd_networkd service is active and
in use when setting the renderer instead of checking for
the networkd executable availability.
> Use #systemd_networkd? guest check for renderer

- plugins/provisioners/shell/provisioner.rb
- test/unit/plugins/provisioners/shell/provisioner_test.rb
This commit fixes a couple of issues when the WinSSH shell is set to
cmd:
- A check for the .bat extension returned by File.extname
- Execute inline scripts with PowerShell when upload_path ends with .ps1
> Fix issues with inline provisioner when WinSSH shell is set to cmd

- lib/vagrant/action/builtin/box_add.rb
- lib/vagrant/action/builtin/handle_box.rb
- lib/vagrant/util/downloader.rb
- lib/vagrant/util/map_command_options.rb
- plugins/kernel_v2/config/vm.rb
- templates/locales/en.yml
- test/unit/vagrant/util/downloader_test.rb
- test/unit/vagrant/util/map_command_options_test.rb
- website/source/docs/vagrantfile/machine_settings.html.md
fixes https://github.com/hashicorp/vagrant/issues/11546
Allow users to specify a map of extra options to pass to the downloader
> Add option `box_download_options`

- lib/vagrant/bundler.rb
Sets prerelease on the request set based on Vagrant's version. This
allows installing plugins which may include a vagrant version constraint
when running on a development version without needing to a manual local
installation of the gem.
> Allow prerelease matches when Vagrant is a prerelease version

- lib/vagrant/util/io.rb
- test/unit/vagrant/util/io_test.rb
When converting encoding to UTF-8 on Windows, allow for unknown
conversions to be properly handled and prevent generating an
error.
Fixes #10872 #11568
> Update IO util to properly handle unknown conversion errors

- lib/vagrant/bundler.rb
- lib/vagrant/errors.rb
- lib/vagrant/plugin/manager.rb
- templates/locales/en.yml
- test/unit/vagrant/plugin/manager_test.rb
During a plugin install, if the plugin is already installed and
activated, no specification will be returned as there was nothing
new installed. In this situation, look for the requested plugin
within the activated specifications. If it is found, then proceed
since the plugin is installed. If it is not found, return an error.
Fixes #11590
> Check if plugin install provides specification

- test/unit/plugins/provisioners/docker/installer_test.rb
This commit fixes a test that only fails on certain users machines where
Vagrant ends up trying to run real guest capabilities to test if the
docker provisioner raises an error if the provisioner install failed. It
fixes it by mocking out the expected return values for those
capabilities rather than relying on them actually running for this
specific unit test.
> Fixes #11606: Mock out guest capabilities instead of running them

- templates/locales/en.yml
- test/unit/plugins/commands/cloud/auth/middleware/add_authentication_test.rb
- test/unit/plugins/commands/cloud/provider/create_test.rb
- test/unit/plugins/commands/cloud/provider/update_test.rb
- test/unit/plugins/commands/cloud/provider/upload_test.rb
- test/unit/plugins/commands/cloud/publish_test.rb
- test/unit/plugins/commands/init/command_test.rb
- test/unit/plugins/providers/docker/config_test.rb
- test/unit/vagrant/util/downloader_test.rb
- website/source/docs/boxes/format.html.md
- website/source/docs/cli/init.html.md
- website/source/docs/provisioning/chef_client.html.md
- website/source/docs/push/ftp.html.md
- website/source/docs/push/index.html.md
This pull request replaces what could be potentially real domains and replaces them with `example.com`. For tests, this hopefully prevents any accidental requests actually being made to what could be real domains, and instead uses the example domain.
> Ensure example domain is used rather than potentially real domain

- lib/vagrant/util/downloader.rb
- plugins/kernel_v2/config/vm.rb
This pull request ensures the util class MapCommandOptions is required. It was previously used in the downloader class, but the require was not moved over. This change just ensures the class is loaded prior to use for the config vm class.
> Ensure MapCommandOptions is required

- website/source/intro/getting-started/provisioning.html.md
This commit adds some clarification to the provisioning guide by
explaining ahead of time that an html folder will be created that will
be used by the provisioning script.
> Fixes #11594: Clarify provisioning guide

- lib/vagrant/action/builtin/handle_forwarded_port_collisions.rb
- lib/vagrant/util/ipv4_interfaces.rb
- lib/vagrant/util/is_port_open.rb
- plugins/providers/docker/action.rb
- plugins/providers/docker/action/forwarded_ports.rb
- plugins/providers/docker/action/prepare_forwarded_port_collision_params.rb
- plugins/providers/docker/communicator.rb
- plugins/providers/docker/driver.rb
- test/unit/plugins/providers/docker/driver_test.rb
- test/unit/vagrant/action/builtin/handle_forwarded_port_collisions_test.rb
- test/unit/vagrant/util/ipv4_interfaces_test.rb
- test/unit/vagrant/util/is_port_open_test.rb
Prior to this commit, if a created but exited container bound a port,
and a new container grabed that same port (say for an ssh port forward),
when the initial container came back up it would fail because the port
also got bound to the second container. This commit fixes that behavior
by first looking at what containers are already bound prior to creating
a container.
> Fixes #9067: Ensure new containers don't grab existing bound ports

- test/unit/vagrant/util/downloader_test.rb
This ensures that these tests will pass if the environment has
`VAGRANT_INSTALLER_ENV=1` set (e.g. in a local development environment).
> Default #in_installer? to false

- website/package-lock.json
- website/package.json
- Exposes new branch logic affecting vmware product download link
Ref: https://github.com/hashicorp/web-components/pull/1171/files#diff-cc5d4cccbfcba7e00d061f4b0c683855R28-R37
```diff
-  const installationLink =
-    productNameLowerCase === 'sentinel'
-      ? `/sentinel/intro/getting-started/install/`
-      : `https://learn.hashicorp.com/${baseProductNameLowerCase}/getting-started/install`
+  const installationLink = (productNameLowerCase => {
+    switch (productNameLowerCase) {
+      case 'sentinel':
+        return `/sentinel/intro/getting-started/install/`
+      case 'vagrant-vmware-utility':
+        return '/docs/providers/vmware/installation'
+      default:
+        return `https://learn.hashicorp.com/${baseProductNameLowerCase}/getting-started/install`
+    }
+ …
```
> Update @hashicorp/react-product-downloader dependency

- website/pages/docs/providers/vmware/vagrant-vmware-utility.mdx
Fix a couple of paths in the VMware Utility installation instructions.
It would be cool if we could hook into `VMWARE_UTILITY_VERSION` to
automatically keep the filename up to date, but this does not appear
possible with the default MDX code blocks.
> Clean up installation instructions

- plugins/commands/destroy/command.rb
- plugins/providers/virtualbox/action.rb
- test/unit/plugins/commands/destroy/command_test.rb
- website/pages/docs/cli/destroy.mdx
fixes virtual box part of https://github.com/hashicorp/vagrant/issues/10292
docker does not halt the machine before destroying.
> Option to forcefully/gracefully destroy virtualbox vm

- plugins/kernel_v2/config/vm.rb
- templates/locales/en.yml
- test/unit/plugins/kernel_v2/config/vm_test.rb
- website/pages/docs/networking/basic_usage.mdx
addresses adding hostname option to network config as per https://github.com/hashicorp/vagrant/issues/11508 
* hostname is a boolean
* a network that sets hostname should have a static ip address
* only one network may set hostname
can be set at `config.vm.network :public_network, hostname: true, ip: "192.168.0.1"`
> Add :hostname option to network config

- lib/vagrant/action/builder.rb
- lib/vagrant/action/builtin/trigger.rb
- lib/vagrant/plugin/v2/trigger.rb
- plugins/kernel_v2/config/vm_trigger.rb
- test/unit/plugins/kernel_v2/config/vm_trigger_test.rb
- test/unit/vagrant/action/builder_test.rb
- test/unit/vagrant/action/builtin/trigger_test.rb
- test/unit/vagrant/plugin/v2/trigger_test.rb
Updates the type to do a proper comparison when checking for
the `:all` special value as well as applied ignores.
Fixes #11599
> Fix trigger matching on `:all` special value

- lib/vagrant/action/builtin/handle_forwarded_port_collisions.rb
- test/unit/vagrant/action/builtin/handle_forwarded_port_collisions_test.rb
If the given host_ip is a loopback address, proceed with the regular
port check.
> Fix #11640: Check port of loopback address

- plugins/guests/debian/cap/change_host_name.rb
- test/unit/plugins/providers/virtualbox/synced_folder_test.rb
- test/unit/vagrant/util/experimental_test.rb
- test/unit/vagrant/util/platform_test.rb
- test/unit/vagrant_test.rb
Hi,
I was going to add some new feature to vagrant, after forking and cloning, I ran unit tests by `bundle exec rake`, but found some errors happened sometimes. So I digged into the failed tests, and made some changes to fix that issue.
Every error is caused by the running order of all specs. Inline comments show the details.
> Fix sometimes-failed test cases that depend on running order

- plugins/guests/haiku/cap/rsync.rb
- plugins/guests/haiku/plugin.rb
- test/unit/plugins/guests/haiku/cap/rsync_test.rb
This PR creates guest capabilities for HaikuOS to install rsync and perform basic synchronization. I created a Vagrant box for testing here: https://app.vagrantup.com/jbonhag/boxes/haiku-x86_64
Caveat:
Running rsync against a destination under the root directory (`/vagrant`)will create directories but not files, so you will see errors like this:
```
rsync: open "/vagrant/Vagrantfile" failed: Invalid Argument (-2147483643)
```
As a workaround, we can create a symlink to e.g. `/boot/home/vagrant` from `/vagrant` using a similar design to the way we create synthetic firmlinks for macOS 10.15 guests. This can be done under a different PR.
Update: Testing box has been updated with the following default synced folder:
```ruby
config.vm.synced_folder ".", "/boot/home/vagrant", type: "rsync"
```
> Fix #9552: Install rsync on Haiku guests

- website/pages/docs/providers/virtualbox/configuration.mdx
Adds an example of setting `check_guest_additions = false` to skip the VirtualBox guest additions check.
> Document check_guest_additions option

- plugins/providers/hyperv/scripts/utils/VagrantVM/VagrantVM.psm1
The hyper-v secure boot template information was added to the box.xml recently. See the corresponding [pull request](https://github.com/hashicorp/packer/pull/9552) for packer.
This PR adds the needed changes for vagrant. The code reads the information out of the box and uses powershell to set the boot template for the VM.
The change is backwards compatible so boxes where this information is missing are still working.
> Set secure boot template setting for hyper-v

- plugins/providers/virtualbox/cap/configure_disks.rb
- plugins/providers/virtualbox/driver/meta.rb
- plugins/providers/virtualbox/driver/version_5_0.rb
- templates/locales/en.yml
- test/unit/plugins/providers/virtualbox/cap/configure_disks_test.rb
- test/unit/plugins/providers/virtualbox/driver/version_5_0_test.rb
This pull request updates the configure_disks capability to only work off of a guests attached disks. Before this, it worked off of the results of `vboxmanage list hdds` which lists every disk for all virtual machines running in VirtualBox. This updates that to instead filter out only the disks associated with the guest, and store that information in the storage controllers attachments data structure to be used instead of the results of `list hdds`.
Fixes #11755
> Ensure VirtualBox Disk capability works only off of guest attached disks

- website/components/footer/index.jsx
- website/data/subnav.js
- website/pages/docs/providers/vmware/installation.mdx
- website/pages/docs/providers/vmware/kernel-upgrade.mdx
- website/pages/downloads/index.jsx
- website/pages/vmware/downloads/index.jsx
- website/pages/vmware/index.jsx
Updating the Vagrant website to have a consistent, orthographic spelling of VMware. Meaning that all instances of "VMWare" are updated to be "VMware"
> Updating "VMware" name usage across website

- lib/vagrant/util/powershell.rb
- test/unit/vagrant/util/powershell_test.rb
For the other occurrences of the powershell executable in `lib/vagrant/util/powershell.rb` this change has already been implemeted in back in 2018: https://github.com/hashicorp/vagrant/pull/9300/commits/ed686ce724f2b6117b03a3267f26d9f66286b387.
> Use the correct powershell executable for privileged commands

- plugins/provisioners/container/client.rb
- test/unit/plugins/provisioners/container/client_test.rb
- website/pages/docs/provisioning/docker.mdx
fixes https://github.com/hashicorp/vagrant/issues/9418
> Allow docker run images to specify version with ':'

- vagrant.gemspec
This release drops support for ruby 2.3 and fixes the detach behavior for Windows
similar vagrant-spec pr: https://github.com/hashicorp/vagrant-spec/pull/36
ref: https://github.com/enkessler/childprocess/releases/tag/v4.0.0
> Update childprocess to 4.0.0

- lib/vagrant/util/ansi_escape_code_remover.rb
fixes https://github.com/hashicorp/vagrant/issues/11135
Looks like a `\e[3J` was getting added from tmux
> Capture escape character [3J

- lib/vagrant/errors.rb
- plugins/communicators/ssh/communicator.rb
- templates/locales/en.yml
- test/unit/plugins/communicators/ssh/communicator_test.rb
This commit changes the SSH communicator to raise an error if Vagrant
doesn't receive an exit status from an SSH command, for example if the
command is terminated by the OOM-killer.
Closes #11715.
> Raise an error on nil exit status

- lib/vagrant/action/builtin/handle_box.rb
- lib/vagrant/vagrantfile.rb
- plugins/kernel_v2/config/vm.rb
- templates/locales/en.yml
- test/unit/plugins/kernel_v2/config/vm_test.rb
- test/unit/vagrant/action/builtin/handle_box_test.rb
- test/unit/vagrant/vagrantfile_test.rb
This fixes an issue where having a box name set to an empty string will
cause all Vagrant commands to fail with an error like:
> ArgumentError: Malformed version number string (random box name)
This may be related to #10663.
> Treat an empty box value as invalid

- test/vagrant-spec/Vagrantfile.spec
This will allow us to filter specs based on the guest operating system,
for example if we don't want to run certain tests on a Windows guest.
See https://github.com/hashicorp/vagrant-spec/pull/35/files#diff-411e94c903d454a80d43973dd16f9b7bR19
for an example.
> Pass guest platform into spec runner

- plugins/hosts/windows/plugin.rb
- plugins/synced_folders/smb/synced_folder.rb
- test/unit/plugins/synced_folders/smb/synced_folder_test.rb
The credential checking capability was not added to the Windows host plugin. This prevented the capability from running, and also caused the tests to be skipped.
The function signature for the `smb_validate_password` method was also different to where it was being used in both the synced_folder plugin and the tests.
The unit tests succeed, but as I'm very unfamiliar with Ruby, I don't really understand them (for example, it looks to me like the `should retry when validation fails` test is sending the same username and password each time, but expecting different results)
> Fix SMB credential checks

- website/_redirects
These redirects match the new collections URLs at Learn. The live redirect was resulting in a 404 for many paths.
It also fixes the splat redirect which will handle most paths that need to be sent to Learn.
> Use correct redirects to Learn

- lib/vagrant/action/builtin/handle_forwarded_port_collisions.rb
- lib/vagrant/util/is_port_open.rb
- test/unit/vagrant/action/builtin/handle_forwarded_port_collisions_test.rb
- test/unit/vagrant/util/is_port_open_test.rb
This updates the behavior of the port forward collision
handling to check if the defined `host_ip` is a known
address for the host platform. If it is not a known address,
a warning is logged rather than forcing an error. This allows
for defining an IP which may not yet exist but will once the
forwards are actually applied.
Also included is an enhancement to the open port check to
speed it up.
Fixes #11713 #11728
> Log warning on unknown host_ip for port forwards

- website/pages/docs/disks/hyperv/index.mdx
- website/pages/docs/disks/hyperv/usage.mdx
- website/pages/docs/disks/index.mdx
- website/pages/docs/disks/usage.mdx
- website/pages/docs/disks/virtualbox/index.mdx
- website/pages/docs/disks/virtualbox/usage.mdx
This commit removes the text about the disk feature being not functional
from the experimental warning. Now that both VirtualBox and Hyper-V have
shipped under the experimental flag, these providers are now functional.
> Remove not functional from disks warning

- lib/vagrant/util/template_renderer.rb
- vagrant.gemspec
Rails switched to erubi as well, as erubis has not seen any new releases since 2011.
> Switch from unmaintained gem erubis to erubi

- plugins/providers/virtualbox/model/storage_controller_array.rb
- test/unit/plugins/providers/virtualbox/model/storage_controller_array_test.rb
Some unsupported storage controllers (e.g. floppy) report a nil
boot_priority which results in a failed sort. Select only supported
storage controllers to avoid that case.
> Avoid sorting of controllers with nil boot_priority

- plugins/commands/cloud/version/release.rb
- test/unit/plugins/commands/cloud/version/release_test.rb
Hi everyone,
this is my first contribution here (and the very first contribution with ruby).
I ran into a little problem at my workplace during automating a vagrant box build process namely that there's no 'assume yes' option at the ```vagrant cloud version release``` command which requires a 'y' to release the version.
I know that I could use programs like 'expect' and 'yes' to solve this but I've always found it more elegant to use the offered ```--yes``` option.
P.S: I hope I didn't violate any of the rules of this community. If I did, please let me know and I'll try my best.
Thank you in advance for looking into my PR.
> --yes options added to CloudCommand::VersionCommand::Command::Release

- Gemfile
This updates the Gemfile to specify the branch for vagrant-spec following GitHub updating branch naming conventions. Until RubyGems fixes it on their end, the branch specification will need to be made.
Fixes #11976
> Gemfile: update vagrant-spec branch #11976

- plugins/guests/arch/cap/smb.rb
- test/unit/plugins/guests/arch/cap/smb_test.rb
Leaving out smbclient from the install will cause a cyclical
dependency error.
```
Was getting error
warning: dependency cycle detected:
warning: smbclient will be installed before its cifs-utils dependency
error: failed to commit transaction (conflicting files)
```
> Install smbclient when setting up arch smb

- .circleci/config.yml
- website/Dockerfile
- website/Makefile
Hello! Instead of using dockerhub (which will enforce rate limiting on anonymous image pulls starting Nov 1st), we're moving projects to our mirror at `docker.mirror.hashicorp.services`. LMK if you have any q's, otherwise feel free to approve and merge on your own
> Use docker mirror

- website/pages/docs/vagrantfile/ssh_settings.mdx
Update documentation to clarify the `extra_args` option
within the ssh configuration only applies to the invocation
of the SSH executable and not the internal ssh communicator.
Context: #12005
> Make note that the `extra_args` option is only for the `ssh` command

- lib/vagrant/util/is_port_open.rb
- test/unit/vagrant/util/is_port_open_test.rb
With WSL port checks can end up resulting in Errno::EALREADY being
raised. When encountered, assume port is unavailable.
Fixes #12006
> Handle Errno::EALREADY exceptions on port checks

- lib/vagrant/action/builder.rb
- lib/vagrant/action/runner.rb
- lib/vagrant/machine.rb
- test/unit/vagrant/action/builder_test.rb
When expanding stack track the origin action name and only apply
it once the stack has completed its expansion. The local env data
is marked with origin action to prevent it from being applied in
nested builders as they are expanded. The value of the stored action
name is checked and invalidated if another action is applied to the
same env in the future so hooks / triggers for that action are
applied as expected.
Fixes #11898 #11972
> Fix application of action named triggers/hooks

- plugins/commands/cloud/client/client.rb
- test/unit/plugins/commands/cloud/client_test.rb
Mark warning of double tokens set when initially print to prevent
the warning from being shown multiple times during a single run.
> Prevent printing token warning more than once

- plugins/guests/linux/cap/reboot.rb
- plugins/guests/windows/cap/reboot.rb
- test/unit/plugins/guests/linux/cap/reboot_test.rb
- test/unit/plugins/guests/windows/cap/reboot_test.rb
- website/pages/docs/other/environmental-variables.mdx
Previously the maximum amount of time Vagrant would poll for whether a VM has successfully reboot was hard coded to 120 seconds.
This change introduces the `VAGRANT_MAX_REBOOT_RETRY_TIMEOUT` environment variable to allow users to configure the maximum time to support OS configurations that happen to take longer than 120 seconds to reboot.
This PR also adds RSpec tests for the maximum retry logic. I wanted to add some tests around the actual environment variable, but since it's set to a constant on the class it'll require unloading and loading the class back up which was fairly ugly to do in the test. You can see below the environment variable in action (and failing the test because the number of retries don't match).
Hopefully this is useful, thank you!
Fixes #11695
> Make the max reboot retry duration configurable

- website/pages/vagrant-cloud/api.mdx
Adds Vagrant Cloud API documentation for using the direct upload
approach with proper curl and ruby examples.
> Update API documentation to include direct

- lib/vagrant/bundler.rb
- lib/vagrant/shared_helpers.rb
- test/unit/support/shared/base_context.rb
- test/unit/vagrant/bundler_test.rb
- test/unit/vagrant/shared_helpers_test.rb
When initializing for internal plugin resolution inspect contraints
on all defined dependencies. If a prerelease constraint is detected,
automatically enable prerelease resolution.
Also includes option to enable prerelease resolution via environment
variable when custom resolution behavior is desired.
> Check dependency list on initialization

- lib/vagrant/bundler.rb
When moving prerelease logic into isolated method from the
Vagrant client prerelease check, the settings on the request
sets where not updated to account for the new method. This
sets the requests sets properly when vagrant is out of develop
mode.
> Apply prerelease checks to request sets

- lib/vagrant/action/builder.rb
- test/unit/vagrant/action/builder_test.rb
The raw actions are used for applying the original trigger behavior
which can insert before and/or after the entire set of actions. When
processing the stack items, mark when the raw action has been applied
to prevent it from being applied again. Triggers around the raw actions
should only ever be applied _once_.
Fixes #12034 #12035
> Track raw actions as they are applied to prevent multiple insertions

- plugins/guests/openwrt/cap/change_host_name.rb
- plugins/guests/openwrt/cap/halt.rb
- plugins/guests/openwrt/cap/insert_public_key.rb
- plugins/guests/openwrt/cap/remove_public_key.rb
- plugins/guests/openwrt/cap/rsync.rb
- plugins/guests/openwrt/guest.rb
- plugins/guests/openwrt/plugin.rb
- test/unit/plugins/guests/openwrt/cap/change_host_name_test.rb
- test/unit/plugins/guests/openwrt/cap/halt_test.rb
- test/unit/plugins/guests/openwrt/cap/insert_public_key_test.rb
- test/unit/plugins/guests/openwrt/cap/remove_public_key_test.rb
- test/unit/plugins/guests/openwrt/cap/rsync_test.rb
This commit includes the following capabilities for OpenWrt:
- Guest detection
- SSH key replacement
- Change host name
- Synced folder support with rsync
Interesting things about OpenWrt:
- root login
- Default shell is ash
- Uses Busybox binaries
- Package manager is `opkg`
PR can be tested with the `vladimir-babichev/openwrt-19.07.3` box. Closes #11790.
> Guest support for OpenWrt

- .github/workflows/testing.yml
- contrib/README.md
- vagrant.gemspec
Update rake to `~> 13.0`. Also, I've fixed the indentation in `contrib/README.md` and sneaked it into this PR :wink: 
I have realized that the testsuite is not being run when the `vagrant.gemspec` is modified. I believe that is an oversight and so I took this opportunity to add it to the testing github action.
> Add ruby test files to testing workflow and bump rake dependency

- website/components/temporary_text-split/style.module.css
- website/next.config.js
- website/package-lock.json
- website/package.json
- website/pages/home/style.module.css
- website/pages/style.css
🎟️ [Asana Task](https://app.asana.com/0/1188331750716498/1199373521776172/f)
🔍 [Preview Link](https://deploy-preview-12118--vagrant-docs.netlify.app/)
This PR pulls in updated versions of `next`, `nextjs-scripts`, and `code-block` in order to avoid shipping `highlight.js` to the client, and to enable build-time code highlighting in future work.
- [`/` - home page](https://deploy-preview-12118--vagrant-docs.netlify.app/)
- The appearance of "text splits" on this page has changed _very slightly_ to accommodate the revised `code-block` component
> Prepare for build-time code highlighting

- templates/commands/init/Vagrantfile.min.erb
This PR is to add 
```
``` 
to the Vagrantfile created when using `init -m`
this is very convenient to have in the file to improve the experience of advanced users that would like minimal Vagrantfile
> Update Vagrantfile.min.erb add vi mode for ruby

- plugins/provisioners/salt/bootstrap-salt.sh
1. Use new `saltproject.io` domain (see [the note](https://github.com/hashicorp/vagrant/pull/12127#discussion_r552869282))
2. Support Python 3
> Modernize Salt bootstrap script

- .github/workflows/testing.yml
- test/unit/plugins/commands/init/command_test.rb
A minimal Vagrantfile may set the vi mode for ruby
> Fix minimal Vagrantfile test

- vagrant.gemspec
`listen` no longer depends on `ruby_dep` and thus this pointlessly drags in another dependency.
> Bump listen gem version and remove ruby_dep

- website/content/docs/cloud-init/usage.mdx
As pointed out here, https://www.grzegorowski.com/how-to-test-cloud-init-locally-with-vagrant, `cloud-init` doesn't work without `disks` flag, so it's being added it.
> Add disks flag in cloud-init usage

- lib/vagrant.rb
- lib/vagrant/patches/net-ssh.rb
- vagrant.gemspec
To prevent resolution issues with the introduction
of a prerelease constraint, update the net-ssh constraint
to be a minimum at the latest release. Include monkey
patches to include support for wanted host key algos.
The monkey patches are only applied to the latest
net-ssh currently and will be ignored once the current
prerelease has been fully released.
Fixes #12212 #12202 #12111
> Update net-ssh constraint to non-prerelease version

- vagrant.gemspec
There were no functional changes between 1.0.0 and 1.1.0:
https://github.com/net-ssh/bcrypt_pbkdf-ruby/compare/b5d1a921fcec8daa368236f5b4c469e08200fd5c...v1.1.0
so this update should be safe
> Bump bcrypt_pbkdf version

- templates/guests/nixos/network.erb
- test/unit/templates/guests/nixos/network_test.rb
The old config style doesn't build anymore on the current release NixOS 20.09. It stopped working some releases ago.
> Fix network config for recent NixOS releases

- website/content/docs/installation/uninstallation.mdx
Tested on latest Mac OS.
System Version:	macOS 11.2.2 (20D80)
Kernel Version:	Darwin 20.3.0
uname -a
Darwin argent.local 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64
> Removal requires sudo access on Mac

- bin/vagrant
- lib/vagrant.rb
- lib/vagrant/bundler.rb
- lib/vagrant/errors.rb
- lib/vagrant/plugin/manager.rb
- templates/locales/en.yml
- test/unit/bin/vagrant_test.rb
- test/unit/vagrant/bundler_test.rb
When installing plugins and a failure is encountered, inspect the error
message and determine if a more specialized error can be provided to the
user on how to resolve the error. If so, use the specialized error, and if
not return the generic error.
This PR also includes an update to Vagrant's startup process which collects
and activates all dependencies as determined by the Vagrant specification
runtime dependencies. The full dependency tree is activated, and the specifications
for the dependencies are stashed for later use when resolving plugins. This
should help when Vagrant is run outside of the installer package or bundler
to properly generate the builtin set.
> Activate builtin specs on startup, provider better plugin install errors

- lib/vagrant/util/curl_helper.rb
- plugins/commands/cloud/client/client.rb
- plugins/commands/cloud/locales/en.yml
- plugins/commands/cloud/util.rb
- test/unit/plugins/commands/cloud/auth/middleware/add_downloader_authentication_test.rb
- test/unit/plugins/commands/cloud/client_test.rb
Prevents redirect notification when getting asset from
the default store. Also fixes some places where the
cloud client was not using the helper method for the
server url. Custom server urls also have api path appended
automatically when not detected.
> Prevent notification on default store, fix client end point

- CHANGELOG.md
file to a .vagrant directory which occurred at approximately commit
4e649cc98792c192c1589a0bd86e8433e90f60cd.
> Added a note to the changelog documenting the change from a .vagrant

- plugins/commands/cloud/auth/middleware/add_authentication.rb
- plugins/commands/cloud/auth/middleware/add_downloader_authentication.rb
- test/unit/plugins/commands/cloud/auth/middleware/add_authentication_test.rb
- test/unit/plugins/commands/cloud/auth/middleware/add_downloader_authentication_test.rb
- website/content/docs/other/environmental-variables.mdx
Replace the `VAGRANT_ALLOW_PARAM_AUTH_TOKEN` environment variable
with `VAGRANT_SERVER_ACCESS_TOKEN_BY_URL` and update the behavior
when the environment variable is set to add the access token as
a query parameter and disable the addition of the authentication
header.
Fixes #12080
> Update authentication middleware access token handling

- lib/vagrant/bundler.rb
Parts of the stdlib which have been externalized but are still
included within Ruby introduce issues when pinning Vagrant's
dependencies to resolve plugin installs. When determining
Vagrant's dependency list prior to solution generation, check
the specification and ignore any default gems to prevent
pinning versions that are not actual dependencies.
Fixes #12248
> Fix dependency resolution where default gems are included

- website/package-lock.json
- website/package.json
Remove the badges from the HCP products on the HashiStackMenu, as they are no longer needed.
[🔍 Preview](https://vagrant-git-brstackmenu-hashicorp.vercel.app/)
> Upgrade stackmenu to latest

- plugins/guests/linux/cap/mount_smb_shared_folder.rb
- test/unit/plugins/guests/linux/cap/mount_smb_shared_folder_test.rb
- test/unit/plugins/guests/linux/cap/persist_mount_shared_folder_test.rb
fixes https://github.com/hashicorp/vagrant/issues/12277
additional tests in the vagrant-spec project https://github.com/hashicorp/vagrant-spec/blob/main/acceptance/synced_folder/smb_spec.rb
> Get folder mount name

- plugins/providers/docker/driver.rb
- test/unit/plugins/providers/docker/driver_test.rb
Relax the pattern matching to allow updated output
format to be properly detected along with the old
output format.
Fixes #12245
> Fix matching on build output for docker provider

- lib/vagrant/patches/net-ssh.rb
- vagrant.gemspec
This fixes an issue introduced from updates to OpenSSH which modifies
the expectations on a user authentication request wanting the signature
algorithm being used and no longer the name of the key type.
Fixes #11783
> Fix SSH communicator connections for rsa keys

- .github/workflows/testing.yml
This should fix #12305 by changing to approved syntax versioning listed [here](https://github.com/ruby/setup-ruby#supported-version-syntax)
> fix versioning syntax #12305

- plugins/guests/linux/cap/reboot.rb
- test/unit/plugins/guests/linux/cap/reboot_test.rb
This adds a check to the `#wait_for_reboot` method on the linux
guest reboot capability to determine if the a reboot is still
in process. This prevents the reboot process from being initiated
and the `#ready?` check on the guest being called before the
system shutdown process has shutdown the communicator process.
Fixes #12270 #12292
> Properly wait for reboot process to start

- .github/workflows/check-unlinked-content.js
- .github/workflows/check-unlinked-content.yml
- website/components/_temp-enable-hidden-pages/index.js
- website/data/docs-nav-data-hidden.json
- website/pages/docs/[[...page]].jsx
🔍 [Preview](https://vagrant-git-fork-zchsh-zshandle-unlinked-content-hashicorp.vercel.app)
This PR fixes an issue where pages that were previously not included in `*-nav-data.json` files were not rendered.
This PR introduces a temporary fix to ensure these pages are rendered, but are not shown in the sidebar navigation, to match previous behaviour. We plan to revisit this issue more intentionally in the near future.
This PR adds a check for unlinked content. This check helps ensure that all files in `website/content` are published to the `packer.io` website
> Note: most these docs pages, except maybe the "macOS Catalina" page, don't seem to be deprecated... so should likely just be added to `nav-data`. Happy to adjust and take that approach instead of the "hidden" approach currently in …
> website: resolve unlinked content

- lib/vagrant/util/powershell.rb
- test/unit/vagrant/util/powershell_test.rb
This updates the powershell detection to look for the `pwsh` executable
and use it when the powershell executable is not available.
Fixes #11085
> Support pwsh executable name for powershell

- test/unit/vagrant/util/powershell_test.rb
On *nix systems we might not have powershell installed and then finding powershell.exe or pwsh.exe fails in some tests. If we instead mock self.executable to return "powershell", then the tests pass and don't cause any side effects.
> Mock the PowerShell.executable method in more tests

- templates/locales/en.yml
- website/content/docs/provisioning/ansible_common.mdx
- website/content/docs/provisioning/ansible_intro.mdx
Page `https://docs.ansible.com/ansible/intro_inventory.html` has been moved and returns a 404. This PR fixes all references and updates the jump anchors as well.
> Website and Templates: Fix links to Ansible inventory user guide

- website/data/alert-banner.js
---
Updates the alert banner data for hashiconf europe going live.
> chore: updates hashiconf alert banner data

- website/pages/downloads/index.jsx
ref:
https://github.com/hashicorp/homebrew-tap#what-packages-are-available
fixes: https://github.com/hashicorp/vagrant/issues/12349 and https://github.com/hashicorp/vagrant/issues/12354
> Add package manager override for brew install instructions

- website/content/docs/provisioning/docker.mdx
- website/content/docs/provisioning/podman.mdx
In particular, they should be more clear about the need to have
a guest VM defined in order to use the provisioners.
> Update Podman and Docker provisioner docs

- website/content/docs/networking/public_network.mdx
In more recent linux versions, if you receive a DHCP address from your `public_network` interface, it will "simply" add a new gateway to your list of possible routes. You can remove this using the `ip route del` command, as seen in this PR.
> Update "Default Router" shell script in publc_network.mdx documentation

- website/content/docs/providers/index.mdx
This brings it in line with the hyper-v overview page: https://github.com/hashicorp/vagrant/blob/main/website/content/docs/providers/hyperv/index.mdx
> Update Hyper-V link.

- .github/CONTRIBUTING.md
- Vagrantfile
- scripts/install_rvm
- scripts/setup_tests
In attempting to get a development environment set up to run the rspec
tests for a forthcoming PR I noticed that the Vagrantfile doesn't appear
to actually set up a functioning environment. I'm not sure when this
changed or how it's been missed but I figured I'd contribute a patch to
fix it up for my benefit and others.
In summary:
1. RVM no longer appears to be installed and configured the way the
current provisioning script expects it be. Namely it requires users to
be added to the `rvm` group rather than the `sudo` group and also
requires a log out and then back in to finish setting up. In light of
that I broke apart the provisioning into two separate shell scripts to
get that 'log out and back in' behavior.
2. While I was there I tried to 'clean up' the script's logic, making it …
> Fix the included Vagrantfile for running rspec tests

- website/content/docs/provisioning/ansible_common.mdx
Some of these URL were pointing to http://docs.ansible.com/ansible/[...] that results of a 404 not found.
I updated all links to https://docs.ansible.com/ansible/latest/[...].
Thank you
> Fixing broken reference to ansible website

- plugins/guests/debian/cap/configure_networks.rb
- test/unit/plugins/guests/debian/cap/configure_networks_test.rb
DAD (Duplicate Address Detection) check times out when we add IPv6 interfaces
> Retry network setup on debain

- website/package-lock.json
- website/package.json
- website/pages/style.css
👀 [Preview](https://vagrant-git-fork-zchsh-zsupgrade-code-block-hashicorp.vercel.app/docs)
This PR upgrades all MDX code snippets to use [our latest `code-block` component](https://github.com/hashicorp/react-components/pull/205), which contains a number of new features detailed in [[MKTG-035] Improvements to our Code Blocks](https://docs.google.com/document/d/1b2ROeAoy708dSqpJZjZRvuhJm9FB86skKEeQC3ZkLMY/edit?ts=5fadaaee).
We've also converted our `code-block` component to use CSS modules, which removes the need for global code-block related style imports.
> website: upgrade code-block

- plugins/commands/cloud/auth/middleware/add_authentication.rb
- test/unit/plugins/commands/cloud/auth/middleware/add_authentication_test.rb
When scrubbing box urls of access token parameters, only return
the processed URL if the access token was removed. If it was not
removed, return the original URL string. This prevents issues with
local file URLs being parsed and replaced with invalid paths.
Fixes: #12340
Fixes: #12350
Fixes: #12320
> Fix local box add with relative path on Windows

- lib/vagrant/patches/net-ssh.rb
Set flag on RSA keys of deprecated RSA SHA1 support when loading
keys based on server version of the transport. This ensures keys
are properly flagged. Flag name has been updated to provide context
on usage.
Version matching on the OpenSSH server version has also been updated
to handle customized naming in the version string (as seen in the
Windows port) and to properly handle when no match is found.
Fixes #12344 
Fixes #12408 
Fixes #12381
> Flag RSA SHA1 deprecation when loading keys

- plugins/provisioners/salt/bootstrap-salt.ps1
A follow-up fix for https://github.com/hashicorp/vagrant/pull/12127
Tls13 is only available on .NET Framework 4.8, so the settings should be more conservative to work on older Windows versions. Based on testing reports from other collaborators:
https://github.com/hashicorp/vagrant/pull/12127#issuecomment-855910966
https://github.com/hashicorp/vagrant/pull/12127#issuecomment-856883383
Thanks to @leon-kleyn, @dafyddj and msmith in Salt Slack community.
> Use more conservative TLS settings to work on older .NET versions

- lib/vagrant/action/general/package.rb
- lib/vagrant/errors.rb
- plugins/commands/box/command/list.rb
- plugins/commands/package/command.rb
- templates/locales/en.yml
- test/unit/vagrant/action/general/package_test.rb
- website/content/docs/cli/package.mdx
Assuming that `info.json` belongs in the `include` directory, this fixes #12191 by pre-pending `include` as the first arg when joining the pathname.
> implement --info flag for package cmd #12191

- lib/vagrant/util.rb
- lib/vagrant/util/line_buffer.rb
- plugins/provisioners/shell/provisioner.rb
- test/unit/plugins/provisioners/shell/provisioner_test.rb
- test/unit/vagrant/util/line_buffer_test.rb
This is an extension of #12403. It's a slight refactor to remove the inclusion
of the StringIO library and to provide a max length for buffering to prevent
a badly behaving provisioner from consuming excess amounts of memory on the
host. Test coverage has also been included.
Thanks @rgl! This changeset also includes a rebase of main and I didn't want
to force push onto your branch so I opened a new PR instead.
Fixes #12403
Fixes #11047
> Line buffer utility and shell provisioner usage

- plugins/guests/suse/cap/halt.rb
- test/unit/plugins/guests/suse/cap/halt_test.rb
We have started seeing occasional shutdown failures on openSUSE Tumbleweed with
Virtualbox inside a qemu virtual machine, where `shutdown -h now` would return
nil. While the machine is successfully turned off, the command fails and vagrant
reports an error.
This commit changes the shutdown command to launch in the background which
also triggers a shutdown, but always succeeds.
> Use systemctl poweroff in the background instead of shutdown

- test/unit/base.rb
- vagrant.gemspec
This gem was added a long time ago and probably used to test the functionality
that is now provided by the vagrant_cloud gem
> Remove no longer required gem webmock

- lib/vagrant/environment.rb
Closes #12453
Hi @soapy1 ! 👋 
After upgrade to Vagrant 2.2.17, `vagrant up` throws the following error:
```bash
install_plugin: wrong number of arguments (given 2, expected 1) (ArgumentError)
from C:/HashiCorp/Vagrant/embedded/gems/2.2.17/gems/vagrant-2.2.17/lib/vagrant/environment.rb:1014:in `block in process_configured_plugins'
...
```
You can test this scenario with the Vagrantfile below:
```ruby
Vagrant.configure('2') do |config|
config.vagrant.plugins = ['vagrant-vbguest', 'vagrant-disksize']
config.vm.box = 'centos/8'
end
```
The vagrantfile above works in `2.2.16`, but in `2.2.17` not 👍  The bugfix that I made here in my PC was the code present in PR 🤝 
Thanks a lot! 🍻
> Fix of error "install_plugin: wrong number of arguments (given 2, expected 1) (ArgumentError)" after upgrade to Vagrant 2.2.17

- plugins/guests/suse/cap/halt.rb
- test/unit/plugins/guests/suse/cap/halt_test.rb
SLE 11 does not ship systemd and then using `systemctl poweroff` does not work. Therefore we fall back to using `/sbin/shutdown` for machines without systemd.
This fixes https://github.com/hashicorp/vagrant/issues/12487
> Add fallback for SLE 11 guest machines

- plugins/hosts/windows/cap/ssh.rb
`Vagrant 2.2.16`
`Windows 10, Version 21H1 (OS build 19043.1023)`
If Vagrant machine is located in directory where space is in the path, Vagrant fails to set permissions for generated SSH private key.
`vagrant ssh` does not work:
```
PS D:\Vagrant Machines\debian_buster64> vagrant ssh
vagrant@127.0.0.1: Permission denied (publickey).
```
Direct SSH connection:
```
PS D:\Vagrant Machines\debian_buster64> ssh -p 2222 -i ".vagrant/machines/default/virtualbox/private_key" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null vagrant@127.0.0.1
Warning: Permanently added '[127.0.0.1]:2222' (ECDSA) to the list of known hosts.
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@         WARNING: UNPROTECTED PRIVATE KEY FILE!          @ …
```
> Escape spaces in SSH key_path

- website/content/docs/triggers/configuration.mdx
Hi!
I've spotted a syntax error in the docs. I haven't checked if this part of the documentation is correct and makes sense as a whole, though.
> Fix syntax error in trigger configuration docs

- website/content/docs/disks/configuration.mdx
Option passed to :dvd disk type should be `file` not `path`.
```
There are errors in the configuration of this machine. Please fix
the following errors and try again:
vm:
* The following settings shouldn't exist: path
* A 'file' option is required when defining a disk of type ':dvd' for guest 'default'.
```
> Fix for :dvd example in disks configuration docs.

- plugins/provisioners/chef/cap/freebsd/chef_installed.rb
- plugins/provisioners/chef/cap/linux/chef_installed.rb
- plugins/provisioners/chef/cap/omnios/chef_installed.rb
- plugins/provisioners/chef/cap/windows/chef_installed.rb
- test/unit/plugins/provisioners/chef/cap/freebsd/chef_installed_test.rb
- test/unit/plugins/provisioners/chef/cap/linux/chef_installed_test.rb
- test/unit/plugins/provisioners/chef/cap/omnios/chef_installed_test.rb
- test/unit/plugins/provisioners/chef/cap/windows/chef_installed_test.rb
- #12346 
- #12337
- Fixes `chef_installed` detection to be compatible with Chef Infra Client 17+.  Chef Infra Client 17 removed the `knife` gem from the omnibus installation so existing detection of the install status is broken.  Updates the `chef_installed` checks to look for the existence of the `chef-client` binary instead of `knife` and performs version checking with 'chef-client'
- Updates the `chef_installed` detection to use the `chef` binary if `chef-workstation` is configured as the `chef.product`. Updates to use the Chef Workstation version (via `chef --version`) for comparison if `chef.version` is specified along with `chef.product = 'chef-workstation'`.
> Updates install checks for Chef provisioners

- website/content/docs/cli/halt.mdx
Detection/use added in https://github.com/hashicorp/vagrant/pull/11482, which has been included since version 2.2.8
Did a quick look around for similar documentation regarding rebooting, which might need to be updated as per https://github.com/hashicorp/vagrant/pull/11483; however, didn't find anything... of course possible that there's something I've missed.
> Add blurb about detection and use of Systemd

- website/content/docs/providers/vmware/faq.mdx
Include information on enabling the VMware Fusion Tech Preview
to work correctly with the Vagrant VMware utility to the VMware
provider FAQ.
Fixes #12551
> Add information about the Fusion Tech Preview

- .github/workflows/testing.yml
- lib/vagrant/errors.rb
- plugins/providers/virtualbox/action/network.rb
- templates/locales/en.yml
- test/unit/plugins/providers/virtualbox/action/network_test.rb
- vagrant.gemspec
VirtualBox introduced a restriction on the valid range for hostonly
networks. When using a version of VirtualBox which includes this
restriction a check is performed on the defined IP address to validate
it is within either the default range (as defined in the VirtualBox
documentation) or the values defined in the network configuration
file.
Fixes (what we can): #12557 #12553
> Validate VirtualBox hostonly network range

- plugins/providers/virtualbox/action/network.rb
- test/unit/plugins/providers/virtualbox/action/network_test.rb
Updates the VirtualBox version check for network range validation
to access the driver via the machine instances provider within the
passed env.
> Access provider driver through machine for version check

- lib/vagrant/errors.rb
- plugins/guests/darwin/cap/mount_smb_shared_folder.rb
- plugins/hosts/darwin/cap/path.rb
- plugins/hosts/darwin/cap/version.rb
- plugins/hosts/darwin/plugin.rb
- templates/locales/en.yml
- test/unit/plugins/hosts/darwin/cap/path_test.rb
- test/unit/plugins/hosts/darwin/cap/version_test.rb
When firmlinks were introduced with Catalina NFS export entries
would only work if the data path was used. This was resolved in
Big Sur so only expand the path with firmlink prefixes when on
Catalina.
Fixes #11834
> Fix NFS host paths on darwin

- plugins/guests/windows/cap/rsync.rb
- test/unit/plugins/guests/windows/cap/rsync_test.rb
This corrects the `mkdir` command used by rsync on Windows to make sure
the destination directory exists before starting to sync.  The old form
was correct on Linux but not on Windows, and it was just a coincidence
that the `-p` argument appeared to be work.
Please note that I am completely unfamiliar with the Vagrant codebase, so I am not sure how to properly test this.  The bug appears to be serious enough that it should always fail, at least on newer Powershell versions (I haven't tried to reproduce on any guest other than Windows 2019 with Powershell 7).
I use the patch herein on my local development system to fix this issue; that is as much testing as this patch has undergone so far.
Closes #11878
> [WIP] Change `mkdir` command on Windows for rsync

- plugins/guests/atomic/guest.rb
- plugins/guests/coreos/cap/configure_networks.rb
- test/unit/plugins/guests/coreos/cap/configure_networks_test.rb
Adds updates to the coreos guest network configuration
capability to use keyfiles with network manager. The
deprecated cloud-init based configuration is retained
to support older versions of coreos and is only used
if the guest has cloud-init enabled.
This also includes an adjustment to the atomic guest
detection. It's original implementation was not strict
enough and would result in the atomic guest matching
coreos.
Fixes #11804
> Fix coreos network configuration

- plugins/hosts/darwin/cap/path.rb
- test/unit/plugins/hosts/darwin/cap/path_test.rb
On Big Sur, mounting NFS mount is failing with a `VagrantPlugins::HostDarwin::Cap::Version (NameError)`  (https://github.com/hashicorp/vagrant/issues/12578).
This PR is an attempt to fix this issue.
I'm of course very open to any feedback to find a better solution.
> Fix missing VagrantPlugins::HostDarwin::Cap::Version on Big Sur

- .github/workflows/backport.yml
This introduces https://github.com/hashicorp/backport-assistant
Labelling and merging a PR with this label will trigger a backport PR to be opened and automerged (see `-automerge` flag) into `stable-website`
> feat: backport-assistant

- website/content/vmware/index.mdx
Adding a placeholder page at `/docs/vmware` so the build can succeed. It will never get hit as we have a redirect in place which will take users to `/docs/providers/vmware`.
> chore(website): /vmware/index placeholder

- website/redirects.next.js
[https://vagrant-30d3c3vhv-hashicorp.vercel.app/home](https://vagrant-30d3c3vhv-hashicorp.vercel.app/home)
> fix: redirects website `/home` to `/`

- website/Dockerfile
This PR updates the website's Dockerfile to use the `node:14.17.0-alpine` image, in line with our other sites.
> website: Update Dockerfile

- plugins/pushes/ftp/push.rb
- test/unit/plugins/pushes/ftp/push_test.rb
When testing all of the push functionality I ran into the fact that the
FTP upload code did not recognize that I had VAGRANT_CWD set, so it
wasn't finding the right files to upload.
This should make everything work properly relative to that location.
> Fix VAGRANT_CWD handling in `vagrant push ftp`

- plugins/pushes/heroku/push.rb
This is just a convenience enhancement - rather than swallowing all the
output from the Heroku push command, print stdout and stderr like we do
elsewhere with subprocesses. Heoku pushes are pretty involved and dump
lots of useful output, so it should be useful for users to see this.
> Print output when pushing to Heroku

- website/content/docs/other/environmental-variables.mdx
This PR is to fix a typo in the docs where the environment variable "VAGRANT_DISABLE_WINCURL" was written as "VAGRANT_WINCURL_DISABLE". The usage of this environment variable can be seen here:
https://github.com/hashicorp/vagrant-installers/blob/main/substrate/launcher/main.go#L339
> Fixing typo for VAGRANT_DISABLE_WINCURL option in website docs

- lib/vagrant/patches/net-ssh.rb
Set the rsa-sha2 algorithms in the kex algorithm set
to properly enable them as supported for key exchange.
Fixes #12533
> Set algorithms in kex

- plugins/guests/redhat/cap/nfs_client.rb
Starting a rocky 9 box (having nfs shares) fails with: `No match for argument: nfs-utils-lib`.
Apparently Rocky 9 does not have a `nfs-utils-lib` but mounting nfs shares without nfs-utils-lib works fine.
So updating the nfs client install to only install `nfs-utils-lib` if the package is available. That way older rhel clones
should continue to work as well.
> Update nfs_client.rb for rocky 9

- plugins/guests/alma/cap/flavor.rb
- plugins/guests/alma/guest.rb
- plugins/guests/alma/plugin.rb
- plugins/guests/centos/cap/flavor.rb
- plugins/guests/centos/guest.rb
- plugins/guests/redhat/cap/flavor.rb
- test/unit/plugins/guests/alma/cap/flavor_test.rb
- test/unit/plugins/guests/centos/cap/flavor_test.rb
- test/unit/plugins/guests/redhat/cap/flavor_test.rb
- guests: add Alma Linux guest support  
- guests: make CentOS/RHEL flavor detection more dynamic
- guests/centos: use GUEST_DETECTION_NAME='centos' to ID CentOS
- guests: RHEL 9 and CentOS stream 9 are out
> Enhancements for EL guests capabilities

- lib/vagrant/bundler.rb
- test/unit/vagrant/bundler_test.rb
When computing the solution set, if a gem is already loaded, make sure
to use the specification of the loaded one instead of the first
available as otherwise there is a risk that when multiple matches are
available the specification for the wrong version may be picked.
When this happens an error message will be triggered that looks like
can't activate json-2.3.0, already activated json-2.5.1
This can occur for distribution packaged vagrants as well as installs
for development purposes where the ruby install may contain a default
gem spec of an older version than is needed.
Fixes: #12521
Fixes: vagrant-libvirt/vagrant-libvirt#1390
Relates: #10826
Relates: #12345
> Improve Gem spec selection when resolving

- lib/vagrant.rb
- lib/vagrant/patches/fake_ftp.rb
- test/unit/plugins/pushes/ftp/adapter_test.rb
- test/unit/plugins/pushes/ftp/push_test.rb
- test/unit/vagrant/action/builtin/box_add_test.rb
- vagrant.gemspec
Sadly, `fake_ftp` is unmaintained since 2021, but all other alternatives haven't been touched for even longer :-/
> Bump fake_ftp to ~> 0.3.0 & adjust tests

- lib/vagrant.rb
- test/unit/base.rb
The fake_ftp patches should only be applied when running tests. Since
the library is a development dependency only, it will not be available
for loading from a release.
> Only patch fake_ftp when running tests

- .ci/build.sh
- .ci/release.sh
- .github/workflows/spectesting.yml
- Makefile
Updates the build job to generate vagrant-go binaries
for linux-amd64/386 and darwin-amd64.
> Include multiple build types

- .github/workflows/build.yml
- .github/workflows/go-spectest.yml
- .github/workflows/go-testing.yml
- .github/workflows/release.yml
- go.mod
Updates the setup-go action to use v3 in all
jobs using it. For the build and release jobs,
which only need a single version setup, use
the defined version within the go.mod file.
> Update go version configuration in setup

- website/content/docs/cli/destroy.mdx
- website/content/docs/cli/halt.mdx
- website/content/docs/cli/powershell.mdx
- website/content/docs/cli/ssh.mdx
- website/content/docs/disks/hyperv/usage.mdx
- website/content/docs/disks/vmware/common-issues.mdx
- website/content/docs/disks/vmware/index.mdx
- website/content/docs/disks/vmware/usage.mdx
- website/content/docs/experimental/vagrant_go.mdx
- website/content/docs/providers/virtualbox/boxes.mdx
- website/content/docs/providers/vmware/vagrant-vmware-utility.mdx
- website/content/docs/provisioning/ansible_local.mdx
- website/content/docs/provisioning/puppet_apply.mdx
- website/content/docs/synced-folders/virtualbox.mdx
- website/content/docs/triggers/usage.mdx
- website/content/docs/vagrantfile/ssh_settings.mdx
- website/content/docs/vagrantfile/tips.mdx
- website/content/vagrant-cloud/request-limits.mdx
- website/data/docs-nav-data.json
Fixes various capitalizations in the docs
* Examples: VMware, Linux/Unix, PowerShell, and some abbreviations
Also, Prettier auto-formatted away some trailing spaces, mostly in experimental/vagrant_go.mdx.
> Fix capitalizations in docs

- .github/ISSUE_TEMPLATE/config.yml
This will link to the forum to encourage users to post questions there instead of GitHub. This was borrowed from Nomad.
> Add new config

- .github/workflows/spectesting.yml
Multiple keys of the same name are not allowed. Instead, the "if's" can be evaluated as a boolean (and) expression
> Fix syntax error in spectesting.yml

- lib/vagrant/box.rb
- lib/vagrant/errors.rb
- templates/locales/en.yml
- test/unit/vagrant/box_test.rb
A Vagrant box must include a [`metadata.json`](https://www.vagrantup.com/docs/boxes/format) file which contains (at least) information about the box provider. This PR adds validation to ensure that is the case and raises an error if there is no provider entry in `metadata.json`
fixes: https://github.com/hashicorp/vagrant/issues/12829
> Raise error if required metadata.json box fields are not present

- internal/core/project.go
Fixes: https://github.com/hashicorp/vagrant/issues/12870 
Depends on: https://github.com/hashicorp/vagrant-plugin-sdk/pull/189
- Adds provider validation to the Vagrantfile core module
- Sets the target provider when provided to the Vagrantfile service
- Makes the provider in the Ruby service  always raise errors when running a `usable?` check
Now when running Vagrant:
```
% ./vagrant up --provider sadg
! Running of task up failed unexpectedly
! Error: rpc error: code = Unknown desc = failed to locate plugin `sadg`
% ./vagrant up --provider hyperv
! The Hyper-V provider only works on Windows. Please try to
use another provider.
% ./vagrant up                  
Bringing machine 'one' up with 'virtualbox' provider...
```
> Provider flag

- lib/vagrant/box_collection.rb
- lib/vagrant/errors.rb
- templates/locales/en.yml
- test/unit/vagrant/box_collection_test.rb
When a box version (or constraint) is provided with an invalid
format, rescue the error and return a customized error with
information for the user explaining the problem.
Fixes #12848
> Provide helpful error message on invalid version

- plugins/communicators/ssh/communicator.rb
Fixes https://github.com/hashicorp/vagrant/issues/12849
Since this fixes a flaky issue, it's a little challenging to reproduce. One way is to slightly change the command that is breaking to force it to be in the desired "broken" state. This diff will do that by forcing the `SSH_AUTH_SOCK` env var on the guest to be empty. 
```
diff --git a/plugins/communicators/ssh/communicator.rb b/plugins/communicators/ssh/communicator.rb
index 1d45096bb..47cd75b58 100644
--- a/plugins/communicators/ssh/communicator.rb
+++ b/plugins/communicators/ssh/communicator.rb
@@ -636,7 +636,7 @@ module VagrantPlugins
if @connection_ssh_info[:forward_agent] && sudo
auth_socket = ""
-              execute("echo; printf $SSH_AUTH_SOCK") do |type, data|
+              execute("export SSH_AUTH_SOCK=; echo; printf …
```
> Ensure last line from extracting the SSH_AUTH_SOCK is not nil

- lib/vagrant/machine.rb
- test/unit/vagrant/machine_test.rb
Per config.ssh documentation, `ssh.private_key_path` should use the default key path when not set. `ssh.keys_only = false` as worded does not prevent key based auth, it simply does not _limit_ to key based auth; setting `ssh.keys_only = false` should not change the default behavior for `ssh.private_key_path`.
Fixes #12884
> (#12884) Use default ssh.private_key_path when ssh.keys_only = false

- vagrant.gemspec
`"~> 1.41.1"` limits us to 1.41 which is already a year old now, relaxing this to `"~> 1.41"` allows us to pick up fresher and maintained releases.
@phinze you introduced this strict pin in a5f0064a86222ba55f0e162e16581ce1af8aaa69, any specific reason for going with this release?
> Relax overly strict grpc-tools version requirement

- plugins/hosts/linux/cap/nfs.rb
- test/unit/plugins/hosts/linux/cap/nfs_test.rb
- website/content/docs/synced-folders/nfs.mdx
Update the NFS exports write capability to use
a static file path when creating and moving the
updated file. Update documentation to match updated
implementation.
> Update NFS exports usage

- go.mod
- go.sum
- lib/vagrant/protobufs/proto/vagrant_plugin_sdk/plugin_pb.rb
This pr picks up the changes from https://github.com/hashicorp/vagrant-plugin-sdk/pull/193 for supporting colored input.
depends on https://github.com/hashicorp/vagrant-plugin-sdk/pull/193
>  Support colored input prompts

- lib/vagrant/util/downloader.rb
- test/unit/vagrant/util/downloader_test.rb
Prevents a space from being included on the
end of the user agent string for the downloader.
Fixes #12921
> Fix downloader user agent

- .github/workflows/testing.yml
- lib/vagrant/errors.rb
- plugins/providers/virtualbox/driver/meta.rb
- plugins/providers/virtualbox/driver/version_7_0.rb
- plugins/providers/virtualbox/plugin.rb
- templates/locales/en.yml
- test/unit/plugins/providers/virtualbox/driver/version_7_0_test.rb
Adds support for VirtualBox 7.0. The 7.0 driver includes a
port forward fix to account for missing port forward information
in the `showvminfo` output when more than one port forward has
been defined on a vm. This is been isolated to just the 7.0.0
VirtualBox release. It will revert to the original behavior on
the VirtualBox 7.0.1 release.
The VirtualBox extension pack was required to prevent the
`VBoxManage` executable from hanging on multiple executions. The
underlying cause of this has still not been determined and is
being investigated.
Fixes #12947 #12950
> Add support for VirtualBox 7.0

- website/redirects.js
This PR resets the redirects file to an empty array. Redirects that previously lived in this file have been moved to the `hashicorp/dev-portal` repository in https://github.com/hashicorp/dev-portal/pull/1277.
Note that docs-related redirects should still be added to this file.
> website: reset redirects file

- website/content/docs/providers/index.mdx
The [existing Hyper-V URL](https://en.wikipedia.org/wiki/Hyper-V) in the [Providers](https://developer.hashicorp.com/vagrant/docs/providers) page redirects to the Wikipedia page while VirtualBox and Docker URLs redirect to the official Docs. Maybe it's methodical to redirect the [Hyper-V](https://learn.microsoft.com/en-us/virtualization/hyper-v-on-windows/about/) URL to the official Microsoft [Hyper-V documentation](https://learn.microsoft.com/en-us/virtualization/hyper-v-on-windows/about/) as well. Hence suggesting the change in URL to the official doc -[https://learn.microsoft.com/en-us/virtualization/hyper-v-on-windows/about/](https://learn.microsoft.com/en-us/virtualization/hyper-v-on-windows/about/)
> Redirect the Hyper-V URL to the official Microsoft Hyper-V Doc

- lib/vagrant/util/install_cli_autocomplete.rb
This is a small one.
Me and a colleague were pairing on an unrelated issue and came across this small typo, so I decided to go ahead and fix it.
> Fixes typo in `lib/vagrant/util/install_cli_autocomplete.rb`

- website/content/docs/cli/up.mdx
Clarifying  the use of 'name' when running `vagrant up` as per the request from the [discuss forum](https://discuss.hashicorp.com/t/how-to-i-start-a-box-with-vagrant-up-using-the-box-name-instead-of-id/46002/5)
> Clarify using 'vagrant up name' must be run from within a Vagrant project

- plugins/providers/virtualbox/action/network.rb
- plugins/providers/virtualbox/driver/version_5_0.rb
- plugins/providers/virtualbox/driver/version_7_0.rb
- test/unit/plugins/providers/virtualbox/action/network_test.rb
- test/unit/plugins/providers/virtualbox/driver/version_7_0_test.rb
This PR adds support to the VirtualBox 7 driver for
`hostonlynets`. This was introduced to VirtualBox
on macOS for interacting with the vmnet framework. 
Usage of `hostonlynets` is isolated to only the
macOS platform via checks in the overrides so on
non-macOS platforms will still see the existing
behavior.
Fixes #12959
> Add hostonlynets support to VirtualBox driver

- vagrant.gemspec
No need to be so overly strict, this is a test dependency, so failures will surface immediately.
> Relax rspec dependency to ~> 3.11

- plugins/commands/serve/command.rb
Fixes #12988
Fixes https://github.com/mitchellh/vagrant-google/issues/266
> Fixes namespace of Google to global space

- lib/vagrant/util/install_cli_autocomplete.rb
- plugins/hosts/gentoo/host.rb
- plugins/hosts/slackware/host.rb
- plugins/provisioners/ansible/provisioner/host.rb
- plugins/provisioners/chef/config/chef_zero.rb
- test/unit/plugins/provisioners/ansible/provisioner_test.rb
The method File.exists? is [deprecated](https://ruby-doc.org/core-2.5.0/File.html).
In the release of Ruby 3.2.0 it is [removed](https://github.com/ruby/ruby/commit/bf97415c02b11a8949f715431aca9eeb6311add2).
Replace File.exists? with File.exist?.
> Replace deprecated File.exists? with File.exist?.

- plugins/provisioners/ansible/cap/guest/debian/ansible_install.rb
- test/unit/plugins/provisioners/ansible/cap/guest/shared/pip_ansible_install_examples.rb
Ran into this issue today dug through the code and resolved it with the following minor change. didn't see this reported in the issue list so if there is another plan to resolve this please close and i will wait for the updated version. Thanks
> Fixed issue provisioning ubuntu 22.04 python-dev has no install candidate

- lib/vagrant/errors.rb
- plugins/providers/virtualbox/driver/version_5_0.rb
- templates/locales/en.yml
- test/unit/plugins/providers/virtualbox/driver/version_5_0_test.rb
If the value of the machine folder can not be found in the
system properties, report a user friendly error message and
include relevant information in the logs for debugging.
Fixes #12968
> Handle missing machine folder value

- plugins/providers/virtualbox/driver/base.rb
- test/unit/plugins/providers/virtualbox/support/shared/virtualbox_driver_version_5_x_examples.rb
This forces the LANG enviroment variable to be set to `"C"` when
executing VBoxManage commands. Doing this prevents localization of
output which causes failures of the VirtualBox driver when scanning
for information.
Fixes #12968
> Force LANG when executing commands

- website/content/vagrant-cloud/api.mdx
This commit fixes some things with the Vagrant Cloud API docs:
* All `POST` calls did not explicitly specify `POST`.
* The `/api/v1/two-factor/request-code` call did not have the correct URL in the cURL example.
* I've also standardized the parameter order on all of the requests in the cURL example (method comes first) and also made a few style changes such as consistent interpolation of variable references.
> Some fixes for the Vagrant Cloud API docs

- plugins/providers/hyperv/scripts/utils/VagrantVM/VagrantVM.psm1
The 7.3.0 release of powershell cleaned up some stray things that
should require the import of the security module to be available.
It causes issues with pre-7.3 versions of powershell that attempt
to load the newer module so we run a check and restrict the module
version based on the powershell version.
Powershell change: https://github.com/PowerShell/PowerShell/pull/16355
Module import issue described here: https://github.com/PowerShell/PowerShell/issues/18530#issuecomment-1312446352
Fixes #12998
> Import the security module for access check

- plugins/providers/virtualbox/driver/version_7_0.rb
- test/unit/plugins/providers/virtualbox/driver/version_7_0_test.rb
Rescue any address errors logging them and ignoring the address. Update
how the host address is determined based on the network configuration.
Host address will be either the lowest address assignable via dhcp
configuration or first address available within the configured subnet.
Fixes #12996
> VirtualBox hostnet addressing

- lib/vagrant.rb
- lib/vagrant/shared_helpers.rb
- plugins/commands/serve/command.rb
Only load the dependencies needed for the serve command if the serve
command is being run. This allows Vagrant to properly load on platforms
where some of the dependency libraries may not be available due to
incompatibilities or being EOL.
Fixes #12997
> Isolate loading dependencies for serve command

- plugins/provisioners/ansible/cap/guest/debian/ansible_install.rb
- test/unit/plugins/provisioners/ansible/cap/guest/debian/ansible_install_test.rb
- test/unit/plugins/provisioners/ansible/cap/guest/shared/pip_ansible_install_examples.rb
This is the somewhat native and probably not the most elegant solution to fix #13016.
But using the guide [Installing Vagrant from Source](https://developer.hashicorp.com/vagrant/docs/installation/source), I tested my changes and vagrant is able to install pip and ansible without any errors and run ansible subsequently.
> Add workaround for Debian 10 and older

- plugins/providers/virtualbox/action/network.rb
- test/unit/plugins/providers/virtualbox/action/network_test.rb
When an address is provided and the type has not been explicitly
provided, parse the address and automatically set the type.
Fixes #12923 #12839
> Set address type when not provided

- website/content/docs/boxes/box_repository.mdx
- website/content/docs/boxes/format.mdx
- website/data/docs-nav-data.json
Split box format information from box repository information to avoid confusion between the metadata.json in the box and metadata for the a box repository.
fixes: https://github.com/hashicorp/vagrant/issues/13040
> Add information about Vagrant boxes

- plugins/providers/virtualbox/driver/version_7_0.rb
- test/unit/plugins/providers/virtualbox/driver/version_7_0_test.rb
In the VM config file port forward information is captured in the Snapshot defition as well as the VM definition. This causes duplicates in port forward entries if the file is queried for all available network adapters. Querying the VM config file for the the Network Adapters only part of the Machine definition resolves this and yields the most up to date port forward info.
fixes https://github.com/hashicorp/vagrant/issues/13044
> Read only machine port forward info

- plugins/communicators/ssh/communicator.rb
- test/unit/plugins/communicators/ssh/communicator_test.rb
This PR moves away from manually doing a SSH keep alive in another thread and instead depends on Netssh's keep alive feature. 
I'm pretty hesitant of touching this kind of [code that's been around forever](https://github.com/hashicorp/vagrant/commit/7fa9892b754b5aef7877a10a87cf875089c5f92c) but it looks like when this was implemented net-ssh was at version [2.6.6](https://github.com/hashicorp/vagrant/blob/7fa9892b754b5aef7877a10a87cf875089c5f92c/vagrant.gemspec#L22). Looks like keepalive functionality wasn't added until [2.7.0](https://github.com/net-ssh/net-ssh/blob/master/CHANGES.txt#L347). 
Fixes https://github.com/hashicorp/vagrant/issues/12783
> Use netssh builtin keep alive functionality

- plugins/synced_folders/rsync/helper.rb
- test/unit/plugins/synced_folders/rsync/helper_test.rb
This change will prepend "^" and append "/" if a start anchor is detected in the regex string. This allows users to specify relative paths to exclude.
It also removes replacing occurences of "*" with "[^/]*". "*" already expresses itself accurately.
This fixes `vagrant rsync-auto --poll`. Previously for a Vagrantfile
```
config.vm.box = "hashicorp/bionic64"
config.vm.synced_folder ".", "/vagrant", type: "rsync",
rsync__exclude: [".git/", "data/", "data/*", "data/**"]
end
```
with a `data` folder 
```
ls -lah | grep data
dr-x------   3 root    staff    96B Jan 19 16:27 data
```
The following error would be produced
```
% vagrant rsync-auto --poll
==> default: Doing an initial rsync...
==> default: Rsyncing folder: /Users/sophia/project/vagrant/ => …
```
> Process rsync exclude regex less

- website/content/docs/providers/hyperv/configuration.mdx
For context, see the conversation https://github.com/hashicorp/vagrant/issues/10349#issuecomment-435185440 .
I'm new to Vagrant and had some confusion when I couldn't find any boolean option to disable Dynamic Memory, which was apparently enabled by the image I was using.  I think explaining `nil` is a valid value may help others who end in in the same situation I was.
> Explain how to disable Dynamic Memory in Hyper-V

- plugins/provisioners/ansible/cap/guest/posix/ansible_installed.rb
- plugins/provisioners/ansible/provisioner/guest.rb
- plugins/provisioners/ansible/provisioner/host.rb
- test/unit/plugins/provisioners/ansible/provisioner_test.rb
Fixes #13010 
I'm using the rather "ugly" workaround with calling `importlib.metadata` via `python` and not any of the other alternatives mentioned in the issue because it's the most compatible. I cannot really expect people to have `pip` installed when checking for the initial version of `ansible`, and `ansible-community` wasn't a part of the standard distribution until fairly recently (6'ish?). To make sure we opt for the broadest amount of compatibility with Ansible versions, `pip` and Python I've chosen the lesser evil.
> Fix installing Ansible provisioner with version and pip

- lib/vagrant/util/platform.rb
Fixes the background issue where the vagrant failing where Get-WindowsFeature command is not available. 
Fixes #11932
> Vagrant is unable to execute Get-WindowsOptionalFeature Command #11932

- plugins/providers/virtualbox/action/check_virtualbox.rb
Virtualbox has supported running with hyperv since version 6.0.0 https://www.virtualbox.org/wiki/Changelog-6.0. (Virtualbox 6.0 is currently EOL) So, this check is no longer required.
This change is required for Virtualbox to work on Windows after https://github.com/hashicorp/vagrant/pull/11933 has been merged. https://github.com/hashicorp/vagrant/pull/11933 fixes the `windows_hyperv_enabled?` function.
Note, this removes the only use of `windows_hyperv_enabled?` in the Vagrant code base. Since this is a publicly available function I don't think it's appropriate to fully remove it for a point release.
> Removes check for hyperv being enabled when verifying virtualbox is usable on windows.

- plugins/communicators/ssh/communicator.rb
- test/unit/plugins/communicators/ssh/communicator_test.rb
- test/unit/plugins/communicators/winssh/communicator_test.rb
When connecting over ssh using net-ssh use the non_interactive argument must be set when authenticating with a password.
The "keyboard-interactive" options may be used as a default auth method, like in the net-ssh defaults (ref: https://github.com/net-ssh/net-ssh/blob/8a176a6ea0db1b59a21834df806a257a0b76e943/lib/net/ssh/config.rb#L52)
fixes https://github.com/hashicorp/vagrant/issues/13008
> Update connection settings when using a password to connect ssh

- lib/vagrant/action/builtin/box_add.rb
- lib/vagrant/errors.rb
- lib/vagrant/util.rb
- lib/vagrant/util/file_mutex.rb
- templates/locales/en.yml
- test/unit/vagrant/action/builtin/box_add_test.rb
- test/unit/vagrant/util/file_mutex_test.rb
Box's are global to Vagrant. Multiple Vagrant process can all access the box directory for both downloading and extracting boxes. A file mutex will ensure that multiple Vagrant process will not trample each other if they are trying to download the same box.
Now if multiple Vagrant process are trying to download the same box the process started first will successfully download and add the box. The second will display an error message:
```
-> % vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'centos/stream8' could not be found. Attempting to find and install...
default: Box Provider: virtualbox
default: Box Version: >= 0
==> default: Loading metadata for box 'centos/stream8'
default: URL: https://vagrantcloud.com/centos/stream8
==> default: Adding box …
```
> Add a file mutex when downloading box files.

- website/content/docs/plugins/provisioners.mdx
Updating the frontmatter of `website/content/docs/plugins/provisioners.mdx`. I'm pretty sure it should be `description`, not `script`. 💭
> docs: change frontmatter key from script to description

- lib/vagrant.rb
- lib/vagrant/plugin/v2/config.rb
- lib/vagrant/shared_helpers.rb
- test/unit/base.rb
Prevent protobuf loading when not in server mode. This allows proper
loading on platforms which don't have support for the protobuf
libraries.
The initial modifications only isolated the grpc related libraries
with the protobuf messages still be required so constants were
available. This change modifies that so the protos are also restricted
to being loaded only when in server mode.
Fixes #12997
> Isolate protobuf message loading to server mode

- .ci/build.sh
- .github/workflows/build.yml
Properly cleanup previous build artifacts, include commit ID
information, and prevent multiple build workflows from running
at once.
> Build updates

- plugins/kernel_v2/config/vm.rb
The final proto related constants were removed in #13031 but the proto
loading still remained. This removes the loading to prevent protos from
being loaded when not in server mode.
> Remove protobuf related loading from config

- plugins/providers/docker/driver.rb
- test/unit/plugins/providers/docker/driver_test.rb
Checks to make sure that a docker container is running before determining whether or not the port is in use. This prevents the a port on an inactive container from being treated as if it is use.
Fixes #13110 #12797
> Ignore inactive docker containers when assigning ports

- plugins/providers/docker/action.rb
Re-order the `SyncedFolders` to occur before `PrepareNFSSettings`, ensuring that the host & machine ips are set appropriately. 
Fixes https://github.com/hashicorp/vagrant/issues/12430
> docker: sync folders before preparing nfs settings

- plugins/providers/virtualbox/driver/base.rb
- test/unit/plugins/providers/virtualbox/driver/base.rb
- test/unit/support/shared/virtualbox_context.rb
The VirtualBox driver sets the LANG env var to prevent localized output
being returned when executing CLI commands. If the `locale` command is
present, do a best effort lookup to determine the properly value to use
for the LANG environment variable.
Fixes #13145
> Fix LANG value used for VirtualBox driver

- plugins/providers/virtualbox/driver/base.rb
- test/unit/plugins/providers/virtualbox/driver/base.rb
Update the locale preference list to prefer UTF-8 variations of `C` when
available.
Fixes #13145
> Update locale preference for the virtualbox driver

- lib/vagrant/util/file_mutex.rb
- test/unit/vagrant/util/file_mutex_test.rb
When unlocking the file mutex utility always unlock the file prior to
deletion to ensure the file can be properly deleted.
Fixes #13157
> Release file lock before file deletion

- plugins/commands/serve/command.rb
- plugins/commands/serve/constants.rb
Since the protos are only loaded when the serve command is invoked, move
the constant alias definitions into an isolated file so they are only
loaded when needed by the serve command
Fixes #13164
> Move constants to isolated file to be loaded on-demand

- plugins/provisioners/salt/bootstrap-salt.ps1
- plugins/provisioners/salt/bootstrap-salt.sh
- plugins/provisioners/salt/bootstrap_downloader.rb
- plugins/provisioners/salt/errors.rb
- plugins/provisioners/salt/provisioner.rb
- templates/locales/en.yml
- test/unit/plugins/provisioners/salt/bootstrap_downloader_test.rb
- test/unit/plugins/provisioners/salt/provisioner_test.rb
Verifies that the bootstrap-salt script that is downloaded during Salt provisioning time is verified against a SHA256 sum. It moves the script download to the host machine, where it is able to also download a corresponding SHA256 file, and compute and validate the two values. This removes the need for the shell scripts in the repo, but preserves the behavior of supplying your own.
> Salt: Verify bootstrap-salt download

- lib/vagrant/util/ssh.rb
- plugins/commands/ssh_config/command.rb
- plugins/kernel_v2/config/ssh_connect.rb
- templates/commands/ssh_config/config.erb
- test/unit/plugins/commands/ssh_config/command_test.rb
- test/unit/vagrant/util/ssh_test.rb
- website/content/docs/vagrantfile/ssh_settings.mdx
Recent versions of OpenSSH remove support of ssh-rsa key types and host
key algorithms from the default conection configuration. Set options to
enable them and provide a configuration option which can disable them if
required.
Fixes #13124
> Enable deprecated key type and host key algorithm

- plugins/communicators/ssh/communicator.rb
- test/unit/plugins/communicators/ssh/communicator_test.rb
- test/unit/plugins/communicators/winssh/communicator_test.rb
The keyboard-interactive authentication method was added due to a
mis-reading hashicorp/vagrant#13008. In that issue it was reported
that Vagrant wasn't properly connecting to a guest using password
based authentication. However, upon further inspection of the debug
output provided in that issue, the root cause was the guest sshd not
being properly configured to allow password authentication.
The keyboard-interactive authentication method has been backed out as
properly configured Vagrant boxes do not require interaction for
authentication. This also resolves an issue introduced by the placement
of the keyboard-interactive auth method which can result in authentication
hanging waiting for user input before reaching key based authentication.
Fixes #13171 #13191
> Remove keyboard-interactive authentication method

- plugins/provisioners/salt/provisioner.rb
* fix minion detection on Windows
* use new command-line option `-ConfigureOnly` to tell
bootstrap not to try installing minion (on Windows)
* fix highstate commands on Windows
Fixes GH-10531
I'm not familiar with the testing arrangements for this project so if the PR needs tests let me know where and how
> Fix Salt provisioner for Windows guests

- .github/workflows/go-spectest-skipped.yml
- .github/workflows/go-spectest.yml
- .github/workflows/go-testing-skipped.yml
- .github/workflows/go-testing.yml
- .github/workflows/testing-skipped.yml
- .github/workflows/testing.yml
Required tests that are skipped based on path matching need to have an
inverse match with the same name that always succeeds to allow the tests
to be marked as passing.
This approach is described in [this article](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/troubleshooting-required-status-checks#handling-skipped-but-required-checks).
> Handle skipped required tests

- templates/locales/en.yml
When an extension fails to build due to missing libraries on the local
system, call out that it is the development files that are misssing and
when installing the library via a package manager it will likely require
the library's development package.
Fixes #13184
> Clarify missing library error

- lib/vagrant/action/builtin/box_add.rb
- lib/vagrant/action/builtin/box_check_outdated.rb
- lib/vagrant/action/builtin/handle_box.rb
- lib/vagrant/util/downloader.rb
- plugins/kernel_v2/config/vm.rb
- test/unit/vagrant/action/builtin/box_add_test.rb
- test/unit/vagrant/action/builtin/box_check_outdated_test.rb
- test/unit/vagrant/util/downloader_test.rb
- website/content/docs/vagrantfile/machine_settings.mdx
When performing a request via curl on Windows using schannel, ssl
certificate revocation checks does not handle verification failures
gracefully when an error is encountered that is unrelated to the actual
revocation of a certificate.
A new option is available to perform best effort revocation checks on
curl, so this is enabled by default on the Windows platform. A new
config option (`box_download_disable_ssl_revoke_best_effort`) has also
been added which can be optionally enabled to restore previous behavior
which results in a hard error if any error is encountered.
More context for this can be found in [this](https://github.com/curl/curl/issues/3727) curl issue and [this](https://github.com/curl/curl/pull/4981) curl PR
which adds support for best effort revocation check.
Fixes #13102
> Perform best effort ssl revocation check on Windows

- lib/vagrant/box_collection.rb
from bsdtar's man page:
```
-S      (x mode only) Extract files as sparse files.  For every block on disk, check first if it contains only NULL bytes and seek over it otherwise.  This works similar
to the conv=sparse option of dd.
```
This is particularly important when dealing with MacVMs that use a raw disk image file that can't be resized after creation. A MacVM's `disk0.img` that it uses as its primary boot device is sparsely allocated so typically you want to size it fairly large since you don't get another opportunity to. In the current state, this unfortunately causes Vagrant box sizes to be huge and can cause space issues trying to work with a single VM since you need...
1. temporarily the size of the compressed box + the extracted box living at `~/.vargant.d/boxes` then...
2. the …
> use the -S flag with bsdtar for sparse extraction of boxes

- plugins/providers/virtualbox/action/network.rb
To distinct between IPv4 and IPv6 configuration, a "6" was added to the network configuration type if an IPv6 address should be configured. This is now duplicate, as with pull [13024](https://github.com/hashicorp/vagrant/pull/13024) the same thing is already done prior and more globally, thus leading to a duplicate "6" at the end of the network config type, i.e. "static66".  
Tested on my local system without breakage using a "private_network" config, but I was unable to extensively test this.
> Remove duplicate appending of "6" to network type

- lib/vagrant.rb
A path check is done prior to loading the vagrant ssl helper, but it was
only checking for a file with a `.so` suffix so `.bundle` files on macos
would be ignored and the helper not loaded.
Include both paths when checking for the library existence.
Fixes #13273
> Fix SSL helper loading on macOS

- lib/vagrant/util/platform.rb
- test/unit/vagrant/util/platform_test.rb
Specifically for Windows hosts, the target CPU string will report as
`x64`, not `x86_64`. Include the value in the mapping to get the
properly value.
Fixes #13274
> Update CPU mapping values

- lib/vagrant/box_collection.rb
- test/unit/vagrant/box_collection_test.rb
When the box collection includes a common box entry which contains
architecture information, and another entry that does not it will
result in an error when sorting due to comparison with a nil value. 
Force a common type when sorting to prevent this error.
Fixes #13314
> Fix box collection sorting

- templates/commands/init/Vagrantfile.erb
This PR fixes a minor typo in the Vagrantfile.erb template:
`accessable` -> `accessible`
> fix(typo): Fix minor typo in Vagrantfile.erb template

- lib/vagrant.rb
- lib/vagrant/errors.rb
- lib/vagrant/patches/net-ssh.rb
- lib/vagrant/util.rb
- lib/vagrant/util/keypair.rb
- plugins/communicators/ssh/communicator.rb
- plugins/kernel_v2/config/ssh_connect.rb
- templates/locales/en.yml
- test/unit/plugins/communicators/ssh/communicator_test.rb
- test/unit/plugins/kernel_v2/config/ssh_connect_test.rb
- website/content/docs/vagrantfile/ssh_settings.mdx
Adds support for generating ecdsa ssh key pairs. This was prompted
by #13323 which raised the issue of ed25519 keys not being FIPS
compliant and causing connection issues. This PR adds a new option
to the ssh configuration providing the ability to specify a desired
key type:
```ruby
config.ssh.key_type = :ecdsa521
end
```
Some monkey patching to the net-ssh library is included with this
PR that will be removed once the modifications can be added upstream.
Fixes #13323
> Add support for ecdsa ssh keys

- plugins/provisioners/ansible/cap/guest/redhat/ansible_install.rb
Add support for RHEL 8 and >8 for ansible pip-installation
Fixes #13316 and #11299
> Support ansible pip-installation for RHEL 8 and greater

- lib/vagrant.rb
- lib/vagrant/patches/builder/mkmf.rb
- lib/vagrant/patches/rubygems.rb
As reported in #13322 Vagrant fails to install plugins with extensions
due to spaces in Windows paths causing errors. Further investigation
found that just quoting the paths used in the flags set by the Vagrant
launcher would not resolve the issue due to how gem authors may
be configuring the build. For example [nokogiri appends environment flags](https://github.com/sparklemotion/nokogiri/blob/b84cc66693c68fb901c0d38317d61b110b10a0fd/ext/nokogiri/extconf.rb#L649)
using `String#split` which improperly splits paths that include spaces
even if they are quoted.
To work around this, the MakeMakefile module needs to be patched to
properly quote any unquoted paths found within flags that may exist.
The module is required into `extconf.rb` files directly, however,
thus can't be patched directly. …
> Patch MakeMakefile for extension builds

- plugins/communicators/ssh/communicator.rb
Prevent newlines from being converted to CRLF when writing private key
to file.
Fixes #13284
> Open private key file in binary mode when writing

- vagrant.gemspec
Updates the vagrant_cloud dependency constraint to a minimum of 3.1.1
which includes a path prefixing fix that resolves an issue affect direct
uploads to Vagrant Cloud.
Fixes #13319
> Update vagrant_cloud dependency constraint

- plugins/communicators/ssh/communicator.rb
- test/unit/plugins/communicators/ssh/communicator_test.rb
Updates the SSH communicator to inspect the guest sshd configuration for
supported key types when creating a new key to replace the default
insecure public key. If the guest cannot be inspected, the connection
will be inspected. If the connection cannot be inspected, it will simply
fall back to the original behavior of using an rsa type key.
Fixes #13271
> Inspect guest for supported key types

- .github/workflows/go-spectest-skipped.yml
- .github/workflows/go-spectest.yml
- .github/workflows/go-testing-skipped.yml
- .github/workflows/go-testing.yml
- .github/workflows/testing-skipped.yml
- .github/workflows/testing.yml
- vagrant.gemspec
> Relax ruby version constraint to allow Ruby 3.3

- lib/vagrant/bundler.rb
When resolving for a plugin while within the installer, force strict
dependencies for all the default gems to prevent the resolver from
generating solutions where it may attempt to upgrade any of them. If
running within bundler, retain the same behavior and ignore them.
Fixes #13261
> Force strict dependencies for default gems

- plugins/providers/docker/driver.rb
This fixes a bug in the docker provider where Vagrant crashes on checking config.size when it is nil. The fix is just checking if config.size is defined?() before checking the value of it.
Here is the error message:
```
❯ vagrant up --provision-with basetools,docker,vault,consul,nomad --provider docker
Bringing machine 'hashiqube0.service.consul' up with 'docker' provider...
==> hashiqube0.service.consul: Creating and configuring docker networks...
/opt/vagrant/embedded/gems/gems/vagrant-2.4.0/plugins/providers/docker/driver.rb:352:in `block in network_defined?': undefined method `size' for nil:NilClass (NoMethodError)
if (config.size > 0 &&
^^^^^
from /opt/vagrant/embedded/gems/gems/vagrant-2.4.0/plugins/providers/docker/driver.rb:350:in `each'
from …
```
> Fix undefined method `size' for nil:NilClass in network_defined?

- website/content/vagrant-cloud/hcp-vagrant/migration-guide.mdx
- website/content/vagrant-cloud/hcp-vagrant/troubleshooting.mdx
- website/data/alert-banner.js
- website/data/vagrant-cloud-nav-data.json
This PR adds two doc pages.
I made a few changes from the google doc specifically
- adding a note banner to the top of the migration guide to highlight our impending site migration
- dropped the screenshots. First because resolving the image path was frustrating but primarily because that would bring the guide more into alignment with the rest of the docs site and because the migration tool is so straight forward that the screenshots weren't terribly helpful.
> Add HCP-Vagrant docs section with Migration Guide & Troubleshooting pages

- website/content/vagrant-cloud/hcp-vagrant/migration-guide.mdx
I forgot a space between the website migration note and the 1st paragraph. This fixes that
> fix spacing on 1st paragraph & migration note

- website/content/vagrant-cloud/hcp-vagrant/post-migration-guide.mdx
- website/data/vagrant-cloud-nav-data.json
Includes information related to post migration including Vagrant Cloud
behavior and API usage.
> Add post migration information

- website/content/vagrant-cloud/hcp-vagrant/migration-guide.mdx
In the conclusion the link to the troubleshooting guide had a space in it. Hopefully that's the only issue.
> Migration guide link typo

- plugins/kernel_v2/config/vm.rb
- templates/locales/en.yml
After struggling quite some time I figured out I had an issue caused by setting an IPv6 ending with :1 
The network_ip_ends_in_one warning message is use for IPv4 to warn user about this matter, I would like to add this warning to IPv6 to avoid some painful debug time to future IPv6 users
> Adding warning for IPv6 ending with 1

- plugins/providers/virtualbox/driver/meta.rb
As reported in https://www.virtualbox.org/ticket/22060, starting with Virtualbox 7.0.16 running:
```
$ vboxmanage --version
WARNING: Environment variable LOGNAME or USER does not correspond to effective user id.
7.0.18r162988
```
the warning line is written to stdout which is an issue since the parsing of the version is used in the provider code to use the correct class to handle following communication with Virtualbox.
This PR improves the version detection by parsing the version in the first line that does not start with `WARNING:`.
> virtualbox version detection: handle WARNING lines

- lib/vagrant/util/file_checksum.rb
As the title says.
Fix is quite simple, forces the `type` to be downcased while getting it from `CHECKSUM_MAP`.
Let me know if I need to fix anything and if it's acceptable or needs more work!
> possible fix for #13470

- plugins/synced_folders/nfs/synced_folder.rb
- templates/locales/en.yml
When mounting lots of NFS folders it would be good to get some sort of feedback to know what it's doing.
This is the same as the vboxsf message:
https://github.com/hashicorp/vagrant/blob/main/plugins/providers/virtualbox/synced_folder.rb#L43-L5
https://github.com/hashicorp/vagrant/blob/main/templates/locales/en.yml#L2704
> NFS Folder Mounting message

- plugins/synced_folders/unix_mount_helpers.rb
in openwrt, /sbin/init --version does not print the version, instead it calls init, which breaks the running system
this was already fixed in https://github.com/hashicorp/vagrant/pull/7813 but somehow was lost in later code changes
> fix openwrt nfs synched folders

- plugins/provisioners/ansible/provisioner/host.rb
- test/unit/plugins/provisioners/ansible/provisioner_test.rb
When not forcing `ansible.compatibility_mode`, Vagrant tries to gather the Ansible version using the `gather_ansible_version` function.
This seems to be incorrectly quoted / escaped.
Fixes https://github.com/hashicorp/vagrant/issues/13234
The noted fix from the issue is being implemented in this PR.
Before:
```bash
vagrant provision
==> hostname: Running provisioner: ansible...
Vagrant gathered an unknown Ansible version:
and falls back on the compatibility mode '1.8'.
```
after:
```bash
vagrant provision
==> hostname: Running provisioner: ansible...
hostname: Running ansible-playbook...
```
Tested with the following versions on MacOS;
`ansible [core 2.15.8]`
`python version = 3.9.16`
`Vagrant 2.4.1` and `Vagrant 2.4.0`
```python
Python 3.9.16 (main, Jun  6 2023, 11:35:35)
[Clang 14.0.3 …
```
> provisioner/ansible: Fix ansible version gathering in host provisioner

- plugins/providers/docker/driver.rb
- test/unit/plugins/providers/docker/driver_test.rb
Sometimes the host network has a nil config, causing a crash on vagrant up when checking the docker networks.
See #13371 for more details of the bug this fixes
> Check if the docker config is nil, fixes #13371

- vagrant.gemspec
base64 will no longer be the default gem in the Ruby 3.4, without this patch following warning message may come from ruby 3.3+
/opt/vagrant/lib/vagrant/util/powershell.rb:4: warning: base64 was
loaded from the standard library, but will no longer be part of the
default gems since Ruby 3.4.0. Add base64 to your Gemfile or gemspec.
See https://github.com/thinreports/thinreports-generator/pull/134
> Add base64 to the gemspec

- plugins/providers/docker/driver.rb
- test/unit/plugins/providers/docker/driver_test.rb
> Properly match container ID when trailing content exists

- plugins/providers/docker/command/exec.rb
- test/unit/plugins/providers/docker/command/exec_test.rb
Updates the passing of `exec_options` as kwargs to the docker local executor, where passing without the `**` was deprecated in Ruby 2.7 and broke in 3.0. Without the double splat, the hash was passed as an element in the `exec_cmd` (splatted) array.
fixes #13388
> Pass docker exec_options to executor as kwargs

- plugins/providers/docker/driver.rb
- test/unit/plugins/providers/docker/driver_test.rb
When checking if a docker image exists or should be rebuilt during a `vagrant up`, check the image presence against the full  & not truncated list of docker images ids (`docker images -q --no-trunc`). Adjusts the regex matching to account for additional characters in the not truncated output, which has been added as a test case. 
fixes #13384
> Match docker image id on full output from list when building

- plugins/hosts/bsd/cap/nfs.rb
- plugins/hosts/bsd/plugin.rb
- plugins/synced_folders/nfs/synced_folder.rb
- test/unit/plugins/hosts/bsd/cap/nfs_test.rb
Updates the `nfs_restart_command` for darwin hosts to use `update` instead of `restart`, after mac Sonoma update. Also adjusts the nfs mount log to run within the block, so it can access the opts hash. 
fixes #13364
> Use `nfsd update` command for restart 

- plugins/providers/virtualbox/action.rb
- test/unit/vagrant/action/builtin/wait_for_communicator_test.rb
When a virtualbox vm is booting initially, allow it to enter the `:paused` state and wait until a new state is entered or the boot_timeout is reached. This allows the GUI menu to be accessed and state selected before it errors, but to still error as expected if the outcome of the selection moves the vm to an invalid state. This matches how previous versions of virtualbox behaved, before the `:paused` state was introduced.
Also adds some simple tests for `WaitForCommunicator`, which came up as I was investigating different ways to address the issue
fixes #13410
> Update provider/virtualbox to allow paused state when booting vm

- plugins/kernel_v2/config/vm.rb
Solve error: undefined method `end_with?' for nil:NilClass (NoMethodError)
This commit fix problem related to commit 1a576716b93a5b736a280c314ac4a24104754459
> Fixed conditions in network_ip_ends_in_one

- vagrant.gemspec
This fixes snakecase errors that may be encountered with the
winrm communicator.
> Bump winrm constraint

- vagrant.gemspec
logger and ostruct will no longer be the default gem in the Ruby 3.5, without this patch following warning message may come from ruby 3.3+
```
/opt/vagrant/lib/vagrant/patches/net-ssh.rb:4: warning: logger was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.5.0.
You can add logger to your Gemfile or gemspec to silence this warning.
/usr/lib/ruby/3.3.0/json/common.rb:3: warning: ostruct was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.5.0.
You can add ostruct to your Gemfile or gemspec to silence this warning.
```
> Add logger and ostruct to the gemspec

- plugins/provisioners/ansible/provisioner/base.rb
Vagrant does an Ansible version check in the Ansible provisioner to determine which compatibility mode to use. The latest version of Ansible is Ansible 10 and this check fails in Vagrant when using Ansible 10.
```
% python3 -c "import importlib.metadata; print('ansible ' + importlib.metadata.version('ansible'))"
ansible 10.3.0
```
This is the first time that double digits are used in an Ansible major version. The regex that is used to determine the major version in Vagrant only checks a single digit. So in this case it matches to 0, which in turn will trigger compatibility mode 1.8 instead of 2.0. Compatibility mode 1.8 uses [sudo](https://github.com/hashicorp/vagrant/blob/main/plugins/provisioners/ansible/provisioner/base.rb#L28) in the command, instead of …
> Fix double digits Ansible version match

- lib/vagrant/patches/net-ssh.rb
Updates the version constraint defined for net-ssh patching to
include current lastest release.
> Bump version constraint for patching

- plugins/provisioners/salt/bootstrap_downloader.rb
This is a fix of URLs that were broken today, see https://saltproject.io/blog/salt-bootstrap-breakage/ for more details
One more update: https://saltproject.io/blog/salt-bootstrap-breakage-part-2/
> Fix Salt bootstrap script URLs

- plugins/providers/docker/driver.rb
- test/unit/plugins/providers/docker/driver_test.rb
Fixes https://github.com/hashicorp/vagrant/issues/13342 adding another regex for the docker log format with containerd storage enabled.
Another approach would be to use the `--iidfile` parameter of docker build to have the id written to a file. This would be less brittle than trying to keep up with different docker/podman log outputs. A working prototype is here https://github.com/tnaroska/vagrant/commit/c8073cf440e401b35ce0a4ce78bd73e8ac33b7c7 This would require more elaborate changes in the unit tests though.
> Fix#13342 adapt docker provider build for containerd storage

- plugins/providers/virtualbox/driver/base.rb
Incompatible encodings will result in an error when the exception
is translated. The outputs may not be UTF-8 encoded so force
the encoding when providing the values in the exception.
Fixes #13515
> Force encoding on command output strings

- bin/vagrant
During startup get the vagrant specification and activate all the
runtime dependencies required by vagrant. This will prevent invalid
specifications from being activated later if environment includes
mixed versions.
> Activate specifications at startup

- vagrant.gemspec
Vagrant version 2.4.2 introduced a patch(512bb74) that sets the logger gem dependency to "~>1.6.1", which is too strict and prevents many Vagrant plugins from being installed.
This patch tones down the dependency specification to mitigate this problem.
Fixes #13527.
Refer-to: Add logger and ostruct to the gemspec by hswong3i · Pull Request #13499 · hashicorp/vagrant <https://github.com/hashicorp/vagrant/pull/13499>
I'm not acquainted with Ruby, RubyGems, and the usage of the `logger` gem in Vagrant, please review.
> Fix overly strict dependency requirement of the logger gem to allow plugin installation

- lib/vagrant/util/curl_helper.rb
- lib/vagrant/util/downloader.rb
- plugins/commands/cloud/auth/middleware/add_downloader_authentication.rb
- plugins/commands/cloud/client/client.rb
- vagrant.gemspec
Updates the minimum constraint for the `vagrant_cloud` gem dependency. Cleans up some of the client wrapper within the cloud plugin. Updated `vagrant_cloud` gem provided authentication now handles HCP based authentication.
> Update authentication handling

- website/content/vagrant-cloud/hcp-vagrant/migration-guide.mdx
- website/content/vagrant-cloud/hcp-vagrant/post-migration-guide.mdx
Include information about HCP token generation.
> Add post-migration auth info

- website/content/intro/support.mdx
- website/content/vagrant-cloud/api/v1.mdx
- website/content/vagrant-cloud/api/v2.mdx
- website/content/vagrant-cloud/boxes/catalog.mdx
- website/content/vagrant-cloud/hcp-vagrant/migration-guide.mdx
- website/content/vagrant-cloud/hcp-vagrant/troubleshooting.mdx
- website/content/vagrant-cloud/index.mdx
- website/content/vagrant-cloud/request-limits.mdx
- website/content/vagrant-cloud/support.mdx
- website/content/vagrant-cloud/users/recovery.mdx
- website/data/intro-nav-data.json
Adds a Support page to the `Intro` section of the vagrant docs. Then replaces all references to the support email with a link to contact support that takes users to the blurb on how to file a support ticket.
This PR replaces #13567, because a vercel outage led to that PR getting a bit cluttered.
> Remove references to support email address

- lib/vagrant/box.rb
- lib/vagrant/box_collection.rb
- lib/vagrant/box_metadata.rb
- plugins/commands/box/command/outdated.rb
- test/unit/plugins/commands/box/command/outdated_test.rb
- test/unit/vagrant/box_metadata_test.rb
When a requesting to check an outdated box or update a box, add an explicit architecture compatibility check in addition to ensuring the version is newer than before.
The architecture compatibility checks allow boxes that were marked as an "unknown" architecture to see new "unknown" architectures as viable update options, if an architecture specific provider is not available. In the scenario that the existing version/provider has an explicit architecture defined, a new version/provider with an "unknown" architecture is not considered compatible.
This architecture check can be bypassed by explicitly setting `config.vm.box_architecture = nil` in the Vagrantfile.
This also fixes an issue where if architecture wasn't defined in the metadata at all, it also wouldn't detect newer versions. …
> Fix architecture constraint in `box outdated` commands

- lib/vagrant.rb
- lib/vagrant/patches/timeout_error.rb
- plugins/communicators/ssh/communicator.rb
- plugins/communicators/winrm/shell.rb
- test/unit/plugins/communicators/winrm/shell_test.rb
Ruby 3.2 introduced a new error, `IO:TimeoutError`, for blocking operations. Formerly, this case would return `Errno::ETIMEDOUT`. Catch the new error while waiting for the communicator so that the retries can be correctly attempted.
https://bugs.ruby-lang.org/issues/18630
Fixes https://github.com/hashicorp/vagrant/issues/13559
> Catch IO::Timeout when waiting for communicator

- vagrant.gemspec
Bumps the versions of `wdm` and `childprocess` gems, which support ruby 3.x
> Bump wdm, childprocess gem constraints

- plugins/providers/docker/driver.rb
- test/unit/plugins/providers/docker/driver_test.rb
Handles the slightly different error text when podman backend is used:
```
Stderr: Error response from daemon: image xxx is in use: image used by yyy: image is in use by a container: consider listing external containers and force-removing image
```
Fixes #13563
> docker provider: handle variation in error text during image removal

- contrib/sudoers/osx
- website/content/docs/synced-folders/nfs.mdx
current vagrant (2.4.3) on macOS invokes nfs with at least two other arguments (status & update) rather than just restart
Fix #13582 @allisonlarson
> update to macOS documentation

- .ci/build
This removes the binary build steps from the build script as the binaries are not longer included when generating the packages.
> Remove binary generation from build script

- plugins/providers/virtualbox/model/storage_controller.rb
- plugins/providers/virtualbox/model/storage_controller_array.rb
This minor change, adds virtio-scsi storage controller to the list of supported. closes #13586
Also it changes formatting of exception
From
> Vagrant was unable to detect a disk controller with any of the
> following supported types:
> 
> **IntelAhci ,PIIX4 ,PIIX3 ,ICH6 ,LsiLogic ,BusLogic**
> 
> Please add one of the supported controller types in order to use the
> disk configuration feature.
To
> ...
> IntelAhci, PIIX4, PIIX3, ICH6, LsiLogic, BusLogic
> ...
> Add VirtioSCSI to the list of supported storage controllers for VirtualBox

- plugins/hosts/darwin/cap/fs_iso.rb
Currently `create_iso` in darwin produces CD image with hybrid format HFS+ISO 9660 This is less interoperable than ISO 9660 alone. In particular, CD label is not readable by the `udev` and breaks some automated configuration system.
Here are the command output on Ubuntu guest:
|   | HFS+ISO 9660 | ISO 9660 |
|---|---|---|
| `sudo blkid -o udev -p /dev/sr0` | ID_PART_TABLE_TYPE=mac | ID_FS_FSBLOCKSIZE=2048<br>ID_FS_BLOCK_SIZE=2048<br>ID_FS_FSSIZE=55296<br>ID_FS_SYSTEM_ID=APPLE\x20INC.\x2c\x20TYPE:\x200002<br>ID_FS_VOLUME_SET_ID=<br>ID_FS_PUBLISHER_ID=<br>ID_FS_DATA_PREPARER_ID=<br>ID_FS_APPLICATION_ID=<br>ID_FS_UUID=2024-12-29-15-35-20-00<br>ID_FS_UUID_ENC=2024-12-29-15-35-20-00<br>ID_FS_VERSION=Joliet\x20Extension<br>ID_FS_LABEL=cidata<br>ID_FS_LABEL_ENC=cidata<br>ID_FS_TYPE=iso9660<br>ID_ …
> Use ISO 9660 format in create_iso under darwin

- plugins/guests/redhat/cap/configure_networks.rb
- plugins/guests/redhat/cap/network_scripts_dir.rb
- templates/guests/redhat/network_manager_device.erb
- test/unit/plugins/guests/redhat/cap/configure_networks_test.rb
- test/unit/plugins/guests/redhat/cap/network_scripts_dir_test.rb
Recent versions of RHEL based guests have updated network configuration.
Detect the correct location of the network configuration files, and
configure the guest based on the detected location.
Fixes #13616
> Update RHEL guest networking

- plugins/guests/amazon/cap/configure_networks.rb
- plugins/guests/amazon/plugin.rb
- plugins/guests/debian/cap/configure_networks.rb
- test/unit/plugins/guests/amazon/cap/configure_networks_test.rb
- test/unit/plugins/hosts/darwin/cap/fs_iso_test.rb
Adds suppport for configuring networking on amazonlinux when
network devices are handled by networkd. When not handled by
networkd, falls back to using the redhat capability.
Fixes #13358
> Update amazonlinux guest network configuration

- website/content/docs/cli/validate.mdx
**Changes:**
- Added an example demonstrating how to validate a Vagrantfile while ignoring provider-specific configurations:
Fix:#13603
> Update documentation for the Vagrant validate command

- lib/vagrant/machine.rb
- plugins/communicators/ssh/communicator.rb
- plugins/kernel_v2/config/ssh_connect.rb
- templates/locales/en.yml
- test/unit/plugins/communicators/ssh/communicator_test.rb
- test/unit/plugins/kernel_v2/config/ssh_connect_test.rb
- website/content/docs/vagrantfile/ssh_settings.mdx
- website/data/intro-nav-data.json
Adds two new options to the SSH connect configuration: `connect_retries`
and `connect_retry_delay`. Provides user configurable values used when
establishing the SSH connection. Previous behavior would retry generally
by the default value without a pause between attempts. Updated behavior
will retry the number of times set within the config (unless value is
provided directly to connect call) and each retry will pause based on
the delay value set in the config (unless value is provided directly
to the connect call).
Fixes #13047
> Provide configurable retries for connect on SSH communicator

- templates/guests/alpine/network_dhcp.erb
- test/unit/plugins/guests/alpine/cap/configure_networks_test.rb
Updates the alpine guest network configuration for public network
entry with `use_dhcp_assigned_default_route` to use the `udhcpc`
command instead of the `dhclient` command which is not included.
Fixes #13605
> Fix alpine networking for public network

- plugins/providers/hyperv/cap/configure_disks.rb
- test/unit/plugins/providers/hyperv/cap/configure_disks_test.rb
Select the first disk as the primary disk when locating the
primary disk within the hyperv provider.
Fixes #13632
> Update primary disk detection in hyperv

- plugins/providers/virtualbox/action/network.rb
- test/unit/plugins/providers/virtualbox/action/network_test.rb
When provided a name for the hostonly network in the VirtualBox
provider, always use the interface name in the final configuration.
Fixes #13620
> Use interface name for hostonly network configuration

- plugins/synced_folders/smb/cap/mount_options.rb
- test/unit/plugins/synced_folders/smb/caps/mount_options_test.rb
The `nofail` option results in failures being improperly suppressed
resulting in a successful run with a failed mount. Removing this
option so mounting failures will properly fail the process.
Fixes #13579
> Remove nofail option from smb synced folder mount options

- lib/vagrant/util/powershell.rb
- test/unit/vagrant/util/powershell_test.rb
- website/content/docs/other/environmental-variables.mdx
Prefer to use the pwsh executable over the powershell executable
as the pwsh exectuable will be faster loading than the powershell
executable. If the pwsh executable is not found, the powershell
executable will be used instead. The preference can be overridden
using the VAGRANT_PREFERRED_POWERSHELL environment variable.
> Prefer pwsh executable over powershell excutable

- lib/vagrant/bundler.rb
When building the internal specs collection, multiple specifications
may exist due to default gems. When building the collection, always
set the specification with the greater version. This change prevents
multiple versions of the same gem attempting to be activated.
Fixes #13652
> Properly handle multiple versions for internal specs

- vagrant.gemspec
Remove dependencies from the gemspec for libraries that
are no longer in use.
> Remove library dependencies

- plugins/communicators/none/communicator.rb
- plugins/communicators/none/plugin.rb
- test/unit/plugins/communicators/none/communicator_test.rb
Adds a communicator which does not provide communication to the
guest machine. All methods for the communicator are simply stubbed
with a successful result. This allows a guest to be configured
with the `:none` communicator and Vagrant to properly `up` it.
Basic functionality described in #13619
> Add a `:none` communicator

- plugins/providers/virtualbox/action/network.rb
- plugins/providers/virtualbox/driver/base.rb
- plugins/providers/virtualbox/driver/meta.rb
- plugins/providers/virtualbox/driver/version_4_0.rb
- plugins/providers/virtualbox/driver/version_4_1.rb
- plugins/providers/virtualbox/driver/version_4_2.rb
- plugins/providers/virtualbox/driver/version_4_3.rb
- plugins/providers/virtualbox/driver/version_5_0.rb
- plugins/providers/virtualbox/driver/version_7_0.rb
- test/unit/plugins/providers/virtualbox/action/network_test.rb
- test/unit/plugins/providers/virtualbox/driver/version_5_0_test.rb
- test/unit/plugins/providers/virtualbox/support/shared/virtualbox_driver_version_4_x_examples.rb
- test/unit/plugins/providers/virtualbox/support/shared/virtualbox_driver_version_7_x_examples.rb
Include network display name within the output of the
`#read_host_only_interfaces` driver method. When matching
the private network name, use the `#read_host_only_interfaces`
method and not the `#read_host_only_networks` method which
is darwin specific. Backport the `display_name` inclusion
to old driver versions for consistent behavior.
Fixes #13655
> Fix VirtualBox private network setup

- lib/vagrant/action/builtin/box_add.rb
- lib/vagrant/box_metadata.rb
- lib/vagrant/errors.rb
- templates/locales/en.yml
- test/unit/vagrant/box_metadata_test.rb
This adjusts the failure detection and errors raised when a box
cannot be added. New errors are added for when a requested provider
on a box does not support an architecture, and for when the no
providers on a box support an architecture. When box supports
an architecture but not with the requested provider, a list of
supported providers will be returned in the error message. If
a version constraint is requested and cannot be satisfied due
to provider and architecture filtering, the list of valid versions
will be provided.
Small change to the version list in the error output: the list
has been reversed so the most recent versions are listed first.
Fixes #13552
> Make box add failure messages more helpful

- plugins/providers/virtualbox/action/network.rb
- test/unit/plugins/providers/virtualbox/action/network_test.rb
Since VirtualBox 6.1.28, if you want to create a host-only network,
virtualbox checks if the ip is in a certain range.
According to the manual (https://www.virtualbox.org/manual/ch06.html),
ipv6 link-local addresses are allowed so add the IPv6 link-local range.
> Allow link-local IPv6 address on host-only network

- lib/vagrant/action/builtin/cloud_init_setup.rb
- lib/vagrant/action/builtin/cloud_init_wait.rb
- lib/vagrant/action/builtin/disk.rb
- lib/vagrant/util/file_checksum.rb
- lib/vagrant/util/mime.rb
- plugins/kernel_v2/config/vm.rb
- plugins/providers/virtualbox/action.rb
- test/unit/vagrant/action/builtin/cloud_init_setup_test.rb
- test/unit/vagrant/action/builtin/cloud_init_wait_test.rb
- test/unit/vagrant/action/builtin/disk_test.rb
- website/content/docs/vagrantfile/machine_settings.mdx
This includes a couple modifications to the cloud-init behavior.
First, the cloud-init wait action will now write a sentinel file
after successfully waiting for cloud-init. This results in subsequent
boots of the machine to skip executing the cloud-init wait command
as cloud-init is only executed on the initial boot.
Second, the cloud-init setup action will check for the sentinel file
written by the cloud-init wait action, and if detected it will skip
the cloud-init setup. When creating the ISO for cloud-init, a second
sentinel file will be used to log the path of the generated ISO
file. If the file exists, the ISO generation process will be skipped.
Fixes #13664
> Update cloud-init behavior and iso generation

- plugins/providers/hyperv/action/import.rb
- test/unit/plugins/providers/hyperv/action/import_test.rb
Result from import may be received in an array. Detect if the result
is an array and extract the first result. Otherwise, if the result
is not a string, force an error.
> Extract hyperv guest ID from result if needed

- plugins/providers/hyperv/action/import.rb
- plugins/providers/hyperv/scripts/import_vm.ps1
- plugins/providers/hyperv/scripts/utils/VagrantVM/VagrantVM.psm1
- test/unit/plugins/providers/hyperv/action/import_test.rb
When importing a box that was built with more resources than is
available on the current system, import would fail. If the memory
and/or cpu values are set in the Vagrantfile configuration, provide
them when importing the guest. This allows the values to be modified
prior to registering the new guest preventing a resource unavailability
error.
Fixes #12180
> Fix hyperv import failure due to lack of resources

- templates/locales/en.yml
Hello maintainers 👋🏼 
This PR updates the `en` language file with the updated login call.
For context, when running `vagrant login`, the following is shown:
> WARNING: This command has been deprecated and aliased to `vagrant cloud auth login`
I've also updated "HashiCorp's Vagrant Cloud" to "the HashiCorp Vagrant Public Registry" to mimic the name shown on https://portal.cloud.hashicorp.com/vagrant/discover.
> updates "login" command and registry name

- lib/vagrant/action/builtin/box_add.rb
- test/unit/vagrant/action/builtin/box_add_test.rb
Currently, during the box add action `env[:architecture]` gets passed down to `add_direct`, however, there is no `architecture` in env, the correct arch which is set in `Vagrantfile` is `box_architecture`, this PR changes the action to pass down the correct parameter
Closes: #13698, #13697
> Update box add action to pass arch correctly
